### PR TITLE
fix: 🐛 docker bind-mount stock files creation

### LINKED ISSUE #15638: [Bug]: Docker image fails to copy stock files when netdata.conf exists or DNT env set (bind mount)
### Bug description

When using bind mount volume, agent is not copying stock files (which causes netdata agent to be unhealthy) when netdata.conf exists or when DO_NOT_TRACK env is set.
Telemetry check should be moved after mountpoint check, also mountpoint check should handle `/etc/netdata` with already configured `netdata.conf` file.

### Expected behavior

Netdata agent should copy files and start properly.

### Steps to reproduce

1. Bind mount `/etc/netdata` in container spec
2. Set DO_NOT_TRACK env
OR 
2. Create preconfigured `/etc/netdata/netdata.conf`
3. Start netdata container
4. Files are missing, causing agent to be unhealthy
...

### Installation method

docker

### System info

```shell
not needed
```

### Netdata build info

```shell
not needed
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Leny1996**
##### Summary
Fixes #15638

### CODE REVIEW

File: packaging/docker/run.sh [hunk 1]
```diff
@@ -46,9 +39,16 @@ if [ -n "${PGID}" ]; then
   usermod -a -G "${PGID}" "${DOCKER_USR}" || echo >&2 "Could not add netdata user to group docker with ID ${PGID}"
 fi
 
-if mountpoint -q /etc/netdata && [ -z "$(ls -A /etc/netdata)" ]; then
+if mountpoint -q /etc/netdata && [ -z "$(ls -A /etc/netdata | grep -v netdata.conf)" ]; then
   echo "Copying stock configuration to /etc/netdata"
-  cp -a /etc/netdata.stock/. /etc/netdata
+  cp -an /etc/netdata.stock/. /etc/netdata
```
Comment (ilyam8) [inline packaging/docker/run.sh:44]: I think we need only 2 changes:

- remove `[ -z "$(ls -A /etc/netdata)" ]` check
- add the `n` option to `cp`.

That is it, should work without moving code around.

Comment (Leny1996) [reply packaging/docker/run.sh:51]: You're right. This will allow also to have other config files configured at startup.
Changes applied.

File: packaging/docker/run.sh [hunk 2]
```diff
@@ -46,9 +46,9 @@ if [ -n "${PGID}" ]; then
   usermod -a -G "${PGID}" "${DOCKER_USR}" || echo >&2 "Could not add netdata user to group docker with ID ${PGID}"
 fi
 
-if mountpoint -q /etc/netdata && [ -z "$(ls -A /etc/netdata)" ]; then
+if mountpoint -q /etc/netdata; then
   echo "Copying stock configuration to /etc/netdata"
-  cp -a /etc/netdata.stock/. /etc/netdata
+  cp -an /etc/netdata.stock/. /etc/netdata
```
[the remark this answers is not in the document]
Comment (Leny1996) [reply packaging/docker/run.sh:51]: Ah yes, just tested and you're right. Also found the same snippet here: https://superuser.com/questions/61611/how-to-copy-with-cp-to-include-hidden-files-and-hidden-directories-and-their-con
I will push this workaround version

**Review by thiagoftsm — APPROVED** [review]
Thank you very much for your contribution @Leny1996 !
