### PR TITLE
fix systemd detection; 

### LINKED ISSUE #4421: Installer does not detect systemd on Ubuntu 14.04
Hi,

There is what seems to be a bug in the installer, the issytemd function has been updated the 11th September of 2018 with this commit : [baac9dc53bc204d4506d7b36b190059d4685bd57](
https://github.com/netdata/netdata/commit/baac9dc53bc204d4506d7b36b190059d4685bd57#diff-73dacc6abc355a242efa2c913233f934)

As you can see, a check has been removed, but this check was also setting up a variable that is used later to loop on : 

```SHELL
    # -- ubuntu runs systemd as init ---
    ## if systemd is not running, it is not systemd
    #pids=$(pidof systemd 2>/dev/null)
    #[ -z "${pids}" ] && return 1

    # check if the running systemd processes are not in our namespace
    myns="$(readlink /proc/self/ns/pid 2>/dev/null)"
    for p in ${pids}
    do
        ns="$(readlink /proc/${p}/ns/pid 2>/dev/null)"

        # if pid of systemd is in our namespace, it is systemd
        [ ! -z "${myns}" ] && [ "${myns}" = "${ns}" ] && return 0
    done

    # else, it is not systemd
    return 1
}

### PR DESCRIPTION
**Pull request by ktsaou**
fixes #4421 
related to #4151

### CODE REVIEW

File: installer/functions.sh [hunk 1]
```diff
@@ -452,10 +452,9 @@ issystemd() {
     # if pid 1 is systemd, it is systemd
     [ "$(basename $(readlink /proc/1/exe) 2>/dev/null)" = "systemd" ] && return 0
 
-    # -- ubuntu runs systemd as init ---
-    ## if systemd is not running, it is not systemd
-    #pids=$(pidof systemd 2>/dev/null)
-    #[ -z "${pids}" ] && return 1
+    # if systemd is not running, it is not systemd
```
Comment (paulfantom) [inline installer/functions.sh]: It would be nice to add a comment that this is here due to a specific setup (ubuntu 14.04)

Comment (ktsaou) [reply installer/functions.sh]: I think it is not.
Our previous assumption was wrong.
Check it again. We don't check if `systemd` is actually running on this system.
