### PR TITLE
ACLK: Implemented Last Will and Testament

### LINKED ISSUE #8369: ACLK Last Will Testament implementation
#### Summary
The ACLK should define a Last Will Testament (LWT) that will be triggered when there is an abnormal link failure (described in the ACLK specifications document)

The LWT message will be (example):

```
{
    "type" : "disconnect",
    "version" : 1,
    "msg-id" : "fbc8509b-c3f7-492e-a1f8-303662853054",
    "timestamp" : 1583858212,
    "payload" : "unexpected"
}
```

The payload value **unexpected** denotes that the disconnection was not initiated by the agent. 

If the agent initiates the disconnection, e.g. when the agent is shutdown, then the message that will be sent will be: 

```
{
    "type" : "disconnect",
    "version" : 1,
    "msg-id" : "fbc8509b-c3f7-492e-a1f8-303662853054",
    "timestamp" : 1583858212,
    "payload" : "graceful"
}
```
The payload value **graceful** denotes that the disconnection was initiated by the agent. 

This will be done in the following way:

1. Agent shutdown is detected while the ACLK is established
2. The **disconnect** message with the **graceful** payload is prepared and send to the cloud
3. Agent explicitly sends a disconnect command to the cloud to gracefully shutdown the connection
    - This is how the broker on the cloud side _understands_ that the LWT will not be sent.
4. Agent shutdown completes

Notes:
1. If the shutdown is detected before agent enters a stable state.
    - Agent should disconnect as soon as possible
2. The timestamp on the LWT message will be in the past, i.e. when the agent initiated the ACLK.

### PR DESCRIPTION
**Pull request by stelfrag**
Fixes #8369
##### Summary
Defines a Last Will and Testament message that the broker will send to the `outbound/meta`
topic if an unexpected (agent or link) failure occurs. 

When the agent performs a normal shutdown an MQTT disconnect packet notifies the broker
that the LWT message should not be sent. In that case a different disconnect message is transmitted and indicates a graceful agent shutdown.

##### Component Name
ACLK

###### Graceful agent shutdown
- Start a claimed agent
- Subscribe to the broker on the `outbound/meta` topic
- Verify ACLK is up and running
- Notice the on connect messages
- Press control - C or send a `kill` signal to the agent
  - Notice a LWT message on `outbound/meta` similar to 
    - `{ "type" : "disconnect", "version" : 1, "msg-id" : "e7558504-eb6f-4bdf-9700-df972e0940e6", "timestamp" : 1584372301, "payload" : "graceful" } `
-----
###### Abnormal agent shutdown
- Start a claimed agent
- Subscribe to the broker on the `outbound/meta` topic
- Verify ACLK is up and running
- Notice the on connect messages
- Send `kill -9` signal to the agent
  - Notice a LWT message on `outbound/meta` similar to 
    - `{ "type" : "disconnect", "version" : 1, "msg-id" : "8ecde43f-5e97-4443-b314-5abab793a8d7", "timestamp" : 1584374934, "payload" : "unexpected" } `

### CODE REVIEW

**Comment by underhood** [comment]
When i CTRL+C i get SEGV
```
==253313== Memcheck, a memory error detector
==253313== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==253313== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==253313== Command: ./netdata -D
==253313== 
2020-03-16 18:14:56: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
^C==253313== Thread 9 ACLK_Main:
==253313== Invalid read of size 8
==253313==    at 0x50F40A: mosquitto_want_write (in /home/timo/projects/netdata/netdata/netdata)
==253313==    by 0x4A5F0C: _link_mosquitto_write (mqtt.c:183)
==253313==    by 0x4A60D8: _link_event_loop (mqtt.c:227)
==253313==    by 0x4A300A: aclk_main_cleanup (agent_cloud_link.c:955)
==253313==    by 0x4A4263: aclk_main (agent_cloud_link.c:1314)
==253313==    by 0x437120: thread_start (threads.c:170)
==253313==    by 0x4E154E1: start_thread (in /usr/lib64/libpthread-2.30.so)
==253313==    by 0x4F316D2: clone (in /usr/lib64/libc-2.30.so)
==253313==  Address 0x80 is not stack'd, malloc'd or (recently) free'd
==253313== 
==253313== 
==253313== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==253313==  Access not within mapped region at address 0x80
==253313==    at 0x50F40A: mosquitto_want_write (in /home/timo/projects/netdata/netdata/netdata)
==253313==    by 0x4A5F0C: _link_mosquitto_write (mqtt.c:183)
==253313==    by 0x4A60D8: _link_event_loop (mqtt.c:227)
==253313==    by 0x4A300A: aclk_main_cleanup (agent_cloud_link.c:955)
==253313==    by 0x4A4263: aclk_main (agent_cloud_link.c:1314)
==253313==    by 0x437120: thread_start (threads.c:170)
==253313==    by 0x4E154E1: start_thread (in /usr/lib64/libpthread-2.30.so)
==253313==    by 0x4F316D2: clone (in /usr/lib64/libc-2.30.so)
==253313==  If you believe this happened as a result of a stack
==253313==  overflow in your program's main thread (unlikely but
==253313==  possible), you can try to increase the size of the
==253313==  main thread stack using the --main-stacksize= flag.
==253313==  The main thread stack size used in this run was 8388608.
==253313== 
==253313== HEAP SUMMARY:
==253313==     in use at exit: 5,336,840 bytes in 37,997 blocks
==253313==   total heap usage: 63,693 allocs, 25,696 frees, 12,616,620 bytes allocated
==253313== 
==253313== LEAK SUMMARY:
==253313==    definitely lost: 114 bytes in 1 blocks
==253313==    indirectly lost: 0 bytes in 0 blocks
==253313==      possibly lost: 8,016 bytes in 152 blocks
==253313==    still reachable: 5,328,606 bytes in 37,843 blocks
==253313==         suppressed: 104 bytes in 1 blocks
==253313== Rerun with --leak-check=full to see details of leaked memory
==253313== 
==253313== For lists of detected and suppressed errors, rerun with: -s
==253313== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

**Comment by stelfrag** [comment]
> _link_event_loop

Thanks Timo, will fix !!

File: aclk/agent_cloud_link.c [hunk 1]
```diff
@@ -935,13 +936,36 @@ void *aclk_query_main_thread(void *ptr)
...
+        // Wakeup thread to cleanup
+        QUERY_THREAD_WAKEUP;
+        // Send a graceful disconnect message
+        time_t time_created = now_realtime_sec();
+        char *msg_id = create_uuid();
+        snprintfz(payload, sizeof(ACLK_LWT_MSG) + 128, ACLK_LWT_MSG, msg_id, time_created, "graceful");
+        aclk_send_message(ACLK_METADATA_TOPIC, payload, msg_id);
+        freez(msg_id);
+
+        _link_event_loop();
```
Comment (amoss) [inline aclk/agent_cloud_link.c]: Why are we calling `_link_event_loop()` three times?

File: aclk/agent_cloud_link.h [hunk 2]
```diff
@@ -29,6 +29,15 @@
 #define ACLK_DEFAULT_PORT 9002
 #define ACLK_DEFAULT_HOST "localhost"
 
+#define ACLK_LWT_MSG    "{ \
```
Comment (amoss) [inline aclk/agent_cloud_link.h]: Why is this format string in a header file instead of in the sprintf call where people can read it?

File: aclk/mqtt.c [hunk 3]
```diff
@@ -244,12 +249,41 @@ void _link_shutdown()
...
+    final_topic = get_topic(sub_topic, topic, ACLK_MAX_TOPIC);
+    if (unlikely(!final_topic)) {
+        errno = 0;
+        error("Unable to build outgoing topic; truncated?");
+        return 1;
+    }
+
+    time_t time_created = now_realtime_sec();
+    char *msg_id = create_uuid();
+    snprintfz(payload, sizeof(ACLK_LWT_MSG)+128, ACLK_LWT_MSG, msg_id, time_created, "unexpected");
```
Comment (amoss) [inline aclk/mqtt.c]: This should be `sizeof(payload)` to guard against changes at either site in the future.

File: aclk/agent_cloud_link.c (hunk 1 above)
Comment (stelfrag) [reply aclk/agent_cloud_link.c]: There is no indication of what is pending in the lws layer and since the event loop is not called in the main loop at that point, the only way I got this to work is by calling the event loop to make sure the message will be delivered (and the disconnect packet as well). 

Calling the event loop e.g 2 times results in the connection being dropped and the cloud gets both messages (graceful and unexpected)

The ideal would be to call the loop and peek the lws internals for pending packets.

File: aclk/agent_cloud_link.h (hunk 2 above)
Comment (stelfrag) [reply aclk/agent_cloud_link.h]: Good point not needed; will change

**Comment by underhood** [comment]
The unclaimed agent SEGV appears to be fixed and both test cases with claimed agent seem to work. I will approve when compiler warnings and related problems are fixed.

File: aclk/mqtt.c (hunk 3 above)
Comment (stelfrag) [reply aclk/mqtt.c]: Removed the define

File: aclk/agent_cloud_link.h (hunk 2 above)
Comment (underhood) [reply aclk/agent_cloud_link.h]: hmmm now you cannot use sizeof and have to put constants for buffer size :/

**Comment by stelfrag** [comment]
> The unclaimed agent SEGV appears to be fixed and both test cases with claimed agent seem to work. I will approve when compiler warnings and related problems are fixed.

Added `extern` for: 

- `aclk_lws_wss_mqtt_layer_disconect_notif
- `get_topic`

 functions to clear the compilter warnings.

File: aclk/agent_cloud_link.h [hunk 4]
```diff
@@ -73,6 +73,7 @@ void *aclk_main(void *ptr);
       .start_routine = aclk_main },
 
 extern int aclk_send_message(char *sub_topic, char *message, char *msg_id);
+extern void aclk_lws_wss_mqtt_layer_disconect_notif();
```
Comment (underhood) [inline aclk/agent_cloud_link.h]: why not just include the file? That way we don't have 3 places to update if function parameters change in future

File: aclk/agent_cloud_link.c (hunk 1 above)
Comment (amoss) [reply aclk/agent_cloud_link.c]: Would it work to check the outgoing queue size for LWS using the stats function that I put in during the stress-testing. My concern is that we tuning this for a specific code path through mosquitto and we have no idea if it will behave like that in production. I would rather see a loop (with a timeout) that keeps hitting the event loop until a condition shows that the message is gone.

Comment (stelfrag) [reply aclk/agent_cloud_link.c]: > Would it work to check the outgoing queue size for LWS using the stats function that I put in during the stress-testing. My concern is that we tuning this for a specific code path through mosquitto and we have no idea if it will behave like that in production. I would rather see a loop (with a timeout) that keeps hitting the event loop until a condition shows that the message is gone.

If that gives accurate indication that the lws layer has flushed all the packets, it will be ideal. I will integrate that into a loop.

File: aclk/agent_cloud_link.h (hunk 4 above)
Comment (stelfrag) [reply aclk/agent_cloud_link.h]: > why not just include the file? That way we don't have 3 places to update if function parameters change in future

Added

File: aclk/agent_cloud_link.c (hunk 1 above)
Comment (stelfrag) [reply aclk/agent_cloud_link.c]: Added check by calling `lws_wss_check_queues` and using that information to call the event loop until the queue is empty  (timeout on 5 seconds).

File: aclk/agent_cloud_link.h [hunk 5]
```diff
@@ -5,6 +5,7 @@
 
 #include "../daemon/common.h"
 #include "mqtt.h"
+#include "aclk_lws_wss_client.h"
```
Comment (amoss) [inline aclk/agent_cloud_link.h]: You can't do this - this file is included everywhere outside of the feature flag.

Comment (stelfrag) [reply aclk/agent_cloud_link.h]: Removed

**Comment by stelfrag** [comment]
> It segfaults when I hit ctrl-c at random points during the startup-up / pop-corning phase:
> 
> ```
> ==12081== Process terminating with default action of signal 11 (SIGSEGV)
> ==12081==  Access not within mapped region at address 0x80
> ==12081==    at 0x203B97: mosquitto_want_write (in /home/amoss/netdata/dev-install3/netdata/usr/sbin/netdata)
> ==12081==    by 0x1704FB: UnknownInlinedFun (mqtt.c:183)
> ==12081==    by 0x1704FB: UnknownInlinedFun (mqtt.c:227)
> ==12081==    by 0x1704FB: aclk_main_cleanup (agent_cloud_link.c:982)
> ==12081==    by 0x1728B7: aclk_main (agent_cloud_link.c:1293)
> ==12081==    by 0x1E3B34: thread_start (threads.c:170)
> ==12081==    by 0x523FFA2: start_thread (pthread_create.c:486)
> ==12081==    by 0x53544CE: clone (clone.S:95)
> ```

Ok will take a look asap

**Comment by amoss** [comment]
Here is another one (might not be due to this PR) :
```
==17942== Process terminating with default action of signal 11 (SIGSEGV)
==17942==  Access not within mapped region at address 0x168B39D0
==17942==    at 0x52476C9: pthread_cancel (pthread_cancel.c:33)
==17942==    by 0x1DFED0: netdata_thread_cancel (threads.c:203)
==17942==    by 0x1732D0: socket_listen_main_static_threaded_cleanup (static-threaded.c:428)
==17942==    by 0x175E30: socket_listen_main_static_threaded (static-threaded.c:458)
==17942==    by 0x1E3B34: thread_start (threads.c:170)
==17942==    by 0x523FFA2: start_thread (pthread_create.c:486)
==17942==    by 0x53544CE: clone (clone.S:95)
```

**Comment by stelfrag** [comment]
> > It segfaults when I hit ctrl-c at random points during the startup-up / pop-corning phase:
> > ```
> > ==12081== Process terminating with default action of signal 11 (SIGSEGV)
> > ==12081==  Access not within mapped region at address 0x80
> > ==12081==    at 0x203B97: mosquitto_want_write (in /home/amoss/netdata/dev-install3/netdata/usr/sbin/netdata)
> > ==12081==    by 0x1704FB: UnknownInlinedFun (mqtt.c:183)
> > ==12081==    by 0x1704FB: UnknownInlinedFun (mqtt.c:227)
> > ==12081==    by 0x1704FB: aclk_main_cleanup (agent_cloud_link.c:982)
> > ==12081==    by 0x1728B7: aclk_main (agent_cloud_link.c:1293)
> > ==12081==    by 0x1E3B34: thread_start (threads.c:170)
> > ==12081==    by 0x523FFA2: start_thread (pthread_create.c:486)
> > ==12081==    by 0x53544CE: clone (clone.S:95)
> > ```
> 
> Ok will take a look asap

Cause by the internal mosq structure being destroyed and set to null. 

When the cleanup code is called it is not certain that netdata_exit variable is set to 1 (yet) which the code that tears down the link assumed.
