### PR TITLE
Return stable or nightly based on version if the file check fails

### LINKED ISSUE #12888: [Feat]: guess the release channel from the program version if `.environment` doesn't exist
### Problem

[get_release_channel()](https://github.com/netdata/netdata/blob/73bb8888f3bffcb36b99b9341f15d21b3de844d0/web/api/formatters/charts2json.c#L7-L37) expects:

- `%s/.environment` file.
- `RELEASE_CHANNEL` line in the file.

❗ **Native packages have no that file**.

If the file doesn't exist we always assume that the release channel is stable:

https://github.com/netdata/netdata/blob/73bb8888f3bffcb36b99b9341f15d21b3de844d0/web/api/formatters/charts2json.c#L13-L15

Which, as you may guess, is correct only 50% of the time 😄 

Facts:
 - If you install the Netdata deb package, the default release channel is nightly, you always get the wrong release channel value.

### Description

I think we need to implement a fallback method if `.environment` is missing. This is must-have for our native packages.

### Importance

must have

### Value proposition

1. People using native packages will get the correct release channel => the dashboard version check will work.

### Proposed implementation

I suggest parsing Netdata binary version: e.g. if it is `vX.Y.Z` - stable, nightly otherwise.

### PR DESCRIPTION
**Pull request by stelfrag**
Fixes #12888
 
##### Summary
Parse the program version (actually check for '-') if the existing detection mechanism fails

##### Test Plan
- Compile and change the `.environment` file to break the detection of the release channel from there

### CODE REVIEW

File: web/api/formatters/charts2json.c [hunk 1]
```diff
@@ -8,30 +8,28 @@ const char* get_release_channel() {
...
                 unsigned int i;
-                for(i = 0; i < procfile_lines(ff); i++) {
-                    if (!procfile_linewords(ff, i)) continue;
-
-                    if (!strcmp(procfile_lineword(ff, i, 0), "RELEASE_CHANNEL") && !strcmp(procfile_lineword(ff, i, 1), "stable")) {
+                for (i = 0; i < procfile_lines(ff); i++) {
+                    if (!procfile_linewords(ff, i))
+                        continue;
+                    if (!strcmp(procfile_lineword(ff, i, 0), "RELEASE_CHANNEL") &&
+                        !strcmp(procfile_lineword(ff, i, 1), "stable")) {
```
Comment (ilyam8) [inline web/api/formatters/charts2json.c:23]: we need to check for 'nightly' here too, so we don't fall back to parsing the program version if the file exists and RELEASE_CHANNEL is nightly

Comment (stelfrag) [reply web/api/formatters/charts2json.c:23]: Good point

**Review by ilyam8 — DISMISSED** [review]

File: web/api/formatters/charts2json.c [hunk 2]
```diff
@@ -8,30 +8,31 @@ const char* get_release_channel() {
...
-                        use_stable = 1;
+                for (i = 0; i < procfile_lines(ff); i++) {
+                    if (!procfile_linewords(ff, i))
+                        continue;
+                    if (!strcmp(procfile_lineword(ff, i, 0), "RELEASE_CHANNEL")) {
+                        if (!strcmp(procfile_lineword(ff, i, 1), "stable"))
+                            use_stable = 1;
+                        else
+                            if (!strcmp(procfile_lineword(ff, i, 1), "nightly"))
+                                use_stable = 0;
```
Comment (ilyam8) [inline web/api/formatters/charts2json.c:27]: neat-pick: else if

**Review by ilyam8 — APPROVED** [review]

**Review by MrZammler — APPROVED** [review]

**Review by vlvkobal — APPROVED** [review]
