### PR TITLE
Fixes the race-hazard in streaming during the shutdown sequence

### LINKED ISSUE #9369: Memory corruption during agent shutdown by STREAMING
##### Bug report summary

During shutdown of the agent the child database pointers are being used by STREAMING code.
After RRDHOST-children are torn down, STREAMING threads that were still connected to the sockets to receive data time out:
```
 STREAM_RECEIVER[CentOS-7-mfundul-lxc-centos7-1,[192.168.122.44]:40602] : STREAM CentOS-7-mfundul-lxc-centos7-1 [receive from [192.168.122.44]:40602]: disconnected (completed 18615 updates). (errno 11, Resource temporarily unavailable)
```

It seems that streaming code uses RRHOST pointers after deallocation (heap memory use after free).

Backtrace:
```
==47320== ERROR: AddressSanitizer: heap-use-after-free on address 0x604600139318 at pc 0x55fcd7 bp 0x7f3faecec4d0 sp 0x7f3faecec4c0
    #0 0x55fcd6 (/usr/sbin/netdata+0x55fcd6)
    #1 0x560365 (/usr/sbin/netdata+0x560365)
    #2 0x467722 (/usr/sbin/netdata+0x467722)
    #3 0x7f3fccc6f867 (/usr/lib64/libasan.so.0.0.0+0x19867)
    #4 0x7f3fcb1acea4 (/usr/lib64/libpthread-2.17.so+0x7ea4)
    #5 0x7f3fcaed58dc (/usr/lib64/libc-2.17.so+0xfe8dc)
0x604600139318 is located 24 bytes inside of 1192-byte region [0x604600139300,0x6046001397a8)
freed by thread T0 here:
    #0 0x7f3fccc6bdd9 (/usr/lib64/libasan.so.0.0.0+0x15dd9)
    #1 0x446855 (/usr/sbin/netdata+0x446855)
    #2 0x506928 (/usr/sbin/netdata+0x506928)
    #3 0x506991 (/usr/sbin/netdata+0x506991)
    #4 0x40f90a (/usr/sbin/netdata+0x40f90a)
    #5 0x417d81 (/usr/sbin/netdata+0x417d81)
    #6 0x4163c1 (/usr/sbin/netdata+0x4163c1)
    #7 0x7f3fcadf9554 (/usr/lib64/libc-2.17.so+0x22554)
previously allocated by thread T44 (STREAM_RECEIVER) here:
    #0 0x7f3fccc6bff5 (/usr/lib64/libasan.so.0.0.0+0x15ff5)
    #1 0x446923 (/usr/sbin/netdata+0x446923)
    #2 0x501e6f (/usr/sbin/netdata+0x501e6f)
    #3 0x504d09 (/usr/sbin/netdata+0x504d09)
    #4 0x55d644 (/usr/sbin/netdata+0x55d644)
    #5 0x560365 (/usr/sbin/netdata+0x560365)
    #6 0x467722 (/usr/sbin/netdata+0x467722)
    #7 0x7f3fccc6f867 (/usr/lib64/libasan.so.0.0.0+0x19867)
Thread T44 (STREAM_RECEIVER) created by T21 (WEB_SERVER[stat) here:
    #0 0x7f3fccc60a0a (/usr/lib64/libasan.so.0.0.0+0xaa0a)
    #1 0x4678eb (/usr/sbin/netdata+0x4678eb)
    #2 0x553476 (/usr/sbin/netdata+0x553476)
    #3 0x57f3f7 (/usr/sbin/netdata+0x57f3f7)
    #4 0x58994e (/usr/sbin/netdata+0x58994e)
    #5 0x460000 (/usr/sbin/netdata+0x460000)
    #6 0x4623a0 (/usr/sbin/netdata+0x4623a0)
    #7 0x58ac80 (/usr/sbin/netdata+0x58ac80)
    #8 0x467722 (/usr/sbin/netdata+0x467722)
    #9 0x7f3fccc6f867 (/usr/lib64/libasan.so.0.0.0+0x19867)
Thread T21 (WEB_SERVER[stat) created by T11 (WEB_SERVER[stat) here:
    #0 0x7f3fccc60a0a (/usr/lib64/libasan.so.0.0.0+0xaa0a)
    #1 0x4678eb (/usr/sbin/netdata+0x4678eb)
    #2 0x58b41f (/usr/sbin/netdata+0x58b41f)
    #3 0x467722 (/usr/sbin/netdata+0x467722)
    #4 0x7f3fccc6f867 (/usr/lib64/libasan.so.0.0.0+0x19867)
Thread T11 (WEB_SERVER[stat) created by T0 here:
    #0 0x7f3fccc60a0a (/usr/lib64/libasan.so.0.0.0+0xaa0a)
    #1 0x4678eb (/usr/sbin/netdata+0x4678eb)
    #2 0x4161b1 (/usr/sbin/netdata+0x4161b1)
    #3 0x7f3fcadf9554 (/usr/lib64/libc-2.17.so+0x22554)
Shadow bytes around the buggy address:
  0x0c094001f210: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c094001f220: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c094001f230: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c094001f240: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c094001f250: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c094001f260: fd fd fd[fd]fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c094001f270: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c094001f280: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c094001f290: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c094001f2a0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c094001f2b0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:     fa
  Heap righ redzone:     fb
  Freed Heap region:     fd
  Stack left redzone:    f1
  Stack mid redzone:     f2
  Stack right redzone:   f3
  Stack partial redzone: f4
  Stack after return:    f5
  Stack use after scope: f8
  Global redzone:        f9
  Global init order:     f6
  Poisoned by user:      f7
  ASan internal:         fe
==47320== ABORTING
```

```
(gdb) list *0x55fcd6
0x55fcd6 is in rrdpush_receive (streaming/receiver.c:418).
413
414
415         size_t count = streaming_parser(rpt, &cd, fp);
416         //size_t count = pluginsd_process(host, &cd, fp, 1);
417
418         log_stream_connection(rpt->client_ip, rpt->client_port, rpt->key, rpt->host->machine_guid, rpt->host->hostname, "DISCONNECTED");
419         error("STREAM %s [receive from [%s]:%s]: disconnected (completed %zu updates).", rpt->host->hostname, rpt->client_ip, rpt->client_port, count);
420
421         netdata_mutex_lock(&rpt->host->receiver_lock);
422         if (rpt->host->receiver == rpt) {
(gdb) list *0x560365
0x560365 is in rrdpush_receiver_thread (streaming/receiver.c:445).
440         netdata_thread_cleanup_push(rrdpush_receiver_thread_cleanup, ptr);
441
442         struct receiver_state *rpt = (struct receiver_state *)ptr;
443         info("STREAM %s [%s]:%s: receive thread created (task id %d)", rpt->hostname, rpt->client_ip, rpt->client_port, gettid());
444
445         rrdpush_receive(rpt);
446
447         netdata_thread_cleanup_pop(1);
448         return NULL;
449     }
```

##### OS / Environment

```
/etc/centos-release:CentOS Linux release 7.8.2003 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.8.2003 (Core)
/etc/system-release:CentOS Linux release 7.8.2003 (Core)
```

##### Netdata version

v1.22.1-297-g13624215 

##### Steps To Reproduce

1. Install netdata with 10 children streaming to it.
2. Restart the service multiple times, detect memory corruption with valgrind or asan.

##### Expected behavior

Streaming code should not touch RRDHOST memory after it has been freed.

### PR DESCRIPTION
**Pull request by amoss**
##### Summary
Fixes #9369 
The streaming component detects when a receiver stream has closed, and stops an attached sender on the same host. This is to support proxy configurations where the stream is passed through. During the shutdown sequence, once `netdata_exit` has been set no thread should touch any `RRDHOST` structure as the non-static threads are not joined before the database shuts down. 

During the shutdown sequence any attached sender is killed by the database during cleanup, so this patch just stops the receiver from trying to do the same.

##### Component Name
streaming

##### Test Plan

* Connect many Child nodes to stream to the Parent.
* Shutdown the Parent and observe the valgrind output.

### CODE REVIEW

**Comment by amoss** [comment]
Haven't seen this one before:
```
==10587== Command: ./netdata -D
==10587== 
2020-06-18 13:49:17: netdata INFO  : MAIN : (0088@daemon/sig:signals_init   ): SIGNAL: Not enabling reaper
^C==10587== 
==10587== HEAP SUMMARY:
==10587==     in use at exit: 8,686,421 bytes in 229,153 blocks
==10587==   total heap usage: 1,574,606 allocs, 1,345,453 frees, 179,600,881 bytes allocated
==10587== 
==10587== 320 bytes in 1 blocks are possibly lost in loss record 11,189 of 11,786
==10587==    at 0x4837B65: calloc (vg_replace_malloc.c:752)
==10587==    by 0x40116D1: allocate_dtv (dl-tls.c:286)
==10587==    by 0x401203D: _dl_allocate_tls (dl-tls.c:532)
==10587==    by 0x5233B95: allocate_stack (allocatestack.c:621)
==10587==    by 0x5233B95: pthread_create@@GLIBC_2.2.5 (pthread_create.c:669)
==10587==    by 0x4FA43AD: uv_thread_create (in /usr/lib/x86_64-linux-gnu/libuv.so.1.0.0)
==10587==    by 0x1CDD61: spawn_init (spawn.c:244)
==10587==    by 0x11F9CC: main (main.c:1389)
==10587== 
==10587== LEAK SUMMARY:
==10587==    definitely lost: 0 bytes in 0 blocks
==10587==    indirectly lost: 0 bytes in 0 blocks
==10587==      possibly lost: 320 bytes in 1 blocks
==10587==    still reachable: 8,686,101 bytes in 229,152 blocks
==10587==         suppressed: 0 bytes in 0 blocks
==10587== Reachable blocks (those to which a pointer was found) are not shown.
==10587== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==10587== 
==10587== For counts of detected and suppressed errors, rerun with: -v
==10587== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

**Comment by amoss** [comment]
Another one that doesn't relate to the streaming bug:
```
==11572== 5,485 (80 direct, 5,405 indirect) bytes in 1 blocks are definitely lost in loss record 10,415 of 10,508
==11572==    at 0x4837B65: calloc (vg_replace_malloc.c:752)
==11572==    by 0x13CE2E: callocz (libnetdata.c:183)
==11572==    by 0x180AE4: pluginsd_process (pluginsd_parser.c:648)
==11572==    by 0x17E0B5: pluginsd_worker_thread (plugins_d.c:248)
==11572==    by 0x14EB5C: thread_start (threads.c:170)
==11572==    by 0x5232FA2: start_thread (pthread_create.c:486)
==11572==    by 0x53454CE: clone (clone.S:95)

```

**Comment by amoss** [comment]
Failed to shutdown during one test with 25 child nodes:
```
==14479== Command: ./netdata -D
==14479== 
2020-06-18 14:03:16: netdata INFO  : MAIN : (0088@daemon/sig:signals_init   ): SIGNAL: Not enabling reaper
==14479== Thread 2:
==14479== Syscall param writev(vector[...]) points to uninitialised byte(s)
==14479==    at 0x533C537: __writev (writev.c:26)
==14479==    by 0x533C537: writev (writev.c:24)
==14479==    by 0x4FA210A: ??? (in /usr/lib/x86_64-linux-gnu/libuv.so.1.0.0)
==14479==    by 0x4FA34DB: uv_write2 (in /usr/lib/x86_64-linux-gnu/libuv.so.1.0.0)
==14479==    by 0x1CEEFC: spawn_process_cmd (spawn_client.c:160)
==14479==    by 0x1CF55B: spawn_client (spawn_client.c:215)
==14479==    by 0x5232FA2: start_thread (pthread_create.c:486)
==14479==    by 0x53454CE: clone (clone.S:95)
==14479==  Address 0x32814704 is 196 bytes inside a block of size 240 alloc'd
==14479==    at 0x483577F: malloc (vg_replace_malloc.c:299)
==14479==    by 0x13CDCB: mallocz (libnetdata.c:177)
==14479==    by 0x1CEE39: spawn_process_cmd (spawn_client.c:142)
==14479==    by 0x1CF55B: spawn_client (spawn_client.c:215)
==14479==    by 0x5232FA2: start_thread (pthread_create.c:486)
==14479==    by 0x53454CE: clone (clone.S:95)
==14479== 
^C
....
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fa23721862e in __GI_epoll_pwait (epfd=3, events=0x7fffeba4b880, 
    maxevents=1024, timeout=-1, set=0x0)
    at ../sysdeps/unix/sysv/linux/epoll_pwait.c:42
42	../sysdeps/unix/sysv/linux/epoll_pwait.c: No such file or directory.
(gdb) bt
#0  0x00007fa23721862e in __GI_epoll_pwait (epfd=3, events=0x7fffeba4b880, 
    maxevents=1024, timeout=-1, set=0x0)
    at ../sysdeps/unix/sysv/linux/epoll_pwait.c:42
#1  0x00007fa237598399 in uv.io_poll () from /lib/x86_64-linux-gnu/libuv.so.1
#2  0x00007fa237589f85 in uv_run () from /lib/x86_64-linux-gnu/libuv.so.1
#3  0x000055bca9f7acfc in spawn_server () at spawn/spawn_server.c:371
#4  0x000055bca9ecab91 in main (argc=<optimized out>, argv=0x7fffeba4eb98)
    at daemon/main.c:911
(gdb) threads
Undefined command: "threads".  Try "help".
(gdb) info threads
  Id   Target Id                                   Frame 
* 1    Thread 0x7fa2370f8c40 (LWP 14481) "netdata" 0x00007fa23721862e in __GI_epoll_pwait (epfd=3, events=0x7fffeba4b880, maxevents=1024, timeout=-1, set=0x0)
    at ../sysdeps/unix/sysv/linux/epoll_pwait.c:42
  2    Thread 0x7fa2370f7700 (LWP 14482) "netdata" futex_wait_cancelable (private=0, expected=0, futex_word=0x55bcaa1aae8c <wait_children_cond+44>)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
(gdb) 
```

File: streaming/receiver.c [hunk 1]
```diff
@@ -418,17 +418,20 @@ static int rrdpush_receive(struct receiver_state *rpt)
     log_stream_connection(rpt->client_ip, rpt->client_port, rpt->key, rpt->host->machine_guid, rpt->host->hostname, "DISCONNECTED");
```
Comment (mfundul) [inline streaming/receiver.c:418]: Still crashing in line 418:
```
(gdb) list *0x560535
0x560535 is in rrdpush_receive (streaming/receiver.c:418).
413
414
415         size_t count = streaming_parser(rpt, &cd, fp);
416         //size_t count = pluginsd_process(host, &cd, fp, 1);
417
418         log_stream_connection(rpt->client_ip, rpt->client_port, rpt->key, rpt->host->machine_guid, rpt->host->hostname, "DISCONNECTED");
419         error("STREAM %s [receive from [%s]:%s]: disconnected (completed %zu updates).", rpt->host->hostname, rpt->client_ip, rpt->client_port, count);
420
421         // During a shutdown there is cleanup code in rrdhost that will cancel the sender thread
422         if (!netdata_exit) {
(gdb) 
```
You should include those lines in the conditional as well.

Comment (amoss) [reply streaming/receiver.c:418]: Facepalm. I'll move them inside. I couldn't trigger it in testing though - went up to 25 child nodes. Are you doing anything other than shutting down the parent while the child nodes are streaming data?

**Comment by amoss** [comment]
True, but this implies that it entered the block while `!netdata_exit` and the flag flipped during execution of the block. This means that it holds the mutex in memory that has been freed while requires a slightly different approach...

**Comment by underhood** [comment]
how about ensuring all receiver threads are stopped before `rrdhost_cleanup_all` gets called in `netdata_cleanup_and_exit` ?

**Comment by amoss** [comment]
> how about ensuring all receiver threads are stopped before `rrdhost_cleanup_all` gets called in `netdata_cleanup_and_exit` ?
> 
> But ofc I do not know the new streaming code that much... but seems to me like something that should help

Overall this would be the best approach but Netdata does not keep track of the threads that it creates that are not in the `static_thread` list. The `netdata_exit` flag is a signal that the processing loops of the dynamic threads should break and exit the thread main body. In the long-term we should properly track and clean up these threads - but it affects more places in the code that are fragile than this fix.

The previous commit was absolute rubbish - fixed the wrong part of the code. I've reverted it and fixed the cleanup code. There is already a shutdown flag used as a hint to the thread that it should finish (for the case where multiple incoming connections collide on a host and one is dead). The host destruction will now set this flag to try to get the thread to start its exit early, and the cleanup code will catch any that get cancelled.

**Comment by amoss** [comment]
Testing seems to show that this stable. I cannot replicate @mfundul's test sequence (libASAN is not running here and valgrind has become unstable trying to fix it). I need confirmation from @mfundul that it survives testing on his system. I'm trying other tests in the meantime - creating / killing child nodes to trigger the other code paths and randomly killing the parent agent. Found something very strange that is probably an artifact of running inside ´gdb` -
```
#39065 0x0000555555588e09 in mallocz (size=154) at libnetdata/libnetdata.c:178
#39066 0x000055555556a3ad in send_statistics (action=<optimized out>, action@entry=0x5555556b8d56 "FATAL", action_result=<optimized out>, action_result@entry=0x7fffc0711780 "netdata:[x]", action_data=<optimized out>, action_data@entry=0x7fffc07117c0 "0178@libnetdata:mallocz        /12") at daemon/main.c:820
#39067 0x000055555558db8f in fatal_int (file=file@entry=0x5555556b77bc "libnetdata/libnetdata.c", function=function@entry=0x5555556b8000 <__FUNCTION__.31659> "mallocz", line=line@entry=178, fmt=fmt@entry=0x5555556b7ae8 "Cannot allocate %zu bytes of memory.") at libnetdata/log/log.c:827
#39068 0x0000555555588e09 in mallocz (size=154) at libnetdata/libnetdata.c:178
#39069 0x000055555556a3ad in send_statistics (action=<optimized out>, action@entry=0x5555556b8d56 "FATAL", action_result=<optimized out>, action_result@entry=0x7fffc0711a00 "netdata:[x]", action_data=<optimized out>, action_data@entry=0x7fffc0711a40 "0184@libnetdata:callocz        /12") at daemon/main.c:820
#39070 0x000055555558db8f in fatal_int (file=file@entry=0x5555556b77bc "libnetdata/libnetdata.c", function=function@entry=0x5555556b7ff8 <__FUNCTION__.31665> "callocz", line=line@entry=184, fmt=fmt@entry=0x5555556b7ae8 "Cannot allocate %zu bytes of memory.") at libnetdata/log/log.c:827
#39071 0x0000555555588e71 in callocz (nmemb=nmemb@entry=1, size=size@entry=16384) at libnetdata/libnetdata.c:184
#39072 0x00005555555d7bdd in rrddim_add_custom (st=st@entry=0x7fffa63c4000, id=0x55556844326b "netdata", name=0x555568443275 "netdata", multiplier=1, divisor=divisor@entry=1, algorithm=algorithm@entry=RRD_ALGORITHM_ABSOLUTE, memory_mode=RRD_MEMORY_MODE_MAP, is_archived=0, dim_uuid=0x0) at database/rrddim.c:310
#39073 0x00005555555cb048 in pluginsd_dimension_action (user=<optimized out>, st=0x7fffa63c4000, id=<optimized out>, name=<optimized out>, algorithm=<optimized out>, multiplier=<optimized out>, divisor=1, options=0x55556844328e "  ", algorithm_type=RRD_ALGORITHM_ABSOLUTE) at collectors/plugins.d/pluginsd_parser.c:127
#39074 0x00005555555cbe21 in pluginsd_dimension (words=<optimized out>, user=0x5555681f8d60, plugins_action=0x5555681fa630) at collectors/plugins.d/pluginsd_parser.c:412
#39075 0x0000555555610616 in parser_action (parser=parser@entry=0x5555681f9930, input=0x555568443260 "DIMENSION") at parser/parser.c:296
#39076 0x00005555555fbc92 in streaming_parser (rpt=rpt@entry=0x5555684431e0, cd=cd@entry=0x7fffc0714860, fp=fp@entry=0x5555681f8b30) at streaming/receiver.c:178
#39077 0x00005555555fc94e in rrdpush_receive (rpt=rpt@entry=0x5555684431e0) at streaming/receiver.c:415
#39078 0x00005555555fcc46 in rrdpush_receiver_thread (ptr=0x5555684431e0) at streaming/receiver.c:448
#39079 0x000055555559ab5d in thread_start (ptr=<optimized out>) at libnetdata/threads/threads.c:170
#39080 0x00007ffff75cdfa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#39081 0x00007ffff74fe4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

**Comment by underhood** [comment]
@amoss yes the stream receiver threads not being the so-called "static thread" causes that `cancel_main_threads();` doesn't care about them. That is why I proposed to add something before to ensure those threads already stop before starting deallocating stuff. I think you need to stop before `rrdhost_cleanup_all` anyway (which is before `cancel_main_threads`)

File: database/rrdhost.c [hunk 2]
```diff
@@ -674,12 +674,20 @@ void rrdhost_free(RRDHOST *host) {
...
+    // clean up streaming
     rrdpush_sender_thread_stop(host); // stop a possibly running thread
     cbuffer_free(host->sender->buffer);
     buffer_free(host->sender->build);
     freez(host->sender);
     host->sender = NULL;
+    netdata_mutex_lock(&host->receiver_lock);
+    if (host->receiver) {
+        netdata_thread_cancel(host->receiver->thread);
+        destroy_receiver_state(host->receiver);
```
Comment (mfundul) [inline database/rrdhost.c:686]: This deallocates the data structures before `host->receiver->thread` is gone, and it corrupts the memory every time, and potentially during runtime, not only during shutdown.

**Comment by underhood** [comment]
Hmmm lot of errors with blocks malloced in metadata log but they not look related to this:
```
2020-06-19 19:14:31: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
==90976== Thread 4:
==90976== Syscall param pwrite64(buf) points to uninitialised byte(s)
==90976==    at 0x4F1825F: pwrite (in /usr/lib64/libpthread-2.30.so)
==90976==    by 0x4D6F45D: ??? (in /usr/lib64/libuv.so.1.0.0)
==90976==    by 0x4D718A7: uv_fs_write (in /usr/lib64/libuv.so.1.0.0)
==90976==    by 0x4AD030: create_metadata_logfile (logfile.c:338)
==90976==    by 0x4AE804: add_new_metadata_logfile (logfile.c:738)
==90976==    by 0x4A9546: metalog_try_link_new_metadata_logfile (metadatalog.c:137)
==90976==    by 0x4B049A: metalog_do_compaction (compaction.c:282)
==90976==    by 0x4A96E2: metalog_test_quota (metadatalog.c:164)
==90976==    by 0x4A9D2A: timer_cb (metadatalog.c:264)
==90976==    by 0x4D68915: uv__run_timers (in /usr/lib64/libuv.so.1.0.0)
==90976==    by 0x4D6BDC9: uv_run (in /usr/lib64/libuv.so.1.0.0)
==90976==    by 0x4AA0BF: metalog_worker (metadatalog.c:324)
==90976==  Address 0x2103a022 is 34 bytes inside a block of size 4,096 alloc'd
==90976==    at 0x483BE45: memalign (vg_replace_malloc.c:906)
==90976==    by 0x483BF47: posix_memalign (vg_replace_malloc.c:1070)
==90976==    by 0x4ACF6F: create_metadata_logfile (logfile.c:329)
==90976==    by 0x4AE804: add_new_metadata_logfile (logfile.c:738)
==90976==    by 0x4A9546: metalog_try_link_new_metadata_logfile (metadatalog.c:137)
==90976==    by 0x4B049A: metalog_do_compaction (compaction.c:282)
==90976==    by 0x4A96E2: metalog_test_quota (metadatalog.c:164)
==90976==    by 0x4A9D2A: timer_cb (metadatalog.c:264)
==90976==    by 0x4D68915: uv__run_timers (in /usr/lib64/libuv.so.1.0.0)
==90976==    by 0x4D6BDC9: uv_run (in /usr/lib64/libuv.so.1.0.0)
==90976==    by 0x4AA0BF: metalog_worker (metadatalog.c:324)
==90976==    by 0x4F0D4E1: start_thread (in /usr/lib64/libpthread-2.30.so)
==90976== 
^C==90976== Thread 1:
==90976== Invalid read of size 8
==90976==    at 0x498C53: rrdvar_index_del (rrdvar.c:40)
==90976==    by 0x498D9D: rrdvar_free (rrdvar.c:60)
==90976==    by 0x497F45: rrdsetvar_free_variables (rrdsetvar.c:21)
==90976==    by 0x498672: rrdsetvar_free (rrdsetvar.c:125)
==90976==    by 0x4916A5: rrdset_free (rrdset.c:334)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Address 0x11b17aa8 is 24 bytes inside a block of size 64 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E25: rrdvar_free (rrdvar.c:68)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483BB1A: calloc (vg_replace_malloc.c:760)
==90976==    by 0x42D346: callocz (libnetdata.c:183)
==90976==    by 0x498F1F: rrdvar_create_and_index (rrdvar.c:81)
==90976==    by 0x498201: rrdsetvar_create_variables (rrdsetvar.c:73)
==90976==    by 0x498447: rrdsetvar_create (rrdsetvar.c:96)
==90976==    by 0x494007: rrdset_create_custom (rrdset.c:907)
==90976==    by 0x4AEBE2: metalog_pluginsd_chart_action (metalogpluginsd.c:17)
==90976==    by 0x479ED1: pluginsd_chart (pluginsd_parser.c:354)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976==    by 0x4ADD8D: load_metadata_logfile (logfile.c:569)
==90976== 
==90976== Invalid read of size 1
==90976==    at 0x483CC46: __strlen_sse2 (vg_replace_strmem.c:461)
==90976==    by 0x4F935FD: __vfprintf_internal (in /usr/lib64/libc-2.30.so)
==90976==    by 0x4F945FD: buffered_vfprintf (in /usr/lib64/libc-2.30.so)
==90976==    by 0x4F91653: __vfprintf_internal (in /usr/lib64/libc-2.30.so)
==90976==    by 0x432170: error_int (log.c:781)
==90976==    by 0x498C7D: rrdvar_index_del (rrdvar.c:40)
==90976==    by 0x498D9D: rrdvar_free (rrdvar.c:60)
==90976==    by 0x497F45: rrdsetvar_free_variables (rrdsetvar.c:21)
==90976==    by 0x498672: rrdsetvar_free (rrdsetvar.c:125)
==90976==    by 0x4916A5: rrdset_free (rrdset.c:334)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==  Address 0x11b17a20 is 0 bytes inside a block of size 36 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E19: rrdvar_free (rrdvar.c:67)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483980B: malloc (vg_replace_malloc.c:307)
==90976==    by 0x4FB5F7E: strdup (in /usr/lib64/libc-2.30.so)
==90976==    by 0x42D1FA: strdupz (libnetdata.c:166)
==90976==    by 0x498E7D: rrdvar_create_and_index (rrdvar.c:73)
==90976==    by 0x498201: rrdsetvar_create_variables (rrdsetvar.c:73)
==90976==    by 0x498447: rrdsetvar_create (rrdsetvar.c:96)
==90976==    by 0x494007: rrdset_create_custom (rrdset.c:907)
==90976==    by 0x4AEBE2: metalog_pluginsd_chart_action (metalogpluginsd.c:17)
==90976==    by 0x479ED1: pluginsd_chart (pluginsd_parser.c:354)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976== 
==90976== Invalid read of size 1
==90976==    at 0x483CC54: __strlen_sse2 (vg_replace_strmem.c:461)
==90976==    by 0x4F935FD: __vfprintf_internal (in /usr/lib64/libc-2.30.so)
==90976==    by 0x4F945FD: buffered_vfprintf (in /usr/lib64/libc-2.30.so)
==90976==    by 0x4F91653: __vfprintf_internal (in /usr/lib64/libc-2.30.so)
==90976==    by 0x432170: error_int (log.c:781)
==90976==    by 0x498C7D: rrdvar_index_del (rrdvar.c:40)
==90976==    by 0x498D9D: rrdvar_free (rrdvar.c:60)
==90976==    by 0x497F45: rrdsetvar_free_variables (rrdsetvar.c:21)
==90976==    by 0x498672: rrdsetvar_free (rrdsetvar.c:125)
==90976==    by 0x4916A5: rrdset_free (rrdset.c:334)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==  Address 0x11b17a21 is 1 bytes inside a block of size 36 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E19: rrdvar_free (rrdvar.c:67)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483980B: malloc (vg_replace_malloc.c:307)
==90976==    by 0x4FB5F7E: strdup (in /usr/lib64/libc-2.30.so)
==90976==    by 0x42D1FA: strdupz (libnetdata.c:166)
==90976==    by 0x498E7D: rrdvar_create_and_index (rrdvar.c:73)
==90976==    by 0x498201: rrdsetvar_create_variables (rrdsetvar.c:73)
==90976==    by 0x498447: rrdsetvar_create (rrdsetvar.c:96)
==90976==    by 0x494007: rrdset_create_custom (rrdset.c:907)
==90976==    by 0x4AEBE2: metalog_pluginsd_chart_action (metalogpluginsd.c:17)
==90976==    by 0x479ED1: pluginsd_chart (pluginsd_parser.c:354)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976== 
==90976== Invalid read of size 1
==90976==    at 0x4841410: mempcpy (vg_replace_strmem.c:1536)
==90976==    by 0x4FAAA27: _IO_default_xsputn (in /usr/lib64/libc-2.30.so)
==90976==    by 0x4F91A81: __vfprintf_internal (in /usr/lib64/libc-2.30.so)
==90976==    by 0x4F945FD: buffered_vfprintf (in /usr/lib64/libc-2.30.so)
==90976==    by 0x4F91653: __vfprintf_internal (in /usr/lib64/libc-2.30.so)
==90976==    by 0x432170: error_int (log.c:781)
==90976==    by 0x498C7D: rrdvar_index_del (rrdvar.c:40)
==90976==    by 0x498D9D: rrdvar_free (rrdvar.c:60)
==90976==    by 0x497F45: rrdsetvar_free_variables (rrdsetvar.c:21)
==90976==    by 0x498672: rrdsetvar_free (rrdsetvar.c:125)
==90976==    by 0x4916A5: rrdset_free (rrdset.c:334)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==  Address 0x11b17a42 is 34 bytes inside a block of size 36 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E19: rrdvar_free (rrdvar.c:67)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483980B: malloc (vg_replace_malloc.c:307)
==90976==    by 0x4FB5F7E: strdup (in /usr/lib64/libc-2.30.so)
==90976==    by 0x42D1FA: strdupz (libnetdata.c:166)
==90976==    by 0x498E7D: rrdvar_create_and_index (rrdvar.c:73)
==90976==    by 0x498201: rrdsetvar_create_variables (rrdsetvar.c:73)
==90976==    by 0x498447: rrdsetvar_create (rrdsetvar.c:96)
==90976==    by 0x494007: rrdset_create_custom (rrdset.c:907)
==90976==    by 0x4AEBE2: metalog_pluginsd_chart_action (metalogpluginsd.c:17)
==90976==    by 0x479ED1: pluginsd_chart (pluginsd_parser.c:354)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976== 
==90976== Invalid read of size 1
==90976==    at 0x4841422: mempcpy (vg_replace_strmem.c:1536)
==90976==    by 0x4FAAA27: _IO_default_xsputn (in /usr/lib64/libc-2.30.so)
==90976==    by 0x4F91A81: __vfprintf_internal (in /usr/lib64/libc-2.30.so)
==90976==    by 0x4F945FD: buffered_vfprintf (in /usr/lib64/libc-2.30.so)
==90976==    by 0x4F91653: __vfprintf_internal (in /usr/lib64/libc-2.30.so)
==90976==    by 0x432170: error_int (log.c:781)
==90976==    by 0x498C7D: rrdvar_index_del (rrdvar.c:40)
==90976==    by 0x498D9D: rrdvar_free (rrdvar.c:60)
==90976==    by 0x497F45: rrdsetvar_free_variables (rrdsetvar.c:21)
==90976==    by 0x498672: rrdsetvar_free (rrdsetvar.c:125)
==90976==    by 0x4916A5: rrdset_free (rrdset.c:334)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==  Address 0x11b17a40 is 32 bytes inside a block of size 36 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E19: rrdvar_free (rrdvar.c:67)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483980B: malloc (vg_replace_malloc.c:307)
==90976==    by 0x4FB5F7E: strdup (in /usr/lib64/libc-2.30.so)
==90976==    by 0x42D1FA: strdupz (libnetdata.c:166)
==90976==    by 0x498E7D: rrdvar_create_and_index (rrdvar.c:73)
==90976==    by 0x498201: rrdsetvar_create_variables (rrdsetvar.c:73)
==90976==    by 0x498447: rrdsetvar_create (rrdsetvar.c:96)
==90976==    by 0x494007: rrdset_create_custom (rrdset.c:907)
==90976==    by 0x4AEBE2: metalog_pluginsd_chart_action (metalogpluginsd.c:17)
==90976==    by 0x479ED1: pluginsd_chart (pluginsd_parser.c:354)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976== 
==90976== Invalid read of size 8
==90976==    at 0x498DB8: rrdvar_free (rrdvar.c:61)
==90976==    by 0x497F45: rrdsetvar_free_variables (rrdsetvar.c:21)
==90976==    by 0x498672: rrdsetvar_free (rrdsetvar.c:125)
==90976==    by 0x4916A5: rrdset_free (rrdset.c:334)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Address 0x11b17aa8 is 24 bytes inside a block of size 64 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E25: rrdvar_free (rrdvar.c:68)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483BB1A: calloc (vg_replace_malloc.c:760)
==90976==    by 0x42D346: callocz (libnetdata.c:183)
==90976==    by 0x498F1F: rrdvar_create_and_index (rrdvar.c:81)
==90976==    by 0x498201: rrdsetvar_create_variables (rrdsetvar.c:73)
==90976==    by 0x498447: rrdsetvar_create (rrdsetvar.c:96)
==90976==    by 0x494007: rrdset_create_custom (rrdset.c:907)
==90976==    by 0x4AEBE2: metalog_pluginsd_chart_action (metalogpluginsd.c:17)
==90976==    by 0x479ED1: pluginsd_chart (pluginsd_parser.c:354)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976==    by 0x4ADD8D: load_metadata_logfile (logfile.c:569)
==90976== 
==90976== Invalid read of size 4
==90976==    at 0x498DF0: rrdvar_free (rrdvar.c:64)
==90976==    by 0x497F45: rrdsetvar_free_variables (rrdsetvar.c:21)
==90976==    by 0x498672: rrdsetvar_free (rrdsetvar.c:125)
==90976==    by 0x4916A5: rrdset_free (rrdset.c:334)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Address 0x11b17ab8 is 40 bytes inside a block of size 64 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E25: rrdvar_free (rrdvar.c:68)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483BB1A: calloc (vg_replace_malloc.c:760)
==90976==    by 0x42D346: callocz (libnetdata.c:183)
==90976==    by 0x498F1F: rrdvar_create_and_index (rrdvar.c:81)
==90976==    by 0x498201: rrdsetvar_create_variables (rrdsetvar.c:73)
==90976==    by 0x498447: rrdsetvar_create (rrdsetvar.c:96)
==90976==    by 0x494007: rrdset_create_custom (rrdset.c:907)
==90976==    by 0x4AEBE2: metalog_pluginsd_chart_action (metalogpluginsd.c:17)
==90976==    by 0x479ED1: pluginsd_chart (pluginsd_parser.c:354)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976==    by 0x4ADD8D: load_metadata_logfile (logfile.c:569)
==90976== 
==90976== Invalid read of size 8
==90976==    at 0x498E0E: rrdvar_free (rrdvar.c:67)
==90976==    by 0x497F45: rrdsetvar_free_variables (rrdsetvar.c:21)
==90976==    by 0x498672: rrdsetvar_free (rrdsetvar.c:125)
==90976==    by 0x4916A5: rrdset_free (rrdset.c:334)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Address 0x11b17aa8 is 24 bytes inside a block of size 64 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E25: rrdvar_free (rrdvar.c:68)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483BB1A: calloc (vg_replace_malloc.c:760)
==90976==    by 0x42D346: callocz (libnetdata.c:183)
==90976==    by 0x498F1F: rrdvar_create_and_index (rrdvar.c:81)
==90976==    by 0x498201: rrdsetvar_create_variables (rrdsetvar.c:73)
==90976==    by 0x498447: rrdsetvar_create (rrdsetvar.c:96)
==90976==    by 0x494007: rrdset_create_custom (rrdset.c:907)
==90976==    by 0x4AEBE2: metalog_pluginsd_chart_action (metalogpluginsd.c:17)
==90976==    by 0x479ED1: pluginsd_chart (pluginsd_parser.c:354)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976==    by 0x4ADD8D: load_metadata_logfile (logfile.c:569)
==90976== 
==90976== Invalid free() / delete / delete[] / realloc()
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E19: rrdvar_free (rrdvar.c:67)
==90976==    by 0x497F45: rrdsetvar_free_variables (rrdsetvar.c:21)
==90976==    by 0x498672: rrdsetvar_free (rrdsetvar.c:125)
==90976==    by 0x4916A5: rrdset_free (rrdset.c:334)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Address 0x11b17a20 is 0 bytes inside a block of size 36 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E19: rrdvar_free (rrdvar.c:67)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483980B: malloc (vg_replace_malloc.c:307)
==90976==    by 0x4FB5F7E: strdup (in /usr/lib64/libc-2.30.so)
==90976==    by 0x42D1FA: strdupz (libnetdata.c:166)
==90976==    by 0x498E7D: rrdvar_create_and_index (rrdvar.c:73)
==90976==    by 0x498201: rrdsetvar_create_variables (rrdsetvar.c:73)
==90976==    by 0x498447: rrdsetvar_create (rrdsetvar.c:96)
==90976==    by 0x494007: rrdset_create_custom (rrdset.c:907)
==90976==    by 0x4AEBE2: metalog_pluginsd_chart_action (metalogpluginsd.c:17)
==90976==    by 0x479ED1: pluginsd_chart (pluginsd_parser.c:354)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976== 
==90976== Invalid free() / delete / delete[] / realloc()
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E25: rrdvar_free (rrdvar.c:68)
==90976==    by 0x497F45: rrdsetvar_free_variables (rrdsetvar.c:21)
==90976==    by 0x498672: rrdsetvar_free (rrdsetvar.c:125)
==90976==    by 0x4916A5: rrdset_free (rrdset.c:334)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Address 0x11b17a90 is 0 bytes inside a block of size 64 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E25: rrdvar_free (rrdvar.c:68)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483BB1A: calloc (vg_replace_malloc.c:760)
==90976==    by 0x42D346: callocz (libnetdata.c:183)
==90976==    by 0x498F1F: rrdvar_create_and_index (rrdvar.c:81)
==90976==    by 0x498201: rrdsetvar_create_variables (rrdsetvar.c:73)
==90976==    by 0x498447: rrdsetvar_create (rrdsetvar.c:96)
==90976==    by 0x494007: rrdset_create_custom (rrdset.c:907)
==90976==    by 0x4AEBE2: metalog_pluginsd_chart_action (metalogpluginsd.c:17)
==90976==    by 0x479ED1: pluginsd_chart (pluginsd_parser.c:354)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976==    by 0x4ADD8D: load_metadata_logfile (logfile.c:569)
==90976== 
==90976== Invalid read of size 8
==90976==    at 0x498C53: rrdvar_index_del (rrdvar.c:40)
==90976==    by 0x498D9D: rrdvar_free (rrdvar.c:60)
==90976==    by 0x488E6B: rrddimvar_free_variables (rrddimvar.c:27)
==90976==    by 0x489AEF: rrddimvar_free (rrddimvar.c:199)
==90976==    by 0x48852B: rrddim_free_custom (rrddim.c:493)
==90976==    by 0x4916FB: rrdset_free (rrdset.c:336)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Address 0x9d56c18 is 24 bytes inside a block of size 64 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E25: rrdvar_free (rrdvar.c:68)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483BB1A: calloc (vg_replace_malloc.c:760)
==90976==    by 0x42D346: callocz (libnetdata.c:183)
==90976==    by 0x498F1F: rrdvar_create_and_index (rrdvar.c:81)
==90976==    by 0x489524: rrddimvar_create_variables (rrddimvar.c:134)
==90976==    by 0x48992B: rrddimvar_create (rrddimvar.c:176)
==90976==    by 0x4880F1: rrddim_add_custom (rrddim.c:419)
==90976==    by 0x4AEE46: metalog_pluginsd_dimension_action (metalogpluginsd.c:70)
==90976==    by 0x47A224: pluginsd_dimension (pluginsd_parser.c:412)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976==    by 0x4ADD8D: load_metadata_logfile (logfile.c:569)
==90976== 
==90976== Invalid read of size 8
==90976==    at 0x498DB8: rrdvar_free (rrdvar.c:61)
==90976==    by 0x488E6B: rrddimvar_free_variables (rrddimvar.c:27)
==90976==    by 0x489AEF: rrddimvar_free (rrddimvar.c:199)
==90976==    by 0x48852B: rrddim_free_custom (rrddim.c:493)
==90976==    by 0x4916FB: rrdset_free (rrdset.c:336)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Address 0x9d56c18 is 24 bytes inside a block of size 64 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E25: rrdvar_free (rrdvar.c:68)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483BB1A: calloc (vg_replace_malloc.c:760)
==90976==    by 0x42D346: callocz (libnetdata.c:183)
==90976==    by 0x498F1F: rrdvar_create_and_index (rrdvar.c:81)
==90976==    by 0x489524: rrddimvar_create_variables (rrddimvar.c:134)
==90976==    by 0x48992B: rrddimvar_create (rrddimvar.c:176)
==90976==    by 0x4880F1: rrddim_add_custom (rrddim.c:419)
==90976==    by 0x4AEE46: metalog_pluginsd_dimension_action (metalogpluginsd.c:70)
==90976==    by 0x47A224: pluginsd_dimension (pluginsd_parser.c:412)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976==    by 0x4ADD8D: load_metadata_logfile (logfile.c:569)
==90976== 
==90976== Invalid read of size 4
==90976==    at 0x498DF0: rrdvar_free (rrdvar.c:64)
==90976==    by 0x488E6B: rrddimvar_free_variables (rrddimvar.c:27)
==90976==    by 0x489AEF: rrddimvar_free (rrddimvar.c:199)
==90976==    by 0x48852B: rrddim_free_custom (rrddim.c:493)
==90976==    by 0x4916FB: rrdset_free (rrdset.c:336)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Address 0x9d56c28 is 40 bytes inside a block of size 64 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E25: rrdvar_free (rrdvar.c:68)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483BB1A: calloc (vg_replace_malloc.c:760)
==90976==    by 0x42D346: callocz (libnetdata.c:183)
==90976==    by 0x498F1F: rrdvar_create_and_index (rrdvar.c:81)
==90976==    by 0x489524: rrddimvar_create_variables (rrddimvar.c:134)
==90976==    by 0x48992B: rrddimvar_create (rrddimvar.c:176)
==90976==    by 0x4880F1: rrddim_add_custom (rrddim.c:419)
==90976==    by 0x4AEE46: metalog_pluginsd_dimension_action (metalogpluginsd.c:70)
==90976==    by 0x47A224: pluginsd_dimension (pluginsd_parser.c:412)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976==    by 0x4ADD8D: load_metadata_logfile (logfile.c:569)
==90976== 
==90976== Invalid read of size 8
==90976==    at 0x498E0E: rrdvar_free (rrdvar.c:67)
==90976==    by 0x488E6B: rrddimvar_free_variables (rrddimvar.c:27)
==90976==    by 0x489AEF: rrddimvar_free (rrddimvar.c:199)
==90976==    by 0x48852B: rrddim_free_custom (rrddim.c:493)
==90976==    by 0x4916FB: rrdset_free (rrdset.c:336)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Address 0x9d56c18 is 24 bytes inside a block of size 64 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E25: rrdvar_free (rrdvar.c:68)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483BB1A: calloc (vg_replace_malloc.c:760)
==90976==    by 0x42D346: callocz (libnetdata.c:183)
==90976==    by 0x498F1F: rrdvar_create_and_index (rrdvar.c:81)
==90976==    by 0x489524: rrddimvar_create_variables (rrddimvar.c:134)
==90976==    by 0x48992B: rrddimvar_create (rrddimvar.c:176)
==90976==    by 0x4880F1: rrddim_add_custom (rrddim.c:419)
==90976==    by 0x4AEE46: metalog_pluginsd_dimension_action (metalogpluginsd.c:70)
==90976==    by 0x47A224: pluginsd_dimension (pluginsd_parser.c:412)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976==    by 0x4ADD8D: load_metadata_logfile (logfile.c:569)
==90976== 
==90976== Invalid free() / delete / delete[] / realloc()
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E19: rrdvar_free (rrdvar.c:67)
==90976==    by 0x488E6B: rrddimvar_free_variables (rrddimvar.c:27)
==90976==    by 0x489AEF: rrddimvar_free (rrddimvar.c:199)
==90976==    by 0x48852B: rrddim_free_custom (rrddim.c:493)
==90976==    by 0x4916FB: rrdset_free (rrdset.c:336)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Address 0x11b1a7d0 is 0 bytes inside a block of size 26 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E19: rrdvar_free (rrdvar.c:67)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483980B: malloc (vg_replace_malloc.c:307)
==90976==    by 0x4FB5F7E: strdup (in /usr/lib64/libc-2.30.so)
==90976==    by 0x42D1FA: strdupz (libnetdata.c:166)
==90976==    by 0x498E7D: rrdvar_create_and_index (rrdvar.c:73)
==90976==    by 0x489524: rrddimvar_create_variables (rrddimvar.c:134)
==90976==    by 0x48992B: rrddimvar_create (rrddimvar.c:176)
==90976==    by 0x4880F1: rrddim_add_custom (rrddim.c:419)
==90976==    by 0x4AEE46: metalog_pluginsd_dimension_action (metalogpluginsd.c:70)
==90976==    by 0x47A224: pluginsd_dimension (pluginsd_parser.c:412)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976== 
==90976== Invalid free() / delete / delete[] / realloc()
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E25: rrdvar_free (rrdvar.c:68)
==90976==    by 0x488E6B: rrddimvar_free_variables (rrddimvar.c:27)
==90976==    by 0x489AEF: rrddimvar_free (rrddimvar.c:199)
==90976==    by 0x48852B: rrddim_free_custom (rrddim.c:493)
==90976==    by 0x4916FB: rrdset_free (rrdset.c:336)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Address 0x9d56c00 is 0 bytes inside a block of size 64 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E25: rrdvar_free (rrdvar.c:68)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483BB1A: calloc (vg_replace_malloc.c:760)
==90976==    by 0x42D346: callocz (libnetdata.c:183)
==90976==    by 0x498F1F: rrdvar_create_and_index (rrdvar.c:81)
==90976==    by 0x489524: rrddimvar_create_variables (rrddimvar.c:134)
==90976==    by 0x48992B: rrddimvar_create (rrddimvar.c:176)
==90976==    by 0x4880F1: rrddim_add_custom (rrddim.c:419)
==90976==    by 0x4AEE46: metalog_pluginsd_dimension_action (metalogpluginsd.c:70)
==90976==    by 0x47A224: pluginsd_dimension (pluginsd_parser.c:412)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976==    by 0x4ADD8D: load_metadata_logfile (logfile.c:569)
==90976== 
==90976== Invalid read of size 8
==90976==    at 0x498C53: rrdvar_index_del (rrdvar.c:40)
==90976==    by 0x498D9D: rrdvar_free (rrdvar.c:60)
==90976==    by 0x488ED8: rrddimvar_free_variables (rrddimvar.c:33)
==90976==    by 0x489AEF: rrddimvar_free (rrddimvar.c:199)
==90976==    by 0x48852B: rrddim_free_custom (rrddim.c:493)
==90976==    by 0x4916FB: rrdset_free (rrdset.c:336)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Address 0x11b1a8c8 is 24 bytes inside a block of size 64 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E25: rrdvar_free (rrdvar.c:68)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483BB1A: calloc (vg_replace_malloc.c:760)
==90976==    by 0x42D346: callocz (libnetdata.c:183)
==90976==    by 0x498F1F: rrdvar_create_and_index (rrdvar.c:81)
==90976==    by 0x4895D1: rrddimvar_create_variables (rrddimvar.c:136)
==90976==    by 0x48992B: rrddimvar_create (rrddimvar.c:176)
==90976==    by 0x4880F1: rrddim_add_custom (rrddim.c:419)
==90976==    by 0x4AEE46: metalog_pluginsd_dimension_action (metalogpluginsd.c:70)
==90976==    by 0x47A224: pluginsd_dimension (pluginsd_parser.c:412)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976==    by 0x4ADD8D: load_metadata_logfile (logfile.c:569)
==90976== 
==90976== Invalid read of size 8
==90976==    at 0x498DB8: rrdvar_free (rrdvar.c:61)
==90976==    by 0x488ED8: rrddimvar_free_variables (rrddimvar.c:33)
==90976==    by 0x489AEF: rrddimvar_free (rrddimvar.c:199)
==90976==    by 0x48852B: rrddim_free_custom (rrddim.c:493)
==90976==    by 0x4916FB: rrdset_free (rrdset.c:336)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Address 0x11b1a8c8 is 24 bytes inside a block of size 64 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E25: rrdvar_free (rrdvar.c:68)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483BB1A: calloc (vg_replace_malloc.c:760)
==90976==    by 0x42D346: callocz (libnetdata.c:183)
==90976==    by 0x498F1F: rrdvar_create_and_index (rrdvar.c:81)
==90976==    by 0x4895D1: rrddimvar_create_variables (rrddimvar.c:136)
==90976==    by 0x48992B: rrddimvar_create (rrddimvar.c:176)
==90976==    by 0x4880F1: rrddim_add_custom (rrddim.c:419)
==90976==    by 0x4AEE46: metalog_pluginsd_dimension_action (metalogpluginsd.c:70)
==90976==    by 0x47A224: pluginsd_dimension (pluginsd_parser.c:412)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976==    by 0x4ADD8D: load_metadata_logfile (logfile.c:569)
==90976== 
==90976== Invalid read of size 4
==90976==    at 0x498DF0: rrdvar_free (rrdvar.c:64)
==90976==    by 0x488ED8: rrddimvar_free_variables (rrddimvar.c:33)
==90976==    by 0x489AEF: rrddimvar_free (rrddimvar.c:199)
==90976==    by 0x48852B: rrddim_free_custom (rrddim.c:493)
==90976==    by 0x4916FB: rrdset_free (rrdset.c:336)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Address 0x11b1a8d8 is 40 bytes inside a block of size 64 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E25: rrdvar_free (rrdvar.c:68)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483BB1A: calloc (vg_replace_malloc.c:760)
==90976==    by 0x42D346: callocz (libnetdata.c:183)
==90976==    by 0x498F1F: rrdvar_create_and_index (rrdvar.c:81)
==90976==    by 0x4895D1: rrddimvar_create_variables (rrddimvar.c:136)
==90976==    by 0x48992B: rrddimvar_create (rrddimvar.c:176)
==90976==    by 0x4880F1: rrddim_add_custom (rrddim.c:419)
==90976==    by 0x4AEE46: metalog_pluginsd_dimension_action (metalogpluginsd.c:70)
==90976==    by 0x47A224: pluginsd_dimension (pluginsd_parser.c:412)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976==    by 0x4ADD8D: load_metadata_logfile (logfile.c:569)
==90976== 
==90976== Invalid read of size 8
==90976==    at 0x498E0E: rrdvar_free (rrdvar.c:67)
==90976==    by 0x488ED8: rrddimvar_free_variables (rrddimvar.c:33)
==90976==    by 0x489AEF: rrddimvar_free (rrddimvar.c:199)
==90976==    by 0x48852B: rrddim_free_custom (rrddim.c:493)
==90976==    by 0x4916FB: rrdset_free (rrdset.c:336)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Address 0x11b1a8c8 is 24 bytes inside a block of size 64 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E25: rrdvar_free (rrdvar.c:68)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483BB1A: calloc (vg_replace_malloc.c:760)
==90976==    by 0x42D346: callocz (libnetdata.c:183)
==90976==    by 0x498F1F: rrdvar_create_and_index (rrdvar.c:81)
==90976==    by 0x4895D1: rrddimvar_create_variables (rrddimvar.c:136)
==90976==    by 0x48992B: rrddimvar_create (rrddimvar.c:176)
==90976==    by 0x4880F1: rrddim_add_custom (rrddim.c:419)
==90976==    by 0x4AEE46: metalog_pluginsd_dimension_action (metalogpluginsd.c:70)
==90976==    by 0x47A224: pluginsd_dimension (pluginsd_parser.c:412)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976==    by 0x4ADD8D: load_metadata_logfile (logfile.c:569)
==90976== 
==90976== Invalid free() / delete / delete[] / realloc()
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E19: rrdvar_free (rrdvar.c:67)
==90976==    by 0x488ED8: rrddimvar_free_variables (rrddimvar.c:33)
==90976==    by 0x489AEF: rrddimvar_free (rrddimvar.c:199)
==90976==    by 0x48852B: rrddim_free_custom (rrddim.c:493)
==90976==    by 0x4916FB: rrdset_free (rrdset.c:336)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Address 0x11b1a830 is 0 bytes inside a block of size 49 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E19: rrdvar_free (rrdvar.c:67)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483980B: malloc (vg_replace_malloc.c:307)
==90976==    by 0x4FB5F7E: strdup (in /usr/lib64/libc-2.30.so)
==90976==    by 0x42D1FA: strdupz (libnetdata.c:166)
==90976==    by 0x498E7D: rrdvar_create_and_index (rrdvar.c:73)
==90976==    by 0x4895D1: rrddimvar_create_variables (rrddimvar.c:136)
==90976==    by 0x48992B: rrddimvar_create (rrddimvar.c:176)
==90976==    by 0x4880F1: rrddim_add_custom (rrddim.c:419)
==90976==    by 0x4AEE46: metalog_pluginsd_dimension_action (metalogpluginsd.c:70)
==90976==    by 0x47A224: pluginsd_dimension (pluginsd_parser.c:412)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976== 
==90976== Invalid free() / delete / delete[] / realloc()
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E25: rrdvar_free (rrdvar.c:68)
==90976==    by 0x488ED8: rrddimvar_free_variables (rrddimvar.c:33)
==90976==    by 0x489AEF: rrddimvar_free (rrddimvar.c:199)
==90976==    by 0x48852B: rrddim_free_custom (rrddim.c:493)
==90976==    by 0x4916FB: rrdset_free (rrdset.c:336)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Address 0x11b1a8b0 is 0 bytes inside a block of size 64 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E25: rrdvar_free (rrdvar.c:68)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483BB1A: calloc (vg_replace_malloc.c:760)
==90976==    by 0x42D346: callocz (libnetdata.c:183)
==90976==    by 0x498F1F: rrdvar_create_and_index (rrdvar.c:81)
==90976==    by 0x4895D1: rrddimvar_create_variables (rrddimvar.c:136)
==90976==    by 0x48992B: rrddimvar_create (rrddimvar.c:176)
==90976==    by 0x4880F1: rrddim_add_custom (rrddim.c:419)
==90976==    by 0x4AEE46: metalog_pluginsd_dimension_action (metalogpluginsd.c:70)
==90976==    by 0x47A224: pluginsd_dimension (pluginsd_parser.c:412)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976==    by 0x4ADD8D: load_metadata_logfile (logfile.c:569)
==90976== 
==90976== Invalid read of size 1
==90976==    at 0x4FAAA70: _IO_default_xsputn (in /usr/lib64/libc-2.30.so)
==90976==    by 0x4F91A81: __vfprintf_internal (in /usr/lib64/libc-2.30.so)
==90976==    by 0x4F945FD: buffered_vfprintf (in /usr/lib64/libc-2.30.so)
==90976==    by 0x4F91653: __vfprintf_internal (in /usr/lib64/libc-2.30.so)
==90976==    by 0x432170: error_int (log.c:781)
==90976==    by 0x498C7D: rrdvar_index_del (rrdvar.c:40)
==90976==    by 0x498D9D: rrdvar_free (rrdvar.c:60)
==90976==    by 0x488E6B: rrddimvar_free_variables (rrddimvar.c:27)
==90976==    by 0x489AEF: rrddimvar_free (rrddimvar.c:199)
==90976==    by 0x48852B: rrddim_free_custom (rrddim.c:493)
==90976==    by 0x4916FB: rrdset_free (rrdset.c:336)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==  Address 0x11b19d20 is 0 bytes inside a block of size 13 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E19: rrdvar_free (rrdvar.c:67)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483980B: malloc (vg_replace_malloc.c:307)
==90976==    by 0x4FB5F7E: strdup (in /usr/lib64/libc-2.30.so)
==90976==    by 0x42D1FA: strdupz (libnetdata.c:166)
==90976==    by 0x498E7D: rrdvar_create_and_index (rrdvar.c:73)
==90976==    by 0x489524: rrddimvar_create_variables (rrddimvar.c:134)
==90976==    by 0x48992B: rrddimvar_create (rrddimvar.c:176)
==90976==    by 0x4880BC: rrddim_add_custom (rrddim.c:418)
==90976==    by 0x4AEE46: metalog_pluginsd_dimension_action (metalogpluginsd.c:70)
==90976==    by 0x47A224: pluginsd_dimension (pluginsd_parser.c:412)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976== 
==90976== Invalid read of size 1
==90976==    at 0x4FAAA7F: _IO_default_xsputn (in /usr/lib64/libc-2.30.so)
==90976==    by 0x4F91A81: __vfprintf_internal (in /usr/lib64/libc-2.30.so)
==90976==    by 0x4F945FD: buffered_vfprintf (in /usr/lib64/libc-2.30.so)
==90976==    by 0x4F91653: __vfprintf_internal (in /usr/lib64/libc-2.30.so)
==90976==    by 0x432170: error_int (log.c:781)
==90976==    by 0x498C7D: rrdvar_index_del (rrdvar.c:40)
==90976==    by 0x498D9D: rrdvar_free (rrdvar.c:60)
==90976==    by 0x488E6B: rrddimvar_free_variables (rrddimvar.c:27)
==90976==    by 0x489AEF: rrddimvar_free (rrddimvar.c:199)
==90976==    by 0x48852B: rrddim_free_custom (rrddim.c:493)
==90976==    by 0x4916FB: rrdset_free (rrdset.c:336)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==  Address 0x11b19d22 is 2 bytes inside a block of size 13 free'd
==90976==    at 0x483AA0C: free (vg_replace_malloc.c:538)
==90976==    by 0x42D279: freez (libnetdata.c:173)
==90976==    by 0x498E19: rrdvar_free (rrdvar.c:67)
==90976==    by 0x499141: rrdvar_free_remaining_variables (rrdvar.c:124)
==90976==    by 0x48A0C7: rrdfamily_free (rrdfamily.c:54)
==90976==    by 0x491725: rrdset_free (rrdset.c:338)
==90976==    by 0x48CCDA: rrdhost_free (rrdhost.c:707)
==90976==    by 0x48D195: rrdhost_free_all (rrdhost.c:798)
==90976==    by 0x40F104: netdata_cleanup_and_exit (main.c:44)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
==90976==  Block was alloc'd at
==90976==    at 0x483980B: malloc (vg_replace_malloc.c:307)
==90976==    by 0x4FB5F7E: strdup (in /usr/lib64/libc-2.30.so)
==90976==    by 0x42D1FA: strdupz (libnetdata.c:166)
==90976==    by 0x498E7D: rrdvar_create_and_index (rrdvar.c:73)
==90976==    by 0x489524: rrddimvar_create_variables (rrddimvar.c:134)
==90976==    by 0x48992B: rrddimvar_create (rrddimvar.c:176)
==90976==    by 0x4880BC: rrddim_add_custom (rrddim.c:418)
==90976==    by 0x4AEE46: metalog_pluginsd_dimension_action (metalogpluginsd.c:70)
==90976==    by 0x47A224: pluginsd_dimension (pluginsd_parser.c:412)
==90976==    by 0x4CDE35: parser_action (parser.c:296)
==90976==    by 0x4AD4C8: replay_record (logfile.c:410)
==90976==    by 0x4ADB6D: iterate_records (logfile.c:526)
==90976== 
==90976== Thread 17:
==90976== Syscall param pwrite64(buf) points to uninitialised byte(s)
==90976==    at 0x4F1825F: pwrite (in /usr/lib64/libpthread-2.30.so)
==90976==    by 0x4D6F45D: ??? (in /usr/lib64/libuv.so.1.0.0)
==90976==    by 0x4D67B1D: ??? (in /usr/lib64/libuv.so.1.0.0)
==90976==    by 0x4F0D4E1: start_thread (in /usr/lib64/libpthread-2.30.so)
==90976==    by 0x50276A2: clone (in /usr/lib64/libc-2.30.so)
==90976==  Address 0x2459b961 is 2,401 bytes inside a block of size 4,096 alloc'd
==90976==    at 0x483BE45: memalign (vg_replace_malloc.c:906)
==90976==    by 0x483BF47: posix_memalign (vg_replace_malloc.c:1070)
==90976==    by 0x49F53D: wal_get_transaction_buffer (journalfile.c:83)
==90976==    by 0x49A77F: commit_data_extent (rrdengine.c:220)
==90976==    by 0x49A8DB: do_commit_transaction (rrdengine.c:244)
==90976==    by 0x49BD4A: do_flush_pages (rrdengine.c:571)
==90976==    by 0x49D563: rrdeng_worker (rrdengine.c:996)
==90976==    by 0x4F0D4E1: start_thread (in /usr/lib64/libpthread-2.30.so)
==90976==    by 0x50276A2: clone (in /usr/lib64/libc-2.30.so)
==90976== 
==90976== 
==90976== Process terminating with default action of signal 27 (SIGPROF)
==90976==    at 0x501D55A: __open_nocancel (in /usr/lib64/libc-2.30.so)
==90976==    by 0x502977F: write_gmon (in /usr/lib64/libc-2.30.so)
==90976==    by 0x5029F8D: _mcleanup (in /usr/lib64/libc-2.30.so)
==90976==    by 0x4F64E86: __run_exit_handlers (in /usr/lib64/libc-2.30.so)
==90976==    by 0x4F6503F: exit (in /usr/lib64/libc-2.30.so)
==90976==    by 0x40F19D: netdata_cleanup_and_exit (main.c:59)
==90976==    by 0x4143FB: signals_handle (signals.c:261)
==90976==    by 0x4136EA: main (main.c:1488)
```
