### PR TITLE
GUI Update check - use version instead of commit

### LINKED ISSUE #5201: Version checker shouldn't compare commits
##### Bug report summary
GUI version check shouldn't compare commits, it should compare content of `packaging/version` with what is installed.

##### OS / Environment
all

##### Component Name
webGUI

##### Steps To Reproduce
1. Install netdata from last nightly release (easiest way is to run latest docker container)
2. Go to web GUI
3. Check "Update" button

##### Expected behavior
Installing `latest` version shouldn't result in a notification about being **not** on latest version.

### PR DESCRIPTION
**Pull request by cakrit**
##### Summary
Fixes #5201 

##### Component Name
web/gui

##### Additional Information
With the new update process that is based on nightly builds instead of commits, the `Update` button on the web GUI is corrected to compare versions.

Possible netdata version formats are:
- `v1.12.0-rc3-37-nightly`
- `v1.12.0-rc3-37-a576f52`
- `v1.12.0-rc3`
- `v1.12.0`

Possible formats of https://github.com/netdata/netdata/blob/master/packaging/version are:
- `v1.12.0-rc3-37-nightly`
- `v1.12.0-rc3`
- `v1.12.0`

### CODE REVIEW

File: web/gui/main.js [hunk 1]
```diff
@@ -2819,89 +2819,43 @@ function versionLog(msg) {
...
 }
 
-function getGithubLatestCommit(callback) {
-    versionLog('Downloading latest git commit id info from github...');
+function getGithubLatestVersion(callback) {
+    versionLog('Downloading latest version id from github...');
 
     $.ajax({
-        url: 'https://api.github.com/repos/netdata/netdata/commits',
+        url: 'https://api.github.com/repositories/10744183/contents/packaging/version?ref=master',
```
Comment (paulfantom) [inline web/gui/main.js]: Why not just download this file? It's raw version is located at https://raw.githubusercontent.com/netdata/netdata/master/packaging/version and it is much clearer what is happening than using some magic link. Additionally you cannot run into GitHub rate limiter since it is not interacting with API.

File: web/gui/main.js [hunk 2]
```diff
@@ -2927,23 +2881,22 @@ function notifyForUpdate(force) {
...
+            var compare = 'https://github.com/netdata/netdata/blob/master/CHANGELOG.md';
+            versionLog('<p><big><strong>New version of netdata available!</strong></big></p><p>Latest version: <b><code>' + sha2 + '</code></b></p><p><a href="' + compare + '" target="_blank">Click here for the changes log</a> and<br/><a href="https://github.com/netdata/netdata/tree/master/packaging/installer/UPDATE.md" target="_blank">click here for directions on updating</a> your netdata installation.</p><p>We suggest to review the changes log for new features you may be interested, or important bug fixes you may need.<br/>Keeping your netdata updated is generally a good idea.</p>');
```
Comment (paulfantom) [inline web/gui/main.js]: We should probably link to docs site instead of github.

File: web/gui/main.js (hunk 1 above)
Comment (paulfantom) [reply web/gui/main.js]: ok
