### PR TITLE
Change query to store host system info values

### LINKED ISSUE #15273: [Bug]: Attempting to insert data into the database about XCP-ng results in a syntax error
### Bug description

See https://github.com/netdata/netdata/discussions/15271

### Expected behavior

The database insert/replace action should complete without error.

### Steps to reproduce

1. Set up a netdata parent node (I'm using 1.40.0).
2. Set up a Xen Server running XCP-ng 8.2.1 and ensure that netdata 1.19 is installed and running.
3. On the Xen Server stream the metrics to the parent node.
4. On the parentnode, check the error log.

### Installation method

kickstart.sh

### System info

```shell
# uname -a; grep -HvE "^#|URL" /etc/*release
Linux XN-XSVM 5.4.0-152-generic #169-Ubuntu SMP Tue Jun 6 22:23:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.6 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.6 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Version: netdata v1.40.0
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' 'CFLAGS=-static -O2 -I/openssl-static/include -I/libnetfilter-acct-static/include/libnetfilter_acct -I/usr/include/libmnl -pipe' 'LDFLAGS=-static -L/openssl-static/lib -L/libnetfilter-acct-static/lib -lnetfilter_acct -L/usr/lib -lmnl' 'PKG_CONFIG=pkg-config --static' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig:/libnetfilter-acct-static/lib/pkgconfig:/usr/lib/pkgconfig'
Install type: manual-static
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
    HTTPD (h2o):                YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    debugfs:                 YES
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

Fixes #15271 
Fixes #15273 

This PR changes slightly how to store the host system info values. It uses inserts with binds, which will address the issue of the values having characters like `'`. Indeed though this will do multiple inserts instead of one, but since they are done once on start it shouldn't be much of an issue.

##### Test Plan

Change something in your `/etc/os-release`, i.e. put the value `NAME="'my_favorite_os'"`. Without this PR there will be fails to store this information. The table `host_info` would be empty (on a new agent). With this PR it should store the data.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

File: database/sqlite/sqlite_metadata.c [hunk 1]
```diff
@@ -378,59 +378,90 @@ static int store_host_metadata(RRDHOST *host)
...
+
+    int store_rc = sqlite3_step_monitored(res);
+    if (unlikely(store_rc != SQLITE_DONE))
+        error_report("Failed to store host info value %s, rc = %d", name, rc);
+
+    rc = sqlite3_reset(res);
+    if (unlikely(rc != SQLITE_OK))
+        error_report("Failed to reset statement to store host info value %s, rc = %d", name, rc);
+
+    return rc != SQLITE_DONE;
```
Comment (thiagoftsm) [inline database/sqlite/sqlite_metadata.c:421]: Why are you testing `rc` instead `store_rc` here? Unless I am missing something in `sqlite3` functions, we should also verify if host info was stored and not only if we can store data again.

Comment (MrZammler) [reply database/sqlite/sqlite_metadata.c]: Thanks Thiago, fixed!

File: database/sqlite/sqlite_metadata.c [hunk 2]
```diff
@@ -378,59 +378,90 @@ static int store_host_metadata(RRDHOST *host)
...
+    ret += add_host_sysinfo_key_value("NETDATA_SYSTEM_TOTAL_DISK_SIZE", system_info->host_disk_space, &host->host_uuid);
+    ret += add_host_sysinfo_key_value("NETDATA_SYSTEM_KERNEL_VERSION", system_info->kernel_version, &host->host_uuid);
+    ret += add_host_sysinfo_key_value("NETDATA_SYSTEM_ARCHITECTURE", system_info->architecture, &host->host_uuid);
+    ret += add_host_sysinfo_key_value("NETDATA_SYSTEM_VIRTUALIZATION", system_info->virtualization, &host->host_uuid);
+    ret += add_host_sysinfo_key_value("NETDATA_SYSTEM_VIRT_DETECTION", system_info->virt_detection, &host->host_uuid);
+    ret += add_host_sysinfo_key_value("NETDATA_SYSTEM_CONTAINER", system_info->container, &host->host_uuid);
+    ret += add_host_sysinfo_key_value("NETDATA_SYSTEM_CONTAINER_DETECTION", system_info->container_detection, &host->host_uuid);
+    ret += add_host_sysinfo_key_value("NETDATA_HOST_IS_K8S_NODE", system_info->is_k8s_node, &host->host_uuid);
+
+    return !(24 == ret);
```
Comment (thiagoftsm) [inline database/sqlite/sqlite_metadata.c:464]: After last commit probably we need to modify this test, because we expect now to have `ret = 24`, so instead to return `true` on success awe are returning `false`, please, take a look in this comparision.

Comment (thiagoftsm) [reply database/sqlite/sqlite_metadata.c:464]: I am marking as resolved after a chat.

**Review by thiagoftsm — APPROVED** [review]
PR is working as expected locally and on cloud, LGTM!

**Review by stelfrag — APPROVED** [review]
