### PR TITLE
Fix crash when receiving malformed labels via streaming.

### LINKED ISSUE #9662: Netdata master crashing at streaming set-up
> 
> 
> Hi,
> 
> I have a similar if not the same issue with Netdata crashing at startup. I deleted all db files but it did not fix the issue.
> 
> Basic system informations
> 
> ```
> Linux ip-172-31-34-68 5.3.0-1030-aws #32~18.04.1-Ubuntu SMP Tue Jun 30 23:04:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> 2GB Ram
> 1CPU
> ```
> 
> Netdata version
> `v1.23.2-24-nightly`
> 
> Installation source
> `netdata.cloud`
> 
> Installation command & parameters
> `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`
> 
> Netdata acts as a master, receiving streams from multiple agents (5). All agents are updated to the last version.
> All worked fine until it began crashing, maybe an auto update is causing this issue?
> 
> Here is the valgrind output
> 
> ```
> ==5233== Memcheck, a memory error detector
> ==5233== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
> ==5233== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
> ==5233== Command: /usr/sbin/netdata -D
> ==5233== 
> 2020-07-20 13:17:46: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
> 2020-07-20 13:17:46: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
> ==5233== Thread 17 STREAM_RECEIVER:
> ==5233== Invalid read of size 1
> ==5233==    at 0x4C32CF2: strlen (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
> ==5233==    by 0x184200: create_label (in /usr/sbin/netdata)
> ==5233==    by 0x14CDA9: pluginsd_label_action (in /usr/sbin/netdata)
> ==5233==    by 0x14BD31: pluginsd_label (in /usr/sbin/netdata)
> ==5233==    by 0x17C8FD: parser_action (in /usr/sbin/netdata)
> ==5233==    by 0x1B4D27: rrdpush_receive (in /usr/sbin/netdata)
> ==5233==    by 0x1B5041: rrdpush_receiver_thread (in /usr/sbin/netdata)
> ==5233==    by 0x12F23F: thread_start (in /usr/sbin/netdata)
> ==5233==    by 0x559B6DA: start_thread (pthread_create.c:463)
> ==5233==    by 0x58D4A3E: clone (clone.S:95)
> ==5233==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
> ==5233== 
> ==5233== 
> ==5233== Process terminating with default action of signal 11 (SIGSEGV)
> ==5233==  Access not within mapped region at address 0x0
> ==5233==    at 0x4C32CF2: strlen (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
> ==5233==    by 0x184200: create_label (in /usr/sbin/netdata)
> ==5233==    by 0x14CDA9: pluginsd_label_action (in /usr/sbin/netdata)
> ==5233==    by 0x14BD31: pluginsd_label (in /usr/sbin/netdata)
> ==5233==    by 0x17C8FD: parser_action (in /usr/sbin/netdata)
> ==5233==    by 0x1B4D27: rrdpush_receive (in /usr/sbin/netdata)
> ==5233==    by 0x1B5041: rrdpush_receiver_thread (in /usr/sbin/netdata)
> ==5233==    by 0x12F23F: thread_start (in /usr/sbin/netdata)
> ==5233==    by 0x559B6DA: start_thread (pthread_create.c:463)
> ==5233==    by 0x58D4A3E: clone (clone.S:95)
> ==5233==  If you believe this happened as a result of a stack
> ==5233==  overflow in your program's main thread (unlikely but
> ==5233==  possible), you can try to increase the size of the
> ==5233==  main thread stack using the --main-stacksize= flag.
> ==5233==  The main thread stack size used in this run was 8388608.
> ==5233== 
> ==5233== HEAP SUMMARY:
> ==5233==     in use at exit: 14,270,977 bytes in 159,046 blocks
> ==5233==   total heap usage: 239,290 allocs, 80,244 frees, 28,620,770 bytes allocated
> ==5233== 
> ==5233== LEAK SUMMARY:
> ==5233==    definitely lost: 4,239 bytes in 418 blocks
> ==5233==    indirectly lost: 0 bytes in 0 blocks
> ==5233==      possibly lost: 210,543 bytes in 6,709 blocks
> ==5233==    still reachable: 14,056,195 bytes in 151,919 blocks
> ==5233==         suppressed: 0 bytes in 0 blocks
> ==5233== Rerun with --leak-check=full to see details of leaked memory
> ==5233== 
> ==5233== For counts of detected and suppressed errors, rerun with: -v
> ==5233== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
> ==5233== could not unlink /tmp/vgdb-pipe-from-vgdb-to-5233-by-root-on-???
> ==5233== could not unlink /tmp/vgdb-pipe-to-vgdb-from-5233-by-root-on-???
> ==5233== could not unlink /tmp/vgdb-pipe-shared-mem-vgdb-5233-by-root-on-???
> Segmentation fault (core dumped)
> ```
> 
> Also my logs are full of segfaults:
> 
> ```
> [Mon Jul 20 13:15:53 2020] STREAM_RECEIVER[4241]: segfault at 0 ip 00007fc230570811 sp 00007fc227ce1178 error 4 in libc-2.27.so[7fc2303e2000+1e7000]
> [Mon Jul 20 13:15:53 2020] Code: 2e 0f 1f 84 00 00 00 00 00 31 c0 c5 f8 77 c3 66 2e 0f 1f 84 00 00 00 00 00 89 f9 48 89 fa c5 f9 ef c0 83 e1 3f 83 f9 20 77 1f <c5> fd 74 0f c5 fd d7 c1 85 c0 0f 85 df 00 00 00 48 83 c7 20 83 e1
> [Mon Jul 20 13:16:24 2020] STREAM_RECEIVER[4473]: segfault at 0 ip 00007f6047dca811 sp 00007f6041d40178 error 4 in libc-2.27.so[7f6047c3c000+1e7000]
> [Mon Jul 20 13:16:24 2020] Code: 2e 0f 1f 84 00 00 00 00 00 31 c0 c5 f8 77 c3 66 2e 0f 1f 84 00 00 00 00 00 89 f9 48 89 fa c5 f9 ef c0 83 e1 3f 83 f9 20 77 1f <c5> fd 74 0f c5 fd d7 c1 85 c0 0f 85 df 00 00 00 48 83 c7 20 83 e1
> [Mon Jul 20 13:16:55 2020] STREAM_RECEIVER[4706]: segfault at 0 ip 00007f85dbf77811 sp 00007f85d5eed178 error 4 in libc-2.27.so[7f85dbde9000+1e7000]
> ```
> 
> If you need more info let me know.

@raduburla do you still have this problem after updating to the latest master?

_Originally posted by @mfundul in https://github.com/netdata/netdata/issues/9521#issuecomment-667010587_

### PR DESCRIPTION
**Pull request by mfundul**
##### Summary
Fixes #9662
##### Component Name
streaming
##### Test Plan
Create labels with empty values in the child node. Test that it does not crash.

### CODE REVIEW

File: daemon/system-info.sh [hunk 1]
```diff
@@ -30,6 +30,9 @@ if [ -z "${VIRTUALIZATION}" ]; then
                     VIRTUALIZATION="none"
             fi
     fi
+    if [ -z "${VIRTUALIZATION}" ]; then
+      VIRTUALIZATION="unknown"
```
Comment (amoss) [inline daemon/system-info.sh:34]: I think that `none` is the expected value instead of `unknown`. It affects the display on the Cloud view - @manos-saratsis will know.

Comment (amoss) [reply daemon/system-info.sh:34]: How does it change from the value on L14 to blank?

Comment (mfundul) [reply daemon/system-info.sh:34]: I just copied it from line 14 of the same file. Also, `none` means something different than `unknown`, so I don't know what we should do about that.

Comment (mfundul) [reply daemon/system-info.sh:34]: One of the commands could have errored, in the user's case it must have been `systemd-detect-virt -v`.

Comment (amoss) [reply daemon/system-info.sh:34]: It goes over the ACLK and changes the labels drawn on the node-view table. Give @manos-saratsis a chance to look into it

**Comment by amoss** [comment]
We are missing the same checks in `metalog_pluginsd_host` and the values pass straight through the host structure.

**Comment by mfundul** [comment]
> 
> 
> We are missing the same checks in `metalog_pluginsd_host` and the values pass straight through the host structure.

`metalog_pluginsd_host_action()` should have handled any errors in the strings supplied by `metalog_pluginsd_host()`.

**Comment by stelfrag** [comment]
> > We are missing the same checks in `metalog_pluginsd_host` and the values pass straight through the host structure.
> 
> `metalog_pluginsd_host_action()` should have handled any errors in the strings supplied by `metalog_pluginsd_host()`.

No labels parsed there

File: daemon/system-info.sh (hunk 1 above)
Comment (amoss) [reply daemon/system-info.sh:34]: L30 above sets it to none

**Comment by amoss** [comment]
I didn't see any checks, it just passes them directly to the host create. The other parser routines check the word pointer and handle missing entries before calling the action.

**Comment by mfundul** [comment]
> 
> 
> I didn't see any checks, it just passes them directly to the host create. The other parser routines check the word pointer and handle missing entries before calling the action.

That's true, we should copy all the checks that are in the streaming code.
