### PR TITLE
Fix flushing error threshold

### LINKED ISSUE #8384: Repeated dbengine global flushing errors for statsd
Hi,

I am having the same issue in v1.20 with the following setup : 

- 10 headless, memory = none collectors, streaming to a central colector
- Around 5k metrics / collector => ~50k metrics on the central collector
- Central collector is running in a lxc container (proxmox), storage is on a dedicated SSD (memory=dbengine)

- OS / Environment
> Linux grafana 4.15.18-12-pve #1 SMP PVE 4.15.18-35 (Wed, 13 Mar 2019 08:24:42 +0100) x86_64 GNU/Linux Debian 9.5 running in a LXC container (Proxmox) - 32GB of RAM (7GB used, the rest is used by the OS for caching), 8 CPU cores peak use 10%

- Netdata Version
>v1.20.0

- Component  Name
>dbengine

In error.log I get the messages : 
```
2020-03-11 10:04:09: netdata ERROR : MAIN : Failed to flush dirty buffers quickly enough in dbengine instance "/opt/netdata/var/cache/netdata/e295a868-5042-11e7-9bce-3863bb3e6c28/dbengine". M
etric data are being deleted, please reduce disk load or use a faster disk.
2020-03-11 10:04:09: netdata ERROR : MAIN : Failed to flush dirty buffers quickly enough in dbengine instance "/opt/netdata/var/cache/netdata/e295a868-5042-11e7-9bce-3863bb3e6c28/dbengine". M
etric data are being deleted, please reduce disk load or use a faster disk.
2020-03-11 10:04:09: netdata ERROR : MAIN : Failed to flush dirty buffers quickly enough in dbengine instance "/opt/netdata/var/cache/netdata/e295a868-5042-11e7-9bce-3863bb3e6c28/dbengine". M
etric data are being deleted, please reduce disk load or use a faster disk.
2020-03-11 10:04:09: netdata ERROR : MAIN : Failed to flush dirty buffers quickly enough in dbengine instance "/opt/netdata/var/cache/netdata/e295a868-5042-11e7-9bce-3863bb3e6c28/dbengine". M
etric data are being deleted, please reduce disk load or use a faster disk.
2020-03-11 10:04:09: netdata ERROR : MAIN : Failed to flush dirty buffers quickly enough in dbengine instance "/opt/netdata/var/cache/netdata/e295a868-5042-11e7-9bce-3863bb3e6c28/dbengine". M
etric data are being deleted, please reduce disk load or use a faster disk.
```

I also get alarms : 

image

Db engine related metrics : 
image

Storage metric for the volume used by the netdata central collector (the one having memory=dbengine), which seems to indicate the disk is not overloaded: 
image
image

Still on the central collector : 
image

```

[backend]
	enabled = yes
	type = graphite
	destination = tcp:127.0.0.1:2003
	data source = as-collected
	prefix = netdata
	update every = 30
	buffer on failures = 10000
	timeout ms = 20000


[global]
	update every = 1
	memory mode = dbengine
	page cache size = 192
	dbengine disk space = 2048
	errors flood protection period = 10
	errors to trigger flood protection = 100000


[statsd]
	decimal detail = 1
	update every (flushInterval) = 1
	max private charts allowed = 100000
	max private charts hard limit = 100001
	private charts memory mode = ram
	private charts history = 600
	private charts hidden = yes
	add dimension for number of events received = no
	gaps on gauges (deleteGauges) = yes
	listen backlog = 16384
	bind to = udp:*:8125 tcp:*:8125

```

_Originally posted by @jbfuzier in https://github.com/netdata/netdata/issues/7468#issuecomment-597529668_

### LINKED ISSUE #8421: dbengine loses recent metrics on abnormal exit
##### Bug report summary
When `dbengine` is in use and netdata abnormally exits, recent metrics are lost.

##### OS / Environment
Arch Linux, kernel version 5.5.9-zen1-2-zen.

##### Netdata version
netdata v1.20.0

##### Component Name
database

##### Steps To Reproduce
1. Run netdata for a few minutes
2. Kill netdata with an abnormal signal, such as ABRT.

##### Expected behavior
Ideally, no metrics should be lost.

But if lost is inevitable, is it possible to make the worst-case configurable?

### PR DESCRIPTION
**Pull request by mfundul**
##### Summary
Fixes #8421
Fixes #8384
##### Component Name
database/dbengine
##### Test Plan
Test scenario with dbengine page cache size smaller than the amount of metrics being generated by collectors.

Test scenario with disks being slower than metric data generation throughput for potential regression detection.

##### Additional Information
Fix flushing error threshold to account for inactive producers of dbengine instance.

### CODE REVIEW

File: daemon/commands.c [hunk 1]
```diff
@@ -510,7 +511,13 @@ static void command_thread(void *arg)
...
         goto error_after_pipe_bind;
     }
-    if ((ret = uv_listen((uv_stream_t *)&server_pipe, SOMAXCONN, connection_cb))) {
+    ret = uv_listen((uv_stream_t *)&server_pipe, SOMAXCONN, connection_cb);
+    if (ret) {
+        /* Fallback to backlog of 1 */
+        info("uv_listen() failed with backlog = %d, falling back to backlog = 1.", SOMAXCONN);
+        ret = uv_listen((uv_stream_t *)&server_pipe, 1, connection_cb);
+    }
+    if (ret) {
```
Comment (thiagoftsm) [inline daemon/commands.c]: This second check is necessary only case we `fallback to backlog of 1`, should we not move it for inside the previous `if`?

Comment (mfundul) [reply daemon/commands.c]: The logic is identical, I did not want to nest too much to improve readability. But if this confuses you, maybe readability is bad after all, hmm.

Comment (thiagoftsm) [reply daemon/commands.c]: No, it does not create any confusion while I am reading, I only requested, because case `ret` was tested to zero before, it won't change late. It was a requested related to performance.

Comment (mfundul) [reply daemon/commands.c]: In that case I prefer it to stay as it is, because I think readability is more important in this case, cause this is only called 1 time during initialization, which is at most 1 per day if you update daily. So I don't think performance is important here.

Comment (thiagoftsm) [reply daemon/commands.c]: I understood, this is the motive that I marked as `resolved`. I am testing the PR now to be sure that everything is right, I will approve it in few hours case there is not any problem.

**Comment by stelfrag** [comment]
Started the agent. Hitting control - C after a while I got core dump

```
#0  0x0000560f5d4a7661 in finalize_data_files (ctx=0x7fc4d6923010) at database/engine/datafile.c:416
#1  0x0000560f5d4a4fee in finalize_rrd_files (ctx=0x7fc4d6923010) at database/engine/rrdengine.c:729
#2  0x0000560f5d4ac86d in rrdeng_exit (ctx=0x7fc4d6923010) at database/engine/rrdengineapi.c:857
#3  0x0000560f5d498ea0 in rrdhost_free (host=0x560f5eb971d0) at database/rrdhost.c:644
#4  0x0000560f5d499187 in rrdhost_free_all () at database/rrdhost.c:702
#5  0x0000560f5d42f678 in netdata_cleanup_and_exit (ret=0) at daemon/main.c:44
#6  0x0000560f5d4346be in signals_handle () at daemon/signals.c:246
#7  0x0000560f5d433bf7 in main (argc=2, argv=0x7fff17351cb8) at daemon/main.c:1350
```

**Comment by mfundul** [comment]
> main

Hmm, I suspect this may be the case for master as well...

**Comment by mfundul** [comment]
@stelfrag I can't reproduce it with either master or this PR. Is this an infrequent occurrence?

**Comment by stelfrag** [comment]
> @stelfrag I can't reproduce it with either master or this PR. Is this an infrequent occurrence?

yes infrequent, it may have to do with corruptions in the db files at some point.  I have caused some 

```
2020-03-22 14:25:20: netdata ERROR : MAIN : (0084@database/e:read_extent_cb ): read_extent_cb: Extent at offset 442368(4072) was read from datafile 1-30. CRC32 check: FAILED
2020-03-22 14:25:20: netdata ERROR : MAIN : (0084@database/e:read_extent_cb ): read_extent_cb: Extent at offset 442368(4072) was read from datafile 1-30. CRC32 check: FAILED
2020-03-22 14:25:20: netdata ERROR : MAIN : (0084@database/e:read_extent_cb ): read_extent_cb: Extent at offset 442368(4072) was read from datafile 1-30. CRC32 check: FAILED
2020-03-22 14:25:25: netdata ERROR : MAIN : (0084@database/e:read_extent_cb ): read_extent_cb: Extent at offset 450560(4525) was read from datafile 1-30. CRC32 check: FAILED
```

yesterday...

**Comment by mfundul** [comment]
> 
> 
> > @stelfrag I can't reproduce it with either master or this PR. Is this an infrequent occurrence?
> 
> yes infrequent, it may have to do with corruptions in the db files at some point. I have caused some
> 
> ```
> 2020-03-22 14:25:20: netdata ERROR : MAIN : (0084@database/e:read_extent_cb ): read_extent_cb: Extent at offset 442368(4072) was read from datafile 1-30. CRC32 check: FAILED
> 2020-03-22 14:25:20: netdata ERROR : MAIN : (0084@database/e:read_extent_cb ): read_extent_cb: Extent at offset 442368(4072) was read from datafile 1-30. CRC32 check: FAILED
> 2020-03-22 14:25:20: netdata ERROR : MAIN : (0084@database/e:read_extent_cb ): read_extent_cb: Extent at offset 442368(4072) was read from datafile 1-30. CRC32 check: FAILED
> 2020-03-22 14:25:25: netdata ERROR : MAIN : (0084@database/e:read_extent_cb ): read_extent_cb: Extent at offset 450560(4525) was read from datafile 1-30. CRC32 check: FAILED
> ```
> 
> yesterday...

That's very interesting, can you create a new issue for me please? I don't see it being relevant to this PR.

**Comment by svenstaro** [comment]
Arch Linux maintainer here. Can we expect a release with this fix soon or should I backport it?

**Comment by mfundul** [comment]
> 
> 
> Arch Linux maintainer here. Can we expect a release with this fix soon or should I backport it?

@svenstaro will get back to you on that.

**Comment by mfundul** [comment]
@svenstaro we expect to release around April 6.

**Comment by svenstaro** [comment]
Ok cool, I can wait for that.
