### PR TITLE
Don't do fatal on error writing the health api management key.

### LINKED ISSUE #12568: [Bug]: Failure to create a management API key file should not shutdown the agent
### Bug description

When the agent fails to create a `management API key file` it will shutdown with a fatal error. It should log an error instead and continue operation. This api key is used in the health management API

### Expected behavior

The agent should start up normally

### Steps to reproduce

1. Configure agent so that the `netdata.api.key` resides in a location that cannot be written by the agent on startup by
setting the `"netdata management api key file` location in the `[registry]` section
2. Try to start the agent and notice that it fails

### Installation method

from source

### System info

```shell
Linux futura 5.13.0-37-generic #42-Ubuntu SMP Tue Mar 15 14:34:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=21.10
/etc/lsb-release:DISTRIB_CODENAME=impish
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 21.10"
/etc/os-release:PRETTY_NAME="Ubuntu 21.10"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="21.10"
/etc/os-release:VERSION="21.10 (Impish Indri)"
/etc/os-release:VERSION_CODENAME=impish
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=impish
```

### Netdata build info

```shell
Version: netdata v1.33.1-262-g89544cba0
Configure options:  '--prefix=/home/stelios/netdata-inst/netdata/usr' '--sysconfdir=/home/stelios/netdata-inst/netdata/etc' '--localstatedir=/home/stelios/netdata-inst/netdata/var' '--libexecdir=/home/stelios/netdata-inst/netdata/usr/libexec' '--libdir=/home/stelios/netdata-inst/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--disable-ml' '--disable-ebpf' '--with-bundled-protobuf' 'CFLAGS=-O0 -ggdb -Wall -Wextra -Wformat-truncation=2 -Wunused-result -Wformat-signedness -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           NO
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

Fixes #12568 

If for any reason there is trouble committing the Health API management key to disk, don't exit, but instead inform the user to fix the problem and provide the produced api key in the log file. This can be used to access the management API, but only during this session of Netdata.

##### Test Plan

Specify a readonly path to save the key (e.g. `/root/something` if running as a normal user) in field `netdata management api key file` under `registry` in `netdata.conf`. Using this PR the agent will keep running, and the printed key can be used to access the API.

### CODE REVIEW

File: web/api/web_api_v1.c [hunk 1]
```diff
@@ -137,16 +137,25 @@ char *get_mgmt_api_key(void) {
...
-            fatal("Cannot create unique management API key file '%s'. Please fix this.", api_key_filename);
+        if(fd == -1) {
+            error("Cannot create unique management API key file '%s'. Please fix this.", api_key_filename);
+            goto temp_key;
+        }
 
-        if(write(fd, guid, GUID_LEN) != GUID_LEN)
-            fatal("Cannot write the unique management API key file '%s'. Please fix this.", api_key_filename);
+        if(write(fd, guid, GUID_LEN) != GUID_LEN) {
+            error("Cannot write the unique management API key file '%s'. Please fix this.", api_key_filename);
```
Comment (thiagoftsm) [inline web/api/web_api_v1.c:146]: A suggestion to help our users, instead `Please fix this`, I think we could say more explicit, saying for users that the permission of directory `netdata_configured_varlib_dir` does not allow to write something  or disk is full.

Comment (MrZammler) [reply web/api/web_api_v1.c:146]: Hey Thiago, thanks!

Indeed though, at that point we can't be sure if the whole `netdata_configured_varlib_dir` is problematic, or just the particular file/path (as set in `netdata management api key file`). I would also be hesitant to guess there what the reason might be for the failure (permissions, disk full?)

If `netdata_configured_varlib_dir` is a problem, then I think we should deal with it somewhere even from main. This place only deals with that particular key.

The dir pointed by the `netdata management api key file` setting will be printed in the output here. We could add a small piece of text to inform user what is needed to change, but then, should that be a trend with other errors as well?

We could e.g. change `Please fix this` to `Please configure 'netdata management api key file' parameter to a proper path and filename`. ?

Comment (thiagoftsm) [reply web/api/web_api_v1.c:146]: > The dir pointed by the netdata management api key file setting will be printed in the output here. We could add a small piece of text to inform user what is needed to change, but then, should that be a trend with other errors as well?

If we add the directory that is having problem, it will be clear for user where is the problem. Right now the current message says something about a file that could not be present on file system.

> We could e.g. change Please fix this to Please configure 'netdata management api key file' parameter to a proper path and filename. ?

I liked the last suggestion, because `Please fix it`, is not given any tip for users about possible problems they are having.

**Review by vkalintiris — APPROVED** [review]

**Review by thiagoftsm — APPROVED** [review]

File: web/api/web_api_v1.c [hunk 2]
```diff
@@ -138,12 +138,12 @@ char *get_mgmt_api_key(void) {
         // save it
         fd = open(api_key_filename, O_WRONLY|O_CREAT|O_TRUNC, 444);
         if(fd == -1) {
-            error("Cannot create unique management API key file '%s'. Please fix this.", api_key_filename);
+            error("Cannot create unique management API key file '%s'. Please adjust config parameter 'netdata management api key file' to a proper path and file.", api_key_filename);
```
[the remark this answers is not in the document]
Comment (MrZammler) [reply web/api/web_api_v1.c:141]: You mean "Fix it" needed it, but the instructions don't... Maybe, but it doesn't hurt either ? :-) 

Some other parts that suggest changes to the config use Please as well, e.g. https://github.com/netdata/netdata/blob/005d817ea88b8f982405b642d5213a67794afde0/collectors/ioping.plugin/ioping.plugin.in#L194

[the remark this answers is not in the document]
Comment (MrZammler) [reply web/api/web_api_v1.c:141]: I think we can change them if needed after this..
