### PR TITLE
Fixes conditional for NetData Updater when checking for new updates

### LINKED ISSUE #8027: manually executed updater compares current to current version, instead of current to latest
##### Bug report summary
When disabling auto-updater and calling it manually, the updater script compares wrong environment variables. It should compare current to latest, but it compares current to current, which always evaluates to true, hence skipping update.

##### OS / Environment
This is a bug in the updater script, applies to bash based installations (at least Ubuntu)

```
Linux ESPRIMO-C720 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version
```
netdata v1.19.0-473-nightly
``` 

##### Component Name
this is a bug in the `./packaging/installer/netdata-updater.sh` file.

##### Steps To Reproduce
1. when a new nightly gets released
2. and auto-updater is disabled (no cronjob for it)
3. call manually `/usr/libexec/netdata/netdata-updater.sh` script

##### Expected behavior
The script should invoke the update procedure and carry out an upgrade.

##### Actual behavior 2020. febr. 10., hétfő, 15:38:03 CET : INFO:  Running on a terminal - (this script also supports running headless from crontab)                                                                                    
2020. febr. 10., hétfő, 15:38:04 CET : INFO:  Current Version: 001019000441                                                                                                                                        
2020. febr. 10., hétfő, 15:38:04 CET : INFO:  Latest Version: 001019000473                                                                                                                                         
2020. febr. 10., hétfő, 15:38:04 CET : INFO:  Newest version 001019000441 <= 001019000473 is already installed

### PR DESCRIPTION
**Pull request by gmeszaros**
This commit changes the check for updated releases when running in manual mode

Fixes #8027 

##### Summary
This PR provides a quick fix for running manual updates.

##### Component Name
Netdata-updater

### CODE REVIEW

**Comment by ilyam8** [comment]
btw

first of all

https://github.com/netdata/netdata/blob/d3fa405141a8d2e6689c2dedb4bedb7cf9120044/packaging/installer/netdata-updater.sh#L141

doesnt work because `Netdata` is not in `PATH` pretty often.

It means that following code

https://github.com/netdata/netdata/blob/d3fa405141a8d2e6689c2dedb4bedb7cf9120044/packaging/installer/netdata-updater.sh#L147-L148

doesnt work at all and only produces errors 

> ./netdata-updater.sh: line 147: [: : integer expression expected

**Comment by ilyam8** [comment]
@Ferroin do we even need this check

https://github.com/netdata/netdata/blob/d3fa405141a8d2e6689c2dedb4bedb7cf9120044/packaging/installer/netdata-updater.sh#L147-L148

?

**Comment by Ferroin** [comment]
> @Ferroin do we even need this check
> 
> https://github.com/netdata/netdata/blob/d3fa405141a8d2e6689c2dedb4bedb7cf9120044/packaging/installer/netdata-updater.sh#L147-L148
> 
> ?

I'm not sure.

Realistically, we _should_ be checking the version like this instead of checking SHA256 hashes of the tarbals to determine if we need to upgrade or not, but we appear to have issues with that working when the user doesn't install in a way that `netdata` ends up in their path.

**Comment by ilyam8** [comment]
First check returns more detailed message and that is pretty much all. We do sha256 checking always anyway.

File: packaging/installer/netdata-updater.sh [hunk 1]
```diff
@@ -144,7 +144,7 @@ update() {
   info "Current Version: ${current_version}"
   info "Latest Version: ${latest_version}"
 
-  if [ "${latest_version}" -gt 0 ] && [ "${current_version}" -gt 0 ] && [ "${current_version}" -ge "${current_version}" ]; then
+  if [ "${latest_version}" -gt 0 ] && [ "${current_version}" -gt 0 ] && [ "${latest_version}" -ge "${current_version}" ]; then
```
Comment (ilyam8) [inline packaging/installer/netdata-updater.sh]: please use `:-0` parameter expansion for `current_version`

Comment (prologic) [reply packaging/installer/netdata-updater.sh]: Please amend with default expansion for `${current_version:-0}` and I'll merge this

Comment (Danamir) [reply packaging/installer/netdata-updater.sh]: Am I misreading something or isn't the check supposed to be reversed : `[ "${current_version}" -ge "${latest_version}" ]` ; ie. block the update if the current version >= latest version.

Comment (ilyam8) [reply packaging/installer/netdata-updater.sh]: yeah, good catch, you are right! 🙈

Comment (prologic) [reply packaging/installer/netdata-updater.sh]: yeah my bad 🤦‍♂️

**Comment by prologic** [comment]
**Test Plan:**

Testing from `master`:

```sh
/netdata # /etc/periodic/daily/netdata-updater
Tue Feb 11 23:41:36 UTC 2020 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
Tue Feb 11 23:41:37 UTC 2020 : INFO:  Current Version: 001019000482
Tue Feb 11 23:41:37 UTC 2020 : INFO:  Latest Version: 001019000481
Tue Feb 11 23:41:37 UTC 2020 : INFO:  Newest version 001019000482 <= 001019000481 is already installed
```

Testing from an older version:

```sh
/netdata # /etc/periodic/daily/netdata-updater
Tue Feb 11 23:50:45 UTC 2020 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
Tue Feb 11 23:50:45 UTC 2020 : INFO:  Current Version: 001019000432
Tue Feb 11 23:50:45 UTC 2020 : INFO:  Latest Version: 001019000481
Tue Feb 11 23:50:45 UTC 2020 : INFO:  Newest version 001019000432 <= 001019000481 is already installed
```
