### PR TITLE
Fix a segmentation fault in backends

### LINKED ISSUE #6626: Segmentation fault in backends
##### Bug report summary
When Netdata is compiled with the Prometheus remote write support, there is a segmentation fault if graphite, json, or opentsdb backend is enabled.

```
==9357== Invalid read of size 4
==9357==    at 0x20C4CC: void google::protobuf::internal::RepeatedPtrFieldBase::Clear<google::protobuf::RepeatedPtrField<prometheus::TimeSeries>::TypeHandler>() (repeated_field.h:1574)
==9357==    by 0x20C201: Clear (repeated_field.h:2085)
==9357==    by 0x20C201: clear_timeseries (remote_write.pb.h:677)
==9357==    by 0x20C201: clear_write_request (remote_write.cc:19)
==9357==    by 0x17720A: backends_main (backends.c:661)
==9357==    by 0x1636D5: thread_start (threads.c:126)
==9357==    by 0x577D57E: start_thread (in /usr/lib/libpthread-2.29.so)
==9357==    by 0x58910E2: clone (in /usr/lib/libc-2.29.so)
==9357==  Address 0x18 is not stack'd, malloc'd or (recently) free'd
==9357==
==9357==
==9357== Process terminating with default action of signal 11 (SIGSEGV): dumping core
```

##### OS / Environment
Arch Linux

##### Netdata version (ouput of `netdata -V`)
netdata v1.16.1-15-g411cd11b

##### Component Name
backends

##### Steps To Reproduce
Compile Netdata with the Prometheus remote write support, enable graphite, json, or opentsdb backend.

##### Expected behavior
No faults when Netdata is compiled with the Prometheus remote write support.

### PR DESCRIPTION
**Pull request by vlvkobal**
##### Summary
Fix a segmentation fault when Netdata is compiled with the Prometheus remote write support.

Fixes #6626

##### Component Name
backends

### CODE REVIEW

File: backends/backends.c [hunk 1]
```diff
@@ -1101,10 +1101,9 @@ void *backends_main(void *ptr) {
 #endif
 
 #if ENABLE_PROMETHEUS_REMOTE_WRITE
-    if(do_prometheus_remote_write) {
-        buffer_free(http_request_header);
+    buffer_free(http_request_header);
```
Comment (mfundul) [inline backends/backends.c]: We do:
`http_request_header = buffer_create(1);`
and:
`buffer_free(http_request_header)`
even when we don't use it at all. Shouldn't we put those 2 under `if(do_prometheus_remote_write)` as well?
