### PR TITLE
Fix Valgrind errors

### LINKED ISSUE #12618: [Bug]: Valgrind reports errors
### Bug description

Reported errors:
```
==926872== 373 bytes in 1 blocks are possibly lost in loss record 1,044 of 1,120
==926872==    at 0x4845899: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==926872==    by 0x1631F3: mallocz (libnetdata.c:176)
==926872==    by 0x3CD5F1: generate_alarm_log_entry (alarm_stream.cc:178)
==926872==    by 0x3C6195: aclk_send_alarm_log_entry (aclk_alarm_api.c:23)
==926872==    by 0x2ECC87: aclk_push_alert_event (sqlite_aclk_alert.c:254)
==926872==    by 0x2E3F74: aclk_database_worker (sqlite_aclk.c:481)
==926872==    by 0x56FA5C1: start_thread (in /usr/lib/libc.so.6)
==926872==    by 0x577F583: clone (in /usr/lib/libc.so.6)

==944217== 84,775 bytes in 179 blocks are definitely lost in loss record 1,092 of 1,092
==944217==    at 0x4845899: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==944217==    by 0x1631F3: mallocz (libnetdata.c:176)
==944217==    by 0x3CD5F1: generate_alarm_log_entry (alarm_stream.cc:178)
==944217==    by 0x3C6195: aclk_send_alarm_log_entry (aclk_alarm_api.c:23)
==944217==    by 0x2ECC87: aclk_push_alert_event (sqlite_aclk_alert.c:254)
==944217==    by 0x2E3F74: aclk_database_worker (sqlite_aclk.c:481)
==944217==    by 0x56FA5C1: start_thread (in /usr/lib/libc.so.6)
==944217==    by 0x577F583: clone (in /usr/lib/libc.so.6)

==926872== Thread 24 ACLK_Query_1:
==926872== Use of uninitialised value of size 8
==926872==    at 0x3B6581: aclk_stats_msg_published (aclk_stats.c:371)
==926872==    by 0x3BA98F: aclk_send_message_with_bin_payload (aclk_tx_msgs.c:164)
==926872==    by 0x3BB035: aclk_http_msg_v2 (aclk_tx_msgs.c:362)
==926872==    by 0x3B744A: http_api_v2 (aclk_query.c:229)
==926872==    by 0x3B6BFC: aclk_query_process_msg (aclk_query.c:341)
==926872==    by 0x3B780A: aclk_query_process_msgs (aclk_query.c:362)
==926872==    by 0x3B7873: aclk_query_main_thread (aclk_query.c:375)
==926872==    by 0x172CB2: thread_start (threads.c:185)
==926872==    by 0x56FA5C1: start_thread (in /usr/lib/libc.so.6)
==926872==    by 0x577F583: clone (in /usr/lib/libc.so.6)

==1103909== Thread 5 AS_mac-mini:
==1103909== Invalid write of size 8
==1103909==    at 0x2E44B5: aclk_database_worker (sqlite_aclk.c:577)
==1103909==    by 0x56FA5C1: start_thread (in /usr/lib/libc.so.6)
==1103909==    by 0x577F583: clone (in /usr/lib/libc.so.6)
==1103909==  Address 0x13c9c098 is 264 bytes inside a block of size 1,272 free'd
==1103909==    at 0x484827F: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1103909==    by 0x1631BD: freez (libnetdata.c:172)
==1103909==    by 0x2D0616: rrdhost_free (rrdhost.c:994)
==1103909==    by 0x2D1D01: rrdhost_free_all (rrdhost.c:1005)
==1103909==    by 0x14A437: netdata_cleanup_and_exit (main.c:60)
==1103909==    by 0x14CFD4: signals_handle (signals.c:261)
==1103909==    by 0x14C3F6: main (main.c:1337)
==1103909==  Block was alloc'd at
==1103909==    at 0x484AA83: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1103909==    by 0x163259: callocz (libnetdata.c:182)
==1103909==    by 0x2D07AA: rrdhost_create (rrdhost.c:170)
==1103909==    by 0x2D1805: rrdhost_find_or_create (rrdhost.c:591)
==1103909==    by 0x39FDC1: rrdpush_receive (receiver.c:479)
==1103909==    by 0x3A094B: rrdpush_receiver_thread (receiver.c:716)
==1103909==    by 0x172CB2: thread_start (threads.c:185)
==1103909==    by 0x56FA5C1: start_thread (in /usr/lib/libc.so.6)
==1103909==    by 0x577F583: clone (in /usr/lib/libc.so.6)
==1103909==
==1103909== Syscall param pwrite64(buf) points to uninitialised byte(s)
==1103909==    at 0x576D23F: pwrite (in /usr/lib/libc.so.6)
==1103909==    by 0x4C3FF15: ??? (in /usr/lib/libuv.so.1.0.0)
==1103909==    by 0x4C378C0: ??? (in /usr/lib/libuv.so.1.0.0)
==1103909==    by 0x56FA5C1: start_thread (in /usr/lib/libc.so.6)
==1103909==    by 0x577F583: clone (in /usr/lib/libc.so.6)
==1103909==  Address 0x91f0961 is 2,401 bytes inside a block of size 4,096 alloc'd
==1103909==    at 0x484AE30: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1103909==    by 0x484AF92: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1103909==    by 0x3902E7: wal_get_transaction_buffer (journalfile.c:83)
==1103909==    by 0x38B6FB: commit_data_extent (rrdengine.c:461)
==1103909==    by 0x38B7CC: do_commit_transaction (rrdengine.c:485)
==1103909==    by 0x38D3CB: do_flush_pages (rrdengine.c:812)
==1103909==    by 0x38DF48: rrdeng_worker (rrdengine.c:1255)
==1103909==    by 0x56FA5C1: start_thread (in /usr/lib/libc.so.6)
==1103909==    by 0x577F583: clone (in /usr/lib/libc.so.6)

==1107789== Thread 6:
==1107789== Syscall param pwrite64(buf) points to uninitialised byte(s)
==1107789==    at 0x576D23F: pwrite (in /usr/lib/libc.so.6)
==1107789==    by 0x4C3FF15: ??? (in /usr/lib/libuv.so.1.0.0)
==1107789==    by 0x4C378C0: ??? (in /usr/lib/libuv.so.1.0.0)
==1107789==    by 0x56FA5C1: start_thread (in /usr/lib/libc.so.6)
==1107789==    by 0x577F583: clone (in /usr/lib/libc.so.6)
==1107789==  Address 0x12348e72 is 3,698 bytes inside a block of size 4,096 alloc'd
==1107789==    at 0x484AE30: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1107789==    by 0x484AF92: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1107789==    by 0x38D064: do_flush_pages (rrdengine.c:733)
==1107789==    by 0x38DF48: rrdeng_worker (rrdengine.c:1255)
==1107789==    by 0x56FA5C1: start_thread (in /usr/lib/libc.so.6)
==1107789==    by 0x577F583: clone (in /usr/lib/libc.so.6)
```

### Expected behavior

None of the above errors are reported.

### Steps to reproduce

Build Netdata
```
sudo CFLAGS="-Og -ggdb -Wall -Wextra -Wformat-signedness -fno-omit-frame-pointer -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTiFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1" ./netdata-installer.sh --use-system-protobuf --disable-lto --dont-wait --dont-start-it
```
Run it with Valgrind
```
sudo valgrind --leak-check=yes /usr/sbin/netdata -P /var/run/netdata/netdata.pid -D -W set global process scheduling policy keep -W set global OOM score keep
```

### Installation method

from git

### System info

```shell
Linux arch-esxi 5.17.1-arch1-1 #1 SMP PREEMPT Mon, 28 Mar 2022 20:55:33 +0000 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID="Arch"
/etc/lsb-release:DISTRIB_RELEASE="rolling"
/etc/lsb-release:DISTRIB_DESCRIPTION="Arch Linux"
/etc/os-release:NAME="Arch Linux"
/etc/os-release:PRETTY_NAME="Arch Linux"
/etc/os-release:ID=arch
/etc/os-release:BUILD_ID=rolling
/etc/os-release:ANSI_COLOR="38;2;23;147;209"
/etc/os-release:LOGO=archlinux-logo
```

### Netdata build info

```shell
Version: netdata v1.33.1-303-g1403229a8
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-plugin-nfacct' '--enable-plugin-freeipmi' '--without-bundled-protobuf' '--disable-lto' 'CFLAGS=-Og -ggdb -Wall -Wextra -Wformat-signedness -fno-omit-frame-pointer -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTiFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             YES
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by vlvkobal**
##### Summary
Fixes
- [x] leaks in alarm_log_entry
- [x] array initialization in ACLK stats
- [x] buffer initialization in rrdengine

Fixes #12618

##### Test Plan
1. Build Netdata
```
sudo CFLAGS="-Og -ggdb -Wall -Wextra -Wformat-signedness -fno-omit-frame-pointer -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTiFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1" ./netdata-installer.sh --use-system-protobuf --disable-lto --dont-wait --dont-start-it
```
2. Run it with Valgrind
```
sudo valgrind --leak-check=yes /usr/sbin/netdata -P /var/run/netdata/netdata.pid -D -W set global process scheduling policy keep -W set global OOM score keep
```
3. Press Ctrl+C and check if there are no errors mentioned above in the Valgrind output.

### CODE REVIEW

**Comment by thiagoftsm** [comment]
@vlvkobal your PR is fixing what is proposed, but before to approve I want to talk with you about this:

```sh
==20269== 864 bytes in 2 blocks are possibly lost in loss record 2,757 of 2,860
==20269==    at 0x484B5FF: calloc (vg_replace_malloc.c:1117)
==20269==    by 0x4013F95: _dl_allocate_tls (in /lib64/ld-2.35.so)
==20269==    by 0x5945D24: pthread_create@@GLIBC_2.34 (in /lib64/libc-2.35.so)
==20269==    by 0x4E1DECC: uv_thread_create_ex (in /usr/lib64/libuv.so.1.0.0)
==20269==    by 0x4E1DF7B: uv_thread_create (in /usr/lib64/libuv.so.1.0.0)
==20269==    by 0x5ADCB0: sql_create_aclk_table (sqlite_aclk.c:656)
==20269==    by 0x5ADD3E: aclk_start_sync_thread (sqlite_aclk.c:246)
==20269==    by 0x63B2E6: sqlite3_exec (sqlite3.c:126225)
==20269==    by 0x5AD980: sql_aclk_sync_init (sqlite_aclk.c:279)
==20269==    by 0x59D1ED: rrd_init (rrdhost.c:759)
==20269==    by 0x42188E: main (main.c:1237)
```

Are we going to fix this with another PR?

Best regards!

**Comment by vlvkobal** [comment]
> ==20269== 864 bytes in 2 blocks are possibly lost in loss record 2,757 of 2,860
==20269==    at 0x484B5FF: calloc (vg_replace_malloc.c:1117)
==20269==    by 0x4013F95: _dl_allocate_tls (in /lib64/ld-2.35.so)
==20269==    by 0x5945D24: pthread_create@@GLIBC_2.34 (in /lib64/libc-2.35.so)
Are we going to fix this with another PR?

Yes. Look at #12620.

**Review by thiagoftsm — APPROVED** [review]

File: database/engine/journalfile.c [hunk 1]
```diff
@@ -81,6 +81,7 @@ void * wal_get_transaction_buffer(struct rrdengine_worker_config* wc, unsigned s
     if (NULL == ctx->commit_log.buf) {
         buf_size = ALIGN_BYTES_CEILING(size);
         ret = posix_memalign((void *)&ctx->commit_log.buf, RRDFILE_ALIGNMENT, buf_size);
+        memset(ctx->commit_log.buf, 0, buf_size);
```
Comment (stelfrag) [inline database/engine/journalfile.c:84]: This could be after the ret check (although it would be fatal anyway)

File: database/engine/rrdengine.c [hunk 2]
```diff
@@ -731,6 +731,7 @@ static int do_flush_pages(struct rrdengine_worker_config* wc, int force, struct
         break;
     }
     ret = posix_memalign((void *)&xt_io_descr->buf, RRDFILE_ALIGNMENT, ALIGN_BYTES_CEILING(size_bytes));
+    memset(xt_io_descr->buf, 0, ALIGN_BYTES_CEILING(size_bytes));
```
Comment (stelfrag) [inline database/engine/rrdengine.c:734]: Same here. Maybe move after the ret check

File: aclk/aclk_stats.c [hunk 3]
```diff
@@ -364,7 +364,7 @@ void aclk_stats_upd_online(int online) {
 }
 
 #ifdef NETDATA_INTERNAL_CHECKS
-static usec_t pub_time[UINT16_MAX];
+static usec_t pub_time[UINT16_MAX] = {0};
```
Comment (underhood) [inline aclk/aclk_stats.c:367]: this was copied from old ACLK but looking at it now it should really be `[UINT16_MAX+1]` as

**Review by thiagoftsm — APPROVED** [review]
Retest after the last commit, and the problems were removed.

**Review by stelfrag — APPROVED** [review]
