### PR TITLE
[Agent crash on api/v1/info call] - fixes #12559

### LINKED ISSUE #12559: [Bug]: Agent crash on api/v1/info call
### Bug description

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  web_client_api_request_v1_info_fill_buffer (host=0x55866c23dd10, wb=0x55866b9ca3b0) at web/api/web_api_v1.c:1054
1054	    buffer_strcat(wb, (host->sender->rrdpush_compression ? "\"enabled\"" : "\"disabled\""));
[Current thread is 1 (Thread 0x7f0492906640 (LWP 652009))]
(gdb) p host->sender
$1 = (struct sender_state *) 0x0
```

### Expected behavior

Agent should not crash

### Steps to reproduce

1. Setup parent - child
2. Specify on the parent `cleanup orphan hosts after seconds = 30`
3. Start parent and child
4. Go to the parent dashboard and view the child's metrics
5. Stop the child while still viewing the childs dashboard (via the parent)
6. Parent crashes

### Installation method

from source

### System info

```shell
Linux futura 5.13.0-37-generic #42-Ubuntu SMP Tue Mar 15 14:34:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=21.10
/etc/lsb-release:DISTRIB_CODENAME=impish
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 21.10"
/etc/os-release:PRETTY_NAME="Ubuntu 21.10"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="21.10"
/etc/os-release:VERSION="21.10 (Impish Indri)"
/etc/os-release:VERSION_CODENAME=impish
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=impish
```

### Netdata build info

```shell
Version: netdata v1.33.1-28-g698f01fb0
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O0 -ggdb -Wall -Wextra -Wformat-truncation=2 -Wunused-result -Wformat-signedness -fstack-protector-all -DxNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by erdem2000**
Fixes [#12559 ](https://github.com/netdata/netdata/issues/12559#event-6333514229)

##### Summary
This PR fixes agent crash on child calls with `api/v1/info`.
The parent creates segmentation fault when the child is closed and tries to access sender information of the child with the `api/v1/info` call.

##### Test Plan

1. Setup parent - child
2. Specify on the parent cleanup orphan hosts after seconds = 30
3. Start parent and child
4. Go to the parent dashboard and view the child's metrics
5. Stop the child while still viewing the childs dashboard or  or run `http://parent.ip:19999/host/child.name/api/v1/info` (via the parent) 
6. Parent shouldn't crash

### CODE REVIEW

**Comment by underhood** [comment]
Also I do not see any mention of this key in:
```
web/api/netdata-swagger.json
web/api/netdata-swagger.yaml
```

again this is not direct fault of this PR but why not fix it while we are at it (lot of people incl. me forget to update those swagger definitions)

**Review by underhood — CHANGES_REQUESTED** [review]
see comments above

File: web/api/web_api_v1.c [hunk 1]
```diff
@@ -1050,9 +1050,13 @@ inline int web_client_api_request_v1_info_fill_buffer(RRDHOST *host, BUFFER *wb)
...
 #ifdef  ENABLE_COMPRESSION
-    buffer_strcat(wb, "\t\"stream-compression\": ");
-    buffer_strcat(wb, (host->sender->rrdpush_compression ? "\"enabled\"" : "\"disabled\""));
-    buffer_strcat(wb, ",\n");
+    if(host->sender){
+        buffer_strcat(wb, "\t\"stream-compression\": ");
+        buffer_strcat(wb, (host->sender->rrdpush_compression ? "\"enabled\"" : "\"disabled\""));
+        buffer_strcat(wb, ",\n");
+    }else{
+        buffer_strcat(wb, "\t\"stream-compression\": \"N/A\",\n");
```
Comment (underhood) [inline web/api/web_api_v1.c:1058]: should it be "N/A"  or "disabled" in this case.
+ still if not too late I would prefer it to be fixed so it is proper nullable JSON boolean `true/false/null`

File: web/api/web_api_v1.c [hunk 2]
```diff
@@ -1050,11 +1050,15 @@ inline int web_client_api_request_v1_info_fill_buffer(RRDHOST *host, BUFFER *wb)
...
 #ifdef  ENABLE_COMPRESSION
-    buffer_strcat(wb, "\t\"stream-compression\": ");
-    buffer_strcat(wb, (host->sender->rrdpush_compression ? "\"enabled\"" : "\"disabled\""));
-    buffer_strcat(wb, ",\n");
+    if(host->sender){
+        buffer_strcat(wb, "\t\"stream-compression\": ");
+        buffer_strcat(wb, (host->sender->rrdpush_compression ? "true" : "false"));
+        buffer_strcat(wb, ",\n");
+    }else{
+        buffer_strcat(wb, "\t\"stream-compression\": null,\n");
```
Comment (underhood) [inline web/api/web_api_v1.c:1058]: should it be `null` here or `false`? Do we want `null` to mean -> not supported in this agent?

Comment (underhood) [reply web/api/web_api_v1.c:1058]: Either this flag says:
- "true" compression is used now
- "false" compression is not used now
- "null" this agent has no compression

or what you suggest quote:
>  It means that it can be enabled or disabled but we don't have any info about it.

In such case it should reflect if it is enabled in configuration file. In such case `we don't have any info about it` makes no sense because we can read config key value regardless of `host->sender` existence.

File: web/api/netdata-swagger.json [hunk 3]
```diff
@@ -1220,6 +1220,11 @@
             "description": "Container technology detection method.",
             "example": "dockerenv"
           },
+          "stream_compression": {
+            "type": "boolean",
+            "description": "Stream transmission compression method.",
+            "example": "true"
```
[the remark this answers is not in the document]
Comment (erdem2000) [reply web/api/netdata-swagger.json:1226]: _for description -> Doesn't it mean compression is enabled?_
It means if the compression is enabled or not for the sender thread (as you stated) of host. Obviously it can be both `disabled `(`false`) or `enabled `(`true`). I can write more detail in the description section. 

Before the PR `null` had only one mean: agent built without stream compression support. In the case of building with compression support it should be `enabled` or `disabled` by the user. But there is a third case which agent is built with compression support but the `sender state` is unreachable (related pointer is `null`). Therefore we can return a different value for this state. My suggestion is below, maybe we can swap `N/A` and `NULL` if it is more meaningful. 

image

What do you think?

File: web/api/web_api_v1.c (hunk 2 above)
Comment (erdem2000) [reply web/api/web_api_v1.c:1058]: BTW, I suggested a more comprehensive solution in the [previous ](https://github.com/netdata/netdata/pull/12565#discussion_r838862644)comment

File: web/api/netdata-swagger.json (hunk 3 above)
[the remark this answers is not in the document]
Comment (underhood) [reply web/api/netdata-swagger.json:1226]: lets not overcomplicate this then, to fix the segfault quickly, we can improve in future

**Review by underhood — APPROVED** [review]

**Review by thiagoftsm — APPROVED** [review]
