### PR TITLE
netdata/installer: Fix error running kickstart as a non-privileged user

### LINKED ISSUE #6633: Install script is unable to delete temporary files because they are root-owned
##### Bug report summary
There is a line at the end of install script which deletes the temp files
https://github.com/netdata/netdata/blob/68dbbc73f751ecc739ec3614aa66865d197f25ea/packaging/installer/kickstart.sh#L331
That command can't fully clear the temporary folder because there are root-owned files in it. The script itself runs under the user-level privileges.

There is no indication of that error in the script output because the output of ``rm`` is discarded to ``/dev/null``.

At the end of that issue I provided the list of files that can't be deleted in my case.

I don't know if those files are supposed to be root-owned. Maybe they do and the solution here is to just run that command as ``sudo rm``. Maybe they not and solution is to change some other part of the install script to run without root privileges.

The ``rm`` command is the last command of ``kickstart.sh`` script. The exit status of the whole install script is ``1`` because of that. That makes it difficult to understand if the install is successful in scripting environment.

##### OS / Environment
Ubuntu 18.04.2 LTS desktop

##### Netdata version (ouput of `netdata -V`)
netdata v1.16.0

##### Steps To Reproduce
``bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait --stable-channel; echo exit status $?``

##### Expected behavior
``exit status 0`` line in the output

##### List of root owned files in temporary directory
```
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/formatters/value/.deps/value.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/formatters/value/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/formatters/.deps/rrd2json.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/formatters/.deps/charts2json.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/formatters/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/formatters/.deps/json_wrapper.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/formatters/.deps/rrdset2json.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/formatters/csv/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/formatters/csv/.deps/csv.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/formatters/ssv/.deps/ssv.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/formatters/ssv/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/formatters/json/.deps/json.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/formatters/json/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/exporters/shell/.deps/allmetrics_shell.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/exporters/shell/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/exporters/.deps/allmetrics.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/exporters/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/.deps/web_api_v1.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/ses/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/ses/.deps/ses.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/median/.deps/median.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/median/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/sum/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/sum/.deps/sum.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/min/.deps/min.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/min/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/des/.deps/des.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/des/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/max/.deps/max.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/max/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/.deps/query.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/.deps/rrdr.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/average/.deps/average.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/average/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/incremental_sum/.deps/incremental_sum.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/incremental_sum/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/stddev/.deps/stddev.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/queries/stddev/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/badges/.deps/web_buffer_svg.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/badges/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/health/.deps/health_cmdapi.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/api/health/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/server/.deps/web_client.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/server/.deps/web_client_cache.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/server/.deps/web_server.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/server/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/server/static/.deps/static-threaded.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/web/server/static/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/backends/graphite/.deps/graphite.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/backends/graphite/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/backends/opentsdb/.deps/opentsdb.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/backends/opentsdb/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/backends/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/backends/.deps/backends.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/backends/prometheus/remote_write/.deps/remote_write.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/backends/prometheus/remote_write/.deps/remote_write.pb.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/backends/prometheus/.deps/backend_prometheus.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/backends/prometheus/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/backends/aws_kinesis/.deps/aws_kinesis_put_record.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/backends/aws_kinesis/.deps/aws_kinesis.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/backends/json/.deps/json.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/backends/json/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/autom4te.cache/traces.0': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/autom4te.cache/output.0': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/autom4te.cache/output.1': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/autom4te.cache/traces.1': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/autom4te.cache/requests': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/registry/.deps/registry_init.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/registry/.deps/registry.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/registry/.deps/registry_person.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/registry/.deps/registry_internals.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/registry/.deps/registry_db.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/registry/.deps/registry_log.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/registry/.deps/registry_url.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/registry/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/registry/.deps/registry_machine.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/procfile/.deps/procfile.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/procfile/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/buffer/.deps/buffer.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/buffer/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/threads/.deps/threads.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/threads/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/storage_number/.deps/storage_number.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/storage_number/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/avl/.deps/avl.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/avl/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/url/.deps/url.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/url/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/eval/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/eval/.deps/eval.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/log/.deps/log.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/log/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/statistical/.deps/statistical.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/statistical/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/socket/.deps/socket.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/socket/.deps/security.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/socket/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/config/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/config/.deps/appconfig.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/adaptive_resortable_list/.deps/adaptive_resortable_list.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/adaptive_resortable_list/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/.deps/libnetdata.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/.deps/os.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/dictionary/.deps/dictionary.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/dictionary/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/clocks/.deps/clocks.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/clocks/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/json/.deps/json.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/json/.deps/jsmn.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/json/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/locks/.deps/locks.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/locks/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/simple_pattern/.deps/simple_pattern.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/simple_pattern/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/health/.deps/health.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/health/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/popen/.deps/popen.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/libnetdata/popen/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/streaming/.deps/rrdpush.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/streaming/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/database/.deps/rrdsetvar.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/database/.deps/rrdvar.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/database/.deps/rrddim.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/database/.deps/rrdcalctemplate.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/database/.deps/rrdset.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/database/.deps/rrdfamily.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/database/.deps/rrddimvar.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/database/.deps/rrd.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/database/.deps/rrdhost.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/database/.deps/rrdcalc.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/database/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/database/engine/.deps/rrdengineapi.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/database/engine/.deps/datafile.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/database/engine/.deps/pagecache.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/database/engine/.deps/rrdenglocking.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/database/engine/.deps/rrdenginelib.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/database/engine/.deps/journalfile.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/database/engine/.deps/rrdengine.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/database/engine/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/daemon/.deps/common.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/daemon/.deps/main.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/daemon/.deps/daemon.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/daemon/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/daemon/.deps/unit_test.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/daemon/.deps/global_statistics.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/daemon/.deps/signals.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/cgroups.plugin/.deps/cgroup-network.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/cgroups.plugin/.deps/sys_fs_cgroup.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/cgroups.plugin/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/macos.plugin/.deps/macos_sysctl.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/macos.plugin/.deps/plugin_macos.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/macos.plugin/.deps/macos_fw.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/macos.plugin/.deps/macos_mach_smi.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/freeipmi.plugin/.deps/freeipmi_plugin.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/checks.plugin/.deps/plugin_checks.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/checks.plugin/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/xenstat.plugin/.deps/xenstat_plugin.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/nfacct.plugin/.deps/plugin_nfacct.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/freebsd.plugin/.deps/plugin_freebsd.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/freebsd.plugin/.deps/freebsd_kstat_zfs.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/freebsd.plugin/.deps/freebsd_ipfw.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/freebsd.plugin/.deps/freebsd_devstat.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/freebsd.plugin/.deps/freebsd_getmntinfo.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/freebsd.plugin/.deps/freebsd_sysctl.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/freebsd.plugin/.deps/freebsd_getifaddrs.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/diskspace.plugin/.deps/plugin_diskspace.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/diskspace.plugin/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_net_sctp_snmp.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/sys_class_power_supply.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_net_dev.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/plugin_proc.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_vmstat.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/sys_devices_system_node.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_sys_kernel_random_entropy_avail.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_interrupts.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/zfs_common.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/sys_fs_btrfs.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_net_rpc_nfsd.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_diskstats.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_net_stat_synproxy.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_stat.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_net_softnet_stat.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_net_netstat.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/sys_kernel_mm_ksm.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_meminfo.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_spl_kstat_zfs.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_net_snmp6.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_net_rpc_nfs.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_net_stat_conntrack.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_self_mountinfo.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_net_snmp.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_net_ip_vs_stats.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_net_sockstat6.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/ipc.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_softirqs.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_loadavg.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_mdstat.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_net_sockstat.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/proc_uptime.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/proc.plugin/.deps/sys_devices_system_edac_mc.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/plugins.d/.deps/plugins_d.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/plugins.d/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/cups.plugin/.deps/cups_plugin.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/cups.plugin/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/apps.plugin/.deps/apps_plugin.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/apps.plugin/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/tc.plugin/.deps/plugin_tc.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/tc.plugin/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/perf.plugin/.deps/perf_plugin.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/perf.plugin/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/idlejitter.plugin/.deps/plugin_idlejitter.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/idlejitter.plugin/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/statsd.plugin/.deps/statsd.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/collectors/statsd.plugin/.deps/.dirstamp': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/health/.deps/health_log.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/health/.deps/health_config.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/health/.deps/health_json.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/health/.deps/health.Po': Permission denied
rm: cannot remove '/tmp/netdata-kickstart-lOWdjy/netdata-v1.16.0/health/.deps/.dirstamp': Permission denied
```

### PR DESCRIPTION
**Pull request by paulkatsoulakis**
##### Summary
One of our users reported an issue occurring with our kickstart installer, when it is executed with a non-privileged user.
Our kickstart has the capability to selectively run commands with sudo where needed, when the user executing kickstart is not root.

During the end of the execution, we had a set of commands that were not executed with sudo and were masked to hide the failure, thus only resulting on a non-zero exit code of the script execution when user is not root.

This PR mitigates this problem and helps cleaning up after installation properly.

Fixes:
1) Make sure we always have a proper TMPDIR variable
2) Make sure we use sudo variable on the deletions 
3) Guard deletions for the cases we shouldn't be deleting anything (for example when /tmp is the TMPDIR)

##### Component Name
netdata/installer

##### Additional Information
Fixes #6633

### CODE REVIEW

File: packaging/installer/kickstart-static64.sh [hunk 1]
```diff
@@ -189,7 +189,7 @@ done
 
 # ---------------------------------------------------------------------------------------------------------------------
 TMPDIR=$(create_tmp_directory)
-cd "${TMPDIR}" || :
+cd "${TMPDIR}" || TMPDIR="/tmp"
```
Comment (cakrit) [inline packaging/installer/kickstart-static64.sh]: I don't understand this. Either `cd` or just set the variable? Doesn't sound right.

Comment (paulkatsoulakis) [reply packaging/installer/kickstart-static64.sh]: Now that you mention it, i don't even know why we need to enter the temp directory.
We always refer the file with the full path

Comment (paulkatsoulakis) [reply packaging/installer/kickstart-static64.sh]: i would probably only consider it as a dummy validation step for the directory creation
