### PR TITLE
Fixes NetData installer on *BSD systems post libmosquitto / eBPF

### LINKED ISSUE #8116: Libmosquito does not install on FreeBSD 12-p2
##### Bug report summary
During the tests with netdata-installer on FreeBSD to confirm that it was not enabling eBPF collector, it was detected that we are not able to compile libmosquito on it.

##### OS / Environment
```
FreeBSD freebsd 12.1-RELEASE-p2 FreeBSD 12.1-RELEASE-p2 GENERIC amd64
1201000
```

##### Netdata version
netdata v1.19.0-661-gb7205e00 

##### Component Name
netdata-installer

##### Steps To Reproduce
1.Run the script file `cmd` that is inside the file attached.

##### Expected behavior
Compile libmmosquitto on FreeBSD

[freebsd.zip](https://github.com/netdata/netdata/files/4216934/freebsd.zip)

### LINKED ISSUE #8119: eBPF Collector installation errors on BSD
##### Bug report summary

Even though the eBPF Collector(s) that were added in #7979 and #8075 are only available for the Linux platform; the NetData Installer incorrectly errors our on BSD with the `--enable-ebpf` option enabled. This was discovered while investigating another similar bug in #8116 

Ultimately we have no CI and Packaging for *BSD so we should fix that (_Issue TBD_).

##### OS / Environment

- *BSD

```sh
root@freebsd:~/netdata # uname -a
FreeBSD freebsd 12.1-RELEASE FreeBSD 12.1-RELEASE r354233 GENERIC  amd64
root@freebsd:~/netdata #
```

##### Netdata version

```sh
root@freebsd:~/netdata # git rev-parse --short HEAD
d004f921d
```

##### Component Name

- area/packaging
- area/ci

##### Steps To Reproduce

1. Clone the netdata repo
2. Run the installer with `--enable-ebpf`
3. Observe that it errors out incorrectly.

##### Expected behavior

Installation is skipped on BSD without error.

### PR DESCRIPTION
**Pull request by prologic**
Kills two birds with one stone:

- Fixes #8116 
- Fixes #8119 

Blame(s):

- #8075
- #8085

##### Summary

Theres a lesson to be learned here 😀

See: #8120

This PR fixes a whole bunch of issues I discovered post our custom
libmosquitto fork (#8085) and our new highly experimental / tech preview
eBPF Collector(s) (#8075) (_amazing how these are just 10 pRs apart!_).

Some notable things:

- Always make sure you use the _right_ options for UNIX tools -- BSD implemtnations of many tools are especially picky about this. We got `mktemp -t -d ...` wrong in so many places :/ TODO: Create a ReviewDog check for this.
- We just weren't handling errors and we just don't have `set -e` on the NetData Installer. We should: TODO: Create Issue and PR for this and fix other places we do not handle errors properly.
- _and a few others..._

##### Component Name

- area/packaging

##### Description of testing that the developer performed

I basically ran:

```sh
root@freebsd:~/netdata # ./netdata-installer.sh --enable-ebpf --install /usr/local --dont-wait --dont-start-it
```

On a fresh FreeBSD system until all errors and bugs were gone.

See the relevant issues where you can clearly see things working correctly again.

##### Additional Information

Humans _should not_ do CI; Computers should!

😳

### CODE REVIEW

File: netdata-installer.sh [hunk 1]
```diff
@@ -456,11 +456,17 @@ bundle_libmosquitto() {
     return 0
   fi
 
+  if [ "$(uname)" != "Linux" ]; then
+    echo >&2 " Sorry NetData with custom libmosquitto is unable on $(uname) at this time!"
```
Comment (knatsakis) [inline netdata-installer.sh]:
```suggestion
    echo >&2 " Sorry NetData with custom libmosquitto is unsupported on $(uname) at this time!"
```

File: netdata-installer.sh [hunk 2]
```diff
@@ -456,11 +456,17 @@ bundle_libmosquitto() {
...
+    echo >&2 " Please contact NetData suppoort! https://github.com/netdata/netdata/issues/new"
+    return 0
```
Comment (knatsakis) [inline netdata-installer.sh]:
```suggestion
    return 1
```

You are returning 1 in the eBPF check, should this also return 1?

Comment (prologic) [reply netdata-installer.sh]: No the way @Ferroin wrote this it needs to `return 0` :)

**Comment by amoss** [comment]
What is the difference between `mktemp -d -t` and `mkdtemp -t -d` ?
Do we still leave the build directories in `/tmp` or are we cleaning them after use?

(you merged this so far I didn't get a chance to ask)

**Comment by prologic** [comment]
> What is the difference between `mktemp -d -t` and `mkdtemp -t -d` ?
> Do we still leave the build directories in `/tmp` or are we cleaning them after use?
> 
> (you merged this so far I didn't get a chance to ask)

My PR explains this a little; but basically the order of the options were wrong and many BSD UNIX tools are a bit more strict/picky about this. So in effect having these options around the wrong way was completing messing with:

```sh
tm="$(mktemp -d -t ...)"
```

Causing it to fail quite miserably.

**Comment by prologic** [comment]
And... As my PR mentions; I only found this out by setting `set -e` in the installer script; which I also discovered that we _do_ fail silently in other places too which is bad IHMO. I'm going to file issues to fix/improve the quality of the installer in this regards and try to ensure we don't get bitten by things like this in future (CI).

**Comment by prologic** [comment]
I just found where I discovered this and write some test cases on a BSD machine:

Consider the following:

```sh
root@freebsd:~/netdata # cat good.sh
#!/usr/bin/env bash

tmp="$(mktemp -d -t netdata-mosquitto-XXXXXX)"
echo $?
echo "tmp=${tmp}"
root@freebsd:~/netdata # cat bad.sh
#!/usr/bin/env bash

tmp="$(mktemp -t -d netdata-mosquitto-XXXXXX)"
echo $?
echo "tmp=${tmp}"
root@freebsd:~/netdata # ./good.sh
0
tmp=/tmp/netdata-mosquitto-XXXXXX.xdznf5va
root@freebsd:~/netdata # ./bad.sh
0
tmp=/tmp/-d.Al2Kcdzd
netdata-mosquitto-13goj6
root@freebsd:~/netdata #
```

**Comment by prologic** [comment]
To further illustrate the strictness and differences of BSD systems:

Man page for GNU's `mktemp`:

```
NAME
       mktemp - create a temporary file or directory

SYNOPSIS
       mktemp [OPTION]... [TEMPLATE]
```

Man page for BSD's `mktemp`:

```sh
NAME
     mktemp - make temporary file name (unique)

SYNOPSIS
     mktemp [-d] [-q] [-t prefix] [-u] template ...
     mktemp [-d] [-q] [-u] -t prefix
```

🤷‍♂️

**Comment by prologic** [comment]
Moral of the story; we have to be portable, and we need moar CI :)
