### PR TITLE
Fix cleanup of obsolete charts

### LINKED ISSUE #9363: netdata ERROR : MAIN : EOF found in spawn pipe.
#### Summary
netdata fails to start in a loop: 

all I see in the log is this: 

020-06-17 18:56:27: netdata INFO  : MAIN : Loading metadata log "/var/cache/netdata/dbengine/metadatalog-00000-00026.mlf".
2020-06-17 18:56:27: netdata INFO  : MAIN : Collector updated metadata for chart disk_qops.dm-22
2020-06-17 18:56:27: netdata ERROR : MAIN : EOF found in spawn pipe.
Shutting down spawn server event loop.
Shutting down spawn server loop complete.

and some times this:
2020-06-17 18:55:28: netdata ERROR : MAIN : Request to remove RRDVAR '' from index failed. Not Found.
2020-06-17 18:55:28: netdata ERROR : MAIN : RRDVAR: Attempted to delete variable '' from host 's5', but it is not found.
EOF found in spawn pipe.
Shutting down spawn server event loop.
Shutting down spawn server loop complete.

the only way to resolve this was clearing the cache folder.

### PR DESCRIPTION
**Pull request by mfundul**
##### Summary
Fixes #9363
##### Component Name
database
##### Test Plan
First add a low timeout for cleaning up obsolete charts.
```
[global]
        cleanup obsolete charts after seconds = 10
```

Then make the `/proc/net/dev` collector obsolete the chart itself, without obsoleting its dimensions, as follows:
1. Start a bunch of LXC containers that will create new network devices.
2. Stop those containers so that the collector obsoletes the relevant charts.
3. Start some more containers.
4. Wait for a minute to trigger the cleanup logic.
5. Gracefully shut down the agent.

At this point, the agent will crash with a double-free or use-after-free during shutdown of localhost `RRDHOST`. This PR should fix that situation.

### CODE REVIEW

**Comment by stelfrag** [comment]
Replicated with a bunch a total of 7 lxc containers as described in the test case

```
2020-09-25 12:34:02: netdata INFO  : MAIN : SYSTEM_INFO: free 0x56364f905520
2020-09-25 12:34:02: netdata INFO  : MAIN : Freeing all memory for host 'netdata'...
2020-09-25 12:34:02: netdata INFO  : MAIN : SYSTEM_INFO: free 0x563652f49750
2020-09-25 12:34:02: netdata INFO  : MAIN : Freeing all memory for host 'futura'...
2020-09-25 12:34:02: netdata ERROR : MAIN : Request to remove RRDVAR '(null)' from index failed. Not Found.
2020-09-25 12:34:02: netdata ERROR : MAIN : RRDVAR: Attempted to delete variable '(null)' from host 'futura', but it is not found.
free(): invalid size
EOF found in spawn pipe.
Shutting down spawn server event loop.
Shutting down spawn server loop complete.
```

**Review by stelfrag — DISMISSED** [review]

File: database/rrdhost.c [hunk 1]
```diff
@@ -1521,9 +1521,41 @@ void rrdhost_cleanup_obsolete_charts(RRDHOST *host) {
         )) {
 #ifdef ENABLE_DBENGINE
             if(st->rrd_memory_mode == RRD_MEMORY_MODE_DBENGINE) {
+                RRDDIM *rd, *last;
+
                 rrdset_flag_set(st, RRDSET_FLAG_ARCHIVED);
                 while(st->variables)  rrdsetvar_free(st->variables);
                 while(st->alarms)     rrdsetcalc_unlink(st->alarms);
+                rrdset_wrlock(st);
+                for( rd = st->dimensions, last = NULL ; likely(rd) ; ) {
```
Comment (underhood) [inline database/rrdhost.c:1530]: this line can use clang format, other than this LGTM.

**Review by underhood — APPROVED** [review]

**Review by stelfrag — APPROVED** [review]
