### PR TITLE
Fix crash in malloc

### LINKED ISSUE #6582: netdata crashing in malloc()
##### Bug report summary
netdata crashes this way:
```
netdata: malloc.c:3700: _int_malloc: Assertion `victim->fd_nextsize->bk_nextsize == victim' failed.
```
##### OS / Environment
linux
##### Netdata version (ouput of `netdata -V`)
netdata v1.16.0-87-g63a4cad
netdata v1.16.0-102-g7d0250e

##### Component Name
web
##### Steps To Reproduce
keep parsing URLs

gdb:
```
[New LWP 15058]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/netdata -D'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fb8908dc067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56    ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) where
#0  0x00007fb8908dc067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fb8908dd448 in __GI_abort () at abort.c:89
#2  0x00007fb89091f0ad in __malloc_assert (assertion=assertion@entry=0x7fb890a0f658 "victim->fd_nextsize->bk_nextsize == victim", 
    file=file@entry=0x7fb890a0b28d "malloc.c", line=line@entry=3595, function=function@entry=0x7fb890a0b615 <__func__.11521> "_int_malloc") at malloc.c:293
#3  0x00007fb89092208f in _int_malloc (av=0x7fb890c4c620 <main_arena>, bytes=17280) at malloc.c:3595
#4  0x00007fb890923020 in __GI___libc_malloc (bytes=17280) at malloc.c:2891
#5  0x00000000004adb4b in mallocz (size=17280) at libnetdata/libnetdata.c:176
#6  0x0000000000440b93 in rrdr_create (st=st@entry=0x7fb8517db000, n=n@entry=540) at web/api/queries/rrdr.c:119
#7  0x000000000044484e in rrd2rrdr (st=st@entry=0x7fb8517db000, points_requested=points_requested@entry=540, after_requested=1564609894, after_requested@entry=-540, 
    before_requested=1564610434, before_requested@entry=0, group_method=group_method@entry=RRDR_GROUPING_AVERAGE, 
    resampling_time_requested=resampling_time_requested@entry=0, options=(RRDR_OPTION_NONZERO | RRDR_OPTION_ABSOLUTE | RRDR_OPTION_JSON_WRAP), 
    dimensions=0x166b0c30 "|in") at web/api/queries/query.c:820
#8  0x000000000042b080 in rrdset2anything_api_v1 (latest_timestamp=<synthetic pointer>, options=517, group_time=0, group_method=1, before=0, after=-540, points=540, 
    format=8, dimensions=0x166b0bf0, wb=0x15b397e0, st=0x7fb8517db000) at web/api/formatters/rrd2json.c:120
#9  web_client_api_request_v1_data (host=<optimized out>, w=<optimized out>, url=0x0) at web/api/web_api_v1.c:472
#10 0x000000000047a7af in web_client_api_request_v1 (url=0x166a2a47 "data", w=0x166a25e0, host=0x159c9630) at web/api/web_api_v1.c:810
#11 web_client_api_request (url=0x166a2a47 "data", w=0x166a25e0, host=0x159c9630) at web/server/web_client.c:600
#12 check_host_and_call () at web/server/web_client.c:576
#13 web_client_process_url.lto_priv.80 (host=0x159c9630, w=w@entry=0x166a25e0, url=0x166a2a44 "v1", url@entry=0x166a2a3f "") at web/server/web_client.c:1388
#14 0x000000000047fa27 in web_client_process_request (w=0x166a25e0) at web/server/web_client.c:1534
#15 web_server_rcv_callback (pi=0x15a85d58, events=0x15a8597c) at web/server/static/static-threaded.c:255
#16 0x000000000044c5fc in poll_events_process (now=3577213, revents=1, pf=0x15a85978, pi=0x15a85d58, p=0x7fb88b064c20) at libnetdata/socket/socket.c:1332
#17 poll_events (sockets=sockets@entry=0x7104c0 <api_sockets>, add_callback=add_callback@entry=0x4804e3 <web_server_add_callback>, 
    del_callback=del_callback@entry=0x47def9 <web_server_del_callback>, rcv_callback=rcv_callback@entry=0x47f6e9 <web_server_rcv_callback>, 
    snd_callback=snd_callback@entry=0x47ea84 <web_server_snd_callback>, tmr_callback=tmr_callback@entry=0x47e66e <web_server_tmr_callback>, access_list=0x15a77ad0, 
    data=0x0, tcp_request_timeout_seconds=60, tcp_idle_timeout_seconds=60, timer_milliseconds=1000, timer_data=0x15a7e040, max_tcp_sockets=128)
    at libnetdata/socket/socket.c:1606
#18 0x000000000047e3f1 in socket_listen_main_static_threaded_worker (ptr=0x15a7e040) at web/server/static/static-threaded.c:389
#19 0x000000000044aac9 in thread_start (ptr=0x15a81be0) at libnetdata/threads/threads.c:126
#20 0x00007fb890c5a064 in start_thread (arg=0x7fb88b065700) at pthread_create.c:309
#21 0x00007fb89098f62d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) 
```

valgrind:
```
cdn77 ~ # cat valgrind.err 
==25012== Memcheck, a memory error detector
==25012== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==25012== Using Valgrind-3.10.0 and LibVEX; rerun with -h for copyright info
==25012== Command: /usr/sbin/netdata -D
==25012== 
==25012== Thread 9:
==25012== Invalid write of size 1
==25012==    at 0x479C31: http_request_validate.lto_priv.81 (web_client.c:1068)
==25012==    by 0x47F92F: web_client_process_request (web_client.c:1491)
==25012==    by 0x47F92F: web_server_rcv_callback (static-threaded.c:255)
==25012==    by 0x44C5FB: poll_events_process (socket.c:1332)
==25012==    by 0x44C5FB: poll_events (socket.c:1606)
==25012==    by 0x47E3F0: socket_listen_main_static_threaded_worker (static-threaded.c:389)
==25012==    by 0x47E648: socket_listen_main_static_threaded (static-threaded.c:497)
==25012==    by 0x44AAC8: thread_start (threads.c:126)
==25012==    by 0x555E063: start_thread (pthread_create.c:309)
==25012==    by 0x585B62C: clone (clone.S:111)
==25012==  Address 0x2c26cdc6 is 22 bytes inside a block of size 22,534 free'd
==25012==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25012==    by 0x4ADAE1: reallocz (libnetdata.c:188)
==25012==    by 0x406AA3: buffer_increase (buffer.c:396)
==25012==    by 0x406EA7: buffer_need_bytes (buffer.h:82)
==25012==    by 0x406EA7: buffer_sprintf (buffer.c:227)
==25012==    by 0x41C335: rrd_stats_api_v1_charts_allmetrics_prometheus.lto_priv.184 (backend_prometheus.c:385)
==25012==    by 0x442273: rrd_stats_api_v1_charts_allmetrics_prometheus_single_host (backend_prometheus.c:760)
==25012==    by 0x442273: web_client_api_request_v1_allmetrics (allmetrics.c:87)
==25012==    by 0x47A7AE: web_client_api_request_v1 (web_api_v1.c:810)
==25012==    by 0x47A7AE: web_client_api_request (web_client.c:600)
==25012==    by 0x47A7AE: check_host_and_call (web_client.c:576)
==25012==    by 0x47A7AE: web_client_process_url.lto_priv.80 (web_client.c:1388)
==25012==    by 0x47FA26: web_client_process_request (web_client.c:1534)
==25012==    by 0x47FA26: web_server_rcv_callback (static-threaded.c:255)
==25012==    by 0x44C5FB: poll_events_process (socket.c:1332)
==25012==    by 0x44C5FB: poll_events (socket.c:1606)
==25012==    by 0x47E3F0: socket_listen_main_static_threaded_worker (static-threaded.c:389)
==25012==    by 0x47E648: socket_listen_main_static_threaded (static-threaded.c:497)
==25012==    by 0x44AAC8: thread_start (threads.c:126)
==25012== 
cdn77 ~ # 
```
##### Expected behavior
not crash

### PR DESCRIPTION
**Pull request by thiagoftsm**
##### Summary
The netdata has a random error to allocate memory in some requests according with outputs  we were receiving from our demo server.

After to check the valgrind output, it was possible to verify that the malloc error could happen steps before due a set of values in an address NULL. This pull request fixes this checking the existence of a valid address before to set the value.
##### Component Name
web/ url parser
##### Additional Information
It fixes #6582

### CODE REVIEW

File: web/server/web_client.c [hunk 1]
```diff
@@ -1041,7 +1041,7 @@ static inline HTTP_VALIDATION http_request_validate(struct web_client *w) {
                 } else {
                     web_client_split_path_query(w, encoded_url);
 
-                    if (w->separator) {
+                    if (w->separator && w->url_search_path) {
```
Comment (mfundul) [inline web/server/web_client.c]: I don't see how this will fix the corruption, the problem is not `w->url_search_path` being NULL. If it was NULL it would crash immediately. The problem is that it is *not* NULL and it goes and writes someplace where it shouldn't. Maybe it should be initialized to NULL at some other place as well?

File: web/server/web_client.c [hunk 2]
```diff
@@ -1064,7 +1064,7 @@ static inline HTTP_VALIDATION http_request_validate(struct web_client *w) {
                 // copy the URL - we are going to overwrite parts of it
                 // TODO -- ideally we we should avoid copying buffers around
                 strncpyz(w->last_url, w->decoded_url, NETDATA_WEB_REQUEST_URL_SIZE);
-                if (w->separator) {
+                if (w->separator && w->url_search_path) {
```
Comment (mfundul) [inline web/server/web_client.c]: I don't see how this will fix the corruption, the problem is not w->url_search_path being NULL. If it was NULL it would crash immediately. The problem is that it is not NULL and it goes and writes someplace where it shouldn't. Maybe it should be initialized to NULL at some other place as well?

File: web/server/web_client.c (hunk 1 above)
Comment (thiagoftsm) [reply web/server/web_client.c]: the web client structure is always set to zero in the file web_client_cache.c in the function present at the line 162, this function is called from static-threaded.c line 16, this is the motive I did not change before, but I am setting it to NULL case I missed something in the whole process.

File: web/server/web_client.c (hunk 2 above)
Comment (thiagoftsm) [reply web/server/web_client.c]: The same thing described above!

File: web/server/web_client.c [hunk 3]
```diff
@@ -1035,13 +1034,15 @@ static inline HTTP_VALIDATION http_request_validate(struct web_client *w) {
                 // a valid complete HTTP request found
 
                 *ue = '\0';
+                //This is to avoid crash in line
+                w->url_search_path = NULL;
```
Comment (mfundul) [inline web/server/web_client.c]: This does not solve the problem. Now it will crash in line 1053 with NULL pointer dereference.
