### PR TITLE
Check for source field when requesting /api/v1/alarm_log

### LINKED ISSUE #15304: [Bug]: Netdata crashes when opening Alarms->Log tab on the parent instance
### Bug description

[Reported on Discord](https://discord.com/channels/847502280503590932/1125422196848853056/1125422196848853056).

See

```c
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
#1  0x00007f98ad3f9f2f in __GI___strdup (s=s@entry=0x0) at strdup.c:41
#2  0x0000565225b1474d in strdupz (s=0x0) at libnetdata/libnetdata.c:448
#3  0x0000565225b86e10 in health_edit_command_from_source (source=0x0) at health/health_config.c:442
#4  0x0000565225ca1f78 in sql_health_alarm_log2json (host=host@entry=0x565227673010, wb=0x56522be4ef10, after=after@entry=0, chart=chart@entry=0x0)
    at database/sqlite/sqlite_health.c:1344
#5  0x0000565225b68cb3 in web_client_api_request_v1_alarm_log (host=0x565227673010, w=0x565233859240, url=<optimized out>) at web/api/web_api_v1.c:463
#6  0x0000565225da3d3a in web_client_api_request (host=host@entry=0x565227673010, w=w@entry=0x565233859240, url_path_fragment=<optimized out>)
    at web/server/web_client.c:710
#7  0x0000565225da4468 in check_host_and_call (func=0x565225da3b50 <web_client_api_request>, url=<optimized out>, w=0x565233859240, host=0x565227673010)
    at web/server/web_client.c:684
#8  web_client_process_url (host=0x565227673010, w=w@entry=0x565233859240, decoded_url_path=<optimized out>) at web/server/web_client.c:1475
#9  0x0000565225da758c in web_client_process_request (w=w@entry=0x565233859240) at web/server/web_client.c:1662
#10 0x0000565225da9d22 in web_server_rcv_callback (pi=0x56522e652ae0, events=0x56522cb614a4) at web/server/static/static-threaded.c:295
#11 0x0000565225b23d23 in poll_process_tcp_read (now=357864, pf=<optimized out>, pi=<optimized out>, p=0x7f98782b43e0) at libnetdata/socket/socket.c:1618
#12 poll_events (sockets=<optimized out>, add_callback=add_callback@entry=0x565225daa0c0 <web_server_add_callback>,
    del_callback=del_callback@entry=0x565225daa030 <web_server_del_callback>, rcv_callback=rcv_callback@entry=0x565225da9cc0 <web_server_rcv_callback>,
    snd_callback=snd_callback@entry=0x565225da9bc0 <web_server_snd_callback>, tmr_callback=tmr_callback@entry=0x0, check_to_stop_callback=<optimized out>,
    access_list=<optimized out>, allow_dns=<optimized out>, data=<optimized out>, tcp_request_timeout_seconds=<optimized out>, tcp_idle_timeout_seconds=<optimized out>,
    timer_milliseconds=<optimized out>, timer_data=<optimized out>, max_tcp_sockets=<optimized out>) at libnetdata/socket/socket.c:1939
#13 0x0000565225da9b4e in socket_listen_main_static_threaded_worker (ptr=<optimized out>) at web/server/static/static-threaded.c:429
#14 0x0000565225b27c15 in netdata_thread_init (ptr=<optimized out>) at libnetdata/threads/threads.c:262
#15 0x00007f98ad878ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#16 0x00007f98ad46ba2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### Expected behavior

Netdata doesn't crash.

### Steps to reproduce

1. Go to the local dashboard of a parent instance
2. and open Alarms->Log

### Installation method

kickstart.sh

### System info

```shell
n/a
```

### Netdata build info

```shell
Version: netdata v1.40.0-69-gfdfc8fa0b
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O2 -g' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
    HTTPD (h2o):                YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    debugfs:                 YES
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

Fixes #15304 

Adds a check for the `source` field when `api/v1/alarm_log` is requested. Will also investigate the missing field in a separate PR.

##### Test Plan

To trigger the issue:

While an agent is running, update the `source` field of table `alert_hash` to NULL for a couple of alerts (that are running on the system). Request `http://localhost:19999/api/v1/alarm_log`. Without this PR there is a crash, with this PR there is not.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Review by stelfrag — APPROVED** [review]

File: database/sqlite/sqlite_health.c [hunk 1]
```diff
@@ -1345,7 +1345,7 @@ void sql_health_alarm_log2json(RRDHOST *host, BUFFER *wb, uint32_t after, char *
         if (sqlite3_column_type(res, 31) != SQLITE_NULL)
             uuid_unparse_lower(*((uuid_t *) sqlite3_column_blob(res, 31)), transition_id);
 
-        char *edit_command = health_edit_command_from_source((char *)sqlite3_column_text(res, 17));
+        char *edit_command = sqlite3_column_bytes(res, 17) > 0 ? health_edit_command_from_source((char *)sqlite3_column_text(res, 17)) : strdupz("UNKNOWN=0=UNKNOWN");
```
Comment (thiagoftsm) [inline database/sqlite/sqlite_health.c:1348]: Hello @MrZammler ,

Considering that you are using a `strdupz` in a function that you won't return the value, we should use `freez` before the function ends.

Best regards!

Comment (MrZammler) [reply database/sqlite/sqlite_health.c:1348]: Hi Thiago! There is a `freez(edit_command);` a few lines below (1457), or did I not understand correctly?

**Review by ilyam8 — APPROVED** [review]

File: database/sqlite/sqlite_health.c (hunk 1 above)
Comment (thiagoftsm) [reply database/sqlite/sqlite_health.c:1348]: I am sorry, I missed that :+1:

**Review by thiagoftsm — APPROVED** [review]
