### PR TITLE
Fix issue with charts not properly synchronized with the cloud

### LINKED ISSUE #12443: [Bug]: agent does not propagate the right chart and dimension liveness to cloud
### Bug description

There are many cases:

1. Charts being live on the agent, but not live at the cloud
2. Charts being obsolete on the agent, but live at the cloud

The way this works now, the cloud is out of sync on charts and dimensions, presenting either incomplete or wrong information about the charts that are available on the cloud.

This is a critical issue, that deserves first priority resolution, as it makes the cloud unusable.

### Expected behavior

Charts and dimensions should always be in-sync with cloud

### Steps to reproduce

1. Start and stop containers and VMs. The cloud table of contents gets bigger and bigger.
2. Start containers and while they run, reboot the machine. After agent restart, charts on the cloud persist although the charts are not there any more.
3. Combine the 2 above (so, have some old charts, reboot, start the containers again) to get into charts being live at the agent, but not live at the cloud.

### Installation method

kickstart.sh

### System info

```shell
N/A
```

### Netdata build info

```shell
# netdata -W buildinfo
Version: netdata v1.33.1-187-g4dca6582b
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O0 -ggdb' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

### Additional info

Related to:

* https://github.com/netdata/cloud-frontend/issues/3030
* https://github.com/netdata/netdata/discussions/12358

@stelfrag @papazach @ilyam8 @dimko

### PR DESCRIPTION
**Pull request by stelfrag**
Fixes #12443
##### Summary
- Reverts changes made that delayed (by taking into account the chart obsoletion setting) the propagation of liveness update of dimensions to the cloud
- Adds additional checks to verify the current liveness of charts during the runtime of the agent
  - This is done as the agent checks for charts that need to be obsoleted
- Adds check for dimension liveness when the `retention update message` is calculated for each node
  - This is done soon after an agent restart (60 seconds after aclk sync messages settle) and periodically (every hour)

##### Test Plan
- As described in the linked issue

### CODE REVIEW

**Comment by ilyam8** [comment]
I've tested the functionality and it works well: if there is no collected data in the selected timeframe - no charts on the Cloud (one minor thing, not Netdata Agent related - I have to refresh the page to get charts disappeared, they are empty with Error status until I do that).

I tested the following cases:

 - Netdata(fixed) -> Cloud
 - Netdata Child -> Netdata Parent(fixed) -> Cloud

**Comment by underhood** [comment]
rebase needed

**Comment by stelfrag** [comment]
Rebasing

**Review by ilyam8 — APPROVED** [review]
Approving based on [manual tests](https://github.com/netdata/netdata/pull/12451#issuecomment-1082996850), this PR fixes the problem 🎉 Not 🤓 enough to review the code.

File: database/sqlite/sqlite_aclk_chart.c [hunk 1]
```diff
@@ -944,6 +941,24 @@ void aclk_update_retention(struct aclk_database_worker_config *wc, struct aclk_d
 
         if (likely(!rc && first_entry_t))
             start_time = MIN(start_time, first_entry_t);
+
+        if (wc->chart_updates) {
+            int live = ((now - last_entry_t) < (RRDSET_MINIMUM_DIM_LIVE_MULTIPLIER * update_every));
+            if ((!live || !first_entry_t) && (dimension_update_count < ACLK_MAX_DIMENSION_CLEANUP)) {
+                (void)aclk_upd_dimension_event(
```
Comment (MrZammler) [inline database/sqlite/sqlite_aclk_chart.c:948]: Hi Stelio. This passes return values from the sql query, but in case of memory mode not dbengine, it will execute SELECT_HOST_CHART_LIST which does not appear to return the same columns as SELECT_HOST_DIMENSION_LIST ?

**Review by underhood — APPROVED** [review]

File: database/sqlite/sqlite_aclk_chart.c (hunk 1 above)
Comment (stelfrag) [reply database/sqlite/sqlite_aclk_chart.c:948]: I will push a fix since this will only work for dbengine

**Review by underhood — APPROVED** [review]

**Review by MrZammler — APPROVED** [review]
Also run locally, didn't notice something weird.
