### PR TITLE
Fix duplicate header leak in ACLK HTTPS client

### LINKED ISSUE #21083: [Bug]: aclk memory leak
### Bug description

```
=================================================================
==508058==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 29 byte(s) in 1 object(s) allocated from:
    #0 0x7f3ea391a42a in strdup /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_interceptors.cpp:593
    #1 0x55c8ac297c30 in strdupz /home/costa/src/netdata-ktsaou.git/src/libnetdata/memory/nd-mallocz.c:428
    #2 0x55c8ab91bec1 in process_http_hdr /home/costa/src/netdata-ktsaou.git/src/aclk/https_client.c:217
    #3 0x55c8ab91c812 in parse_http_hdr /home/costa/src/netdata-ktsaou.git/src/aclk/https_client.c:269
    #4 0x55c8ab91e6ea in parse_http_response /home/costa/src/netdata-ktsaou.git/src/aclk/https_client.c:420
    #5 0x55c8ab9202c1 in read_parse_response /home/costa/src/netdata-ktsaou.git/src/aclk/https_client.c:623
    #6 0x55c8ab9211ea in handle_http_request /home/costa/src/netdata-ktsaou.git/src/aclk/https_client.c:710
    #7 0x55c8ab922c95 in https_request /home/costa/src/netdata-ktsaou.git/src/aclk/https_client.c:880
    #8 0x55c8abc9b561 in aclk_https_request /home/costa/src/netdata-ktsaou.git/src/aclk/aclk_otp.c:28
    #9 0x55c8abc9d92b in aclk_send_otp_response /home/costa/src/netdata-ktsaou.git/src/aclk/aclk_otp.c:384
    #10 0x55c8abc9e5f9 in aclk_get_mqtt_otp /home/costa/src/netdata-ktsaou.git/src/aclk/aclk_otp.c:498
    #11 0x55c8ab8fb762 in aclk_attempt_to_connect /home/costa/src/netdata-ktsaou.git/src/aclk/aclk.c:706
    #12 0x55c8ab8fc85a in aclk_main /home/costa/src/netdata-ktsaou.git/src/aclk/aclk.c:887
    #13 0x55c8ac04124d in nd_thread_starting_point /home/costa/src/netdata-ktsaou.git/src/libnetdata/threads/threads.c:367
    #14 0x7f3ea385e11a in asan_thread_start /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_interceptors.cpp:239
    #15 0x7f3ea1e969ca  (/usr/lib/libc.so.6+0x969ca) (BuildId: 4fe011c94a88e8aeb6f2201b9eb369f42b4a1e9e)

Direct leak of 29 byte(s) in 1 object(s) allocated from:
    #0 0x7f3ea391a42a in strdup /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_interceptors.cpp:593
    #1 0x55c8ac297c30 in strdupz /home/costa/src/netdata-ktsaou.git/src/libnetdata/memory/nd-mallocz.c:428
    #2 0x55c8ab91bec1 in process_http_hdr /home/costa/src/netdata-ktsaou.git/src/aclk/https_client.c:217
    #3 0x55c8ab91c812 in parse_http_hdr /home/costa/src/netdata-ktsaou.git/src/aclk/https_client.c:269
    #4 0x55c8ab91e6ea in parse_http_response /home/costa/src/netdata-ktsaou.git/src/aclk/https_client.c:420
    #5 0x55c8ab9202c1 in read_parse_response /home/costa/src/netdata-ktsaou.git/src/aclk/https_client.c:623
    #6 0x55c8ab9211ea in handle_http_request /home/costa/src/netdata-ktsaou.git/src/aclk/https_client.c:710
    #7 0x55c8ab922c95 in https_request /home/costa/src/netdata-ktsaou.git/src/aclk/https_client.c:880
    #8 0x55c8abc9b561 in aclk_https_request /home/costa/src/netdata-ktsaou.git/src/aclk/aclk_otp.c:28
    #9 0x55c8abc9cbd3 in aclk_get_otp_challenge /home/costa/src/netdata-ktsaou.git/src/aclk/aclk_otp.c:294
    #10 0x55c8abc9e31a in aclk_get_mqtt_otp /home/costa/src/netdata-ktsaou.git/src/aclk/aclk_otp.c:479
    #11 0x55c8ab8fb762 in aclk_attempt_to_connect /home/costa/src/netdata-ktsaou.git/src/aclk/aclk.c:706
    #12 0x55c8ab8fc85a in aclk_main /home/costa/src/netdata-ktsaou.git/src/aclk/aclk.c:887
    #13 0x55c8ac04124d in nd_thread_starting_point /home/costa/src/netdata-ktsaou.git/src/libnetdata/threads/threads.c:367
    #14 0x7f3ea385e11a in asan_thread_start /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_interceptors.cpp:239
    #15 0x7f3ea1e969ca  (/usr/lib/libc.so.6+0x969ca) (BuildId: 4fe011c94a88e8aeb6f2201b9eb369f42b4a1e9e)

Direct leak of 29 byte(s) in 1 object(s) allocated from:
    #0 0x7f3ea391a42a in strdup /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_interceptors.cpp:593
    #1 0x55c8ac297c30 in strdupz /home/costa/src/netdata-ktsaou.git/src/libnetdata/memory/nd-mallocz.c:428
    #2 0x55c8ab91bec1 in process_http_hdr /home/costa/src/netdata-ktsaou.git/src/aclk/https_client.c:217
    #3 0x55c8ab91c812 in parse_http_hdr /home/costa/src/netdata-ktsaou.git/src/aclk/https_client.c:269
    #4 0x55c8ab91e6ea in parse_http_response /home/costa/src/netdata-ktsaou.git/src/aclk/https_client.c:420
    #5 0x55c8ab9202c1 in read_parse_response /home/costa/src/netdata-ktsaou.git/src/aclk/https_client.c:623
    #6 0x55c8ab9211ea in handle_http_request /home/costa/src/netdata-ktsaou.git/src/aclk/https_client.c:710
    #7 0x55c8ab922c95 in https_request /home/costa/src/netdata-ktsaou.git/src/aclk/https_client.c:880
    #8 0x55c8abc9b561 in aclk_https_request /home/costa/src/netdata-ktsaou.git/src/aclk/aclk_otp.c:28
    #9 0x55c8abca0ef9 in aclk_get_env /home/costa/src/netdata-ktsaou.git/src/aclk/aclk_otp.c:825
    #10 0x55c8ab8fb367 in aclk_attempt_to_connect /home/costa/src/netdata-ktsaou.git/src/aclk/aclk.c:668
    #11 0x55c8ab8fc85a in aclk_main /home/costa/src/netdata-ktsaou.git/src/aclk/aclk.c:887
    #12 0x55c8ac04124d in nd_thread_starting_point /home/costa/src/netdata-ktsaou.git/src/libnetdata/threads/threads.c:367
    #13 0x7f3ea385e11a in asan_thread_start /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_interceptors.cpp:239
    #14 0x7f3ea1e969ca  (/usr/lib/libc.so.6+0x969ca) (BuildId: 4fe011c94a88e8aeb6f2201b9eb369f42b4a1e9e)

SUMMARY: AddressSanitizer: 87 byte(s) leaked in 3 allocation(s).
```

### Expected behavior

Not to leak memory.

### Steps to reproduce

1. Compile with ASAN and leak-checker
2. Start Netdata from the command line
3. Wait for ACLK to connect
4. Stop Netdata with control-C
5. ASAN reports the leak

### Installation method

kickstart.sh

### System info

```shell
irrelevant
```

### Netdata build info

```shell
latest nightly
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ktsaou**
- free the previous allocation when the same header key is seen again
- keep parser init/reset safety tweaks from the local branch

Fixes #21083

In other works, aclk was leaking the value of each duplicate http response header key received. It was using the last, but all previous were leaked. Now it frees duplicates before allocating a new one (still uses the last one).

### CODE REVIEW

File: src/aclk/https_client.c [hunk 1]
```diff
@@ -214,6 +222,10 @@ static int process_http_hdr(http_parse_ctx *parse_ctx, const char *key, const ch
         }
         return 0;
     }
+    void *prev_val = NULL;
+    if (!c_rhash_get_ptr_by_str(parse_ctx->headers, key, &prev_val))
+        freez(prev_val); // drop previous allocation before overwriting
```
Comment (ktsaou) [inline src/aclk/https_client.c:227]: @stelfrag if you don't want to keep the rest, the above 2 lines fix the actual leak.

All the others are supposed to make this more robust.

**Review by stelfrag — APPROVED** [review]
