### PR TITLE
Fix container virtualization info

### LINKED ISSUE #10568: Machine virtualization incorrectly identified in proxmox host with lxc containers
##### Bug report summary
Our system-info.sh returns "none" for virtualization technology, but it is lxc.

##### OS / Environment
Debian buster

##### Netdata version
Latest
 

##### Component Name
system-info.sh

##### Steps To Reproduce
run `systemd-detect-virt` and `systemd-detect-virt -v`. The former returns `lxc`, the latter `none`.

##### Expected behavior
Return the correct virtualization technology.

reference: https://community.netdata.cloud/t/best-way-to-setup-netdata-in-a-proxmox-host-with-some-lxc-containers/81

### PR DESCRIPTION
**Pull request by vlvkobal**
##### Summary
The detection of container virtualization technology was prevented by an incorrect check for the corresponding variable.

Fixes #10568

##### Test Plan
Run `system-info.sh` in a Proxmox container. It should return `NETDATA_SYSTEM_CONTAINER=lxc`

### CODE REVIEW

**Comment by ilyam8** [comment]
I briefly checked the master branch and it looks like the **only** problematic line is

https://github.com/netdata/netdata/blob/f0658258075f65c87bc8d121347fdc1e6e3c8dd6/daemon/system-info.sh#L36

It should be changed to `CONTAINER="$(systemd-detect-virt -c)"`. Can you check if it fixes the problem?

File: daemon/system-info.sh [hunk 1]
```diff
@@ -33,7 +33,8 @@ if [ -z "${VIRTUALIZATION}" ]; then
   if command -v systemd-detect-virt >/dev/null 2>&1; then
     VIRTUALIZATION="$(systemd-detect-virt -v)"
     VIRT_DETECTION="systemd-detect-virt"
-    CONTAINER=${CONTAINER:-$(systemd-detect-virt -c)}
+    CONTAINER_DETECT_TMP="$(systemd-detect-virt -c)"
```
Comment (ilyam8) [inline daemon/system-info.sh:36]: not really needed to be upper case

**Review by ilyam8 — APPROVED** [review]
