### PR TITLE
Fixed global GUID map memory leak

### LINKED ISSUE #9724: Memory leak during global GUID map object creation
#### Summary

When an object of type `GUID_CHAR_TYPE` is about to be created but already exists, the memory allocated is not released
inside the `find_or_generate_guid` function.

Sample valgrind output:

```
==2636955== 10,102 bytes in 629 blocks are possibly lost in loss record 2,937 of 3,003
==2636955==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==2636955==    by 0x14360D: mallocz (libnetdata.c:177)
==2636955==    by 0x1CF1F8: find_or_generate_guid (global_uuid_map.c:231)
==2636955==    by 0x1CF072: find_or_generate_guid (global_uuid_map.c:209)
==2636955==    by 0x1BEDED: rrdeng_metric_init (rrdengineapi.c:121)
==2636955==    by 0x1A30E0: rrddim_add_custom (rrddim.c:394)
==2636955==    by 0x1CC6EF: metalog_pluginsd_dimension_action (metalogpluginsd.c:168)
==2636955==    by 0x194AF0: pluginsd_dimension (pluginsd_parser.c:420)
==2636955==    by 0x1ECAE9: parser_action (parser.c:296)
==2636955==    by 0x1CA7F8: replay_record (logfile.c:411)
==2636955==    by 0x1CAED5: iterate_records (logfile.c:527)
==2636955==    by 0x1CB0B8: load_metadata_logfile (logfile.c:563)
```

### PR DESCRIPTION
**Pull request by stelfrag**
Fixes #9724

##### Summary
The object memory is now released if the object already exists in the map.

The memory leak only affects the `GUID_TYPE_CHAR` objects. 

##### Component Name
database

##### Test Plan
- Run valgrind to track the  `GUID_TYPE_CHAR` object creation during the creation of `GUID_TYPE_DIMENSION` or `GUID_TYPE_CHART` object in `find_or_generate_guid`

### CODE REVIEW

File: database/engine/global_uuid_map/global_uuid_map.c [hunk 1]
```diff
@@ -244,10 +244,12 @@ int find_or_generate_guid(void *object, uuid_t *uuid, GUID_TYPE object_type, int
         uv_rwlock_wrunlock(&global_lock);
         return rc;
     }
-    //uv_rwlock_wrunlock(&global_lock);
+    else {
```
Comment (mfundul) [inline database/engine/global_uuid_map/global_uuid_map.c:247]: You don't really need the `else` here because the `if` above it returns :)

File: database/engine/global_uuid_map/global_uuid_map.c [hunk 2]
```diff
@@ -244,10 +244,12 @@ int find_or_generate_guid(void *object, uuid_t *uuid, GUID_TYPE object_type, int
         uv_rwlock_wrunlock(&global_lock);
         return rc;
```
Comment (mfundul) [inline database/engine/global_uuid_map/global_uuid_map.c:245]: You could also add a `if (rc) freez(target_object);` here.

File: database/engine/global_uuid_map/global_uuid_map.c (hunk 1 above)
Comment (stelfrag) [reply database/engine/global_uuid_map/global_uuid_map.c:247]: > You don't really need the `else` here because the `if` above it returns :)

How do you DO that!! :smile:

File: database/engine/global_uuid_map/global_uuid_map.c (hunk 2 above)
Comment (stelfrag) [reply database/engine/global_uuid_map/global_uuid_map.c:245]: True, I will add

File: database/engine/global_uuid_map/global_uuid_map.c (hunk 1 above)
Comment (mfundul) [reply database/engine/global_uuid_map/global_uuid_map.c:247]: No shame!!!

Comment (amoss) [reply database/engine/global_uuid_map/global_uuid_map.c]: lol
