### PR TITLE
Don't send alert events without wc->host

### LINKED ISSUE #12539: [Bug]: Agent crashes during ACLK sync
### Bug description

The agent crashes when executing a push alert event

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055744e6b9e6f in aclk_push_alert_event (wc=0x55745a388d40, cmd=...) at database/sqlite/sqlite_aclk_alert.c:204
204	        alarm_log.utc_offset = wc->host->utc_offset;
[Current thread is 1 (Thread 0x7f14965e2640 (LWP 220682))]
(gdb) where
#0  0x000055744e6b9e6f in aclk_push_alert_event (wc=0x55745a388d40, cmd=...) at database/sqlite/sqlite_aclk_alert.c:204
#1  0x000055744e6add7e in aclk_database_worker (arg=0x55745a388d40) at database/sqlite/sqlite_aclk.c:481
#2  0x00007f149ba60947 in start_thread (arg=<optimized out>) at pthread_create.c:435
#3  0x00007f149baf0a44 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100
(gdb) up
#1  0x000055744e6add7e in aclk_database_worker (arg=0x55745a388d40) at database/sqlite/sqlite_aclk.c:481
481	                    aclk_push_alert_event(wc, cmd);
(gdb) p wc->host
$1 = (RRDHOST *) 0x0
```

### Expected behavior

The agent should handle this situation and not crash

### Steps to reproduce

Cannot be reproduced every time but it happens. 

### Installation method

from source

### System info

```shell
Linux futura 5.13.0-37-generic #42-Ubuntu SMP Tue Mar 15 14:34:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=21.10
/etc/lsb-release:DISTRIB_CODENAME=impish
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 21.10"
/etc/os-release:PRETTY_NAME="Ubuntu 21.10"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="21.10"
/etc/os-release:VERSION="21.10 (Impish Indri)"
/etc/os-release:VERSION_CODENAME=impish
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=impish
```

### Netdata build info

```shell
Version: netdata v1.33.1-236-gb0e6c0700
Configure options:  '--prefix=/home/stelios/netdata-inst/netdata/usr' '--sysconfdir=/home/stelios/netdata-inst/netdata/etc' '--localstatedir=/home/stelios/netdata-inst/netdata/var' '--libexecdir=/home/stelios/netdata-inst/netdata/usr/libexec' '--libdir=/home/stelios/netdata-inst/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--disable-ml' '--disable-ebpf' '--with-bundled-protobuf' 'CFLAGS=-O0 -ggdb -Wall -Wextra -Wformat-truncation=2 -Wunused-result -Wformat-signedness -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           NO
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

Don't try to send alert events if `wc->host` is not yet connected. If that happens, it is better to wait for the next iteration of the function (when eventually `wc->host` will be ok... ?) instead of sending an event with missing timezone data.

Fixes #12539 

##### Test Plan

Since it's hard to reproduce, basic testing of alerts still going to the cloud after this change should be ok.

### CODE REVIEW

File: database/sqlite/sqlite_aclk_alert.c [hunk 1]
```diff
@@ -135,6 +135,9 @@ void aclk_push_alert_event(struct aclk_database_worker_config *wc, struct aclk_d
     if (unlikely(!claim_id))
         return;
 
+    if (unlikely(!wc->host))
+        return;
```
Comment (stelfrag) [inline database/sqlite/sqlite_aclk_alert.c:139]: leaks memory allocated for  `claim_id`

Comment (MrZammler) [reply database/sqlite/sqlite_aclk_alert.c:140]: Indeed it does! Thanks!

**Review by stelfrag — APPROVED** [review]

**Review by underhood — APPROVED** [review]
