### PR TITLE
Get netdata execution path early to avoid user permission issues

### LINKED ISSUE #9113: netdata: spawn/spawn.c:202: create_spawn_server: Assertion `ret == 0' failed.
Hi , 
netdata stoped working on the server 
is it a known issue for you , since i looked up for this issue and couldn't find information  / solution regarding it  

 when try to restart the service get this error : 
Starting netdata...2020-05-20 14:45:30: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
2020-05-20 14:45:30: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
                                                           [  OK  ]

and from the log file : 
```
2020-05-20 14:45:30: netdata INFO  : MAIN : resources control: allowed file descriptors: soft = 350000, max = 350000
2020-05-20 14:45:30: netdata INFO  : MAIN : Adjusted my Out-Of-Memory (OOM) score from 0 to 1000.
2020-05-20 14:45:30: netdata INFO  : MAIN : Adjusted netdata scheduling policy to idle (5), with priority 0.
2020-05-20 14:45:30: netdata INFO  : MAIN : Running with process scheduling policy 'idle'
2020-05-20 14:45:30: netdata INFO  : MAIN : netdata started on pid 58514.
2020-05-20 14:45:30: netdata INFO  : MAIN : Initializing spawn client.
netdata: spawn/spawn.c:202: create_spawn_server: Assertion `ret == 0' failed.
```
OS:
```
runing on : 
CentOS release 6.8 (Final)
Linux  3.10.79-1.el6.elrepo.x86_64 #1 SMP Mon May 18 12:08:18 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

```
netdat version : 

netdata v1.22.1-74-nightly

tried to uninstall and reinstall netdata , same issue

### LINKED ISSUE #9331: CentOS 6.10: "Cannot start netdata without the spawn server."
When trying to install Netdata on CentOS 6.10 (using root) with:

`bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)`

I get the following logging:

```
2020-06-12 19:42:00: netdata INFO  : MAIN : resources control: allowed file descriptors: soft = 1024, max = 1024
2020-06-12 19:42:00: netdata ERROR : MAIN : Out-Of-Memory (OOM) score setting is not supported on this system. (errno 2, No such file or directory)
2020-06-12 19:42:00: netdata ERROR : MAIN : Cannot adjust netdata scheduling policy to idle (5), with priority 0. Falling back to nice. (errno 38, Function not implemented)
2020-06-12 19:42:00: netdata ERROR : MAIN : Cannot get my current process scheduling policy. (errno 38, Function not implemented)
2020-06-12 19:42:00: netdata INFO  : MAIN : netdata started on pid 16328.
2020-06-12 19:42:00: netdata INFO  : MAIN : Initializing spawn client.
2020-06-12 19:42:00: netdata ERROR : MAIN : uv_exepath("", 4096) (user: netdata) failed (permission denied). (errno 13, Permission denied)
2020-06-12 19:42:00: netdata FATAL : MAIN :Cannot start netdata without the spawn server. # : Invalid argument
2020-06-12 19:42:00: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...
2020-06-12 19:42:00: netdata INFO  : MAIN : EXIT: cleaning up the database...
2020-06-12 19:42:00: netdata INFO  : MAIN : Cleaning up database [0 hosts(s)]...
2020-06-12 19:42:00: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...
```

Netdata is successfully installed, but isn't able to start. A process restart of netdata (/etc/init.d/netdata restart) gives the same logging output, obviously.

### PR DESCRIPTION
**Pull request by mfundul**
##### Summary
Fixes #9331 
Fixes #9113 

##### Component Name
daemon

##### Test Plan

Run it in affected CentOS 6 systems, see if the problem is resolved.

##### Additional Information

For some unknown reason some CentOS 6 installations fail to get the netdata binary execution path with libuv library calls and get "permission denied" errors. This PR attempts to get the path early before switching user to work around potential permission issues in path resolution or elsewhere.

### CODE REVIEW

File: daemon/daemon.c [hunk 1]
```diff
@@ -5,6 +5,27 @@
...
+{
+    int ret;
+    size_t exepath_size = 0;
+    struct passwd *passwd = NULL;
+    char *user = NULL;
+
+    passwd = getpwuid(getuid());
+    user = (passwd && passwd->pw_name) ? passwd->pw_name : "";
+
+    exepath_size = sizeof(exepath);
```
Comment (amoss) [inline daemon/daemon.c:20]: This should be `sizeof(exepath) -1`. There is a `buffer[*size] = '\0';` inside the library.

Comment (mfundul) [reply daemon/daemon.c]: Yeap.
