### PR TITLE
netdata/daemon: SSL fix - broken compilation case when ssl library not present!

### LINKED ISSUE #6200: Update fails because of new system dependencies
I have netdata installed on several KVM hosts that run Debian 8/9.  I ran the install via `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` about a few months ago.  Over the weekend, they have all been failing to update due to missing system dependencies.  I decided to uninstall & reinstall on one of the hosts to see if it would install more packages that weren't already there.  Turns out, it did bring in several new packages:

```Loading /etc/os-release ...

/etc/os-release information:
NAME            : Debian GNU/Linux
VERSION         : 9 (stretch)
ID              : debian
ID_LIKE         :
VERSION_ID      : 9

We detected these:
Distribution    : debian
Version         : 9
Codename        : 9 (stretch)
Package Manager : install_apt_get
Packages Tree   : debian
Detection Method: /etc/os-release
Default Python v: 2

 > Checking if package 'autoconf-archive' is installed...
 > Checking if package 'zlib1g-dev' is installed...
 > Checking if package 'uuid-dev' is installed...
 > Checking if package 'libmnl-dev' is installed...
 > Checking if package 'libuv1-dev' is installed...
dpkg-query: no packages found matching libuv1-dev
 > Checking if package 'liblz4-dev' is installed...
dpkg-query: no packages found matching liblz4-dev
 > Checking if package 'libssl-dev' is installed...
dpkg-query: no packages found matching libssl-dev
 > Checking if package 'libjudy-dev' is installed...
dpkg-query: no packages found matching libjudy-dev

The following command will be run:

 >> IMPORTANT <<
    Please make sure your system is up to date
    by running:   apt-get update

apt-get install libjudy-dev
apt-get install liblz4-dev
apt-get install libssl-dev
apt-get install libuv1-dev


Press ENTER to run it >
```

What is the proper procedure for handling new system requirements when netdata needs them?  I'm assuming the auto-update feature doesn't do this automatically (which is good IMO).  The updates were all failing due to the missing libssl-dev:

https://gist.github.com/churnd/496e0556d5fc442f001416b2320a5070

### PR DESCRIPTION
**Pull request by thiagoftsm**
#### Summary
Some users are reporting that they can't compile Netdata successfully when no SSL support present. The unique files that did not have any verification of the SSL were the following two files, so I changed them to fix the problem.

```
libnetdata/socket/security.h
libnetdata/socket/security.c
```

##### Component Name
netdata/daemon
netdata/packaging

##### Additional Information
Fixes #6200

### CODE REVIEW

**Comment by paulkatsoulakis** [comment]
Compilation seems to be failing on a bare docker image of "debian:9"

```
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/netdata/web'
make[2]: Leaving directory '/netdata/web'
make[2]: Entering directory '/netdata'
  CC       collectors/apps.plugin/apps_plugin.o
  CC       libnetdata/adaptive_resortable_list/adaptive_resortable_list.o
  CC       libnetdata/config/appconfig.o
In file included from libnetdata/config/../libnetdata.h:302:0,
                 from libnetdata/config/appconfig.c:3:
libnetdata/config/../socket/socket.h:6:30: fatal error: openssl/ossl_typ.h: No such file or directory
 #include <openssl/ossl_typ.h>
                              ^
In file included from libnetdata/adaptive_resortable_list/../libnetdata.h:302:0,
                 from libnetdata/adaptive_resortable_list/adaptive_resortable_list.c:3:
libnetdata/adaptive_resortable_list/../socket/socket.h:6:30: fatal error: openssl/ossl_typ.h: No such file or directory
 #include <openssl/ossl_typ.h>
                              ^
compilation terminated.
compilation terminated.
In file included from collectors/apps.plugin/../../libnetdata/libnetdata.h:302:0,
                 from collectors/apps.plugin/apps_plugin.c:9:
collectors/apps.plugin/../../libnetdata/socket/socket.h:6:30: fatal error: openssl/ossl_typ.h: No such file or directory
 #include <openssl/ossl_typ.h>
                              ^
compilation terminated.
Makefile:2685: recipe for target 'libnetdata/adaptive_resortable_list/adaptive_resortable_list.o' failed
make[2]: *** [libnetdata/adaptive_resortable_list/adaptive_resortable_list.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:2685: recipe for target 'libnetdata/config/appconfig.o' failed
make[2]: *** [libnetdata/config/appconfig.o] Error 1
Makefile:2685: recipe for target 'collectors/apps.plugin/apps_plugin.o' failed
make[2]: *** [collectors/apps.plugin/apps_plugin.o] Error 1
make[2]: Leaving directory '/netdata'
Makefile:2807: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/netdata'
Makefile:1500: recipe for target 'all' failed
make: *** [all] Error 2
 FAILED   

root@618713da1189:/netdata# 
```

```
root@618713da1189:/netdata# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@618713da1189:/netdata# exit
```

File: libnetdata/socket/socket.h [hunk 1]
```diff
@@ -3,7 +3,9 @@
 #ifndef NETDATA_SOCKET_H
 #define NETDATA_SOCKET_H
 
-#include <openssl/ossl_typ.h>
+#if defined(ENABLE_HTTPS) || defined(ENABLE_DBENGINE)
```
Comment (mfundul) [inline libnetdata/socket/socket.h]: This include file is not actually used by dbengine so `defined(ENABLE_DBENGINE)` is not actually doing anything

Comment (thiagoftsm) [reply libnetdata/socket/socket.h]: I do not ask nothing from this file too, so I will remove it, the necessary files for SSL are inside the libnetdata/security/socket.h .
