### PR TITLE
Decode url before checking for question mark

### LINKED ISSUE #15344: [Bug]: After v1.38.1, netdata stopped interpreting encoded URLs
### Bug description

On Netdata v < 1.39.0, the following URL work fine:

```
curl -s localhost:19999/api/v1/allmetrics%3Fformat=prometheus | tail -1
netdata_cgroup_cpu_limit_percentage_average{chart="cgroup_stoic_shirley.cpu_limit",family="cpu",dimension="used"} 0.0900000 1689047342000
```

On v > 1.38.1, the following URL is broken:

```
curl -s localhost:19999/api/v1/allmetrics%3Fformat=prometheus | tail -1
Unsupported API command: allmetrics?format=prometheus
```

It looks like the interpretation of encoded URLs has stopped working.
This breaks Prometheus as the `"metrics_path": "/api/v1/allmetrics?format=prometheus",` is an URL encoded value.

### Expected behavior

Encoded URLs are parsed fine.

### Steps to reproduce

1. Have Netdata > 1.38.1 
2. `curl localhost:19999/api/v1/allmetrics%3Fformat=prometheus`
3. See the error `Unsupported API command: allmetrics?format=prometheus`

### Installation method

manual setup of official DEB/RPM packages

### System info

```shell
Linux foo 5.4.230-1.el7.elrepo.x86_64 #1 SMP Mon Jan 23 12:23:20 EST 2023 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.9.2009 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.9.2009 (Core)
/etc/system-release:CentOS Linux release 7.9.2009 (Core)
```

### Netdata build info

```shell
Version: netdata v1.39.1
Configure options:  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--datadir=/usr/share' '--includedir=/usr/include' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--with-bundled-protobuf' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--disable-dependency-tracking' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro ' 'CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'PKG_CONFIG_PATH=:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Install type: binpkg-rpm
    Binary architecture: x86_64
    Packaging distro:
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

Fixes #15344 

Decode the url string before checking for a question mark. Each part of the url (before and after question mark) would be decoded after the check.

##### Test Plan

Besides checking the case of #15344, tests should include proper dashboard functionality, charts, data, as well as cloud connectivity for anything weird.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

File: web/server/web_client.c [hunk 1]
```diff
@@ -2282,29 +2281,24 @@ void web_client_decode_path_and_query_string(struct web_client *w, const char *p
...
-            url_decode_r(buffer, path_and_query_string, NETDATA_WEB_REQUEST_URL_SIZE + 1);
+            buffer_strcat(w->url_path_decoded, buffer);
             *question_mark_start = c;
-        } else
-            url_decode_r(buffer, path_and_query_string, NETDATA_WEB_REQUEST_URL_SIZE + 1);
-
-        buffer[NETDATA_WEB_REQUEST_URL_SIZE + 1] = '\0';
-        buffer_strcat(w->url_path_decoded, buffer);
+        } else {
+            buffer_strcat(w->url_query_string_decoded, buffer);
```
Comment (stelfrag) [inline web/server/web_client.c:2299]: This will not produce the same output as before. Will be if ? is missing. Previously buffer was not populated

Comment (MrZammler) [reply web/server/web_client.c]: Indeed it didn't!

**Review by stelfrag — APPROVED** [review]

**Review by ilyam8 — APPROVED** [review]
