### PR TITLE
Fix the netdata-updater.sh to correctly pass REINSTALL_OPTIONS (finally)

### LINKED ISSUE #8782: Fix netdata-updater for static installs
This is a reoccuring bug that was fixed quite some time ago in #7197 then refixed and now it has come back. I must have missed something blindly obvious :/ This issue is to track and fix that once and for all.

### LINKED ISSUE #9763: Netdata nightly builds not updating automatically
Using Nightly builds, 64bit Netdata. Automated updates stopped working again for last few weeks. If I run the updater or one line static installer (with or without --nightly-builds option) it is disabled forcing manual updates.

Other issues I'm having, in case somehow related:

- SystemD charts section enabled in Netdata config but not displayed for some time, several weeks or so.
- Chart height adjusters (Up/down arrow icons) don't work on iPad.
- All Charts just suddenly disappear (open bug on this [here])(https://github.com/netdata/netdata/issues/9745)

##### Bug report summary

```

 --- Install (but not enable) netdata updater tool --- 
Update script is located at /opt/netdata/usr/libexec/netdata/netdata-updater.sh

 --- Check if we must enable/disable the netdata updater tool --- 
You chose *NOT* to enable auto-update, removing any links to the updater from cron (it may have happened if you are reinstalling)

Did not find any cron entries to remove
```

I've NEVER chosen NOT to enable auto-update, so this isn't correct and may be part of the issue.

##### OS / Environment

CENTOS 7.8 virtuozzo [vpsXXXXXX]  WHM/CPANEL v88.0.13

```

uname -a; grep -Hv "^#" /etc/*release
Linux vpsXXXXXX.inmotionhosting.com 3.10.0-1062.12.1.vz7.131.10 #1 SMP Mon Mar 16 15:39:59 MSK 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.8.2003 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.8.2003 (Core)
/etc/system-release:CentOS Linux release 7.8.2003 (Core)

```

```
/opt/netdata/usr/libexec/netdata/netdata-updater.sh --help
Entering /tmp/netdata-updater-CuD6VO

  ^
  |.-.   .-.   .-.   .-.   .  netdata
  |   '-'   '-'   '-'   '-'   real-time performance monitoring, done right!
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

  (C) Copyright 2017, Costa Tsaousis
  All rights reserved
  Released under GPL v3+

  You are about to install netdata to this system.
  netdata will be installed at:

                    /opt/netdata

  The following changes will be made to your system:

  # USERS / GROUPS
  User 'netdata' and group 'netdata' will be added, if not present.

  # LOGROTATE
  This file will be installed if logrotate is present.

   - /etc/logrotate.d/netdata

  # SYSTEM INIT
  This file will be installed if this system runs with systemd:

   - /lib/systemd/system/netdata.service

   or, for older Centos, Debian/Ubuntu or OpenRC Gentoo:

   - /etc/init.d/netdata         will be created


  This package can also update a netdata installation that has been
  created with another version of it.

  Your netdata configuration will be retained.
  After installation, netdata will be (re-)started.

  netdata re-distributes a lot of open source software components.
  Check its full license at:
  https://github.com/netdata/netdata/blob/master/LICENSE.md
Creating directory /opt/netdata
Verifying archive integrity...  100%   All good.
Uncompressing netdata, the real-time performance and health monitoring system  100%  
 --- Attempt to create user/group netdata/netadata --- 
Group 'netdata' already exists.
User 'netdata' already exists.
 --- Add user netdata to required user groups --- 
Group 'docker' does not exist.
 FAILED  Failed to add netdata user to secondary groups 

Group 'nginx' does not exist.
 FAILED  Failed to add netdata user to secondary groups 

Group 'varnish' does not exist.
 FAILED  Failed to add netdata user to secondary groups 

Group 'haproxy' does not exist.
 FAILED  Failed to add netdata user to secondary groups 

User 'netdata' is already in group 'adm'.
User 'netdata' is already in group 'nsd'.
Group 'proxy' does not exist.
 FAILED  Failed to add netdata user to secondary groups 

Group 'squid' does not exist.
 FAILED  Failed to add netdata user to secondary groups 

Group 'ceph' does not exist.
 FAILED  Failed to add netdata user to secondary groups 

User 'netdata' is already in group 'nobody'.
Group 'I2C' does not exist.
 FAILED  Failed to add netdata user to secondary groups 

 --- Check SSL certificates paths --- 
 --- Install logrotate configuration for netdata --- 
[/opt/netdata]# chmod 644 /etc/logrotate.d/netdata 
 OK   

 --- Telemetry configuration --- 
You can opt out from anonymous statistics via the --disable-telemetry option, or by creating an empty file /opt/netdata/etc/netdata/.opt-out-from-anonymous-statistics 

 --- Install netdata at system init --- 
Installing systemd service...
[/opt/netdata]# cp system/netdata.service /lib/systemd/system/netdata.service 
 OK   

[/opt/netdata]# systemctl daemon-reload 
 OK   

[/opt/netdata]# systemctl enable netdata 
 OK   

 --- Install (but not enable) netdata updater tool --- 
Update script is located at /opt/netdata/usr/libexec/netdata/netdata-updater.sh

 --- Check if we must enable/disable the netdata updater tool --- 
You chose *NOT* to enable auto-update, removing any links to the updater from cron (it may have happened if you are reinstalling)

Did not find any cron entries to remove

 --- creating quick links --- 
[/opt/netdata]# rm sbin 
 OK   

[/opt/netdata]# ln -s bin sbin 
 OK   

[/opt/netdata/usr]# rm bin 
 OK   

[/opt/netdata/usr]# ln -s ../bin bin 
 OK   

[/opt/netdata/usr]# rm sbin 
 OK   

[/opt/netdata/usr]# ln -s ../bin sbin 
 OK   

[/opt/netdata/usr]# rm local 
 OK   

[/opt/netdata/usr]# ln -s . local 
 OK   

[/opt/netdata]# rm netdata-configs 
 OK   

[/opt/netdata]# ln -s etc/netdata netdata-configs 
 OK   

[/opt/netdata]# rm netdata-web-files 
 OK   

[/opt/netdata]# ln -s usr/share/netdata/web netdata-web-files 
 OK   

[/opt/netdata]# rm netdata-plugins 
 OK   

[/opt/netdata]# ln -s usr/libexec/netdata netdata-plugins 
 OK   

[/opt/netdata]# rm netdata-dbs 
 OK   

[/opt/netdata]# ln -s var/lib/netdata netdata-dbs 
 OK   

[/opt/netdata]# rm netdata-metrics 
 OK   

[/opt/netdata]# ln -s var/cache/netdata netdata-metrics 
 OK   

[/opt/netdata]# rm netdata-logs 
 OK   

[/opt/netdata]# ln -s var/log/netdata netdata-logs 
 OK   

[/opt/netdata/etc/netdata]# rm orig 
 OK   

[/opt/netdata/etc/netdata]# ln -s ../../usr/lib/netdata/conf.d orig 
 OK   

 --- fix permissions --- 
[/opt/netdata]# chmod g+rx\,o+rx /opt 
 OK   

[/opt/netdata]# chown -R netdata:netdata /opt/netdata 
 OK   

 --- fix plugin permissions --- 
[/opt/netdata]# chown root:netdata usr/libexec/netdata/plugins.d/apps.plugin 
 OK   

[/opt/netdata]# chmod 4750 usr/libexec/netdata/plugins.d/apps.plugin 
 OK   

[/opt/netdata]# chown root:netdata usr/libexec/netdata/plugins.d/ioping 
 OK   

[/opt/netdata]# chmod 4750 usr/libexec/netdata/plugins.d/ioping 
 OK   

[/opt/netdata]# chown root:netdata usr/libexec/netdata/plugins.d/cgroup-network 
 OK   

[/opt/netdata]# chmod 4750 usr/libexec/netdata/plugins.d/cgroup-network 
 OK   

[/opt/netdata]# chown root:netdata bin/fping 
 OK   

[/opt/netdata]# chmod 4750 bin/fping 
 OK   

Configure TLS certificate paths
Using /etc/pki/tls for TLS configuration and certificates
Save install options
 --- starting netdata --- 
 --- Restarting netdata instance --- 

Stopping all netdata threads
[/opt/netdata]# stop_all_netdata 
 OK   

Starting netdata using command 'systemctl start netdata'
[/opt/netdata]# systemctl start netdata 
 OK   


  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata              .-.   .-.   .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   is installed now!  -'   '-'   '-'   '-'  
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

[/opt/netdata]# chmod 0644 /opt/netdata/etc/netdata/netdata.conf 
 OK   

Switching back to /root

```

##### Netdata version

netdata v1.24.0-49-gc6ba56af

 (plus previous releases in last 2-3 weeks approx)

##### Steps To Reproduce

/opt/netdata/usr/libexec/netdata/netdata-updater.sh

##### Expected behavior

Netdata to detect auto updater is broken and attempt to fix itself if a configuration issue or bug preventing this from working to be squished and normal auto updates restored.

P.S. One daily new version check is too slow, why not one check say every 6 hours or once per hour?

### PR DESCRIPTION
**Pull request by prologic**
Fixes #8782
Fixes #9763 

##### Summary

ssia

##### Component Name

- area/packaging

##### Test Plan

__WARNING:__ Testing this is a _bit tricky_ to say the least. It's a bit of a chicken 'n egg type problem until this PR is merved.

1. First of all, you need to patch the `netdata-updater.sh` on your system with teh following patch:

```#!diff
--- a/packaging/installer/netdata-updater.sh
+++ b/packaging/installer/netdata-updater.sh
@@ -123,13 +123,12 @@ set_tarball_urls() {
   if [ "$1" = "stable" ]; then
     local latest
     # Simple version
-    # latest="$(curl -sSL https://api.github.com/repos/netdata/netdata/releases/latest | grep tag_name | cut -d'"' -f4)"
     latest="$(download "https://api.github.com/repos/netdata/netdata/releases/latest" /dev/stdout | grep tag_name | cut -d'"' -f4)"
     export NETDATA_TARBALL_URL="https://github.com/netdata/netdata/releases/download/$latest/netdata-$latest.${extension}"
     export NETDATA_TARBALL_CHECKSUM_URL="https://github.com/netdata/netdata/releases/download/$latest/sha256sums.txt"
   else
-    export NETDATA_TARBALL_URL="https://storage.googleapis.com/netdata-nightlies/netdata-latest.${extension}"
-    export NETDATA_TARBALL_CHECKSUM_URL="https://storage.googleapis.com/netdata-nightlies/sha256sums.txt"
+    export NETDATA_TARBALL_URL="$NETDATA_NIGHTLIES_BASEURL/netdata-latest.${extension}"
+    export NETDATA_TARBALL_CHECKSUM_URL="$NETDATA_NIGHTLIES_BASEURL/sha256sums.txt"
   fi
 }

@@ -185,8 +184,8 @@ update() {
       do_not_start="--dont-start-it"
     fi

-    if [ -n "${NETDATA_SELECTED_DASHBOARD}" ] ; then
-        env="NETDATA_SELECTED_DASHBOARD=${NETDATA_SELECTED_DASHBOARD}"
+    if [ -n "${NETDATA_SELECTED_DASHBOARD}" ]; then
+      env="NETDATA_SELECTED_DASHBOARD=${NETDATA_SELECTED_DASHBOARD}"
     fi

     info "Re-installing netdata..."
@@ -222,6 +221,9 @@ export NETDATA_LIB_DIR="${NETDATA_LIB_DIR:-${NETDATA_PREFIX}/var/lib/netdata}"
 # Source the tarbal checksum, if not already available from environment (for existing installations with the old logic)
 [[ -z "${NETDATA_TARBALL_CHECKSUM}" ]] && [[ -f ${NETDATA_LIB_DIR}/netdata.tarball.checksum ]] && NETDATA_TARBALL_CHECKSUM="$(cat "${NETDATA_LIB_DIR}/netdata.tarball.checksum")"

+# Grab the nightlies baseurl (defaulting to our Google Storage bucket)
+export NETDATA_NIGHTLIES_BASEURL="${NETDATA_NIGHTLIES_BASEURL:-https://storage.googleapis.com/netdata-nightlies}"
+
 if [ "${INSTALL_UID}" != "$(id -u)" ]; then
   fatal "You are running this script as user with uid $(id -u). We recommend to run this script as root (user with uid 0)"
 fi
```

2. Then you need to rebuild the artifacts with the `./build-artifacts.sh` which I plan to commit to this PR and the repo at the top-level (_I have future plans to refactor how we build the dist and makeself archives and how we publish them_).

```#!sh
$ ./build-artifacts.sh
.
.
.
CRC: 3614907360
MD5: fd7b57a2dd851c819dca3694808c7d65

Self-extractable archive "/opt/netdata.gz.run" successfully created.
 OK

[/usr/src/netdata.git]# rm /usr/src/netdata.git/packaging/makeself/./makeself.lsm.tmp
 OK

[/usr/src/netdata.git]# mkdir -p artifacts
 OK

[/usr/src/netdata.git]# mv /opt/netdata.gz.run artifacts/netdata-v1.21.1-75-g150140a1.gz.run
 OK

[/usr/src/netdata.git]# ln -s artifacts/netdata-v1.21.1-75-g150140a1.gz.run netdata-latest.gz.run
ln: netdata-latest.gz.run: File exists
```

3. Then you need to serve up the files in `./artifacts` with a web server that is capable of serving static resources. I use [prologic/static](https://github.com/prologic/static) for this purpose:

```#!sh
$ static -root ./artifacts/
[static] 2020/04/23 12:45:03 (10.0.0.3:54050) "GET /sha256sums.txt HTTP/1.1" 200 558 6.337534ms
[static] 2020/04/23 12:45:04 (10.0.0.3:54052) "GET /netdata-latest.gz.run HTTP/1.1" 200 37390233 633.729474ms
```

4. Fix the broken `REINSTALL_OPTIONS` on a system with teh static NetData Agent installed by inserting ` --auto-update` (_note the space_) into the `.environment` file, normally located at `/opt/netdata/etc/netdata/.enviornment`. I just use vi/vim here.

5. And finally you need to run the `netdata-updater.sh` with a custom `NETDATA_NIGHTLIES_BASEURL` LIKE SO:

```#!SH
root@vz1:~# NETDATA_NIGHTLIES_BASEURL=http://10.0.0.109:8000 /opt/netdata/usr/libexec/netdata/netdata-updater.sh
Entering /tmp/netdata-updater-MWdHDW

  ^
  |.-.   .-.   .-.   .-.   .  netdata
  |   '-'   '-'   '-'   '-'   real-time performance monitoring, done right!
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

  (C) Copyright 2017, Costa Tsaousis
  All rights reserved
  Released under GPL v3+

  You are about to install netdata to this system.
  netdata will be installed at:

                    /opt/netdata

  The following changes will be made to your system:

  # USERS / GROUPS
  User 'netdata' and group 'netdata' will be added, if not present.

  # LOGROTATE
  This file will be installed if logrotate is present.

   - /etc/logrotate.d/netdata

  # SYSTEM INIT
  This file will be installed if this system runs with systemd:

   - /lib/systemd/system/netdata.service

   or, for older Centos, Debian/Ubuntu or OpenRC Gentoo:

   - /etc/init.d/netdata         will be created


  This package can also update a netdata installation that has been
  created with another version of it.

  Your netdata configuration will be retained.
  After installation, netdata will be (re-)started.

  netdata re-distributes a lot of open source software components.
  Check its full license at:
  https://github.com/netdata/netdata/blob/master/LICENSE.md
Creating directory /opt/netdata
Verifying archive integrity...  100%   All good.
Uncompressing netdata, the real-time performance and health monitoring system  100%
 --- Attempt to create user/group netdata/netadata ---
.
.
.
 --- Install (but not enable) netdata updater tool ---
Update script is located at /opt/netdata/usr/libexec/netdata/netdata-updater.sh

 --- Check if we must enable/disable the netdata updater tool ---
Adding to cron
Auto-updating has been enabled. Updater script linked to: /etc/cron.daily/netdata-updater

netdata-updater.sh works from cron. It will trigger an email from cron
only if it fails (it should not print anything when it can update netdata).

 --- creating quick links ---
Stopping all netdata threads
[/opt/netdata]# stop_all_netdata
 OK

Starting netdata using command 'systemctl start netdata'
[/opt/netdata]# systemctl start netdata
 OK


  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata              .-.   .-.   .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   is installed now!  -'   '-'   '-'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

[/opt/netdata]# chmod 0644 /opt/netdata/etc/netdata/netdata.conf
 OK

Switching back to /root
```

_Note_ that the error `Invalid option: " --auto-update"` is now gone.

And just to confirm:

```#!sh
root@vz1:~# ls -lah /etc/cron.daily/
total 52K
drwxr-xr-x   2 root root 4.0K Apr 23 12:45 .
drwxr-xr-x 110 root root  12K Apr 21 14:12 ..
-rwxr-xr-x   1 root root 1.5K May 29  2019 apt-compat
-rwxr-xr-x   1 root root  314 Nov  8  2014 aptitude
-rwxr-xr-x   1 root root  355 Oct 17  2014 bsdmainutils
-rwxr-xr-x   1 root root 1.2K Apr 19  2019 dpkg
-rwxr-xr-x   1 root root  377 Aug 29  2018 logrotate
-rwxr-xr-x   1 root root 1.1K Feb 10  2019 man-db
-rwxr-xr-x   1 root root  543 Nov 15  2018 mlocate
lrwxrwxrwx   1 root root   51 Apr 23 12:45 netdata-updater -> /opt/netdata/usr/libexec/netdata/netdata-updater.sh
-rwxr-xr-x   1 root root  249 Nov 21  2014 passwd
-rw-r--r--   1 root root  102 Jun 11  2015 .placeholder
root@vz1:~#
```

And:

```#!sh
root@vz1:~# grep REINSTALL_OPTIONS /opt/netdata/etc/netdata/.environment
REINSTALL_OPTIONS=" --auto-update"
root@vz1:~#
```

##### Additional Information

This is a long standing bug that was attempted to eb fixed twice. Both times
didn't actually fix the bug becuase tehre was in fact another bug. We never
properly handled `REINSTALL_OPTIONS` in the first place and properly passed
this to the Makeself archive. The arguments need to be word-split.

### CODE REVIEW

File: packaging/installer/netdata-updater.sh [hunk 1]
```diff
@@ -254,7 +256,8 @@ if [ "${IS_NETDATA_STATIC_BINARY}" == "yes" ]; then
   fi
 
   # Do not pass any options other than the accept, for now
-  if sh "${TMPDIR}/netdata-latest.gz.run" --accept -- "${REINSTALL_OPTIONS}"; then
+  read -r -a reinstall_options <<< "$REINSTALL_OPTIONS"
+  if sh "${TMPDIR}/netdata-latest.gz.run" --accept -- "${reinstall_options[@]}"; then
```
Comment (knatsakis) [inline packaging/installer/netdata-updater.sh:260]: I think it's simpler to:

```suggestion
  if sh "${TMPDIR}/netdata-latest.gz.run" --accept -- ${REINSTALL_OPTIONS}; then
```

and add a comment to silence shellcheck.

File: build-artifacts.sh [hunk 2]
```diff
@@ -0,0 +1,27 @@
+#!/bin/sh
```
Comment (knatsakis) [inline build-artifacts.sh:1]: Where is this used? Is it here by mistake?

Comment (knatsakis) [reply build-artifacts.sh:1]: Oh never mind. I just saw for commit message

File: packaging/installer/netdata-updater.sh (hunk 1 above)
Comment (prologic) [reply packaging/installer/netdata-updater.sh:260]: I _could_ have sworn I tested this and it fails in a similar way. Happy to re-test though :) And I'll report back...

Comment (prologic) [reply packaging/installer/netdata-updater.sh]: I'm slightly embarrased but you are right. Not becuase you are right becuase I'm aware of what happened and its all a bit silly :(

File: build-artifacts.sh (hunk 2 above)
Comment (prologic) [reply build-artifacts.sh:1]: Yeah its used to actually locally build the artifacts. I will use this later to refactor the process for publishing things with Github Workflows.

**Comment by prologic** [comment]
As discussed, this ig going into Backlog and will be re-worked to have CI that verifies this works continuously which will also make review reasier and prevent future regressions of the updater.

**Comment by Simonmicro** [comment]
Hey, whats the state of this? It has been months since the last activity - and I guess the updater is **still broken**.

**Comment by prologic** [comment]
> Hey, whats the state of this? It has been months since the last activity - and I guess the updater is **still broken**.

You are right. Other bugs got in the way of completing this. The fix is valid, but it got pushed back until we have some tests in place to verify out updater doesn't break in CI. Sorry about this.

**Comment by Ferroin** [comment]
@prologic sorry about the delay in approving this after getting it updated like you requested. It would be good to get this merged soon, as we now have two open issues about it.
