### PR TITLE
Move cleanup of obsolete charts to a separate thread

### LINKED ISSUE #11186: High load when a lot of charts are created
##### Bug report summary

If a lot of charts are created in a short period of time, which is particularly common for k8s, there is a high load and gaps in charts.

When there are ~20000 charts in Netdata, one call to `rrdhost_cleanup_obsolete_charts` takes ~0,0018 sec on Ryzen 3950. If, for example, 100 network interfaces are created, more than 1000 charts are added to Netdata and it takes ~1,8 sec to run through the cleanup loops.

How it looks like when 200 network interfaces are created:
image

perf report when 50 docker containers are created:
```
Samples: 44K of event 'cpu-cycles', Event count (approx.): 33751695799, DSO: netdata
  Children      Self  Command          Symbol
+   39.11%     0.00%  PLUGIN[proc]     [.] thread_start                                                             
+   39.11%     0.00%  PLUGIN[proc]     [.] proc_main                                                                
-   37.80%     0.02%  PLUGIN[proc]     [.] do_proc_net_dev                                                          
   - 37.79% do_proc_net_dev                                                                                         
      - 34.95% rrdset_create_custom                                                                                 
         + 31.38% rrdhost_cleanup_obsolete_charts                                                                   
         + 1.32% rrdcalctemplate_link_matching                                                                      
         + 0.54% store_active_chart                                                                                 
      + 2.58% rrddim_add_custom                                                                                     
+   34.95%     0.01%  PLUGIN[proc]     [.] rrdset_create_custom                                                     
+   31.38%    26.53%  PLUGIN[proc]     [.] rrdhost_cleanup_obsolete_charts                                          
+   20.45%     0.00%  PLUGIN[cgroups]  [.] thread_start                                                             
-   20.45%     0.00%  PLUGIN[cgroups]  [.] cgroups_main                                                             
   - 20.44% cgroups_main                                                                                            
      - 20.02% update_cgroup_charts                                                                                 
         - 17.69% rrdset_create_custom                                                                              
              15.94% rrdhost_cleanup_obsolete_charts                                                                
         + 1.94% rrddim_add_custom                                                                                  
+   20.02%     0.01%  PLUGIN[cgroups]  [.] update_cgroup_charts                                                     
+   17.69%     0.00%  PLUGIN[cgroups]  [.] rrdset_create_custom                                                     
+   17.23%     0.00%  PLUGINSD[go.d]   [.] thread_start                                                             
+   17.23%     0.00%  PLUGINSD[go.d]   [.] pluginsd_worker_thread                                                   
+   17.20%     0.03%  PLUGINSD[go.d]   [.] pluginsd_process                                                         
+   16.88%     0.76%  PLUGINSD[go.d]   [.] parser_action                                                            
+   15.94%    15.68%  PLUGIN[cgroups]  [.] rrdhost_cleanup_obsolete_charts                                          
+    5.95%     0.05%  PLUGINSD[go.d]   [.] avl_search_lock                                                          
+    4.95%     0.25%  PLUGINSD[go.d]   [.] avl_search                                                               
+    4.49%     3.47%  PLUGIN[proc]     [.] rrdset_free   
```

##### OS / Environment

```
Linux arch-esxi 5.12.6-arch1-1 #1 SMP PREEMPT Sun, 23 May 2021 00:45:50 +0000 x86_64 GNU/Linux
/etc/lsb-release:LSB_VERSION=1.4
/etc/lsb-release:DISTRIB_ID=Arch
/etc/lsb-release:DISTRIB_RELEASE=rolling
/etc/lsb-release:DISTRIB_DESCRIPTION="Arch Linux"
/etc/os-release:NAME="Arch Linux"
/etc/os-release:PRETTY_NAME="Arch Linux"
/etc/os-release:ID=arch
/etc/os-release:BUILD_ID=rolling
/etc/os-release:ANSI_COLOR="38;2;23;147;209"
/etc/os-release:HOME_URL="https://www.archlinux.org/"
/etc/os-release:DOCUMENTATION_URL="https://wiki.archlinux.org/"
/etc/os-release:SUPPORT_URL="https://bbs.archlinux.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.archlinux.org/"
/etc/os-release:LOGO=archlinux
```

##### Netdata version

```
Version: netdata v1.31.0-18-ga1eecbe15
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-plugin-nfacct' '--enable-plugin-freeipmi' '--enable-backend-kinesis' '--enable-backend-prometheus-remote-write' '--disable-cloud' '--disable-lto' 'CFLAGS=-Og -ggdb -Wall -Wextra -Wformat-signedness -fno-omit-frame-pointer -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           NO (by user request)
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES shared-lib
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             YES
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

##### Installation method

From source

##### Component Name

Collectors

##### Steps To Reproduce

1. Set memory mode to ram. This allows repeating the test w/o removing _dbengine_ data, just restart netdata service.

2. Enable the `example` go.d module in `go.d.conf` and add 20000 charts in `go.d/example.conf`
```
jobs:
  - name: example
    charts:
      num: 20000
      dimensions: 2
```
3. Run
```
for i in $(seq 1 200); do sudo ip link add dev dumm$i type dummy; sudo ip link set dev dumm$i up; echo "created iface dumm$i"; done
```
4. Check the `netdata.plugin_proc_cpu` and `netdata.plugin_proc_modules` charts.

---

Dummy interfaces cleanup

```bash
for iface in $(ip link show | grep -E -o dumm[0-9]+ | sort -V); do ip link del dev $iface; echo "deleted iface $iface"; done
```

##### Expected behavior

There are no gaps in charts when new charts are created.

### PR DESCRIPTION
**Pull request by vlvkobal**
##### Summary

If there are a lot of charts in the database, a call to `rrdhost_cleanup_obsolete_charts` is quite a CPU-intensive task. It doesn't make sense to call it on every chart creation. We are moving it to a separate thread and make sure it won't run too frequently. 

Fixes #11186.

##### Component Name

Netdata core

##### Test Plan

1. Valgrind

2.
```
for i in $(seq 1 1000); do sudo ip link add dev dumm$i type dummy; sudo ip link set dev dumm$i up; echo "created iface dumm$i"; done

for i in $(seq 1 1000); do sudo ip link del dev dumm$i up; echo "deleted iface dumm$i"; done
```

3.
```
for i in $(seq 1 50); do docker run -d --rm --name nginx$i nginx; done

docker stop $(docker ps -a -q --filter='ancestor=nginx')
```

### CODE REVIEW

File: daemon/service.h [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+
+/* Run service jobs every X seconds */
+#define SERVICE_HEARTBEAT 10
+
+#define NETDATA_PLUGIN_HOOK_SERVICE \
+    { \
+        .name = "SERVICE", \
+        .config_section = NULL, \
+        .config_name = NULL, \
+        .enabled = 0, \
```
Comment (stelfrag) [inline daemon/service.h:16]: Shouldn't this be `.enabled = 1` to get it started?

File: database/rrdset.c [hunk 2]
```diff
@@ -860,6 +864,7 @@ RRDSET *rrdset_create_custom(
     rrdset_flag_clear(st, RRDSET_FLAG_DETAIL);
     rrdset_flag_clear(st, RRDSET_FLAG_DEBUG);
     rrdset_flag_clear(st, RRDSET_FLAG_OBSOLETE);
+    st->rrdhost->obsolete_charts_count--;
```
Comment (stelfrag) [inline database/rrdset.c:867]: This is on creation so the count will drop below zero (quickly prints 4294966968 on my test)

Comment (vlvkobal) [reply database/rrdset.c:867]: Yeah, you are right. I've already saw that.

File: daemon/service.h (hunk 1 above)
Comment (vlvkobal) [reply daemon/service.h:16]: Thanks, will fix that.

File: daemon/service.h [hunk 3]
```diff
@@ -0,0 +1,24 @@
+// SPDX-License-Identifier: GPL-3.0-or-later
+
+#ifndef NETDATA_SERVICE_H
+#define NETDATA_SERVICE_H 1
+
+#include "daemon/common.h"
```
Comment (vkalintiris) [inline daemon/service.h:6]: Not needed.

File: daemon/service.c [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+    netdata_thread_cleanup_push(service_main_cleanup, ptr);
+    unsigned int sec = 0;
+    heartbeat_t hb;
+    heartbeat_init(&hb);
+    usec_t step = USEC_PER_SEC;
+
+    debug(D_SYSTEM, "Service thread starts");
+
+    if (unlikely(netdata_exit))
+        goto cleanup;
```
Comment (vkalintiris) [inline daemon/service.c:29]: Not needed

File: daemon/service.c [hunk 5]
```diff
@@ -0,0 +1,68 @@
...
+
+    sec = 0;
+    while (1) {
+        heartbeat_next(&hb, step);
+        sec++;
+
+        if (unlikely(netdata_exit))
+            break;
```
Comment (vkalintiris) [inline daemon/service.c:37]: This should be the `while`'s condition expression.

File: daemon/service.c [hunk 6]
```diff
@@ -0,0 +1,68 @@
...
+    static_thread->enabled = NETDATA_MAIN_THREAD_EXITED;
+}
+
+/*
+ * The service thread.
+ */
+void *service_main(void *ptr)
+{
+    netdata_thread_cleanup_push(service_main_cleanup, ptr);
+    unsigned int sec = 0;
```
Comment (vkalintiris) [inline daemon/service.c:21]: We don't need this extra logic because `sleep` is cancelable. We can just sleep for `SERVICE_HEARTBEAT` seconds.

File: daemon/service.c [hunk 7]
```diff
@@ -0,0 +1,68 @@
...
+                rrdhost_cleanup_obsolete_charts(host);
+#ifdef ENABLE_ACLK
+                if (host->deleted_charts_count)
+                    aclk_update_chart(host, "dummy-chart", ACLK_CMD_CHARTDEL);
+#endif
+                rrdhost_unlock(host);
+            }
+        }
+
+        rrd_unlock();
```
Comment (vkalintiris) [inline daemon/service.c:60]: I'm entering opinionated territory here, but I can't resist the temptation :)

1. Move this into a new function called `rrd_cleanup_obsolete_charts`.
2. Remove `rrdhost_cleanup_obsolete_charts` from  `database/rrd.h` since it won't be called externally.

The reason for mentioning this is that I like the idea of having a service thread and I can see it growing over time. It would be nice to keep this code without extra business logic, so that in the future we can have:

```
// loop start
...
cleanup_this_thing();
cleanup_and_that_thing();
....
// loop end
```

File: daemon/service.h [hunk 8]
```diff
@@ -0,0 +1,24 @@
...
+
+/* Run service jobs every X seconds */
+#define SERVICE_HEARTBEAT 10
```
Comment (vkalintiris) [inline daemon/service.h:9]: Should this be a user-configurable option?

File: CMakeLists.txt [hunk 9]
```diff
@@ -840,6 +840,8 @@ set(DAEMON_FILES
         daemon/main.h
         daemon/signals.c
         daemon/signals.h
+        daemon/service.c
```
Comment (vkalintiris) [inline CMakeLists.txt:843]: Daemon is already overloaded with a lot of stuff. What do you think about creating a new top-level dir for this?

File: database/rrdset.c [hunk 10]
```diff
@@ -932,15 +936,6 @@ RRDSET *rrdset_create_custom(
 
     store_active_chart(st->chart_uuid);
 
-#ifdef ENABLE_ACLK
-    host->obsolete_count = 0;
-#endif
-    rrdhost_cleanup_obsolete_charts(host);
-#ifdef ENABLE_ACLK
-    if (host->obsolete_count)
-        aclk_update_chart(st->rrdhost, "dummy-chart", ACLK_CMD_CHARTDEL);
```
Comment (vkalintiris) [inline database/rrdset.c:941]: @underhood: Under which situation can we have a dummy chart after the cleanup process?

**Review by vkalintiris — DISMISSED** [review]

**Comment by vkalintiris** [comment]
@vlvkobal It was my intention to leave only comments in my review, but I accidentally selected _approve_, and I don't know how to revert my change :)

File: daemon/service.c (hunk 7 above)
Comment (MrZammler) [reply daemon/service.c:60]: A watchdog, yes. Then perhaps the cleanup_* functions should be "spread" over the life of the thread (as to e.g. not cause spikes with running all cleanup_* every X seconds)....

File: daemon/service.h (hunk 8 above)
Comment (MrZammler) [reply daemon/service.h:9]: In my opinion no... but it could be variable during runtime....

Comment (vkalintiris) [reply daemon/service.h:9]: @vlvkobal if you don't have a different opinion on this, you can move the macro definition in `daemon/service.c` as it's not used anywhere else.

File: daemon/service.c (hunk 7 above)
Comment (MrZammler) [reply daemon/service.c:60]: Just to clarify a bit, my comment is on the general discussion of a service thread :-) . I think this PR is a good start we can build upon over later iterations.

File: daemon/service.h (hunk 8 above)
Comment (MrZammler) [reply daemon/service.h:9]: Same for this :-) We can "pick" a time to run cleanups, maybe when there's not much else going on (cpu side), but in later iterations.

File: database/rrdset.c (hunk 10 above)
Comment (stelfrag) [reply database/rrdset.c:941]: > @underhood: Under which situation can we have a dummy chart after the cleanup process?

The ACLK_CMD_CHARTDEL will not send a delete for a specific chart so in that sense it is dummy (not used at all).

File: daemon/service.h (hunk 3 above)
Comment (vlvkobal) [reply daemon/service.h]: Removed.

File: daemon/service.c (hunk 4 above)
Comment (vlvkobal) [reply daemon/service.c]: Removed.

File: daemon/service.c (hunk 5 above)
Comment (vlvkobal) [reply daemon/service.c]: Fixed.

File: daemon/service.h (hunk 8 above)
Comment (vlvkobal) [reply daemon/service.h]: I don't think it should be configurable. I moved the macro from the header to the source.

File: CMakeLists.txt (hunk 9 above)
Comment (vlvkobal) [reply CMakeLists.txt:843]: Maybe later. I don't think we need to separate this code in advance.

File: daemon/service.c (hunk 6 above)
Comment (vlvkobal) [reply daemon/service.c]: Fixed.

File: daemon/service.c (hunk 7 above)
Comment (vlvkobal) [reply daemon/service.c]: Done.

**Comment by vlvkobal** [comment]
I made a lot of stress tests with this PR and the master branch. The conclusion is that despite the problems we have with the chart locking and invalidation scheme, the PR is a bit more stable than the master branch.

---

Test conditions:
```
[global]
    cleanup obsolete charts after seconds = N
```
where N = 0, 1, 3, 5, 10.

Netdata chart creation/obsoletion/deletion is stressed using the following script:
```
for k in $(seq 1 1000); do echo -n "Pass #$k"; echo -ne "\nCreating: "; for i in $(seq 1 100); do sudo ip link add dev dumm$i type dummy; sudo ip link set dev dumm$i up; echo -n "."; done; echo -ne "\nDeleting: "; for i in $(seq 1 100); do sudo ip link del dev dumm$i up; echo -n "."; done; echo ""; done
```

---

This PR:
There are segmentation faults when N = 0, 1, 3, usually after 30-50 interface creation/deletion cycles.
<details>
<summary>Errors encountered</summary>

```
==1163509== Thread 5 PLUGIN[proc]:
==1163509== Invalid read of size 4
==1163509==    at 0x197EB4: rrdset_is_obsolete (rrdset.c:190)
==1163509==    by 0x27F4C7: netdev_charts_release (proc_net_dev.c:175)
==1163509==    by 0x27FDBD: netdev_free (proc_net_dev.c:248)
==1163509==    by 0x27FF10: netdev_cleanup (proc_net_dev.c:480)
==1163509==    by 0x283040: do_proc_net_dev (proc_net_dev.c:1342)
==1163509==    by 0x270AC9: proc_main (plugin_proc.c:142)
==1163509==    by 0x151353: thread_start (threads.c:184)
==1163509==    by 0x525F258: start_thread (in /usr/lib/libpthread-2.33.so)
==1163509==    by 0x56F75E2: clone (in /usr/lib/libc-2.33.so)
==1163509==  Address 0x11bad158 is not stack'd, malloc'd or (recently) free'd

==1467275== Thread 5 PLUGIN[proc]:
==1467275== Invalid read of size 1
==1467275==    at 0x19A71C: rrdset_next_usec (rrdset.c:971)
==1467275==    by 0x281A25: do_proc_net_dev (proc_net_dev.c:966)
==1467275==    by 0x270AC9: proc_main (plugin_proc.c:142)
==1467275==    by 0x151353: thread_start (threads.c:184)
==1467275==    by 0x525F258: start_thread (in /usr/lib/libpthread-2.33.so)
==1467275==    by 0x56F75E2: clone (in /usr/lib/libc-2.33.so)
==1467275==  Address 0x1588a159 is not stack'd, malloc'd or (recently) free'd

==1526769== Thread 5 PLUGIN[proc]:
==1526769== Invalid read of size 4
==1526769==    at 0x19AEBA: rrdset_isnot_obsolete (rrdset.c:210)
==1526769==    by 0x19AEBA: rrdset_done (rrdset.c:1388)
==1526769==    by 0x281A9B: do_proc_net_dev (proc_net_dev.c:1000)
==1526769==    by 0x270AC9: proc_main (plugin_proc.c:142)
==1526769==    by 0x151353: thread_start (threads.c:184)
==1526769==    by 0x525F258: start_thread (in /usr/lib/libpthread-2.33.so)
==1526769==    by 0x56F75E2: clone (in /usr/lib/libc-2.33.so)
==1526769==  Address 0x2b8 is not stack'd, malloc'd or (recently) free'd

==1759825== Thread 5 PLUGIN[proc]:
==1759825== Invalid read of size 1
==1759825==    at 0x4845633: strcmp (vg_replace_strmem.c:863)
==1759825==    by 0x197759: rrdset_compare_name (rrdset.c:54)
==1759825==    by 0x136BCB: avl_search (avl.c:26)
==1759825==    by 0x13741D: avl_search_lock (avl.c:388)
==1759825==    by 0x197C06: rrdset_index_find_name (rrdset.c:84)
==1759825==    by 0x197C06: rrdset_set_name (rrdset.c:153)
==1759825==    by 0x198BC7: rrdset_create_custom (rrdset.c:566)
==1759825==    by 0x282274: do_proc_net_dev (proc_net_dev.c:945)
==1759825==    by 0x270AC9: proc_main (plugin_proc.c:142)
==1759825==    by 0x151353: thread_start (threads.c:184)
==1759825==    by 0x525F258: start_thread (in /usr/lib/libpthread-2.33.so)
==1759825==    by 0x56F75E2: clone (in /usr/lib/libc-2.33.so)
==1759825==  Address 0x0 is not stack'd, malloc'd or (recently) free'd

==2318594== Thread 12 SERVICE:
==2318594== Invalid read of size 1
==2318594==    at 0x57549F0: __strcmp_avx2 (in /usr/lib/libc-2.33.so)
==2318594==    by 0x197759: rrdset_compare_name (rrdset.c:54)
==2318594==    by 0x136EF7: avl_remove (avl.c:152)
==2318594==    by 0x137478: avl_remove_lock (avl.c:395)
==2318594==    by 0x1977EA: rrdset_index_del_name (rrdset.c:68)
==2318594==    by 0x19837B: rrdset_free (rrdset.c:337)
==2318594==    by 0x195736: rrdhost_cleanup_obsolete_charts (rrdhost.c:1457)
==2318594==    by 0x195809: rrd_cleanup_obsolete_charts (rrdhost.c:1475)
==2318594==    by 0x12BA77: service_main (service.c:33)
==2318594==    by 0x151353: thread_start (threads.c:184)
==2318594==    by 0x525F258: start_thread (in /usr/lib/libpthread-2.33.so)
==2318594==    by 0x56F75E2: clone (in /usr/lib/libc-2.33.so)
==2318594==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
```
</details>

There are no segmentation faults if N = 5, 10. There was one successful continuous test performed with 6000 cycles (approximately 7-8 hours) and N = 10.

---

The master branch:

The timex plugin (the proc plugin is in a different thread) was modified so that new charts were created on every iteration, therefore `rrdost_cleanup_obsolete_charts` was called.
<details>
<summary>The patch</summary>

```
diff --git a/collectors/timex.plugin/plugin_timex.c b/collectors/timex.plugin/plugin_timex.c
index b3e722a4c..915045a44 100644
--- a/collectors/timex.plugin/plugin_timex.c
+++ b/collectors/timex.plugin/plugin_timex.c
@@ -53,13 +53,15 @@ void *timex_main(void *ptr)
         // ----------------------------------------------------------------

         if (do_sync) {
-            static RRDSET *st_sync_state = NULL;
-            static RRDDIM *rd_sync_state;
+            static size_t iteration = 0;
+            char iter_name[1024];
+            snprintf(iter_name, 1023, "clock_sync_state_%lu", iteration);
+            RRDSET *st_sync_state = NULL;

             if (unlikely(!st_sync_state)) {
                 st_sync_state = rrdset_create_localhost(
                     "system",
-                    "clock_sync_state",
+                    iter_name,
                     NULL,
                     "clock synchronization",
                     NULL,
@@ -71,13 +73,16 @@ void *timex_main(void *ptr)
                     update_every,
                     RRDSET_TYPE_LINE);

-                rd_sync_state = rrddim_add(st_sync_state, "state", NULL, 1, 1, RRD_ALGORITHM_ABSOLUTE);
+                rrddim_add(st_sync_state, "state", NULL, 1, 1, RRD_ALGORITHM_ABSOLUTE);
             } else {
                 rrdset_next(st_sync_state);
             }

-            rrddim_set_by_pointer(st_sync_state, rd_sync_state, sync_state != TIME_ERROR ? 1 : 0);
+            rrddim_set(st_sync_state, "state", sync_state != TIME_ERROR ? 1 : 0);
             rrdset_done(st_sync_state);
+
+            rrdset_is_obsolete(st_sync_state);
+            iteration++;
         }

         if (do_sync) {

```
</details>


There are segmentation faults when N = 0, 1, 3, 5, usually after 10-40 interface creation/deletion cycles. I think that the `rrdset_done (rrdset.c:1514)` is the most frequent place for the seqmentation fault to occur because of the different timing (much more operations before calling `rrdost_cleanup_obsolete_charts`) comparing to the case with a separate service thread.
<details>
<summary>Errors encountered</summary>

```
==3536948== Thread 5 PLUGIN[proc]:
==3536948== Invalid read of size 1
==3536948==    at 0x19B698: rrdset_done (rrdset.c:1514)
==3536948==    by 0x281A0B: do_proc_net_dev (proc_net_dev.c:1171)
==3536948==    by 0x26FBDB: proc_main (plugin_proc.c:142)
==3536948==    by 0x15144A: thread_start (threads.c:184)
==3536948==    by 0x525F258: start_thread (in /usr/lib/libpthread-2.33.so)
==3536948==    by 0x56F75E2: clone (in /usr/lib/libc-2.33.so)
==3536948==  Address 0xd0 is not stack'd, malloc'd or (recently) free'd

==315171== Thread 6 PLUGIN[timex]:
==315171== Invalid read of size 1
==315171==    at 0x57549F0: __strcmp_avx2 (in /usr/lib/libc-2.33.so)
==315171==    by 0x19807E: rrdset_compare_name (rrdset.c:54)
==315171==    by 0x136FEE: avl_remove (avl.c:152)
==315171==    by 0x13756F: avl_remove_lock (avl.c:395)
==315171==    by 0x19810F: rrdset_index_del_name (rrdset.c:68)
==315171==    by 0x198C74: rrdset_free (rrdset.c:333)
==315171==    by 0x196151: rrdhost_cleanup_obsolete_charts (rrdhost.c:1457)
==315171==    by 0x19AE78: rrdset_create_custom (rrdset.c:938)
==315171==    by 0x26DD19: timex_main (plugin_timex.c:62)
==315171==    by 0x15144A: thread_start (threads.c:184)
==315171==    by 0x525F258: start_thread (in /usr/lib/libpthread-2.33.so)
==315171==    by 0x56F75E2: clone (in /usr/lib/libc-2.33.so)
==315171==  Address 0x0 is not stack'd, malloc'd or (recently) free'd

==3713695== Thread 5 PLUGIN[proc]:
==3713695== Invalid read of size 4
==3713695==    at 0x1987D9: rrdset_is_obsolete (rrdset.c:190)
==3713695==    by 0x27E551: netdev_charts_release (proc_net_dev.c:167)
==3713695==    by 0x27EECF: netdev_free (proc_net_dev.c:248)
==3713695==    by 0x27F022: netdev_cleanup (proc_net_dev.c:480)
==3713695==    by 0x282152: do_proc_net_dev (proc_net_dev.c:1342)
==3713695==    by 0x26FBDB: proc_main (plugin_proc.c:142)
==3713695==    by 0x15144A: thread_start (threads.c:184)
==3713695==    by 0x525F258: start_thread (in /usr/lib/libpthread-2.33.so)
==3713695==    by 0x56F75E2: clone (in /usr/lib/libc-2.33.so)
==3713695==  Address 0x12504158 is not stack'd, malloc'd or (recently) free'd
```
</details>

There are no segmentation faults if N = 10.

**Comment by vlvkobal** [comment]
Another stress test:
```
[global]
    cleanup obsolete charts after seconds = 10

[plugin:cgroups]
        check for new cgroups every = 1
```
```
for k in $(seq 1 100); do echo -n "Pass #$k"; echo -ne "\nCreating: \n"; for i in $(seq 1 30); do docker run -d --rm --name nginx$i nginx; done; sleep 2; echo -ne "Deleting: \n"; docker stop $(docker ps -a -q --filter='ancestor=nginx'); done
```

The master branch (without any changes to the code) crashes much faster than this PR.

I've also tested the code in a streaming configuration, where a lot of charts were created/deleted on a child. Neither the master branch nor the PR has crashed so far.

**Review by thiagoftsm — APPROVED** [review]
LGTM!

**Comment by vkalintiris** [comment]
@vlvkobal why do we need:

1. https://github.com/netdata/netdata/pull/11222/commits/fa4654868fa603b14028e2f42f7eeb121d9d399b, and
2. https://github.com/netdata/netdata/pull/11222/commits/3ce3e439b99d255b378b83e9f96804d8c129765f?

**Comment by vlvkobal** [comment]
There are no advantages of keeping the linked list for configuration sections. The list was used for historical reasons - there wasn't any traversing function for the AVL tree in Netdata when the code was written. I didn't see any sense in making the new code more complicated for no reason.

**Comment by stelfrag** [comment]
> There are no advantages of keeping the linked list for configuration sections. The list was used for historical reasons - there wasn't any traversing function for the AVL tree in Netdata when the code was written. I didn't see any sense in making the new code more complicated for no reason.

This changes the output of netdata.conf. The `global` section is no longer on top, so it says `# global netdata configuration` but what comes next is `[registry]` 


```
# You can uncomment and change any of the options below.
# The value shown in the commented settings, is the default value.
#

# global netdata configuration

[registry]
```

**Comment by vlvkobal** [comment]
> The global section is no longer on top

I've returned the linked list back and fixed section removal.

**Review by thiagoftsm — APPROVED** [review]
After a new round of tests, I observed that this branch continues stable.

**Review by vkalintiris — APPROVED** [review]
