### PR TITLE
Don't install eBPF plugin components when they shouldn't be installed

### LINKED ISSUE #9750: 1.24.0 can not be crosscompiled due to libbpf (externaldep)
##### Bug report summary
```
checking if perf.plugin should be enabled... yes
checking for libelf... yes
checking for struct bpf_prog_info... yes
checking for externaldeps/libbpf/libbpf.a... configure: error: cannot check for file existence when cross compiling
```

##### OS / Environment
My OS:
```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.1 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.1 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Steps To Reproduce

1. Download SDK for OpenWrt
2. Use this Makefile https://github.com/openwrt/packages/commit/2de28dd95b8c92e2e76038314cab2e180a4cd554
and change version and hash

##### Expected behavior
It should be compiled even when cross compiling, because package libbpf is not available in OpenWrt
https://github.com/openwrt/packages/pull/12949 

Also, why ebpf plugin can not be disabled as others like nfacct/freeipmi and so on?

### PR DESCRIPTION
**Pull request by vlvkobal**
##### Summary
Don't install eBPF components
- when eBPF plugin is explicitly disabled using the `--disable-ebpf` flag.
- on FreeBSD.
- on macOS.

Possibly fixes #9750

##### Component Name
eBPF plugin

##### Test Plan
Check Netdata installation
- With the `--disable-ebpf` flag.
- On FreeBSD.
- On macOS.

### CODE REVIEW

File: netdata-installer.sh [hunk 1]
```diff
@@ -1435,6 +1435,12 @@ should_install_ebpf() {
     return 1
   fi
 
+  if [ "$(uname -s)" != Linux ]; then
```
Comment (ilyam8) [inline netdata-installer.sh:1438]: not a bid deal but `"Linux"` looks better to me

Comment (vlvkobal) [reply netdata-installer.sh]: Fixed.

**Review by amoss — APPROVED** [review]
