### PR TITLE
Remove health from archived metrics

### LINKED ISSUE #9457: Netdata doesn't responds. I think it "loads" some cached files for a very long time
netdata fails to response. 
when I check the error.log I see these: 

```cmd
2020-07-01 08:55:37: netdata INFO  : MAIN : Metadata log "/var/cache/netdata/dbengine/metadatalog-00000-00053.mlf" loaded (size:525447).
2020-07-01 08:55:37: netdata INFO  : MAIN : Loading metadata log "/var/cache/netdata/dbengine/metadatalog-00000-00054.mlf".
2020-07-01 08:57:38: netdata INFO  : MAIN : Metadata log "/var/cache/netdata/dbengine/metadatalog-00000-00054.mlf" loaded (size:525527).
2020-07-01 08:57:38: netdata INFO  : MAIN : Loading metadata log "/var/cache/netdata/dbengine/metadatalog-00000-00055.mlf".
2020-07-01 09:00:01: netdata INFO  : MAIN : Metadata log "/var/cache/netdata/dbengine/metadatalog-00000-00055.mlf" loaded (size:524833).
2020-07-01 09:00:01: netdata INFO  : MAIN : Loading metadata log "/var/cache/netdata/dbengine/metadatalog-00000-00056.mlf".
2020-07-01 09:01:32: netdata INFO  : MAIN : Metadata log "/var/cache/netdata/dbengine/metadatalog-00000-00056.mlf" loaded (size:548068).
2020-07-01 09:01:32: netdata INFO  : MAIN : Loading metadata log "/var/cache/netdata/dbengine/metadatalog-00000-00057.mlf".
2020-07-01 09:02:56: netdata INFO  : MAIN : Metadata log "/var/cache/netdata/dbengine/metadatalog-00000-00057.mlf" loaded (size:817266).
2020-07-01 09:02:56: netdata INFO  : MAIN : Loading metadata log "/var/cache/netdata/dbengine/metadatalog-00000-00058.mlf".
2020-07-01 09:04:00: netdata INFO  : MAIN : Metadata log "/var/cache/netdata/dbengine/metadatalog-00000-00058.mlf" loaded (size:525035).
2020-07-01 09:04:00: netdata INFO  : MAIN : Loading metadata log "/var/cache/netdata/dbengine/metadatalog-00000-00059.mlf".
2020-07-01 09:06:16: netdata INFO  : MAIN : Metadata log "/var/cache/netdata/dbengine/metadatalog-00000-00059.mlf" loaded (size:524322).
2020-07-01 09:06:16: netdata INFO  : MAIN : Loading metadata log "/var/cache/netdata/dbengine/metadatalog-00000-00060.mlf".
```

the folder has 68 mlf files.

I think it tries to load these files forever. 

##### OS / Environment
Linux s5 4.19-ovh-xxxx-std-ipv6-64 #871709 SMP Thu Aug 29 08:31:48 UTC 2019 x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"

##### Netdata version
netdata v1.23.0-24-nightly

 

I expect that when reloading netdata - it will respond immediately then load historical data in the bg.

### PR DESCRIPTION
**Pull request by mfundul**
##### Summary
Fixes #9457
##### Component Name
database
health
##### Test Plan
Have users that originally reported the issue verify it is fixed.

##### Additional Information
Disassociate health variables and alarms from archived charts and dimensions.

### CODE REVIEW

File: database/rrdset.c [hunk 1]
```diff
@@ -533,6 +533,7 @@ RRDSET *rrdset_create_custom(
 
     char fullid[RRD_ID_LENGTH_MAX + 1];
     snprintfz(fullid, RRD_ID_LENGTH_MAX, "%s.%s", type, id);
+    int changed_from_archived_to_active = 0;
```
Comment (thiagoftsm) [inline database/rrdset.c:536]: Considering that this variable is not used outside the the block `539 - 667`, we could move the declaration inside the conditional. There is also a code quality analysis that we use that in normal situation does this check.

**Comment by ilyam8** [comment]
I didnt check the code, but i tested this PR and it fixes [the bug](https://github.com/netdata/netdata/issues/9457). This PR should be reviewed/merged ASAP in my opinion.

My tests:
- [one](https://github.com/netdata/netdata/issues/9457#issuecomment-657046352)
- [two](https://github.com/netdata/netdata/issues/9457#issuecomment-657049459)

**Comment by ilyam8** [comment]
I did same as described in https://github.com/netdata/netdata/issues/9534#issuecomment-658039510

The issue is fixed.
