### PR TITLE
Fix internal registry 

### LINKED ISSUE #9427: "registry to announce" not honoured in alarm-notify.sh
With the latest release (1.23.0), the url in the notification always points to https://app.netdata.cloud (and, btw it goes to a 404 page) even with "registry to announce" set.
I see in alarm-notify.sh that it overrides the local registry url if the file /var/lib/netdata/registry/netdata.public.unique.id exists.
I tried to remove that file but it is regenerated as soon as netdata restart.
In the previous version the notifications used the correct, internal, url.

### PR DESCRIPTION
**Pull request by thiagoftsm**
##### Summary
Fixes #9427 

The spawn server was initialized before the registry to be initialized, but environment variables set for the function `registry_init()` must be set before the spawn server to be called. This PR moves the registry initialization position to fix this bug. 

##### Component Name
Spawn Server
##### Test Plan
1 - Set registry server inside `netdata.conf`:

```
[registry]
        enabled = yes
        registry db directory = /var/lib/netdata/registry
        registry to announce = https://localhost:19999
        registry hostname = hades
```

2 - Create an alarm inside `/etc/netdata/health.d`, for example:

```
 alarm: dev_dim_template
    on: system.cpu
    os: linux
lookup: sum -3s at 0 every 3 percentage foreach *
 units: %
 every: 1s
  warn: $this > 1
  crit: $this > 4
```

3 - Configure `health_alarm_notify.conf` to send the alarm for a channel.
4 - Start Netdata
5 - Verify if the link sent with alarm has the `registry to announce` in the URL `https://localhost:19999/goto-host-from-alarm.html?host=hades&chart=system.cpu&family=cpu&alarm=dev_dim_template_user&alarm_unique_id=1593269432&alarm_id=1593269248&alarm_event_id=7&alarm_when=1593269205`

### CODE REVIEW

File: daemon/main.c [hunk 1]
```diff
@@ -1386,6 +1386,7 @@ int main(int argc, char **argv) {
     netdata_threads_init_after_fork((size_t)config_get_number(CONFIG_SECTION_GLOBAL, "pthread stack size", (long)default_stacksize));
 
     // fork the spawn server
+    registry_init();
```
Comment (mfundul) [inline daemon/main.c:1389]: Can you move this 1 line above so that the comment matches the spawn server?

Comment (thiagoftsm) [reply daemon/main.c:1389]: Of course, I moved it and I added a proper comment.

File: daemon/main.c [hunk 2]
```diff
@@ -1385,6 +1385,8 @@ int main(int argc, char **argv) {
 
     netdata_threads_init_after_fork((size_t)config_get_number(CONFIG_SECTION_GLOBAL, "pthread stack size", (long)default_stacksize));
 
+    // initialyze internal registry
```
Comment (mfundul) [inline daemon/main.c:1388]: typo: `initialyze` -> `initialize`
