### PR TITLE
Fix some errors reported by Coverity

### LINKED ISSUE #6791: Coverity Scan Defects 5/9/19
Please find the latest report on new defect(s) introduced to netdata/netdata found with Coverity Scan.

23 new defect(s) introduced to netdata/netdata found with Coverity Scan.
1 defect(s), reported by Coverity Scan earlier, were marked fixed in the recent build analyzed by Coverity Scan.

New defect(s) Reported-by: Coverity Scan
Showing 20 of 23 defect(s)

```
** CID 348646:  Memory - illegal accesses  (RETURN_LOCAL)
/collectors/cups.plugin/cups_plugin.c: 204 in get_job_metrics()


________________________________________________________________________________________________________
*** CID 348646:  Memory - illegal accesses  (RETURN_LOCAL)
/collectors/cups.plugin/cups_plugin.c: 204 in get_job_metrics()
198     
199             printf("CHART cups.job_size_%s '' 'Active job size of destination %s' KB '%s' job_size stacked %i %i\n", dest, dest, dest, netdata_priority++, netdata_update_every);
200             printf("DIMENSION pending '' absolute 1 1\n");
201             printf("DIMENSION held '' absolute 1 1\n");
202             printf("DIMENSION processing '' absolute 1 1\n");
203         };
>>>     CID 348646:  Memory - illegal accesses  (RETURN_LOCAL)
>>>     Using "jm", which points to an out-of-scope variable "new_job_metrics".
204         return jm;
205     }
206     
207     int collect_job_metrics(char *name, void *entry, void *data) {
208         (void)data;
209     

** CID 348645:  Integer handling issues  (OVERFLOW_BEFORE_WIDEN)
/daemon/unit_test.c: 1722 in test_dbengine_check_metrics()


________________________________________________________________________________________________________
*** CID 348645:  Integer handling issues  (OVERFLOW_BEFORE_WIDEN)
/daemon/unit_test.c: 1722 in test_dbengine_check_metrics()
1716         for (c = 0; c < REGION_POINTS[current_region] ; c += QUERY_BATCH) {
1717             time_now = time_start + (c + 2) * update_every;
1718             for (i = 0 ; i < CHARTS ; ++i) {
1719                 for (j = 0; j < DIMS; ++j) {
1720                     rd[i][j]->state->query_ops.init(rd[i][j], &handle, time_now, time_now + QUERY_BATCH * update_every);
1721                     for (k = 0; k < QUERY_BATCH; ++k) {
>>>     CID 348645:  Integer handling issues  (OVERFLOW_BEFORE_WIDEN)
>>>     Potentially overflowing expression "i * 16 * REGION_POINTS[current_region]" with type "int" (32 bits, signed) is evaluated using 32-bit arithmetic, and then used in a context that expects an expression of type "collected_number" (64 bits, signed).
1722                         last = i * DIMS * REGION_POINTS[current_region] + j * REGION_POINTS[current_region] + c + k;
1723                         expected = unpack_storage_number(pack_storage_number((calculated_number)last, SN_EXISTS));
1724     
1725                         n = rd[i][j]->state->query_ops.next_metric(&handle, &time_retrieved);
1726                         value = unpack_storage_number(n);
1727     

** CID 348644:  Integer handling issues  (OVERFLOW_BEFORE_WIDEN)
/daemon/unit_test.c: 1691 in test_dbengine_create_metrics()


________________________________________________________________________________________________________
*** CID 348644:  Integer handling issues  (OVERFLOW_BEFORE_WIDEN)
/daemon/unit_test.c: 1691 in test_dbengine_create_metrics()
1685         for (c = 0; c < REGION_POINTS[current_region] ; ++c) {
1686             time_now += update_every; // time_now = start + (c + 2) * update_every
1687             for (i = 0 ; i < CHARTS ; ++i) {
1688                 st[i]->usec_since_last_update = USEC_PER_SEC * update_every;
1689     
1690                 for (j = 0; j < DIMS; ++j) {
>>>     CID 348644:  Integer handling issues  (OVERFLOW_BEFORE_WIDEN)
>>>     Potentially overflowing expression "i * 16 * REGION_POINTS[current_region]" with type "int" (32 bits, signed) is evaluated using 32-bit arithmetic, and then used in a context that expects an expression of type "collected_number" (64 bits, signed).
1691                     next = i * DIMS * REGION_POINTS[current_region] + j * REGION_POINTS[current_region] + c;
1692                     rrddim_set_by_pointer_fake_time(rd[i][j], next, time_now);
1693                 }
1694                 rrdset_done(st[i]);
1695             }
1696         }

** CID 348643:  Resource leaks  (RESOURCE_LEAK)
/libnetdata/url/url.c: 60 in url_decode()


________________________________________________________________________________________________________
*** CID 348643:  Resource leaks  (RESOURCE_LEAK)
/libnetdata/url/url.c: 60 in url_decode()
54      * @return a pointer for the url decoded.
55      */
56     char *url_decode(char *str) {
57         size_t size = strlen(str) + 1;
58     
59         char *buf = mallocz(size);
>>>     CID 348643:  Resource leaks  (RESOURCE_LEAK)
>>>     Variable "buf" going out of scope leaks the storage it points to.
60         return url_decode_r(buf, str, size);
61     }
62     
63     /**
64      *  Percentage escape decode
65      *

** CID 348642:  Null pointer dereferences  (REVERSE_INULL)
/database/rrdcalc.c: 440 in rrdcalc_unlink_and_free()


________________________________________________________________________________________________________
*** CID 348642:  Null pointer dereferences  (REVERSE_INULL)
/database/rrdcalc.c: 440 in rrdcalc_unlink_and_free()
434                 rc->next = NULL;
435             }
436             else
437                 error("Cannot unlink alarm '%s.%s' from host '%s': not found", rc->chart?rc->chart:"NOCHART", rc->name, host->hostname);
438         }
439     
>>>     CID 348642:  Null pointer dereferences  (REVERSE_INULL)
>>>     Null-checking "rc" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
440         if (rc) {
441             RRDCALC *rdcmp = (RRDCALC *) avl_search_lock(&(host)->alarms_idx_health_log, (avl *)rc);
442             if (rdcmp) {
443                 rdcmp = (RRDCALC *) avl_remove_lock(&(host)->alarms_idx_health_log, (avl *)rc);
444                 if (!rdcmp) {
445                     error("Cannot remove the health alarm index from health_log");

** CID 348641:  Error handling issues  (CHECKED_RETURN)
/libnetdata/popen/popen.c: 71 in custom_popene()


________________________________________________________________________________________________________
*** CID 348641:  Error handling issues  (CHECKED_RETURN)
/libnetdata/popen/popen.c: 71 in custom_popene()
65         }
66     
67         // Mark all files to be closed by the exec() stage of posix_spawn()
68         int i;
69         for(i = (int) (sysconf(_SC_OPEN_MAX) - 1); i >= 0; i--)
70             if(i != STDIN_FILENO && i != STDERR_FILENO)
>>>     CID 348641:  Error handling issues  (CHECKED_RETURN)
>>>     Calling "fcntl(i, 2, 1)" without checking return value. This library function may fail and return an error code.
71                 fcntl(i, F_SETFD, FD_CLOEXEC);
72     
73         if (!posix_spawn_file_actions_init(&fa)) {
74             // move the pipe to stdout in the child
75             if (posix_spawn_file_actions_adddup2(&fa, pipefd[PIPE_WRITE], STDOUT_FILENO)) {
76                 error("posix_spawn_file_actions_adddup2() failed");

** CID 348640:  Resource leaks  (RESOURCE_LEAK)
/libnetdata/health/health.c: 139 in health_silencers_json_read_callback()


________________________________________________________________________________________________________
*** CID 348640:  Resource leaks  (RESOURCE_LEAK)
/libnetdata/health/health.c: 139 in health_silencers_json_read_callback()
133                 if(!strcmp(e->name,"type")) {
134                     debug(D_HEALTH, "JSON: Processing type=%s",e->data.string);
135                     if (!strcmp(e->data.string,"SILENCE")) silencers->stype = STYPE_SILENCE_NOTIFICATIONS;
136                     else if (!strcmp(e->data.string,"DISABLE")) silencers->stype = STYPE_DISABLE_ALARMS;
137                 } else {
138                     debug(D_HEALTH, "JSON: Adding %s=%s", e->name, e->data.string);
>>>     CID 348640:  Resource leaks  (RESOURCE_LEAK)
>>>     Ignoring storage allocated by "health_silencers_addparam(e->callback_data, e->name, e->data.string)" leaks it.
139                     health_silencers_addparam(e->callback_data, e->name, e->data.string);
140                 }
141                 break;
142     
143             case JSON_BOOLEAN:
144                 debug(D_HEALTH, "JSON: Processing all_alarms");

** CID 348639:    (RESOURCE_LEAK)
/collectors/proc.plugin/sys_block_zram.c: 185 in read_mm_stat()
/collectors/proc.plugin/sys_block_zram.c: 187 in read_mm_stat()
/collectors/proc.plugin/sys_block_zram.c: 196 in read_mm_stat()


________________________________________________________________________________________________________
*** CID 348639:    (RESOURCE_LEAK)
/collectors/proc.plugin/sys_block_zram.c: 185 in read_mm_stat()
179     
180     static inline int read_mm_stat(procfile *ff, MM_STAT *stats) {
181         ff = procfile_readall(ff);
182         if (!ff)
183             return -1;
184         if (procfile_lines(ff) < 1)
>>>     CID 348639:    (RESOURCE_LEAK)
>>>     Returning without freeing "ff" leaks the storage that it points to.
185             return -1;
186         if (procfile_linewords(ff, 0) < 7)
187             return -1;
188     
189         stats->orig_data_size = str2ull(procfile_word(ff, 0));
190         stats->compr_data_size = str2ull(procfile_word(ff, 1));
/collectors/proc.plugin/sys_block_zram.c: 187 in read_mm_stat()
181         ff = procfile_readall(ff);
182         if (!ff)
183             return -1;
184         if (procfile_lines(ff) < 1)
185             return -1;
186         if (procfile_linewords(ff, 0) < 7)
>>>     CID 348639:    (RESOURCE_LEAK)
>>>     Returning without freeing "ff" leaks the storage that it points to.
187             return -1;
188     
189         stats->orig_data_size = str2ull(procfile_word(ff, 0));
190         stats->compr_data_size = str2ull(procfile_word(ff, 1));
191         stats->mem_used_total = str2ull(procfile_word(ff, 2));
192         stats->mem_limit = str2ull(procfile_word(ff, 3));
/collectors/proc.plugin/sys_block_zram.c: 196 in read_mm_stat()
190         stats->compr_data_size = str2ull(procfile_word(ff, 1));
191         stats->mem_used_total = str2ull(procfile_word(ff, 2));
192         stats->mem_limit = str2ull(procfile_word(ff, 3));
193         stats->mem_used_max = str2ull(procfile_word(ff, 4));
194         stats->same_pages = str2ull(procfile_word(ff, 5));
195         stats->pages_compacted = str2ull(procfile_word(ff, 6));
>>>     CID 348639:    (RESOURCE_LEAK)
>>>     Returning without freeing "ff" leaks the storage that it points to.
196         return 0;
197     }
198     
199     static inline int _collect_zram_metrics(char* name, ZRAM_DEVICE *d, int advance, DICTIONARY* dict) {
200         MM_STAT mm;
201         int value;

** CID 348638:  Control flow issues  (DEADCODE)
/collectors/apps.plugin/apps_plugin.c: 3524 in send_collected_data_to_netdata()


________________________________________________________________________________________________________
*** CID 348638:  Control flow issues  (DEADCODE)
/collectors/apps.plugin/apps_plugin.c: 3524 in send_collected_data_to_netdata()
3518         }
3519         send_END();
3520     
3521         send_BEGIN(type, "uptime_avg", dt);
3522         for (w = root; w ; w = w->next) {
3523             if(unlikely(w->exposed && w->processes))
>>>     CID 348638:  Control flow issues  (DEADCODE)
>>>     Execution cannot reach the expression "0UL" inside this statement: "send_SET(w->name, (w->proce...".
3524                 send_SET(w->name, w->processes?(w->uptime_sum / w->processes):0);
3525         }
3526         send_END();
3527     
3528         send_BEGIN(type, "uptime_max", dt);
3529         for (w = root; w ; w = w->next) {

** CID 348637:  Memory - illegal accesses  (USE_AFTER_FREE)
/collectors/proc.plugin/sys_class_power_supply.c: 275 in do_sys_class_power_supply()


________________________________________________________________________________________________________
*** CID 348637:  Memory - illegal accesses  (USE_AFTER_FREE)
/collectors/proc.plugin/sys_class_power_supply.c: 275 in do_sys_class_power_supply()
269                     }
270                 }
271     
272                 // read property files
273                 int read_error = 0;
274                 struct ps_property *pr;
>>>     CID 348637:  Memory - illegal accesses  (USE_AFTER_FREE)
>>>     Using freed pointer "ps->property_root".
275                 for(pr = ps->property_root; pr && !read_error; pr = pr->next) {
276                     struct ps_property_dim *pd;
277                     for(pd = pr->property_dim_root; pd; pd = pd->next) {
278                         if(likely(!pd->always_zero)) {
279                             char buffer[30 + 1];
280     

** CID 348636:  Memory - illegal accesses  (UNINIT)
/database/engine/pagecache.c: 1048 in free_page_cache()


________________________________________________________________________________________________________
*** CID 348636:  Memory - illegal accesses  (UNINIT)
/database/engine/pagecache.c: 1048 in free_page_cache()
1042             /* Find first page in range */
1043             Index = (Word_t) 0;
1044             PValue = JudyLFirst(page_index->JudyL_array, &Index, PJE0);
1045             if (likely(NULL != PValue)) {
1046                 descr = *PValue;
1047             }
>>>     CID 348636:  Memory - illegal accesses  (UNINIT)
>>>     Using uninitialized value "descr".
1048             while (descr != NULL) {
1049                 /* Iterate all page descriptors of this metric */
1050     
1051                 if (descr->pg_cache_descr_state & PG_CACHE_DESCR_ALLOCATED) {
1052                     /* Check rrdenglocking.c */
1053                     pg_cache_descr = descr->pg_cache_descr;

** CID 348635:  Null pointer dereferences  (FORWARD_NULL)
/collectors/proc.plugin/proc_mdstat.c: 200 in do_proc_mdstat()


________________________________________________________________________________________________________
*** CID 348635:  Null pointer dereferences  (FORWARD_NULL)
/collectors/proc.plugin/proc_mdstat.c: 200 in do_proc_mdstat()
194                     else if(unlikely(*s == ']')) {
195                         *s = '\0';
196                         break;
197                     }
198                     s++;
199                 }
>>>     CID 348635:  Null pointer dereferences  (FORWARD_NULL)
>>>     Dereferencing null pointer "str_inuse".
200                 if(unlikely(str_total[0] == '\0' || str_inuse[0] == '\0')) {
201                     error("Cannot read /proc/mdstat raid health status. Unexpected format.");
202                     continue;
203                 }
204     
205                 raid->inuse_disks = str2ull(str_inuse);

** CID 348634:  Null pointer dereferences  (FORWARD_NULL)
/database/engine/rrdengine.c: 836 in basic_functional_test()


________________________________________________________________________________________________________
*** CID 348634:  Null pointer dereferences  (FORWARD_NULL)
/database/engine/rrdengine.c: 836 in basic_functional_test()
830         for (i = 0 ; i < NR_PAGES ; ++i) {
831             buf = rrdeng_get_latest_page(ctx, &uuid[i], (void **)&handle[i]);
832             if (NULL == buf) {
833                 ++failed_validations;
834                 fprintf(stderr, "Page %d was LOST.\n", i);
835             }
>>>     CID 348634:  Null pointer dereferences  (FORWARD_NULL)
>>>     Passing null pointer "buf" to "memcmp", which dereferences it.
836             if (memcmp(backup[i], buf, UUID_STR_LEN * 100)) {
837                 ++failed_validations;
838                 fprintf(stderr, "Page %d data comparison with backup FAILED validation.\n", i);
839             }
840             rrdeng_put_page(ctx, handle[i]);
841         }

** CID 348633:  Resource leaks  (RESOURCE_LEAK)
/database/engine/rrdengine.c: 461 in do_flush_pages()


________________________________________________________________________________________________________
*** CID 348633:  Resource leaks  (RESOURCE_LEAK)
/database/engine/rrdengine.c: 461 in do_flush_pages()
455         ++ctx->stats.io_write_extents;
456         do_commit_transaction(wc, STORE_DATA, xt_io_descr);
457         datafile->pos += ALIGN_BYTES_CEILING(size_bytes);
458         ctx->disk_space += ALIGN_BYTES_CEILING(size_bytes);
459         rrdeng_test_quota(wc);
460     
>>>     CID 348633:  Resource leaks  (RESOURCE_LEAK)
>>>     Variable "compressed_buf" going out of scope leaks the storage it points to.
461         return ALIGN_BYTES_CEILING(size_bytes);
462     }
463     
464     static void after_delete_old_data(uv_work_t *req, int status)
465     {
466         struct rrdengine_instance *ctx = req->data;

** CID 348632:    (OVERRUN)


________________________________________________________________________________________________________
*** CID 348632:    (OVERRUN)
/database/engine/rrdenginelib.c: 49 in print_page_descr()
43                          (uint64_t)descr->end_time);
44         if (!descr->extent) {
45             pos += snprintfz(str + pos, BUFSIZE - pos, "N/A");
46         } else {
47             pos += snprintfz(str + pos, BUFSIZE - pos, "%"PRIu64, descr->extent->offset);
48         }
>>>     CID 348632:    (OVERRUN)
>>>     Overrunning array of 512 bytes at byte offset 512 by dereferencing pointer "str + pos".
49         snprintfz(str + pos, BUFSIZE - pos, "\n\n");
50         fputs(str, stderr);
51     }
52     
53     int check_file_properties(uv_file file, uint64_t *file_size, size_t min_size)
54     {
/database/engine/rrdenginelib.c: 45 in print_page_descr()
39                                          "--->len:%"PRIu32" time:%"PRIu64"->%"PRIu64" xt_offset:",
40                          uuid_str,
41                          descr->page_length,
42                          (uint64_t)descr->start_time,
43                          (uint64_t)descr->end_time);
44         if (!descr->extent) {
>>>     CID 348632:    (OVERRUN)
>>>     Overrunning array of 512 bytes at byte offset 512 by dereferencing pointer "str + pos".
45             pos += snprintfz(str + pos, BUFSIZE - pos, "N/A");
46         } else {
47             pos += snprintfz(str + pos, BUFSIZE - pos, "%"PRIu64, descr->extent->offset);
48         }
49         snprintfz(str + pos, BUFSIZE - pos, "\n\n");
50         fputs(str, stderr);
/database/engine/rrdenginelib.c: 47 in print_page_descr()
41                          descr->page_length,
42                          (uint64_t)descr->start_time,
43                          (uint64_t)descr->end_time);
44         if (!descr->extent) {
45             pos += snprintfz(str + pos, BUFSIZE - pos, "N/A");
46         } else {
>>>     CID 348632:    (OVERRUN)
>>>     Overrunning array of 512 bytes at byte offset 512 by dereferencing pointer "str + pos".
47             pos += snprintfz(str + pos, BUFSIZE - pos, "%"PRIu64, descr->extent->offset);
48         }
49         snprintfz(str + pos, BUFSIZE - pos, "\n\n");
50         fputs(str, stderr);
51     }
52     

** CID 348631:  Integer handling issues  (OVERFLOW_BEFORE_WIDEN)
/daemon/unit_test.c: 1722 in test_dbengine_check_metrics()


________________________________________________________________________________________________________
*** CID 348631:  Integer handling issues  (OVERFLOW_BEFORE_WIDEN)
/daemon/unit_test.c: 1722 in test_dbengine_check_metrics()
1716         for (c = 0; c < REGION_POINTS[current_region] ; c += QUERY_BATCH) {
1717             time_now = time_start + (c + 2) * update_every;
1718             for (i = 0 ; i < CHARTS ; ++i) {
1719                 for (j = 0; j < DIMS; ++j) {
1720                     rd[i][j]->state->query_ops.init(rd[i][j], &handle, time_now, time_now + QUERY_BATCH * update_every);
1721                     for (k = 0; k < QUERY_BATCH; ++k) {
>>>     CID 348631:  Integer handling issues  (OVERFLOW_BEFORE_WIDEN)
>>>     Potentially overflowing expression "j * REGION_POINTS[current_region]" with type "int" (32 bits, signed) is evaluated using 32-bit arithmetic, and then used in a context that expects an expression of type "collected_number" (64 bits, signed).
1722                         last = i * DIMS * REGION_POINTS[current_region] + j * REGION_POINTS[current_region] + c + k;
1723                         expected = unpack_storage_number(pack_storage_number((calculated_number)last, SN_EXISTS));
1724     
1725                         n = rd[i][j]->state->query_ops.next_metric(&handle, &time_retrieved);
1726                         value = unpack_storage_number(n);
1727     

** CID 348630:    (OVERRUN)


________________________________________________________________________________________________________
*** CID 348630:    (OVERRUN)
/database/engine/rrdenginelib.c: 22 in print_page_cache_descr()
16                                         "--->len:%"PRIu32" time:%"PRIu64"->%"PRIu64" xt_offset:",
17                         pg_cache_descr->page, uuid_str,
18                         descr->page_length,
19                         (uint64_t)descr->start_time,
20                         (uint64_t)descr->end_time);
21         if (!descr->extent) {
>>>     CID 348630:    (OVERRUN)
>>>     Overrunning array of 512 bytes at byte offset 512 by dereferencing pointer "str + pos".
22             pos += snprintfz(str + pos, BUFSIZE - pos, "N/A");
23         } else {
24             pos += snprintfz(str + pos, BUFSIZE - pos, "%"PRIu64, descr->extent->offset);
25         }
26     
27         snprintfz(str + pos, BUFSIZE - pos, " flags:0x%2.2lX refcnt:%u\n\n", pg_cache_descr->flags, pg_cache_descr->refcnt);
/database/engine/rrdenginelib.c: 24 in print_page_cache_descr()
18                         descr->page_length,
19                         (uint64_t)descr->start_time,
20                         (uint64_t)descr->end_time);
21         if (!descr->extent) {
22             pos += snprintfz(str + pos, BUFSIZE - pos, "N/A");
23         } else {
>>>     CID 348630:    (OVERRUN)
>>>     Overrunning array of 512 bytes at byte offset 512 by dereferencing pointer "str + pos".
24             pos += snprintfz(str + pos, BUFSIZE - pos, "%"PRIu64, descr->extent->offset);
25         }
26     
27         snprintfz(str + pos, BUFSIZE - pos, " flags:0x%2.2lX refcnt:%u\n\n", pg_cache_descr->flags, pg_cache_descr->refcnt);
28         debug(D_RRDENGINE, "%s", str);
29     }
/database/engine/rrdenginelib.c: 27 in print_page_cache_descr()
21         if (!descr->extent) {
22             pos += snprintfz(str + pos, BUFSIZE - pos, "N/A");
23         } else {
24             pos += snprintfz(str + pos, BUFSIZE - pos, "%"PRIu64, descr->extent->offset);
25         }
26     
>>>     CID 348630:    (OVERRUN)
>>>     Overrunning array of 512 bytes at byte offset 512 by dereferencing pointer "str + pos".
27         snprintfz(str + pos, BUFSIZE - pos, " flags:0x%2.2lX refcnt:%u\n\n", pg_cache_descr->flags, pg_cache_descr->refcnt);
28         debug(D_RRDENGINE, "%s", str);
29     }
30     
31     void print_page_descr(struct rrdeng_page_descr *descr)
32     {

** CID 348629:  Security best practices violations  (TOCTOU)
/health/health.c: 49 in health_silencers_init()


________________________________________________________________________________________________________
*** CID 348629:  Security best practices violations  (TOCTOU)
/health/health.c: 49 in health_silencers_init()
43      * Silencers init
44      *
45      * Function used to initialize the silencer structure.
46      */
47     void health_silencers_init(void) {
48         struct stat statbuf;
>>>     CID 348629:  Security best practices violations  (TOCTOU)
>>>     Calling function "stat" to perform check on "silencers_filename".
49         if (!stat(silencers_filename,&statbuf)) {
50             off_t length = statbuf.st_size;
51             if (length && length < HEALTH_SILENCERS_MAX_FILE_LEN) {
52                 FILE *fd = fopen(silencers_filename, "r");
53                 if (fd) {
54                     char *str = mallocz((length+1)* sizeof(char));

** CID 348628:    (USE_AFTER_FREE)
/collectors/proc.plugin/sys_class_power_supply.c: 265 in do_sys_class_power_supply()
/collectors/proc.plugin/sys_class_power_supply.c: 251 in do_sys_class_power_supply()
/collectors/proc.plugin/sys_class_power_supply.c: 262 in do_sys_class_power_supply()


________________________________________________________________________________________________________
*** CID 348628:    (USE_AFTER_FREE)
/collectors/proc.plugin/sys_class_power_supply.c: 265 in do_sys_class_power_supply()
259                     }
260     
261                     if(unlikely(!keep_fds_open)) {
262                         close(ps->capacity->fd);
263                         ps->capacity->fd = -1;
264                     }
>>>     CID 348628:    (USE_AFTER_FREE)
>>>     Dereferencing freed pointer "ps->capacity".
265                     else if(unlikely(lseek(ps->capacity->fd, 0, SEEK_SET) == -1)) {
266                         error("Cannot seek in file '%s'", ps->capacity->filename);
267                         close(ps->capacity->fd);
268                         ps->capacity->fd = -1;
269                     }
270                 }
/collectors/proc.plugin/sys_class_power_supply.c: 251 in do_sys_class_power_supply()
245                         if(unlikely(ps->capacity->fd == -1)) {
246                             error("Cannot open file '%s'", ps->capacity->filename);
247                             power_supply_free(ps);
248                         }
249                     }
250     
>>>     CID 348628:    (USE_AFTER_FREE)
>>>     Dereferencing freed pointer "ps->capacity".
251                     ssize_t r = read(ps->capacity->fd, buffer, 30);
252                     if(unlikely(r < 1)) {
253                         error("Cannot read file '%s'", ps->capacity->filename);
254                         power_supply_free(ps);
255                     }
256                     else {
/collectors/proc.plugin/sys_class_power_supply.c: 262 in do_sys_class_power_supply()
256                     else {
257                         buffer[r] = '\0';
258                         ps->capacity->value = str2ull(buffer);
259                     }
260     
261                     if(unlikely(!keep_fds_open)) {
>>>     CID 348628:    (USE_AFTER_FREE)
>>>     Dereferencing freed pointer "ps->capacity".
262                         close(ps->capacity->fd);
263                         ps->capacity->fd = -1;
264                     }
265                     else if(unlikely(lseek(ps->capacity->fd, 0, SEEK_SET) == -1)) {
266                         error("Cannot seek in file '%s'", ps->capacity->filename);
267                         close(ps->capacity->fd);

** CID 348627:    (RESOURCE_LEAK)
/libnetdata/popen/popen.c: 121 in custom_popene()
/libnetdata/popen/popen.c: 101 in custom_popene()


________________________________________________________________________________________________________
*** CID 348627:    (RESOURCE_LEAK)
/libnetdata/popen/popen.c: 121 in custom_popene()
115     error_after_posix_spawn_file_actions_init:
116         if (posix_spawn_file_actions_destroy(&fa))
117             error("posix_spawn_file_actions_destroy");
118     error_after_pipe:
119         close(pipefd[PIPE_READ]);
120         close(pipefd[PIPE_WRITE]);
>>>     CID 348627:    (RESOURCE_LEAK)
>>>     Variable "fp" going out of scope leaks the storage it points to.
121         return NULL;
122     }
123     
124     // See man environ
125     extern char **environ;
126     
/libnetdata/popen/popen.c: 101 in custom_popene()
95         if (!posix_spawn(&pid, "/bin/sh", &fa, &attr, spawn_argv, env)) {
96             *pidptr = pid;
97             debug(D_CHILDS, "Spawned command: '%s' on pid %d from parent pid %d.", command, pid, getpid());
98         } else {
99             error("Failed to spawn command: '%s' from parent pid %d.", command, getpid());
100             close(pipefd[PIPE_READ]);
>>>     CID 348627:    (RESOURCE_LEAK)
>>>     Overwriting "fp" in "fp = NULL" leaks the storage that "fp" points to.
101             fp = NULL;
102         }
103         close(pipefd[PIPE_WRITE]);
104     
105         if (!error) {
106             // posix_spawnattr_init() succeeded
```

________________________________________________________________________________________________________
To view the defects in Coverity Scan visit, https://u2389337.ct.sendgrid.net/wf/click?upn=08onrYu34A-2BWcWUl-2F-2BfV0V05UPxvVjWch-2Bd2MGckcRaF9xdVVnAWPHuu4AkIHkbrBIv-2F8XQlpq2lgGZc6umQJDyN03hSWb98WnkINy2cfBM-3D_-2BPPYzd87qq10IXJQDD0DUwjyjvfV4MTALaQhIiX1dQzNJgJzpz-2FQHCfyqfECqy8TywqOrGh-2BlhZbt780S83sTfd8ww3UGoI2qlJPnNrVu6jU2WJb95s-2Fzec1u4Duy6oCJb7EuPjzowfdHnxrwOMw8tbsu4dGE0WKHAwEzCWtye3wLYagiKcD2ZVQ0-2BpyNE9TBD9hGGYomVU6Rh12ESewRPir51khMfYSt0hfAWYMG08-3D

  To manage Coverity Scan email notifications for "chris@netdata.cloud", click https://u2389337.ct.sendgrid.net/wf/click?upn=08onrYu34A-2BWcWUl-2F-2BfV0V05UPxvVjWch-2Bd2MGckcRbVDbis712qZDP-2FA8y06Nq4fGEAjLVOI5EQQWVQwGeUCfrKrJmSnvwYrSkaLPVT2d9UQ-2FwHvbwBLBuq3G4zGkkDM434zplxyAG-2FxgWNTsX-2FuUaa-2F0uZuMzqACLy9Dze5WY-3D_-2BPPYzd87qq10IXJQDD0DUwjyjvfV4MTALaQhIiX1dQzNJgJzpz-2FQHCfyqfECqy8Tam6F5sdT1c0TgnwiFv0Ah4guU1CN5Xl075Wlsfw5i3cKSGhElYwpySqmrCLU-2FBlD0LHn2rth6J7-2FAjLCvr8tJhsP4boQH5W-2B4cbNax8ZsHbVUA54jw8a3T4AKo4vQdq3O553PFXepftCGWmBSvf8TfLlxjWlw8bUk-2BEDDia8uPg-3D

### PR DESCRIPTION
**Pull request by thiagoftsm**
##### Summary
Fixes #6791 

This PR fixes the following errors found in the report delivered by Coverity on 09/05/2019:

CID 348627: Considering that the official documentation fdopen(3) says "The file descriptor is not dup'ed, and will be closed when the stream created by fdopen() is  closed.", I choice to use `fclose` instead `close()` and `fp =NULL`.
CID 348628: There was a real possibility to clean a structure and use it after this, so I introducted a test for the pointer.
CID 348629: It was changed the call from stat for a file pointer movement to measure the file size.
CID 348635: It was added a conditional to verify the existence of the address before to test the first value of a pointer.
CID 348638: Without any doubt our current code is the safest option, so I did not touch it.
CID 348639: We have a reuse of pointer here that generates this wrong error message.
CID 348640: We do not have resource leak here, because in this case Netdata always given an allocated structure
CID 348641: I added an if to verify the return, and I am calling perror to redirect the data to error.log.
CID 348643: The function here is never used inside Netdata, so I removed it.
CID 348646: Clion is saying that Cups plugin is not linked, and here I confess I agree with the error reported, but I do not know the whole structure, so I am for others to do an study about this case.

I did not touch the code related with dbengine due talk in Slack channel.
##### Component Name
Netdata core

### CODE REVIEW

File: libnetdata/popen/popen.c [hunk 1]
```diff
@@ -116,7 +117,7 @@ static inline FILE *custom_popene(const char *command, volatile pid_t *pidptr, c
     if (posix_spawn_file_actions_destroy(&fa))
         error("posix_spawn_file_actions_destroy");
 error_after_pipe:
-    close(pipefd[PIPE_READ]);
+    fclose(fp);
```
Comment (mfundul) [inline libnetdata/popen/popen.c]: This will not work because if `fdopen()` fails you need to `close()` the pipe and not `fclose()` it.

You must change it to:
```
    if (fp)
        fclose(fp);
    else
        close(pipefd[PIPE_READ]);
```
```

**Comment by cosmix** [comment]
@thiagoftsm many thanks for the PR. As a note, however, you should have split your work with clean commits, one per Coverity issue.

File: libnetdata/popen/popen.c (hunk 1 above)
Comment (thiagoftsm) [reply libnetdata/popen/popen.c]: Thank you @mfundul , I really missed this.

**Comment by thiagoftsm** [comment]
> @thiagoftsm many thanks for the PR. As a note, however, you should have split your work with clean commits, one per Coverity issue.

You are welcome @cosmix! I created only one, because there was only one report, and I imagined that would be simple to do the association between errors and fixes here, but I agree with you that it would be more clean to have the fixes per issue, but we have sometimes more  than one bug in specific files. Can we at least to do PRs per file? Remeber we are talking about 23 bugs.

**Comment by cosmix** [comment]
No I meant one commit per Coverity issue. Not one PR per Coverity issue :)

File: health/health.c [hunk 2]
```diff
@@ -64,15 +66,13 @@ void health_silencers_init(void) {
...
             } else {
-                error("Cannot open the file %s",silencers_filename);
+                error("Health silencers file %s has the size %ld that is out of range[ 1 , %d ]. Aborting read.", silencers_filename, length, HEALTH_SILENCERS_MAX_FILE_LEN);
             }
+            fclose(fd);
         } else {
-            error("Health silencers file %s has the size %ld that is out of range[ 1 , %d ]. Aborting read.", silencers_filename, length, HEALTH_SILENCERS_MAX_FILE_LEN);
+            error("Cannot open the file %s",silencers_filename);
         }
-    } else {
```
[the remark this answers is not in the document]
Comment (thiagoftsm) [reply health/health.c]: The silencers_filename is not a file that always exists, it only exists case the user talks with the Agent and  send a message to it stores the health information inside this file. When this file does not exists, the Agent works with its default behavior.

File: libnetdata/popen/popen.c [hunk 3]
```diff
@@ -68,7 +68,8 @@ static inline FILE *custom_popene(const char *command, volatile pid_t *pidptr, c
     int i;
     for(i = (int) (sysconf(_SC_OPEN_MAX) - 1); i >= 0; i--)
         if(i != STDIN_FILENO && i != STDERR_FILENO)
-            fcntl(i, F_SETFD, FD_CLOEXEC);
+            if (fcntl(i, F_SETFD, FD_CLOEXEC) == -1)
+                perror("custom peopen");
```
[the remark this answers is not in the document]
Comment (mfundul) [reply libnetdata/popen/popen.c]: This was in the spirit of the [old popen](https://github.com/netdata/netdata/blob/v1.15.0/libnetdata/popen/popen.c#L73). Failing to close the files for the child process is like falling back to legacy [popen](http://man7.org/linux/man-pages/man3/popen.3.html) library call.

This is why I did not handle an error condition at all when porting the old popen to the new one. The OOM problem was because `fork()` would duplicate the address space (which could be 10s of GiB), but the per-process file descriptors being duplicated have not been observed to be a big problem yet.

I could argue that using the POSIX `popen()` semantics would be good enough and we don't even have to close any files, but there are concerns about security (leaking file descriptors to child process) and file descriptor limits.

However, the current behaviour does guarantee that a plugin will run even if it fails to close some file descriptors. So the question is, do we want to fail-stop when we fail to clean-up before cloning a process or do we tolerate file descriptor leaks so as to not disrupt netdata monitoring?

[the remark this answers is not in the document]
Comment (cosmix) [reply libnetdata/popen/popen.c]: I remember. My question was more of the rhetorical nature: is it enough to log an error? It's seldom enough or a sign of robust engineering.

I agree that it's probably not going to be a problem, but I think we should handle those things.

> So the question is, do we want to fail-stop when we fail to clean-up before cloning a process or do we tolerate file descriptor leaks so as to not disrupt netdata monitoring?

And that's something we need to discuss and agree on.

[the remark this answers is not in the document]
Comment (thiagoftsm) [reply libnetdata/popen/popen.c]: To use the `perror` was not the best option, I agree with you, so I changed to use the `error` together with `strerror`.
Now about the original code does not do nothing when an error happens, I imagined that the original development was done based in the following sentence of the documentation  ```If the FD_CLOEXEC bit is set, the file descriptor will automatically be closed during a successful execve(2).  (If the execve(2) fails, the file descriptor is left open.) ```  , no less important , we close the PIPE few lines below this code. @mfundul can you confirm my initial thought?

[the remark this answers is not in the document]
Comment (mfundul) [reply libnetdata/popen/popen.c]: `error()` already includes `strerror` as you can see [here](https://github.com/netdata/netdata/blob/ab6f1c0b25c38e70585bfc65ec88ce5f5337f473/libnetdata/log/log.c#L758).

Moreover, this `fcntl(i, F_SETFD, FD_CLOEXEC)` is about all the file descriptors of the process, other than the pipe itself, so it's kind of the complement of the `close(pipefd[PIPE_READ]);`

[the remark this answers is not in the document]
Comment (thiagoftsm) [reply libnetdata/popen/popen.c]: Thank you @mfundul , I fixed it.

File: collectors/proc.plugin/proc_mdstat.c [hunk 4]
```diff
@@ -197,7 +197,7 @@ int do_proc_mdstat(int update_every, usec_t dt) {
                 }
                 s++;
             }
-            if(unlikely(str_total[0] == '\0' || str_inuse[0] == '\0')) {
+            if(unlikely(str_total[0] == '\0' || (str_inuse && str_inuse[0] == '\0'))) {
```
Comment (mfundul) [inline collectors/proc.plugin/proc_mdstat.c]: This should be:
```
if (unlikely(str_total[0] == '\0' || !str_inuse || str_inuse[0] == '\0')) {
```
cause the way it is right now if `str_inuse` is `NULL` then it will succeed and do:
```
raid->inuse_disks = str2ull(str_inuse);
```

File: collectors/proc.plugin/sys_class_power_supply.c [hunk 5]
```diff
@@ -245,13 +245,18 @@ int do_sys_class_power_supply(int update_every, usec_t dt) {
                     if(unlikely(ps->capacity->fd == -1)) {
                         error("Cannot open file '%s'", ps->capacity->filename);
                         power_supply_free(ps);
+                        ps = NULL;
```
Comment (mfundul) [inline collectors/proc.plugin/sys_class_power_supply.c]: If you do `ps = NULL;` it will crash immediately afterwards in line 252: `ssize_t r = read(ps->capacity->fd, buffer, 30);`

Comment (cakrit) [reply collectors/proc.plugin/sys_class_power_supply.c]: Actually, I don't get that `read` at all. Even in the previous version, we should end up segfaulting when `ps->capacity->fd == -1`, right? I mean, it zeroes everything. Looks like the code is missing an `} else {` here.

Comment (mfundul) [reply collectors/proc.plugin/sys_class_power_supply.c]: It probably did not segfault immediately due to it not being NULL. We either need to move the code in the `if (ps)` or use an `else` as you suggested.

File: collectors/proc.plugin/proc_mdstat.c (hunk 4 above)
Comment (thiagoftsm) [reply collectors/proc.plugin/proc_mdstat.c]: I changed the comparison as it was suggested.

File: collectors/proc.plugin/sys_class_power_supply.c (hunk 5 above)
Comment (thiagoftsm) [reply collectors/proc.plugin/sys_class_power_supply.c]: I decided to use an `else`, I tested both to see what would be more readable, and I confess I liked more the `else`.

File: collectors/proc.plugin/sys_class_power_supply.c [hunk 6]
```diff
@@ -245,67 +245,75 @@ int do_sys_class_power_supply(int update_every, usec_t dt) {
...
+                                    power_supply_free(ps);
+                                    break;
+                                }
+                            }
+
+                            ssize_t r = read(pd->fd, buffer, 30);
+                            if(unlikely(r < 1)) {
+                                error("Cannot read file '%s'", pd->filename);
                                 read_error = 1;
                                 power_supply_free(ps);
```
Comment (mfundul) [inline collectors/proc.plugin/sys_class_power_supply.c]: This does not break cleanly out of the 2 nested loops and it can be called multiple times in theory. That would be `free()` after `free()` which sounds bad.

File: collectors/proc.plugin/sys_class_power_supply.c [hunk 7]
```diff
@@ -245,67 +245,75 @@ int do_sys_class_power_supply(int update_every, usec_t dt) {
...
                                 break;
                             }
-                        }
-
-                        ssize_t r = read(pd->fd, buffer, 30);
-                        if(unlikely(r < 1)) {
-                            error("Cannot read file '%s'", pd->filename);
-                            read_error = 1;
-                            power_supply_free(ps);
```
Comment (mfundul) [inline collectors/proc.plugin/sys_class_power_supply.c]: Same as above.

File: health/health.c [hunk 8]
```diff
@@ -45,12 +45,14 @@ inline char *health_stock_config_dir(void) {
  * Function used to initialize the silencer structure.
  */
 void health_silencers_init(void) {
-    struct stat statbuf;
-    if (!stat(silencers_filename,&statbuf)) {
-        off_t length = statbuf.st_size;
-        if (length && length < HEALTH_SILENCERS_MAX_FILE_LEN) {
-            FILE *fd = fopen(silencers_filename, "r");
-            if (fd) {
+    if (silencers_filename) {
```
Comment (mfundul) [inline health/health.c]: By looking at the configuration code `silencers_filename` is never going to be NULL, but even if it could be it would be nice to have an error print for that case.

Comment (thiagoftsm) [reply health/health.c]: You are correct, this is a global variable that will never be NULL, because we give a default value for it when the user does not specify. Thanks!

File: collectors/proc.plugin/sys_class_power_supply.c (hunk 6 above)
Comment (thiagoftsm) [reply collectors/proc.plugin/sys_class_power_supply.c]: It was fixed now.

File: collectors/proc.plugin/sys_class_power_supply.c (hunk 7 above)
Comment (thiagoftsm) [reply collectors/proc.plugin/sys_class_power_supply.c]: I used the same solution that I used above, now I will check an error that we are having with custom_peopen.

**Comment by thiagoftsm** [comment]
@mfundul I removed the `if` and `error()` from libnetdata/popen/popen.c when we call the `fcntl` and I decided to use `(void)`, because we were generating thousands of error message.

File: health/health.c (hunk 8 above)
Comment (mfundul) [reply health/health.c]: Hmm, yes, that's why the original code of Kosta was not doing any error handling, some file descriptors in the range are bound to not exist.

See here:
https://github.com/netdata/netdata/blob/4f64e8edbdb0d4b68b882aa34474a0156b6ba150/libnetdata/popen/popen.c#L73

Comment (thiagoftsm) [reply health/health.c]: Yes, let us hope that the `(void)` will be enough to coverity does not raise more errors.

File: collectors/proc.plugin/sys_class_power_supply.c (hunk 6 above)
Comment (mfundul) [reply collectors/proc.plugin/sys_class_power_supply.c]: But still the code can go to `pr = pr->next` from:
```
for(pr = ps->property_root; pr && !read_error; pr = pr->next) {
```
and call `power_supply_free(ps);` another time?

Comment (thiagoftsm) [reply collectors/proc.plugin/sys_class_power_supply.c]: The `read_error` variable avoid it continues going in the next element of the for loop, as you can see it is set to `1`, every time we clean the structure.

Comment (mfundul) [reply collectors/proc.plugin/sys_class_power_supply.c]: Ah, yes, you're right!

Comment (mfundul) [reply collectors/proc.plugin/sys_class_power_supply.c]: Then I guess `ps = NULL;` is not really necessary because the next use is only `struct power_supply *ps = power_supply_root;` ?

Comment (thiagoftsm) [reply collectors/proc.plugin/sys_class_power_supply.c]: I agree 100%, I removed the unnecessary set of a variable. Thank you!
