### PR TITLE
Detect a buggy Ubuntu kernel

### LINKED ISSUE #9634: ubuntu 18.04.1 segfault after reinstalling netdata: usercopy: Kernel memory overwrite attempt detected to process stack (offset 0, size 4)!
##### Bug report summary
3 of our Ubuntu 18.04.1 build servers have started crashing after I reinstalled netdata this week.  

Machine 1 rebooted overnight and came up without networking last night.  

Machine 2 seemed to have tried a netdata update and failed, its /usr/sbin/netdata was 0bytes.  When I tried to run kickstart, after building it crashed the machine and the system rebooted. After the reboot, ran kickstart again and this time it installed and appears to be running.

Machine 3 seems to be stuck in a kernel panic boot loop.

A snippet of syslog from machine 1 before crash
```
  24 Jul 30 06:30:55 userv1 netdata[4992]: 2020-07-30 06:30:55: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
  25 Jul 30 06:30:56 userv1 ebpf.plugin: Does not have a configuration file inside `/etc/netdata/ebpf.conf. It will try to load stock file.
  26 Jul 30 06:30:56 userv1 ebpf.plugin: Name resolution is disabled, collector will not parser "hostnames" list.
  27 Jul 30 06:30:56 userv1 ebpf.plugin: The network value of CIDR 127.0.0.1/8 was updated for 127.0.0.0 .
  28 Jul 30 06:30:56 userv1 ebpf.plugin: Loaded config file '/etc/netdata/apps_groups.conf'
  29 Jul 30 06:30:56 userv1 kernel: [19816692.705560] trace_kprobe: Event kprobes/p_netdata_vfs_write_0 doesn't exist.
  30 Jul 30 06:30:56 userv1 kernel: [19816692.705571] trace_kprobe: Event kprobes/p_netdata_tcp_cleanup_rbuf_0 doesn't exist.
  31 Jul 30 06:30:56 userv1 systemd-resolved[16251]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
  32 Jul 30 06:30:56 userv1 kernel: [19816692.905217] usercopy: Kernel memory overwrite attempt detected to process stack (offset 0, size 4)!
  33 Jul 30 06:30:56 userv1 kernel: [19816692.905238] ------------[ cut here ]------------
  34 Jul 30 06:30:56 userv1 kernel: [19816692.905240] kernel BUG at /build/linux-hwe-jDoxDp/linux-hwe-4.18.0/mm/usercopy.c:100!
  35 Jul 30 06:30:56 userv1 kernel: [19816692.905270] invalid opcode: 0000 [#1] SMP NOPTI
  36 Jul 30 06:30:56 userv1 kernel: [19816692.905283] CPU: 8 PID: 5370 Comm: STREAM_SENDER[u Not tainted 4.18.0-13-generic #14~18.04.1-Ubuntu
  37 Jul 30 06:30:56 userv1 kernel: [19816692.905294] Hardware name: Micro-Star International Co., Ltd. MS-7B79/X470 GAMING PLUS (MS-7B79), BIOS A.40 06/28/2018
  38 Jul 30 06:30:56 userv1 kernel: [19816692.905309] RIP: 0010:usercopy_abort+0x6d/0x80
  39 Jul 30 06:30:56 userv1 kernel: [19816692.905317] Code: 44 d0 53 48 c7 c0 50 3b d0 8e 51 48 c7 c6 b7 15 cf 8e 41 53 48 89 f9 48 0f 45 f0 4c 89 d2 48 c7 c7 40 3c d0 8e e8 46 1c e6 ff <0f> 0b 49 c7      c1 0a 43 d2 8e 4d 89 cb 4d 89 c8 eb a5 66 90 0f 1f 44
...
  49 Jul 30 06:30:56 userv1 kernel: [19816692.905427] Call Trace:
  50 Jul 30 06:30:56 userv1 kernel: [19816692.905435]  __check_object_size+0x15f/0x1a0
  51 Jul 30 06:30:56 userv1 kernel: [19816692.905444]  __probe_kernel_read+0x4c/0x90
  52 Jul 30 06:30:56 userv1 kernel: [19816692.905451]  bpf_probe_read+0x1d/0x50
```

Machine 1 [syslog.log](https://github.com/netdata/netdata/files/5002228/syslog.log)

##### OS / Environment
Machine 1:
```
Linux userv1 4.18.0-13-generic #14~18.04.1-Ubuntu SMP Thu Dec 6 14:09:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```
Machine 2:
```
Linux userv2 4.18.0-13-generic #14~18.04.1-Ubuntu SMP Thu Dec 6 14:09:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
```
Machine 3:
Similar though haven't gotten it to boot yet

##### Netdata version
 netdata v1.23.2

##### Component Name
eBPF presumably

##### Steps To Reproduce
* Install missing packages
 ```bash <(curl -sSL https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh) -i netdata```
* Ran kickstart 
```bash <(curl -Ss https://my-netdata.io/kickstart.sh) --stable-channel --dont-wait --auto-update```
* Registered to cloud

##### Expected behavior
No crash

### PR DESCRIPTION
**Pull request by vlvkobal**
##### Summary
There is a buggy Ubuntu HWE kernel (Ubuntu 18.04 - 4.18.0-13) that crashes when it tries to load BPF programs for the eBPF plugin.
```
 kernel BUG at /build/linux-hwe-jDoxDp/linux-hwe-4.18.0/mm/usercopy.c:100!
  35 Jul 30 06:30:56 userv1 kernel: [19816692.905270] invalid opcode: 0000 [#1] SMP NOPTI
  36 Jul 30 06:30:56 userv1 kernel: [19816692.905283] CPU: 8 PID: 5370 Comm: STREAM_SENDER[u Not tainted 4.18.0-13-generic #14~18.04.1-Ubuntu
  37 Jul 30 06:30:56 userv1 kernel: [19816692.905294] Hardware name: Micro-Star International Co., Ltd. MS-7B79/X470 GAMING PLUS (MS-7B79), BIOS A.40 06/28/2018
  38 Jul 30 06:30:56 userv1 kernel: [19816692.905309] RIP: 0010:usercopy_abort+0x6d/0x80
  39 Jul 30 06:30:56 userv1 kernel: [19816692.905317] Code: 44 d0 53 48 c7 c0 50 3b d0 8e 51 48 c7 c6 b7 15 cf 8e 41 53 48 89 f9 48 0f 45 f0 4c 89 d2 48 c7 c7 40 3c d0 8e e8 46 1c e6 ff <0f> 0b 49 c7      c1 0a 43 d2 8e 4d 89 cb 4d 89 c8 eb a5 66 90 0f 1f 44
...
  49 Jul 30 06:30:56 userv1 kernel: [19816692.905427] Call Trace:
  50 Jul 30 06:30:56 userv1 kernel: [19816692.905435]  __check_object_size+0x15f/0x1a0
  51 Jul 30 06:30:56 userv1 kernel: [19816692.905444]  __probe_kernel_read+0x4c/0x90
  52 Jul 30 06:30:56 userv1 kernel: [19816692.905451]  bpf_probe_read+0x1d/0x50
```
We will avoid starting the plugin on this kernel.

Fixes #9634

##### Component Name
eBPF plugin

##### Test Plan
- Run the eBPF collector on a system with a non-listed kernel and check it runs.
- Add the non-affected kernel version to the `ebpf_kernel_reject_list.txt` file and verify that the collector refuses to run.

### CODE REVIEW

File: libnetdata/ebpf/ebpf.c [hunk 1]
```diff
@@ -4,6 +4,7 @@
 #include <sys/stat.h>
 #include <fcntl.h>
 #include <dlfcn.h>
+#include <linux/version.h>
```
Comment (thiagoftsm) [inline libnetdata/ebpf/ebpf.c:7]: This header is present only when we install Linux headers, with the code we have on this PR I do not think it is necessary.

Comment (thiagoftsm) [reply libnetdata/ebpf/ebpf.c:7]: I saw you are using `KERNEL_VERSION`, I will suggest you use another definition like `NETDATA_MINIMUM_EBPF_KERNEL` to avoid bring this hard dependency. Or is it required now with `libbpf`?

Comment (vlvkobal) [reply libnetdata/ebpf/ebpf.c]: You are right. I've removed the dependency.

**Comment by amoss** [comment]
The logic in this patch is backwards, we do not want to change C code in the future to update the reject list. It should keep the reject list in a plain text file, one line per version string:

1. Get the current version string (either from version or version_signature)
2. Scan the file line by line
3. If the string is listed in the reject list then exit the collector

This means that adding a version to the reject list in the future is just modifying the text file and can be done by a non-C-dev.

**Comment by stelfrag** [comment]
It correctly detects a buggy kernel version (I marked my kernel as buggy and it worked just fine).  I will recheck after the changes suggested by @amoss are addressed

**Comment by vlvkobal** [comment]
There is no single common method available to check for a specific distribution/kernel version. I don't see the point of doing a premature generalization when we don't even know what we have to check in the future if we will need it at all.

**Comment by amoss** [comment]
The general code is not any more complex than the specific code. If the problem has already happened once this early in the life of the ebpf collector then we must ensure it is easy to fix next time it occurs.
