### PR TITLE
Handle disconnected sockets in unbound collector.

### LINKED ISSUE #6434: python.d ERROR: unbound[local] : [Errno 57] Socket is not connected FreeBSD
Hi,

I have set-up netdata (v1.15.0) to monitor my local unbound server on FreeBSD 12 through its control socket.

My error logs are flooding every second (poll rate) with the following: 
2019-07-11 19:42:51: python.d ERROR: unbound[local] : [Errno 57] Socket is not connected
2019-07-11 19:42:52: python.d ERROR: unbound[local] : [Errno 57] Socket is not connected
2019-07-11 19:42:53: python.d ERROR: unbound[local] : [Errno 57] Socket is not connected
2019-07-11 19:42:54: python.d ERROR: unbound[local] : [Errno 57] Socket is not connected
2019-07-11 19:42:55: python.d ERROR: unbound[local] : [Errno 57] Socket is not connected
2019-07-11 19:42:56: python.d ERROR: unbound[local] : [Errno 57] Socket is not connected
2019-07-11 19:42:57: python.d ERROR: unbound[local] : [Errno 57] Socket is not connected
2019-07-11 19:42:58: python.d ERROR: unbound[local] : [Errno 57] Socket is not connected

I have in unbound.conf (python.d plugin):
```
local:
 extended: true
 socket: /var/run/unbound/unbound-control.sock
```

I have in unbound.conf:
```
remote-control:
        control-enable: yes
        control-interface: /var/run/unbound/unbound-control.sock
```

**The unbound charts are working fine, although logs are obviously flooding.**

### PR DESCRIPTION
**Pull request by Ferroin**
#### Summary
This adds an explicit check for the case of a socket that's already
disconnected and skips logging an error message.  The conditionn
technically is an error, but it's one that we can recover from trivially
by just doing nothing in this case (we were trying to disconnect the
scoket anyway, so if it's already disconnected, we don't need to change
anything).

This uses Python's `errno` module so that we can detect this situation
in a system-agnostic manner.

##### Component Name
collectors/python.d

##### Additional Information

Fixes #6434

-----

@ilyam8 I'm of the opinion that this check should probably just go into the `SocketService` base class instead of being an as-needed thing in specific modules.  I honestly can't think of any case where a socket being disconnected as reported in #6434 would be an actual error in the disconnect method (it just means the socket is already in the state we want it to be in).

@Duffyx Could you check and see if this change stops the error logs getting flooded with the message you were seeing?  As mentioned in the issue itself, I wasn't able to reproduce this locally, so I'm going to need some help to make sure it works.

### CODE REVIEW

File: collectors/python.d.plugin/unbound/unbound.chart.py [hunk 1]
```diff
@@ -264,6 +265,21 @@ def check(self):
...
+            try:
+                self.debug('closing socket')
+                self._sock.shutdown(2)  # 0 - read, 1 - write, 2 - all
+                self._sock.close()
+            except Exception as error:
+                if ('errno' in error) and (error.errno == errno.ENOTCONN):
+                    pass
+                else:
+                    self.error(error)
+                self.error(error)
```
Comment (ilyam8) [inline collectors/python.d.plugin/unbound/unbound.chart.py]: we dont need last `self.error(error)

**Comment by Duffyx** [comment]
Hmm, this seems to break functionality as the charts don't work anymore. The error:

2019-07-29 19:04:21: python.d ERROR: unbound[local] : update() unhandled exception: argument of type 'OSError' is not iterable
2019-07-29 19:04:24: python.d ERROR: unbound[local] : unix socket "/var/run/unbound/unbound-control.sock": error sending request: [Errno 32] Broken pipe
2019-07-29 19:04:24: python.d ERROR: unbound[local] : update() unhandled exception: argument of type 'OSError' is not iterable
2019-07-29 19:04:27: python.d ERROR: unbound[local] : unix socket "/var/run/unbound/unbound-control.sock": error sending request: [Errno 32] Broken pipe
2019-07-29 19:04:27: python.d ERROR: unbound[local] : update() unhandled exception: argument of type 'OSError' is not iterable
2019-07-29 19:04:33: python.d ERROR: unbound[local] : unix socket "/var/run/unbound/unbound-control.sock": error sending request: [Errno 32] Broken pipe
2019-07-29 19:04:33: python.d ERROR: unbound[local] : update() unhandled exception: argument of type 'OSError' is not iterable

**Comment by Ferroin** [comment]
@Duffyx Yeah, looking back at the code now, that's my fault (I've apparently gotten too used to JavaScript's object model...).

Fixed that particular issue now.

**Comment by Duffyx** [comment]
:-) Thats fine. Just run time tested this on my machine. Works great. No more log flooding, graphs are working. Thanks!

**Comment by ilyam8** [comment]
> update() unhandled exception: 'NoneType' object has no attribute 'splitlines'

Nice catch @Duffyx, @Ferroin please fix the issue in this PR too.

> I'm of the opinion that this check should probably just go into the SocketService base class instead of being an as-needed thing in specific modules.

lgtm

**Comment by Ferroin** [comment]
>> I'm of the opinion that this check should probably just go into the SocketService base class instead of being an as-needed thing in specific modules.
>>
> lgtm

@ilyam8 would you prefer I just update this PR for that, or should I close this one and open a new one?

**Comment by ilyam8** [comment]
Update this one is ok

**Comment by Ferroin** [comment]
Updated to fix the issue that @Duffyx noticed, as well as moving the check to the `SocketService` class so that all modules can benefit from it.

@Duffyx that last error line you saw should be replaced with this update to be a warning instead.  I don't think there's anything we can do about the first two error lines, but as long as the graphs are working it's probably not an issue (especially since it's only happening on startup).

**Comment by ilyam8** [comment]
@Ferroin 	

https://github.com/netdata/netdata/blob/fc3ca0d3c1f0971bfb0b1822abef7b1d2ccaafd5/collectors/python.d.plugin/unbound/unbound.chart.py#L277-L281

**Comment by ilyam8** [comment]
@Duffyx please test the fix one more time

**Comment by Duffyx** [comment]
2019-07-30 20:41:29: python.d WARNING: unbound[local] : Received second no data from socket.
2019-07-30 20:41:29: python.d WARNING: unbound[local] : Received second no data from socket.
2019-07-30 20:41:30: python.d WARNING: unbound[local] : Received second no data from socket.
2019-07-30 20:41:30: python.d WARNING: unbound[local] : Received second no data from socket.
2019-07-30 20:41:31: python.d WARNING: unbound[local] : Received second no data from socket.
2019-07-30 20:41:31: python.d WARNING: unbound[local] : Received second no data from socket.
2019-07-30 20:41:32: python.d WARNING: unbound[local] : Received second no data from socket.
2019-07-30 20:41:32: python.d WARNING: unbound[local] : Received second no data from socket.
2019-07-30 20:41:33: python.d WARNING: unbound[local] : Received second no data from socket.
2019-07-30 20:41:33: python.d WARNING: unbound[local] : Received second no data from socket.
2019-07-30 20:41:34: python.d WARNING: unbound[local] : Received second no data from socket.
2019-07-30 20:41:34: python.d WARNING: unbound[local] : Received second no data from socket.
2019-07-30 20:41:35: python.d WARNING: unbound[local] : Received second no data from socket.
2019-07-30 20:41:35: python.d WARNING: unbound[local] : Received second no data from socket.

Error message: Received second no data from socket. The "second" I added to debug from which statement it was coming. But it is thus coming from _get_data function.

**Comment by Ferroin** [comment]
@Duffyx Huh, that's odd that it would be flooding the logs.  The condition it's looking for is what should have been triggering that single group of error messages on startup that you mentioned above.  Can you confirm for certain that the info shown in the charts actually makes sense (maybe do something that would look up a lot of DNS records via Unbound and confirm that the charts show the requests)?

@ilyam8 Any ideas why this would now be spamming the log when the same condition it's looking for only happened once before?

**Comment by Duffyx** [comment]
@Ferroin So I just did some DNS benchmarks and charts seem to react just fine on the load.

**Comment by ilyam8** [comment]
> 2019-07-30 20:41:34: python.d WARNING: unbound[local] : Received second no data from socket.
2019-07-30 20:41:34: python.d WARNING: unbound[local] : Received second no data from socket.
2019-07-30 20:41:35: python.d WARNING: unbound[local] : Received second no data from socket.
2019-07-30 20:41:35: python.d WARNING: unbound[local] : Received second no data from socket.

I see 2 log messages every second. @Duffyx You are saying that module works fine, you see the charts on the dashboartd and there are no gaps and at the same time there is warning msg every seconds and that msg comes from `_get_data`?

**Comment by Ferroin** [comment]
@ilyam8 Nice catch that it's happening more than once a second, I hadn't noticed that.  That makes me think that my initial gut feeling about this was right, and Python is being stupid and associating the else clause with the wrong if statement (there's an if statement inside a loop on the immediately previous line).

**Comment by Duffyx** [comment]
Second, hold your horses. My patches might be not 100% right after you stated that its python thats stupid. I just noticed my identation wasnt quite right.

**Comment by Duffyx** [comment]
Oh yeah baby, it's the chosen one! :-) I'm not seeing any more errors at all related to the unbound plugin after applying this fix. Sorry for that last noise, thats on me!
