### PR TITLE
Anonymous statistics

### LINKED ISSUE #4735: RFC: anonymous usage statistics
## Motivation

We need anonymous statistics about netdata. Such statistics will be used for:

1. **Quality assurance**, to help us understand if netdata behaves as expected and help us identify repeating issues for certain distributions or environment.

2. **Usage statistics**, to help us focus on the parts of netdata that are used the most, or help us identify the extend our development decisions influence the community (i.e. can we drop a certain collector? which is the most used collector to optimize? can we drop node.d.plugin? is anyone using netdata statsd? which backends are used by how many? etc).

## Collection points

These are the points we can collect these statistics:

1. The netdata installer, updater, uninstaller. These reports will not exist when we will distribute binary packages.
2. In the unlikely event netdata crashes.
3. When netdata starts (1 minute after it starts, to report also plugins and modules collecting data).
4. When a user accesses a netdata dashboard.

## Opt out

Users should be able to opt-out from this data collection.

To make it easier for users to opt-out globally, they will need to create the file `/etc/netdata/.opt-out-from-anonymous-statistics`, with one of following values:

- `all`, to opt-out from all kinds of statistics, including crashes
- `usage`, to opt-out from usage statistics only (points 3 and 4 above)
- `user`, to opt-out from user usage statistics only (point 4 above)

This file will be generated by the custom installer scripts, with the command line option `--out-out-from-anonymous-statistics VALUE`, so that a user that is not willing to share anything, will give this option to the installer and no data will be shared at all.

## Public reports

We will publish reports with these data. All data will be public, for everyone to see and examine, with the exception of 2 values:

- The `IPs` that sent the usage statistics
- The unique netdata machine IDs that sent the usage statistics

The above values will be used in calculating statistics, but will be deleted from the database as soon as the calculations of the statistics allow.

## Information to be collected

We should maintain a public wiki, explaining the usage statistics we maintain, the purpose we collect it for and the actual reports we generated using these statistics.

All this information will be public.

### netdata info

The following information about netdata itself:

- version as given by `netdata -V`

- unique netdata machine ID (random, generated when netdata starts) as stored in `/var/lib/netdata/registry/netdata.public.unique.id`

### operating system info

- The following information from `/etc/os-release`:
  - `NAME`, like `Debian GNU/Linux`, `Gentoo`, `Manjaro Linux`
  - `VERSION_ID`, like `9`
  - `ID`, like `debian`, `gentoo`, `manjaro`
  - `ID_LIKE`, like `arch`

- The following information from `uname`
  - Kernel name, as given by `uname -s`, example `Linux`
  - Kernel version, as given by `uname -r`, example `4.19.2-1-MANJARO`
  - Architecture, as given by `uname -m`, example `x86_64`

- Information about the virtualization technology
  - The output of the command `systemd-detect-virt`, example `none`, or `kvm`

### Installation reports

Installation reports (install, update, uninstall) should also report the final status of the operation (`OK`, `FAILED`, `CANCELLED`).

### Crash reports

Netdata daemon crash reports should provide a stack trace when possible.

## Implementation

We could provide a script that will be installed as `/usr/libexec/netdata/plugins.d/send-anonymous-usage-info.sh` to take care of all reports, except the user one (point 4).

This script will collect and send all reports, respecting the contents of `/etc/netdata/.opt-out-from-anonymous-statistics`.

This script will be called by all installation scripts and netdata itself to send the information required by points 1, 2 and 3.

Netdata itself should read the contents of `/etc/netdata/.opt-out-from-anonymous-statistics` and expose this information to the dashboard, so that the dashboard will not send user statistics (point 4).

### PR DESCRIPTION
**Pull request by cakrit**
##### Summary
Fixes #4735 
Will cancel #4743, so I can progress on this one. 

##### Additional Information
- [x] build the script
- [x] run it from `netdata` on start
- [x] run it from `netdata` on fatal
- [x] read opt-out file from `netdata` and expose it to the dashboard
- [x] make the dashboard send anonymous user statistics

### CODE REVIEW

File: daemon/anonymous-statistics.sh [hunk 1]
```diff
@@ -0,0 +1,141 @@
...
+    # http://stackoverflow.com/a/25518345
+    [ -f "/.dockerenv" ] &&
+        VIRTUALIZATION="docker" &&
+        VIRT_DETECTION="dockerenv"
+fi
+
+# -------------------------------------------------------------------------------------------------
+# check netdata version
+
+if [ -z "${NETDATA_VERSION}" ]; then
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: What is the scenario where this variable is set?

File: daemon/anonymous-statistics.sh [hunk 2]
```diff
@@ -0,0 +1,141 @@
...
+VIRT_DETECTION="none"
+
+if [ ! -z "$(command -v systemd-detect-virt 2>/dev/null)" ]
+then
+    VIRTUALIZATION="$(systemd-detect-virt)"
+    VIRT_DETECTION="systemd-detect-virt"
+else
+    # /proc/1/sched exposes the host's pid of our init !
+    # http://stackoverflow.com/a/37016302
+    pid=$( head -n 1 </proc/1/sched 2>/dev/null | { IFS='(),#:' read name pid th threads; echo $pid; } )
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: unused variables: `name`, `th`, `threads`
use `read -r` instead of `read` to prevent mangling backslashes

File: daemon/anonymous-statistics.sh [hunk 3]
```diff
@@ -0,0 +1,141 @@
...
+        if [ -f "${dir}/.opt-out-from-anonymous-statistics" ]; then
+            OPTOUT="$(cat "${dir}/.opt-out-from-anonymous-statistics")"
+            break
+        fi
+    done
+else
+    OPTOUT="$(cat "${NETDATA_CONFIG_DIR}/.opt-out-from-anonymous-statistics")"
+fi
+
+if [ "${OPTOUT}" = "all" ] || ( [ "${OPTOUT}" = "usage" ] && [ "${ACTION}" = "START" ] ); then
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: There is no need to spawn a subshell with `(...)` when the same behavior can be accomplished with `{ ..; }`.

File: daemon/anonymous-statistics.sh [hunk 4]
```diff
@@ -20,16 +23,17 @@ OPTOUT=
...
         if [ -f "${dir}/.opt-out-from-anonymous-statistics" ]; then
-            OPTOUT="$(cat "${dir}/.opt-out-from-anonymous-statistics")"
+            OPTOUT=all
             break
         fi
     done
 else
-    OPTOUT="$(cat "${NETDATA_CONFIG_DIR}/.opt-out-from-anonymous-statistics")"
+    if [ -f "${NETDATA_CONFIG_DIR}/.opt-out-from-anonymous-statistics" ]; then
+        OPTOUT=all
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: Why not just exit this script when this file is detected?

File: daemon/anonymous-statistics.sh [hunk 5]
```diff
@@ -0,0 +1,157 @@
...
+ACTION="${1}"
+ACTION_RESULT="${2}"
+ACTION_DATA="${3}"
+
+# -------------------------------------------------------------------------------------------------
+# check opt-out
+
+OPTOUT=
+if [ -z "${NETDATA_CONFIG_DIR}" ]; then
+    for dir in "$(netdata -W get global 'config directory' '/etc/netdata' 2>/dev/null)" "/etc/netdata" "/opt/netdata/etc/netdata"; do
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: Where does `/opt/netdata` come from? Why not use `${NETDATA_USER_CONFIG_DIR}`?

File: daemon/anonymous-statistics.sh [hunk 6]
```diff
@@ -0,0 +1,157 @@
...
+        if [ -f "${dir}/.opt-out-from-anonymous-statistics" ]; then
+            OPTOUT=all
+            break
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: Just `exit 0` instead of creating a variable which can take only one value (`all`) later used just to run `exit 0`.

File: daemon/anonymous-statistics.sh (hunk 5 above)
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: Where does `/opt/netdata` come from?

File: daemon/anonymous-statistics.sh [hunk 7]
```diff
@@ -0,0 +1,157 @@
...
+#      ACTION_RESULT  -- OK or FAILED
+
+ACTION="${1}"
+ACTION_RESULT="${2}"
+ACTION_DATA="${3}"
+
+# -------------------------------------------------------------------------------------------------
+# check opt-out
+
+OPTOUT=
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: Variable is unneeded and unnecessary complicates this script

File: daemon/anonymous-statistics.sh [hunk 8]
```diff
@@ -0,0 +1,157 @@
...
+if [ -z "${NETDATA_CONFIG_DIR}" ]; then
+    for dir in "$(netdata -W get global 'config directory' '/etc/netdata' 2>/dev/null)" "/etc/netdata" "/opt/netdata/etc/netdata"; do
+        if [ -f "${dir}/.opt-out-from-anonymous-statistics" ]; then
+            OPTOUT=all
+            break
+        fi
+    done
+else
+    if [ -f "${NETDATA_CONFIG_DIR}/.opt-out-from-anonymous-statistics" ]; then
+        OPTOUT=all
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: Just `exit 0`

File: daemon/anonymous-statistics.sh [hunk 9]
```diff
@@ -0,0 +1,157 @@
...
+    fi
+fi
+
+if [ "${OPTOUT}" = "all" ] ; then
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: Check is unnecessary after changing previous assignments of `OPTOUT=all` to `exit 0`

File: daemon/anonymous-statistics.sh [hunk 10]
```diff
@@ -0,0 +1,157 @@
...
+    exit 0
+fi
+
+# -------------------------------------------------------------------------------------------------
+# detect the operating system
+
+OS_DETECTION=
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: It would be better to initialize those variables with some value (ex. "unknown") as they are later pushed to GA.

File: daemon/anonymous-statistics.sh [hunk 11]
```diff
@@ -0,0 +1,157 @@
...
+elif [ -f "/etc/lsb-release" ]; then
+    OS_DETECTION="/etc/lsb-release"
+    DISTRIB_ID=
+    DISTRIB_RELEASE=
+    DISTRIB_CODENAME=
+    eval "$(grep -E "^(DISTRIB_ID|DISTRIB_RELEASE|DISTRIB_CODENAME)=" </etc/lsb-release)"
+    NAME="${DISTRIB_ID}"
+    VERSION="${DISTRIB_RELEASE}"
+    ID="${DISTRIB_CODENAME}"
+elif [ ! -z "$(command -v lsb_release 2>/dev/null)" ]; then
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: `lsb_release` command relies on `/etc/lsb-release` file so this part is just a code duplicate.

File: daemon/anonymous-statistics.sh [hunk 12]
```diff
@@ -0,0 +1,157 @@
...
+KERNEL_VERSION="$(uname -r)"
+ARCHITECTURE="$(uname -m)"
+
+# -------------------------------------------------------------------------------------------------
+# detect the virtualization
+
+VIRTUALIZATION="unknown"
+VIRT_DETECTION="none"
+
+if [ ! -z "$(command -v systemd-detect-virt 2>/dev/null)" ]
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: So basically if someone starts netdata on any non-systemd OS in AWS, GCP or on any other cloud infra, we will assume it is running in non-virtualized environment? We at least should check for `hypervisor` flag in `/proc/cpuinfo`.

File: daemon/anonymous-statistics.sh [hunk 13]
```diff
@@ -0,0 +1,157 @@
...
+
+    # lxc sets environment variable 'container'
+    [ ! -z "${container}" ] &&
+        VIRTUALIZATION="lxc" &&
+        VIRT_DETECTION="containerenv"
+
+    # docker creates /.dockerenv
+    # http://stackoverflow.com/a/25518345
+    [ -f "/.dockerenv" ] &&
+        VIRTUALIZATION="docker" &&
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: What if I run in a docker container on a VM?

File: daemon/anonymous-statistics.sh [hunk 14]
```diff
@@ -0,0 +1,157 @@
...
+    VIRTUALIZATION="$(systemd-detect-virt)"
+    VIRT_DETECTION="systemd-detect-virt"
+else
+    # /proc/1/sched exposes the host's pid of our init !
+    # http://stackoverflow.com/a/37016302
+    pid=$( head -n 1 </proc/1/sched 2>/dev/null | { IFS='(),#:' read -r _unused pid _unused _unused; echo $pid; } )
+    if [ ! -z "${pid}" ]; then
+        pid=$(( pid + 0 ))
+        [ ${pid} -ne 1 ] &&
+            VIRTUALIZATION="container" &&
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: Just a note: virtualization != containerization

File: daemon/anonymous-statistics.sh [hunk 15]
```diff
@@ -0,0 +1,157 @@
...
+#      ACTION_RESULT  -- error code
+#      ACTION_DATA    -- error message
+# - START       - netdata started
+# - INSTALL     - installation action
+#      ACTION_DATA    -- installation method from /var/lib/netdata/.installation
+#      ACTION_RESULT  -- OK or FAILED
+
+ACTION="${1}"
+ACTION_RESULT="${2}"
+ACTION_DATA="${3}"
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: Shouldn't we check if variables from above are actually set?

File: daemon/anonymous-statistics.sh [hunk 16]
```diff
@@ -0,0 +1,157 @@
...
+
+    # ubuntu and debian supply /bin/running-in-container
+    # https://www.apt-browse.org/browse/ubuntu/trusty/main/i386/upstart/1.12.1-0ubuntu4/file/bin/running-in-container
+    [ -x "/bin/running-in-container" ] &&
+        "/bin/running-in-container" >/dev/null 2>&1 &&
+        VIRTUALIZATION="container" &&
+        VIRT_DETECTION="/bin/running-in-container"
+
+    # lxc sets environment variable 'container'
+    [ ! -z "${container}" ] &&
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: This is only checking if variable is empty or not. To check if variable is set, you should use parameter expansion:
```bash
[ ! -z ${container+x} ] ...
```

**Comment by cakrit** [comment]
> Where does /opt/netdata come from?
In some systems it's installed there. I've seen it in an issue myself.

> lsb_release command relies on /etc/lsb-release file so this part is just a code duplicate.
Not always, apparently: https://github.com/brocaar/lora-gateway-bridge/issues/30

> Shouldn't we check if variables from above are actually set?

No need, the http request will be done correctly, but no event will appear if the first two are missing. The third one is optional in the GA event params I'm using. Good point though, I had missed the second param in the START event.

I can't answer the other questions.

File: daemon/anonymous-statistics.sh [hunk 17]
```diff
@@ -0,0 +1,157 @@
...
+    if [ ! -z "${pid}" ]; then
+        pid=$(( pid + 0 ))
+        [ ${pid} -ne 1 ] &&
+            VIRTUALIZATION="container" &&
+            VIRT_DETECTION="pid"
+    fi
+
+    # ubuntu and debian supply /bin/running-in-container
+    # https://www.apt-browse.org/browse/ubuntu/trusty/main/i386/upstart/1.12.1-0ubuntu4/file/bin/running-in-container
+    [ -x "/bin/running-in-container" ] &&
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: Cleaner solution:

```
if /bin/running-in-container >/dev/null 2>&1 ; then
	VIRTUALIZATION="container"
	VIRT_DETECTION="/bin/running-in-container"
fi
```

File: daemon/anonymous-statistics.sh [hunk 18]
```diff
@@ -0,0 +1,157 @@
...
+        "/bin/running-in-container" >/dev/null 2>&1 &&
+        VIRTUALIZATION="container" &&
+        VIRT_DETECTION="/bin/running-in-container"
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: Whole script `/bin/running-in-container` just checks for the content of `/run/container_type` which in turn should contain a containerization type (our variable called VIRTUALIZATION). So maybe instead of checking for this file, we should just `cat /run/container_type` and assign it to `$VIRTUALIZATION`?

Source: I went to a link from a comment in L98.

Also to be fair, this file needs to have upstart installed, which limits scope of this check only to older ubuntu distributions running inside lxc (docker images shouldn't have init system).

File: daemon/anonymous-statistics.sh [hunk 19]
```diff
@@ -0,0 +1,157 @@
...
+    [ -f "/.dockerenv" ] &&
+        VIRTUALIZATION="docker" &&
+        VIRT_DETECTION="dockerenv"
+fi
+
+# -------------------------------------------------------------------------------------------------
+# check netdata version
+
+if [ -z "${NETDATA_VERSION}" ]; then
+    NETDATA_VERSION="$(netdata -V 2>&1 | cut -d ' ' -f 2)"
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: What is the execution scenario where `NETDATA_VERION` is prepopulated?

Are you sure that `$(netdata -V 2>&1 | cut -d ' ' -f 2)` will be executed when netdata was installed in a non-default installation path (when `NETDATA_PREFIX` was used during installation)?

File: daemon/anonymous-statistics.sh [hunk 20]
```diff
@@ -0,0 +1,157 @@
...
+fi
+
+# -------------------------------------------------------------------------------------------------
+# check netdata unique id
+
+if [ -z "${NETDATA_REGISTRY_UNIQUE_ID}" ]; then
+    for dir in "$(netdata -W get global 'lib directory' '/var/lib/netdata' 2>/dev/null)" "/var/lib/netdata" "/opt/netdata/var/lib/netdata"; do
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: Probably checking `"/var/lib/netdata"` first would be more efficient looking that this is our default installation path?

File: daemon/anonymous-statistics.sh [hunk 21]
```diff
@@ -0,0 +1,157 @@
...
+fi
+
+# -------------------------------------------------------------------------------------------------
+# send the anonymous statistics to GA
+ACTION_DATA=$(echo "${ACTION_DATA}" | tr '"' "'")
+
+payload="&v=1&an=netdata&aip=1&t=pageview&_s=1&ds=statistics&tid=UA-64295674-3&cid=${NETDATA_REGISTRY_UNIQUE_ID}&t=event&av=${NETDATA_VERSION}&ec=${ACTION}&ea=${ACTION_RESULT}&dh=netdata-agent.my-netdata.io&dp=%2Fstatistics"
+
+curl -X POST -Ss --max-time 2 \
+--data-raw "${payload}"   					\
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: nit: those whitespaces look unnecessary

File: daemon/anonymous-statistics.sh (hunk 11 above)
Comment (paulfantom) [reply daemon/anonymous-statistics.sh]: > Not always, apparently: brocaar/lora-gateway-bridge#30

**Comment by cakrit** [comment]
> If PID is not 1, then we are sure we are not in a container, so this check should be -eq instead of -ne.
My laptop gets pid 1 outside a container, so it's not true.

File: daemon/anonymous-statistics.sh [hunk 22]
```diff
@@ -0,0 +1,157 @@
...
+
+if [ ! -z "$(command -v systemd-detect-virt 2>/dev/null)" ]
+then
+    VIRTUALIZATION="$(systemd-detect-virt)"
+    VIRT_DETECTION="systemd-detect-virt"
+else
+    # /proc/1/sched exposes the host's pid of our init !
+    # http://stackoverflow.com/a/37016302
+    pid=$( head -n 1 </proc/1/sched 2>/dev/null | { IFS='(),#:' read -r _unused pid _unused _unused; echo $pid; } )
+    if [ ! -z "${pid}" ]; then
```
[the remark this answers is not in the document]
Comment (paulfantom) [reply daemon/anonymous-statistics.sh]: To be fair this:
```
pid=$( head -n 1 </proc/1/sched 2>/dev/null | { IFS='(),#:' read -r _unused pid _unused _unused; echo $pid; } )
echo $pid
```

Will return `1` when running inside a container or outside of a container

File: daemon/anonymous-statistics.sh [hunk 23]
```diff
@@ -0,0 +1,157 @@
...
+        pid=$(( pid + 0 ))
+        [ ${pid} -ne 1 ] &&
```
[the remark this answers is not in the document]
Comment (paulfantom) [reply daemon/anonymous-statistics.sh]: To be fair this:
```
pid=$( head -n 1 </proc/1/sched 2>/dev/null | { IFS='(),#:' read -r _unused pid _unused _unused; echo $pid; } )
echo $pid
```

Will return `1` when running inside a container or outside of a container, because we are asking for PID 1: "/proc/**1**/sched"

File: daemon/anonymous-statistics.sh (hunk 22 above)
[the remark this answers is not in the document]
Comment (paulfantom) [reply daemon/anonymous-statistics.sh]: I think I got what was the intention and if I am correct, then this whole section should be written as:
```sh
process=$( head -n 1 </proc/1/sched 2>/dev/null | { IFS='(),#:' read -r process _unused _unused _unused; echo $process; } )

if [ "${process}" == "netdata" ]; then
   VIRTUALIZATION="container"
   VIRT_DETECTION="pid"
fi
```

[the remark this answers is not in the document]
Comment (paulfantom) [reply daemon/anonymous-statistics.sh]: Or even simpler:
```sh
IFS='(),#:' read -r process _unused </proc/1/sched
if [ "${process}" == "netdata" ]; then
   VIRTUALIZATION="container"
   VIRT_DETECTION="pid"
fi
```

File: daemon/anonymous-statistics.sh (hunk 23 above)
[the remark this answers is not in the document]
Comment (paulfantom) [reply daemon/anonymous-statistics.sh]: I think I got what was the intention and if I am correct, then this whole section should be written as:
```sh
process=$( head -n 1 </proc/1/sched 2>/dev/null | { IFS='(),#:' read -r process _unused _unused _unused; echo $process; } )

if [ "${process}" == "netdata" ]; then
   VIRTUALIZATION="container"
   VIRT_DETECTION="pid"
fi
```

[the remark this answers is not in the document]
Comment (paulfantom) [reply daemon/anonymous-statistics.sh]: Or even simpler:
```sh
IFS='(,' read -r process _unused </proc/1/sched
if [ "${process}" == "netdata" ]; then
   VIRTUALIZATION="container"
   VIRT_DETECTION="pid"
fi
```

File: daemon/anonymous-statistics.sh [hunk 24]
```diff
@@ -0,0 +1,146 @@
...
+OS_DETECTION="unknown"
+NAME="unknown"
+VERSION="unknown"
+VERSION_ID="unknown"
+ID="unknown"
+ID_LIKE="unknown"
+
+if [ -f "/etc/os-release" ]; then
+    OS_DETECTION="/etc/os-release"
+    eval "$(grep -E "^(NAME|ID|ID_LIKE|VERSION|VERSION_ID)=" </etc/os-release)"
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: What if there is no value in `/etc/os-release`? For example our own docker image is based on alpine and `/etc/os-release` have only:
```sh
bash-4.4# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.8.2
PRETTY_NAME="Alpine Linux v3.8"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

Which means that `ID_LIKE` will be empty.

According to https://www.freedesktop.org/software/systemd/man/os-release.html only `NAME`, `VERSION` and `ID` are mandatory.

File: daemon/anonymous-statistics.sh [hunk 25]
```diff
@@ -0,0 +1,146 @@
...
+    DISTRIB_RELEASE="unknown"
+    DISTRIB_CODENAME="unknown"
+    eval "$(grep -E "^(DISTRIB_ID|DISTRIB_RELEASE|DISTRIB_CODENAME)=" </etc/lsb-release)"
+    NAME="${DISTRIB_ID}"
+    VERSION="${DISTRIB_RELEASE}"
+    ID="${DISTRIB_CODENAME}"
+elif [ ! -z "$(command -v lsb_release 2>/dev/null)" ]; then
+    OS_DETECTION="lsb_release"
+    NAME="$(lsb_release -i 2>/dev/null | sed "s/[[:space:]]*:[[:space:]]*/:/g" | cut -d ':' -f 2)"
+    VERSION_ID="$(lsb_release -f 2>/dev/null | sed "s/[[:space:]]*:[[:space:]]*/:/g" | cut -d ':' -f 2)"
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: `lsb_release` doesn't support `-f` parameter.

```sh
root@4036e62f0da6:/# lsb_release --help
Usage: lsb_release [options]

Options:
  -h, --help         show this help message and exit
  -v, --version      show LSB modules this system supports
  -i, --id           show distributor ID
  -d, --description  show description of this distribution
  -r, --release      show release number of this distribution
  -c, --codename     show code name of this distribution
  -a, --all          show all of the above information
  -s, --short        show requested information in short format
```

Comment (paulfantom) [reply daemon/anonymous-statistics.sh]: Also there is no need for all this parsing since `lsb_release` supports `-s` option which simplifies lines like this:
```
NAME="$(lsb_release -i 2>/dev/null | sed "s/[[:space:]]*:[[:space:]]*/:/g" | cut -d ':' -f 2)"
```

to 
```
NAME="$(lsb_release -is 2>/dev/null)"
```

File: daemon/anonymous-statistics.sh [hunk 26]
```diff
@@ -0,0 +1,146 @@
...
+    DISTRIB_ID="unknown"
+    DISTRIB_RELEASE="unknown"
+    DISTRIB_CODENAME="unknown"
+    eval "$(grep -E "^(DISTRIB_ID|DISTRIB_RELEASE|DISTRIB_CODENAME)=" </etc/lsb-release)"
+    NAME="${DISTRIB_ID}"
+    VERSION="${DISTRIB_RELEASE}"
+    ID="${DISTRIB_CODENAME}"
+elif [ ! -z "$(command -v lsb_release 2>/dev/null)" ]; then
+    OS_DETECTION="lsb_release"
+    NAME="$(lsb_release -i 2>/dev/null | sed "s/[[:space:]]*:[[:space:]]*/:/g" | cut -d ':' -f 2)"
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: `lsb_release -i` should probably be assigned to `ID` and not `NAME`. `NAME` should probably be taken from `lsb_release -d`.

File: daemon/anonymous-statistics.sh [hunk 27]
```diff
@@ -0,0 +1,146 @@
...
+            break
+        fi
+    done
+fi
+
+# -------------------------------------------------------------------------------------------------
+# send the anonymous statistics to GA
+ACTION_DATA=$(echo "${ACTION_DATA}" | tr '"' "'")
+
+payload="&v=1&an=netdata&aip=1&t=pageview&_s=1&ds=statistics&tid=UA-64295674-3&cid=${NETDATA_REGISTRY_UNIQUE_ID}&t=event&av=${NETDATA_VERSION}&ec=${ACTION}&ea=${ACTION_RESULT}&dh=netdata-agent.my-netdata.io&dp=%2Fstatistics"
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: What does `dh=netdata-agent.my-netdata.io` do and why this is static?

Comment (paulfantom) [reply daemon/anonymous-statistics.sh]: I went to GA docs and `dh` is for page tracking, but we are not doing page tracing here, so why `dh` and `dp` are set?

Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: Maybe it would be better to change `ds` (data source) to something more meaningful than "statistics", like "shell" since we are sending this from shell?

File: daemon/anonymous-statistics.sh [hunk 28]
```diff
@@ -0,0 +1,146 @@
...
+--data-urlencode "cd3=${ID_LIKE}" \
+--data-urlencode "cd4=${VERSION}" \
+--data-urlencode "cd5=${VERSION_ID}" \
+--data-urlencode "cd6=${OS_DETECTION}" \
+--data-urlencode "cd7=${KERNEL_NAME}" \
+--data-urlencode "cd8=${KERNEL_VERSION}" \
+--data-urlencode "cd9=${ARCHITECTURE}" \
+--data-urlencode "cd10=${VIRTUALIZATION}" \
+--data-urlencode "cd11=${VIRT_DETECTION}" \
+"https://www.google-analytics.com/collect" >/dev/null 2>&1
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: Please make it more readable. It shouldn't be this hard to do a code review of this reqest as GA docs are pretty clear. However this takes too much time due to jumping from one section to another.

To make it more readable please:
- stop mixing `data-raw` with `data-urlencode` and stick to one of those.
- cleanup ordering of parameters and group them in the same way as they are grouped in GA docs: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters

File: daemon/anonymous-statistics.sh [hunk 29]
```diff
@@ -0,0 +1,146 @@
...
+
+exit $?
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: This is an antipattern, it is recommended to do `set -e` at the beginning of a script.

File: daemon/anonymous-statistics.sh [hunk 30]
```diff
@@ -0,0 +1,146 @@
...
+
+ACTION="${1}"
+ACTION_RESULT="${2}"
+ACTION_DATA="${3}"
+
+# -------------------------------------------------------------------------------------------------
+# check opt-out
+
+if [ -z "${NETDATA_CONFIG_DIR}" ]; then
+    for dir in "$(netdata -W get global 'config directory' '/etc/netdata' 2>/dev/null)" "/etc/netdata" "/opt/netdata/etc/netdata"; do
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: Also same thing as with `/var/lib/netdata` - probably it would be more efficient to put `/etc/netdata` as a first parameter.

File: daemon/anonymous-statistics.sh [hunk 31]
```diff
@@ -0,0 +1,146 @@
...
+
+
+ACTION="${1}"
+ACTION_RESULT="${2}"
+ACTION_DATA="${3}"
+
+# -------------------------------------------------------------------------------------------------
+# check opt-out
+
+if [ -z "${NETDATA_CONFIG_DIR}" ]; then
```
[the remark this answers is not in the document]
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: Executed by the daemon.

File: daemon/anonymous-statistics.sh (hunk 30 above)
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: Done

File: daemon/anonymous-statistics.sh (hunk 24 above)
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: I did make a change for the important params (NAME, VERSION, ID), so we try lsb if they're unknown after os-release

File: daemon/anonymous-statistics.sh (hunk 26 above)
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: Done

File: daemon/anonymous-statistics.sh (hunk 25 above)
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: -d was wrong, I used -r in the proper place.

File: daemon/anonymous-statistics.sh [hunk 32]
```diff
@@ -0,0 +1,146 @@
...
+# check netdata version
+
+if [ -z "${NETDATA_VERSION}" ]; then
+    NETDATA_VERSION="$(netdata -V 2>&1 | cut -d ' ' -f 2)"
+fi
+
+# -------------------------------------------------------------------------------------------------
+# check netdata unique id
+
+if [ -z "${NETDATA_REGISTRY_UNIQUE_ID}" ]; then
```
[the remark this answers is not in the document]
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: Searched, no scenario and I couldn't add it to the global variables, a required dependency couldn't be satisfied at that point of the code. I removed the if

File: daemon/anonymous-statistics.sh (hunk 27 above)
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: Were left over from testing. Also corrected the type (t=) to event instead of pageview.

File: daemon/anonymous-statistics.sh (hunk 28 above)
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: > stop mixing data-raw with data-urlencode and stick to one of those.

No need to url-encode what certainly doesn't require url-encoding just to make it pretty. Did the rest.

File: daemon/anonymous-statistics.sh (hunk 29 above)
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: Done

File: daemon/anonymous-statistics.sh (hunk 12 above)
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: I found the following, but the dude says that the hypervisor check works only for Type-1 virt. 
https://stackpointer.io/unix/linux-check-running-virtual-machine/553/

File: daemon/anonymous-statistics.sh (hunk 5 above)
Comment (paulfantom) [reply daemon/anonymous-statistics.sh]: The alternative you propose creates a faster code, so I would consider it to be a preferable solution.

File: daemon/anonymous-statistics.sh (hunk 12 above)
Comment (paulfantom) [reply daemon/anonymous-statistics.sh]: > Type-1 hypervisors run directly on the host’s hardware to control the hardware and to manage guest operating systems. KVM, Citrix XenServer, Microsoft Hyper-V and VMware ESX/ESXi are some exmaples of Type-1 hypervisors.

Which is a majority of hypervisors.

File: daemon/anonymous-statistics.sh (hunk 16 above)
Comment (paulfantom) [reply daemon/anonymous-statistics.sh]: Don't know anything about lxc and what are the possible values of this variable. Comment at the top suggest that this is checking if variable is **set**, but code doesn't reflect it.

File: daemon/anonymous-statistics.sh (hunk 19 above)
Comment (paulfantom) [reply daemon/anonymous-statistics.sh]: When you install in non-default location, then it is entirely possible that command `netdata` ends up in location not included in `$PATH`. For example assume installation in `/home/user/apps`.

File: daemon/anonymous-statistics.sh (hunk 21 above)
Comment (paulfantom) [reply daemon/anonymous-statistics.sh]: I was saying that in regard to whitespaces between parameter and `\`, not regarding whitespaces at the start of a line. Sorry for lack of clearance.

File: daemon/anonymous-statistics.sh (hunk 24 above)
Comment (paulfantom) [reply daemon/anonymous-statistics.sh]: No, you won't have it `unknown`, you will have it empty (without any value).

File: daemon/anonymous-statistics.sh [hunk 33]
```diff
@@ -0,0 +1,159 @@
...
+VERSION_ID="unknown"
+ID="unknown"
+ID_LIKE="unknown"
+
+if [ -f "/etc/os-release" ]; then
+    OS_DETECTION="/etc/os-release"
+    eval "$(grep -E "^(NAME|ID|ID_LIKE|VERSION|VERSION_ID)=" </etc/os-release)"
+fi
+
+if [ "${NAME}" == "unknown" -o "${VERSION}" == "unknown" -o "${ID}" == "unknown" ] ; then
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: Those essentially **cannot** be unknown when `/etc/os-release` is present as those three are **mandatory** parameters. Everything else is optional, but those three are always populated.

File: daemon/anonymous-statistics.sh (hunk 23 above)
[the remark this answers is not in the document]
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: I included this one as well.

File: daemon/anonymous-statistics.sh (hunk 33 above)
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: As we saw VERSION isn't populated in Manjaro.

File: daemon/anonymous-statistics.sh (hunk 12 above)
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: I added hypervisor check.

File: daemon/anonymous-statistics.sh (hunk 19 above)
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: Made it like this:
```
if [ -z "${NETDATA_VERSION}" ]; then
	NETDATA_VERSION="uknown"
	netdata -V >/dev/null 2>&1 && NETDATA_VERSION="$(netdata -V 2>&1 | cut -d ' ' -f 2)"
fi
```

File: daemon/anonymous-statistics.sh (hunk 33 above)
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: We saw that in Manjaro we don't get VERSION

File: daemon/anonymous-statistics.sh (hunk 27 above)
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: It was made shell

File: daemon/anonymous-statistics.sh (hunk 20 above)
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: Done

File: daemon/anonymous-statistics.sh (hunk 13 above)
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: Split container from virtualization

File: daemon/anonymous-statistics.sh (hunk 14 above)
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: Split container from virtualization

File: daemon/anonymous-statistics.sh [hunk 34]
```diff
@@ -0,0 +1,173 @@
...
```
Comment (paulfantom) [inline daemon/anonymous-statistics.sh]: koalaman/shellcheck/wiki/SC2166 is still valid.

```suggestion
if [ "${NAME}" == "unknown" ] || [ "${VERSION}" == "unknown" ] || [ "${ID}" == "unknown" ] ; then
```

**Comment by cakrit** [comment]
> I have attached the statistics script to a build system and I would consider this script production ready. However this PR cannot be merged before adding an option to installer script to automatically opt out from telemetry during installation process. This is important as without it we will have a lot of meaningless data generated by out CI.

This is not blocking since netdata isn't started during CI and we only trigger anonymous statistics via the daemon and the web interface. 

Moved it out of WIP, please do final reviews so we can merge.

File: docs/privacy-policy.md [hunk 35]
```diff
@@ -1,12 +1,12 @@
-# Privacy policy
+# Privacy Policy
 
 ## 1. Preamble
 
-This Privacy Policy explains the collection, use, processing, transferring and disclosure of personal information by Netdata, Inc (“ND” or “Netdata”), a Delaware corporation.
+This Privacy Policy explains the collection, use, processing, transferring and disclosure of personal information by Netdata, Inc (“ND” or “Netdata”), a Delaware Corporation.
 
-This Privacy Policy is incorporated into and made part of Netdata Master Terms of Use (“Master Terms”) located [here](terms-of-use.md).
+This Privacy Policy is incorporated into and made part of Netdata Master Terms of Use (“Master Terms”) located at https://netdata.cloud/legal/terms-of-use.
```
Comment (ktsaou) [inline docs/privacy-policy.md]: make sure this URL works.

File: daemon/anonymous-statistics.sh (hunk 18 above)
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: We assign it to CONTAINER now and we do run other checks as well. So I'l like to leave it as is to finish.

File: daemon/anonymous-statistics.sh (hunk 19 above)
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: This was fixed from your commit.

File: daemon/anonymous-statistics.sh (hunk 16 above)
Comment (cakrit) [reply daemon/anonymous-statistics.sh]: It's semantics, the effect is the same.
