### PR TITLE
Fixes support for read-only /lib on SystemD systems like CoreOS in  kickstart static64

### LINKED ISSUE #68: CoreOS Support
Can you verify if this works on a large CoreOS cluster?

Thanks,

### LINKED ISSUE #5558: Static installer fails on systemd where /lib is read-only
##### Bug report summary

Static package fails to install on CoreOS because /lib is read-only

https://github.com/netdata/netdata/issues/68#issuecomment-469716965

##### OS / Environment

CoreOS

##### Steps To Reproduce

```
bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --non-interactive
```

##### Expected behavior

It should install the systemd unit to /etc/systemd/system if it can detect that /lib is read-only, instead it errors out with:

```
 --- Install netdata at system init --- 
Installing systemd service...
[/opt/netdata]# cp system/netdata.service /lib/systemd/system/netdata.service 
cp: cannot create regular file '/lib/systemd/system/netdata.service': Read-only file system
 FAILED   

 FAILED  Cannot install netdata init service. 
```

### PR DESCRIPTION
**Pull request by prologic**
##### Summary

Fixes support for SystemD based systems with a read-only `/lib` such as CoreOS where only `/etc` is writeable and thus the `SYSTEMD_DIRECTORY` should be `/etc/systemd/system`. This PR finally makes netdata work correctly on such systems.

Fixes #5558 

And finally Fixes #68 proper.

##### Component Name

Packaging

##### Additional Information

There are still some warnings/errors on installation; but I will handle those separately. I can confirm the NetData against is successfully installed, running and the Web interface operational:

```bash
core@localhost ~ $ bash <(curl -s http://10.0.0.104:8000/kickstart-static64.sh) --non-interactive
 --- Installation sources were given as input, running installation using "/home/core/netdata-v1.19.0-305-g26abdeab.gz.run" ---
[/tmp/netdata-kickstart-Qv8laH]$ cp /home/core/netdata-v1.19.0-305-g26abdeab.gz.run /tmp/netdata-kickstart-Qv8laH/netdata-latest.gz.run
 OK

[/tmp/netdata-kickstart-Qv8laH]$ cp /home/core/sha256sum.txt /tmp/netdata-kickstart-Qv8laH/sha256sum.txt
 OK

 --- Installing netdata ---
[/tmp/netdata-kickstart-Qv8laH]$ sudo sh /tmp/netdata-kickstart-Qv8laH/netdata-latest.gz.run --accept -- --auto-update

  ^
  |.-.   .-.   .-.   .-.   .  netdata
  |   '-'   '-'   '-'   '-'   real-time performance monitoring, done right!
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

  (C) Copyright 2017, Costa Tsaousis
  All rights reserved
  Released under GPL v3+

  You are about to install netdata to this system.
  netdata will be installed at:

                    /opt/netdata

  The following changes will be made to your system:

  # USERS / GROUPS
  User 'netdata' and group 'netdata' will be added, if not present.

  # LOGROTATE
  This file will be installed if logrotate is present.

   - /etc/logrotate.d/netdata

  # SYSTEM INIT
  This file will be installed if this system runs with systemd:

   - /lib/systemd/system/netdata.service

   or, for older Centos, Debian/Ubuntu or OpenRC Gentoo:

   - /etc/init.d/netdata         will be created


  This package can also update a netdata installation that has been
  created with another version of it.

  Your netdata configuration will be retained.
  After installation, netdata will be (re-)started.

  netdata re-distributes a lot of open source software components.
  Check its full license at:
  https://github.com/netdata/netdata/blob/master/LICENSE.md
Backing up existing directory
Creating directory /opt/netdata
Verifying archive integrity...  100%   All good.
Uncompressing netdata, the real-time performance and health monitoring system  100%
 --- Found old etc/netdata directory, reinstating this ---
 --- Trigger stock config clean up ---
 --- Deleting stock configuration files from user configuration directory ---
 --- Attempt to create user/group netdata/netadata ---
Group 'netdata' already exists.
User 'netdata' already exists.
 --- Add user netdata to required user groups ---
User 'netdata' is already in group 'docker'.
Group 'nginx' does not exist.
 FAILED  Failed to add netdata user to secondary groups

Group 'varnish' does not exist.
 FAILED  Failed to add netdata user to secondary groups

Group 'haproxy' does not exist.
 FAILED  Failed to add netdata user to secondary groups

Group 'adm' does not exist.
 FAILED  Failed to add netdata user to secondary groups

Group 'nsd' does not exist.
 FAILED  Failed to add netdata user to secondary groups

Group 'proxy' does not exist.
 FAILED  Failed to add netdata user to secondary groups

Group 'squid' does not exist.
 FAILED  Failed to add netdata user to secondary groups

Group 'ceph' does not exist.
 FAILED  Failed to add netdata user to secondary groups

Group 'nobody' does not exist.
 FAILED  Failed to add netdata user to secondary groups

Group 'I2C' does not exist.
 FAILED  Failed to add netdata user to secondary groups

 --- Check SSL certificates paths ---
 --- Install logrotate configuration for netdata ---
[/opt/netdata]# chmod 644 /etc/logrotate.d/netdata
 OK

 --- Telemetry configuration ---
You can opt out from anonymous statistics via the --disable-telemetry option, or by creating an empty file /opt/netdata/etc/netdata/.opt-out-from-anonymous-statistics

 --- Install netdata at system init ---
Installing systemd service...
[/opt/netdata]# cp system/netdata.service /etc/systemd/system/netdata.service
 OK

[/opt/netdata]# systemctl daemon-reload
 OK

[/opt/netdata]# systemctl enable netdata
Created symlink /etc/systemd/system/multi-user.target.wants/netdata.service -> /etc/systemd/system/netdata.service.
 OK

 --- Install (but not enable) netdata updater tool ---
Cannot figure out the cron directory to handle netdata-updater.sh activation/deactivation
 FAILED  Cannot cleanup old netdata updater tool.

Update script is located at /opt/netdata/usr/libexec/netdata/netdata-updater.sh

 --- Check if we must enable/disable the netdata updater tool ---
Cannot figure out the cron directory to handle netdata-updater.sh activation/deactivation
 FAILED  Cannot enable netdata updater tool

 --- creating quick links ---
[/opt/netdata]# rm sbin
 OK

[/opt/netdata]# ln -s bin sbin
 OK

[/opt/netdata/usr]# rm bin
 OK

[/opt/netdata/usr]# ln -s ../bin bin
 OK

[/opt/netdata/usr]# rm sbin
 OK

[/opt/netdata/usr]# ln -s ../bin sbin
 OK

[/opt/netdata/usr]# rm local
 OK

[/opt/netdata/usr]# ln -s . local
 OK

[/opt/netdata]# rm netdata-configs
 OK

[/opt/netdata]# ln -s etc/netdata netdata-configs
 OK

[/opt/netdata]# rm netdata-web-files
 OK

[/opt/netdata]# ln -s usr/share/netdata/web netdata-web-files
 OK

[/opt/netdata]# rm netdata-plugins
 OK

[/opt/netdata]# ln -s usr/libexec/netdata netdata-plugins
 OK

[/opt/netdata]# rm netdata-dbs
 OK

[/opt/netdata]# ln -s var/lib/netdata netdata-dbs
 OK

[/opt/netdata]# rm netdata-metrics
 OK

[/opt/netdata]# ln -s var/cache/netdata netdata-metrics
 OK

[/opt/netdata]# rm netdata-logs
 OK

[/opt/netdata]# ln -s var/log/netdata netdata-logs
 OK

[/opt/netdata/etc/netdata]# rm orig
 OK

[/opt/netdata/etc/netdata]# ln -s ../../usr/lib/netdata/conf.d orig
 OK

 --- fix permissions ---
[/opt/netdata]# chmod g+rx\,o+rx /opt
 OK

[/opt/netdata]# chown -R netdata:netdata /opt/netdata
 OK

 --- fix plugin permissions ---
[/opt/netdata]# chown root:netdata usr/libexec/netdata/plugins.d/apps.plugin
 OK

[/opt/netdata]# chmod 4750 usr/libexec/netdata/plugins.d/apps.plugin
 OK

[/opt/netdata]# chown root:netdata usr/libexec/netdata/plugins.d/ioping
 OK

[/opt/netdata]# chmod 4750 usr/libexec/netdata/plugins.d/ioping
 OK

[/opt/netdata]# chown root:netdata usr/libexec/netdata/plugins.d/cgroup-network
 OK

[/opt/netdata]# chmod 4750 usr/libexec/netdata/plugins.d/cgroup-network
 OK

[/opt/netdata]# chown root:netdata bin/fping
 OK

[/opt/netdata]# chmod 4750 bin/fping
 OK

 --- starting netdata ---
 --- Restarting netdata instance ---

Stopping all netdata threads
[/opt/netdata]# stop_all_netdata
Stopping netdata on pid 3144 ....
netdata on pid 3144 stopped.
 OK

Starting netdata using command 'systemctl start netdata'
[/opt/netdata]# systemctl start netdata
 OK

Ooops! it seems netdata is not started.
Attempting another netdata start using command 'systemctl start netdata'
[/opt/netdata]# systemctl start netdata
 OK


  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata              .-.   .-.   .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   is installed now!  -'   '-'   '-'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

[/opt/netdata]# chmod 0644 /opt/netdata/etc/netdata/netdata.conf
 OK

 OK

[/tmp/netdata-kickstart-Qv8laH]$ sudo rm /tmp/netdata-kickstart-Qv8laH/netdata-latest.gz.run
 OK

[/tmp/netdata-kickstart-Qv8laH]$ sudo rm -rf /tmp/netdata-kickstart-Qv8laH
 OK

core@localhost ~ $ ps aux | grep netdata
netdata   4365  0.5  1.0  74932 21000 ?        Ssl  02:54   0:00 /opt/netdata/bin/srv/netdata -P /opt/netdata/var/run/netdata/netdata.pid -D -W set global process scheduling policy keep -W set global OOM score keep
netdata   4431  0.0  0.0   1632  1236 ?        S    02:54   0:00 bash /opt/netdata/usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
root      4435  0.2  0.0   3784  1796 ?        S    02:54   0:00 /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1
netdata   4439  0.0  0.8 123284 17076 ?        Sl   02:54   0:00 /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 1
core      4681  0.0  0.0   2820   848 pts/0    S+   02:55   0:00 grep --colour=auto netdata
core@localhost ~ $
```

**NOTE:** This depends on #7725 as I had to make some minor fixes to test and validate my changes locally.

### CODE REVIEW

File: packaging/installer/functions.sh [hunk 1]
```diff
@@ -374,7 +374,13 @@ install_netdata_service() {
 
             SYSTEMD_DIRECTORY=""
 
-            if [ -d "/lib/systemd/system" ]; then
+            if [ -f "/etc/os-release" ]; then
+                source "/etc/os-release" || return 1
+            fi
+
+            if [ x"$ID" = x"coreos" ]; then
+                SYSTEMD_DIRECTORY="/etc/systemd/system"
```
Comment (Ferroin) [inline packaging/installer/functions.sh]: While this does work, I'm kind of the opinion that this doesn't completely fix #5558. We should be checking writability of each of the places we're trying to put the unit file, and picking the first writable one in the list (with `/etc/systemd/system` being at the end of the list), as there are other reasons that `/lib/systemd/system` and `/usr` might be read-only besides running on CoreOS.

**Comment by prologic** [comment]
> Aside from the specific code commen (which I don't feel is worth lack of approval provided the Fixes tag for #5558 is removed before merging)t, this needs to update the `kickstart.sh` checksum on line 55 of `packaging/installer/README.md`

I knew you would say this (_the checksums bit that is!_); I actually have on my list of things to do to somehow automate this; I couldn't quite remember where it was at first. But yes I will fix!

Also; Why do you feel that this PR should not fix/close #5558 ? I _feel_ it should as it _does_ correctly/mostly get NetData Agent running on CoreOS alongside the side as originally intended and asked for in #68 (_at least in my testing_)

File: packaging/installer/functions.sh (hunk 1 above)
Comment (prologic) [reply packaging/installer/functions.sh]: Ahhh. Sorry I commented on your earlier comment too soon! Let's not have a discussion in both places! :)

So... In actuality I did try it this way at first only to realise that the level of code/effort required was vastly more complicated than just "Are we on CoreOS? Yes? Then write here."

I do agree with you; but I _feel_ this will become more apparently as we run into more edge-cases and esoteric SystemD configurations on other systems. If however the variations are small then the extra engineering effort/complexity won't be worth it anyway.

**Comment by Ferroin** [comment]
> Also; Why do you feel that this PR should not fix/close #5558 ? I _feel_ it should as it _does_ correctly/mostly get NetData Agent running on CoreOS alongside the side as originally intended and asked for in #68 (_at least in my testing_)

It does fix things on CoreOS, but _only_ on CoreOS. Either we need to update #5558's title to reflect that it only cares about CoreOS (and then open another issue to cover the just supporting this in a distro-agnostic way which this shouldn't close), or treat #5558 as requesting support for ths type of thing in a distro-agnostic manner.

Put simply, we really need to support read-only `/` and `/usr` with a writable `/etc` like CoreOS does without depending on it being CoreOS, because there are other systems that are configured that way and we should install correctly there too.

File: packaging/installer/functions.sh (hunk 1 above)
Comment (knatsakis) [reply packaging/installer/functions.sh]: > So... In actuality I did try it this way at first only to realise that the level of code/effort required was vastly more complicated than just "Are we on CoreOS? Yes? Then write here."

Could you elabolate a bit more regarding why it is complicated? I am thinking it would be a matter of testing for writeability with something like '[ -w /path/to/dir ]' but I guess I am missing something

Comment (prologic) [reply packaging/installer/functions.sh]: TIL: `[ -w /path/to/dir ]` <-- 🤣

Given @Ferroin's comment below I'll look into this again. Perhaps doing this is easier than I first though :)
