### PR TITLE
Fix empty dbengine files

### LINKED ISSUE #9521: Netdata fails to start
##### Basic system informations
```
Linux cloudvps 4.19.0-9-cloud-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version
```
netdata v1.23.1
```

##### Installation source
```
netdata.cloud
```

##### Installation command & parameters
```
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --stable-channel --disable-telemetry
```

##### System Logs
<details>

```cmd
● netdata.service - Real time performance monitoring
   Loaded: loaded (/lib/systemd/system/netdata.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2020-07-11 01:08:36 CEST; 28s ago
  Process: 15765 ExecStartPre=/bin/mkdir -p /var/cache/netdata (code=exited, status=0/SUCCESS)
  Process: 15766 ExecStartPre=/bin/chown -R netdata:netdata /var/cache/netdata (code=exited, status=0/SUCCESS)
  Process: 15767 ExecStartPre=/bin/mkdir -p /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 15768 ExecStartPre=/bin/chown -R netdata:netdata /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 15769 ExecStart=/usr/sbin/netdata -P /var/run/netdata/netdata.pid -D (code=exited, status=1/FAILURE)
 Main PID: 15769 (code=exited, status=1/FAILURE)


Jul 11 01:13:41 cloudvps systemd[1]: Started Real time performance monitoring.
-- Subject: A start job for unit netdata.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit netdata.service has finished successfully.
-- 
-- The job identifier is 1829.
Jul 11 01:13:41 cloudvps netdata[16837]: SIGNAL: Not enabling reaper
Jul 11 01:13:41 cloudvps netdata[16837]: 2020-07-11 01:13:41: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
Jul 11 01:13:41 cloudvps systemd[1]: netdata.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecStart= process belonging to unit netdata.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Jul 11 01:13:41 cloudvps systemd[1]: netdata.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit netdata.service has entered the 'failed' state with result 'exit-code'.
```
</details>

##### Netdata Log file
[error.log](https://github.com/netdata/netdata/files/4905890/error.log)

### PR DESCRIPTION
**Pull request by mfundul**
##### Summary
Fixes #9521
##### Component Name
database
##### Test Plan
1. Stop the agent.
2. Go to the cache folder:
```
cd /var/cache/netdata/dbengine
```
3. Create an empty file for the metadata log:
```
touch metadatalog-00000-00013.mlf
```
4. Create empty files for dbgengine:
```
touch datafile-1-0000000333.ndf
touch journalfile-1-0000000333.njf
```
5. Start the agent.
6. The agent should operate normally from now on.

##### Additional Information
This PR changes the handling of empty dbengine and metadata-log files. Previously the dbengine instance would abort. Now it deletes the corrupted files and continues.

### CODE REVIEW

**Review by stelfrag — APPROVED** [review]
Looks good 

- Handles 0 size datafiles and metadata log files that would make the agent fail to start
- It will not handle journal files that are 0 size (will not delete) but those are properly reused and do not cause a problem

**Comment by amoss** [comment]
This is not how a journal file should work, which leads me to believe that what you are calling a journal file in the dbengine is actually something else.

If I start the agent, let it run and then shut it down gracefully, I see this:
```
-rw------- 1 amoss amoss 303104 Aug 27 10:33 datafile-1-0000000001.ndf
-rw------- 1 amoss amoss 135168 Aug 27 10:33 journalfile-1-0000000001.njf
-rw------- 1 amoss amoss 282256 Aug 27 10:33 metadatalog-00000-00002.mlf
-rw------- 1 amoss amoss   7808 Aug 27 10:33 metadatalog-00000-00003.mlf
```

* Why is there a journal file after a graceful shutdown - it should be empty or non-existent?
* If I delete the journalfile the agent now deletes the datafile on a restart - why does it do this?

**Comment by mfundul** [comment]
> 
> 
> This is not how a journal file should work, which leads me to believe that what you are calling a journal file in the dbengine is actually something else.
> 
> If I start the agent, let it run and then shut it down gracefully, I see this:
> 
> ```
> -rw------- 1 amoss amoss 303104 Aug 27 10:33 datafile-1-0000000001.ndf
> -rw------- 1 amoss amoss 135168 Aug 27 10:33 journalfile-1-0000000001.njf
> -rw------- 1 amoss amoss 282256 Aug 27 10:33 metadatalog-00000-00002.mlf
> -rw------- 1 amoss amoss   7808 Aug 27 10:33 metadatalog-00000-00003.mlf
> ```
> 
>     * Why is there a journal file after a graceful shutdown - it should be empty or non-existent?
> 
>     * If I delete the journalfile the agent now deletes the datafile on a restart - why does it do this?

The dbengine design consists of a big WAL (write-ahead-log). There are no indexed metadata for dbengine, only those WAL files, which are being replayed during start-up to recreate the metadata state in memory. Such metadata can be disk offsets, metric GUIDs, time ranges, page sizes etc.

The journalfile and its corresponding datafile are always in pairs, and are rotated together. The new logic dictates that, if there is corruption, get rid of the corrupted pair so that the netdata service is not stuck in an infinite boot loop.

**Comment by amoss** [comment]
So then it is not a journal file, it is the metadata for the data (but stored implicitly as series of replay steps rather than explicitly as data-structures). This does not give us the fault tolerance that a journal file would.

**Comment by mfundul** [comment]
> 
> 
> So then it is not a journal file, it is the metadata for the data (but stored implicitly as series of replay steps rather than explicitly as data-structures). This does not give us the fault tolerance that a journal file would.

If you're asking whether the current implementation is transactional, no it is not. There is a transaction ID in the protocol for future work but this kind of work never got into the roadmap.

File: database/engine/datafile.c [hunk 1]
```diff
@@ -305,33 +326,45 @@ static int scan_data_files(struct rrdengine_instance *ctx)
...
+        if (must_delete_pair) {
+            char path[RRDENG_PATH_MAX];
+
+            error("Deleting invalid data and journal file pair.");
+            ret = unlink_journal_file(journalfile);
+            if (!ret) {
+                generate_journalfilepath(datafile, path, sizeof(path));
+                info("Deleted journal file \"%s\".", path);
+            }
+            ret = unlink_data_file(datafile);
```
Comment (amoss) [inline database/engine/datafile.c:352]: We don't close the file before unlinking it any more - this should be safe (in posix). Not sure about libuv

Comment (mfundul) [reply database/engine/datafile.c:352]: No you're right, I should fix that. It slipped.

**Review by amoss — DISMISSED** [review]
Test cases work correctly, code looks correct.

File: database/engine/datafile.c (hunk 1 above)
Comment (amoss) [reply database/engine/datafile.c:352]: Well done - I read the wrong part:
```
If the name was the last link to a file but any processes still have the file open, the file will remain in existence until the last file descriptor referring to it is closed.
```

**Review by stelfrag — APPROVED** [review]

**Review by amoss — APPROVED** [review]
