### PR TITLE
Fix race condition with orphan hosts

### LINKED ISSUE #9627: Segfault with numerous records at stream.conf
##### Bug report summary
I have about 3339 strings at stream.conf and netdata crash after few seconds after start.
I tried to reduce number of strings at stream.conf to 100-200 and netdata start and run fine.

At /var/log/netdata/error.log I found 
```Jul 29 15:34:20 ru-spb-nd-master1 netdata[3605]: 2020-07-29 15:34:20: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
Jul 29 15:34:25 ru-spb-nd-master1 kernel: [7659994.866939] STREAM_RECEIVER[3717]: segfault at 0 ip 00007f551f833206 sp 00007f5516460198 error 4 in libc-2.28.so[7f551f7bd000+148000]
Jul 29 15:34:25 ru-spb-nd-master1 kernel: [7659994.866948] Code: 0f 1f 40 00 66 0f ef c0 66 0f ef c9 66 0f ef d2 66 0f ef db 48 89 f8 48 89 f9 48 81 e1 ff 0f 00 00 48 81 f9 cf 0f 00 00 77 6a <f3> 0f 6f 20 66 0f 74 e0 66 0f d7 d4 85 d2 74 04 0f bc c2 c3 48 83
Jul 29 15:34:25 ru-spb-nd-master1 systemd[1]: netdata.service: Main process exited, code=killed, status=11/SEGV
Jul 29 15:34:25 ru-spb-nd-master1 systemd[1]: netdata.service: Failed with result 'signal'.
```

##### OS / Environment
I have latest netdata installed from git with ```netdata-installer.sh```
```netdata -v
netdata v1.23.2-83-ga4ebf1d4
```
Running on Debian 10(buster)
```uname -a; grep -Hv "^#" /etc/*release
Linux ru-spb-nd-master1 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"```

### PR DESCRIPTION
**Pull request by mfundul**
##### Summary
Fixes #9627
##### Component Name
streaming
##### Test plan
1. Create a 1000 node streaming set-up.
2. Use `dbengine`, disable health for streaming, delete the cache.
2. Use master code, observe crash.
3. Delete the cache again.
4. Use this PR, observe no crash.
5. Restart the agent, observe health is still disabled for all child hosts, no crash.
6. Enable health for streaming.
7. Restart the agent, observe health is enabled for all child hosts.

### CODE REVIEW

File: streaming/receiver.c [hunk 1]
```diff
@@ -455,12 +453,20 @@ static int rrdpush_receive(struct receiver_state *rpt)
     if (!netdata_exit && rpt->host) {
         netdata_mutex_lock(&rpt->host->receiver_lock);
         if (rpt->host->receiver == rpt) {
+            netdata_mutex_unlock(&rpt->host->receiver_lock);
```
Comment (amoss) [inline streaming/receiver.c:456]: Backing out of the lock is dangerous as it allows the receiver to be detached from the host by another thread. Why not take the host lock over the whole if-nest L453-472?

Comment (ilyam8) [reply streaming/receiver.c:456]: Today's lock order is 😜 :
- `host_lock`
- `global_lock`
- `receiver_lock`

Comment (amoss) [reply streaming/receiver.c:456]: Yes, I figured that was the approach. I agree with the locking order shown in the PR:
1. Global
2. Host
3. Receiver

From memory I think this is consistent with the code-base but we need to check.  I can see a problem with this - the flags are protected under the host lock which is root cause of needing to back-out / relock in several places. I don't want to fix that in this PR but we should put a new flags lock in place *only* to cover the flags. I did something similar in the dead branch for the replication code. Then I think we should use:

1. Global
2. Host
3. Receiver
...
n. Flags

i.e. it should always be the last lock in the order.

**Comment by amoss** [comment]
I believe that this is consistent with the assumptions in `rrdhost_free`.

**Comment by mfundul** [comment]
After those changes it still crashes, seemingly due to difference between `host` and `rpt->host`:

```
Program received signal SIGSEGV, Segmentation fault.

(gdb) bt
#0  0x00007ffff65393a9 in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
#1  0x0000000000537d10 in __netdata_rwlock_wrlock (rwlock=0x7ffb1196e190) at libnetdata/locks/locks.c:186
#2  0x00000000005204f3 in netdata_rwlock_wrlock_debug (file=0x5a8468 "database/rrddim.c",
    function=0x5c61e0 <__FUNCTION__.31399.140533> "rrddim_add_custom", line=222, rwlock=0x7ffb1196e190)
    at libnetdata/locks/locks.c:287
#3  0x00000000004d3fee in rrddim_add_custom (st=0x7ffb1196d000, id=0xa8c627e3 "guest_nice", name=0xa8c627f0 "guest_nice",
    multiplier=1, divisor=1, algorithm=RRD_ALGORITHM_PCENT_OVER_DIFF_TOTAL, memory_mode=RRD_MEMORY_MODE_RAM, is_archived=0,
    dim_uuid=0x0) at database/rrddim.c:222
#4  0x00000000004e2692 in pluginsd_dimension_action (user=0xa8e9a980, st=0x7ffb1196d000, id=0xa8c627e3 "guest_nice",
    name=0xa8c627f0 "guest_nice", algorithm=0xa8c627fd "percentage-of-incremental-row", multiplier=1, divisor=1,
    options=0xa8c62821 "  ", algorithm_type=RRD_ALGORITHM_PCENT_OVER_DIFF_TOTAL) at collectors/plugins.d/pluginsd_parser.c:127
#5  0x00000000004e388c in pluginsd_dimension (words=0x7ffb367d1120, user=0xa8e9a980, plugins_action=0xa8e9b7f0)
    at collectors/plugins.d/pluginsd_parser.c:420
#6  0x0000000000482de3 in parser_action (parser=0xa8e9aa90, input=0xa8c627d8 "DIMENSION") at parser/parser.c:296
#7  0x00000000004a95b4 in streaming_parser (rpt=0xa8c62750, cd=0x7ffb367d3710, fp=0xa8e8edb0) at streaming/receiver.c:229
#8  0x00000000004aa868 in rrdpush_receive (rpt=0xa8c62750) at streaming/receiver.c:445
#9  0x00000000004aabca in rrdpush_receiver_thread (ptr=0xa8c62750) at streaming/receiver.c:482
#10 0x00000000005153e5 in thread_start (ptr=0xa8c64730) at libnetdata/threads/threads.c:184
#11 0x00007ffff6535ea5 in start_thread () from /lib64/libpthread.so.0
#12 0x00007ffff625e8dd in clone () from /lib64/libc.so.6


(gdb) frame 3
(gdb) print st->rrdhost->hostname
$4 = 0x9653c380 "CentOS-7-mfundul-lxc-centos7-263"

(gdb) frame 7
(gdb) print *rpt
$5 = {host = 0x9c5b75c0, thread = 140716927715072, fd = 1794, key = 0xa8c63230 "f7859939-0112-4640-893f-42df9b1a5daf", 
  hostname = 0xa8c63460 "CentOS-7-mfundul-lxc-centos7-375", registry_hostname = 0xa8c63490 "CentOS-7-mfundul-lxc-centos7-375", 
  machine_guid = 0xa8c634c0 "847a60a0-5e8d-11ea-992b-8504dd3f1e78", os = 0xa8c636a0 "linux", timezone = 0xa8c63830 "UTC", 
  tags = 0x0, client_ip = 0xa8c63850 "192.168.150.252", client_port = 0xa8c63b00 "55240", program_name = 0xa8c63f40 "netdata", 
  program_version = 0xa8c645f0 "v1.20.0", system_info = 0xa8c5c880, update_every = 1, stream_version = 2, 
  last_msg_t = 1599038597, 
  read_buffer = "DIMENSION\000\"guest_nice\000 \"guest_nice\000 \"percentage-of-incremental-row\000 1\000\061\000\"  \000\000\000tacked\000 1010\000\061\000\"   \000 \"proc.plugin\000 \"/proc/stat\000\000\000\000ata.statsd_cpu\000 \"stacked\000 132002\000\061\000\"   \000 \"statsd.plugin\000 \"stats", '\000' <repeats 832 times>, read_len = 77, ssl = {conn = 0x0, flags = 8}, 
  shutdown = 0, exited = 0}
```

This will have to be fixed before we close this issue.

**Comment by amoss** [comment]
The two pointers are resolving to two different hosts, not two instances of the same host. Why are CentOS-7-mfundul-lxc-centos7-263 and CentOS-7-mfundul-lxc-centos7-375 streaming the same chart?

**Comment by mfundul** [comment]
> 
> 
> The two pointers are resolving to two different hosts, not two instances of the same host. Why are CentOS-7-mfundul-lxc-centos7-263 and CentOS-7-mfundul-lxc-centos7-375 streaming the same chart?

That's exactly what is happening. So the parser resolves in `CentOS-7-mfundul-lxc-centos7-263` and `rpt` points to `CentOS-7-mfundul-lxc-centos7-375`. Moreover, `rpt->host` points to corrupted data, because apparently `CentOS-7-mfundul-lxc-centos7-375` has been already freed. I'll reproduce this with address sanitizer.

**Comment by mfundul** [comment]
The crash has moved inside the parser now. It appears to be the same use-after-free case as before, for host allocation, but it happens later in the parser with this PR's code:
```
AddressSanitizer: heap-use-after-free on address 0x604601739630 at pc 0x645afd bp 0x7ffa5a6e83d0 sp 0x7ffa5a6e83c0
READ of size 8 at 0x604601739630 thread T1317 (STREAM_RECEIVER)
    #0 0x645afc (/usr/sbin/netdata+0x645afc) avl_search (libnetdata/avl/avl.c:25).
    #1 0x64893d (/usr/sbin/netdata+0x64893d) avl_search_lock (libnetdata/avl/avl.c:372).
    #2 0x575853 (/usr/sbin/netdata+0x575853) rrdset_index_find (database/rrdset.c:38).
    #3 0x575dbd (/usr/sbin/netdata+0x575dbd) rrdset_find (database/rrdset.c:99).
    #4 0x578aa8 (/usr/sbin/netdata+0x578aa8) rrdset_find_on_create (database/rrdset.c:480).
    #5 0x57a42d (/usr/sbin/netdata+0x57a42d) rrdset_create_custom (database/rrdset.c:677).
    #6 0x5b2d54 (/usr/sbin/netdata+0x5b2d54) pluginsd_chart_action (collectors/plugins.d/pluginsd_parser.c:53).
    #7 0x5b4dfa (/usr/sbin/netdata+0x5b4dfa) pluginsd_chart (collectors/plugins.d/pluginsd_parser.c:358).
    #8 0x4f6092 (/usr/sbin/netdata+0x4f6092) parser_action (parser/parser.c:296).
    #9 0x54683e (/usr/sbin/netdata+0x54683e) streaming_parser (streaming/receiver.c:229).
    #10 0x549669 (/usr/sbin/netdata+0x549669) rrdpush_receive (streaming/receiver.c:445).
    #11 0x549d8e (/usr/sbin/netdata+0x549d8e) rrdpush_receiver_thread (streaming/receiver.c:482).
    #12 0x623e01 (/usr/sbin/netdata+0x623e01) thread_start (libnetdata/threads/threads.c:184).
    #13 0x7ffff4e64867 (/usr/lib64/libasan.so.0.0.0+0x19867)
    #14 0x7ffff35a5ea4 (/usr/lib64/libpthread-2.17.so+0x7ea4)
    #15 0x7ffff32ce8dc (/usr/lib64/libc-2.17.so+0xfe8dc)
0x604601739630 is located 816 bytes inside of 1224-byte region [0x604601739300,0x6046017397c8)
freed by thread T1285 (STREAM_RECEIVER) here:
    #0 0x7ffff4e60dd9 (/usr/lib64/libasan.so.0.0.0+0x15dd9)
    #1 0x62e947 (/usr/sbin/netdata+0x62e947) freez (libnetdata/libnetdata.c:173).
    #2 0x56ff8d (/usr/sbin/netdata+0x56ff8d) rrdhost_free (database/rrdhost.c:896).
    #3 0x5a58be (/usr/sbin/netdata+0x5a58be) rrdhost_cleanup_orphan_hosts_nolock (database/rrdhost.c:621).
    #4 0x5a55af (/usr/sbin/netdata+0x5a55af) rrdhost_find_or_create (database/rrdhost.c:583).
    #5 0x5477f9 (/usr/sbin/netdata+0x5477f9) rrdpush_receive (streaming/receiver.c:294).
    #6 0x549d8e (/usr/sbin/netdata+0x549d8e) rrdpush_receiver_thread (streaming/receiver.c:482).
    #7 0x623e01 (/usr/sbin/netdata+0x623e01) thread_start (libnetdata/threads/threads.c:184).
    #8 0x7ffff4e64867 (/usr/lib64/libasan.so.0.0.0+0x19867)
previously allocated by thread T194 (STREAM_RECEIVER) here:
    #0 0x7ffff4e60ff5 (/usr/lib64/libasan.so.0.0.0+0x15ff5)
    #1 0x62ea15 (/usr/sbin/netdata+0x62ea15) callocz (libnetdata/libnetdata.c:183).
    #2 0x5a1e8e (/usr/sbin/netdata+0x5a1e8e) rrdhost_create (database/rrdhost.c:139).
    #3 0x5a5466 (/usr/sbin/netdata+0x5a5466) rrdhost_find_or_create (database/rrdhost.c:534).
    #4 0x5477f9 (/usr/sbin/netdata+0x5477f9) rrdpush_receive (streaming/receiver.c:294).
    #5 0x549d8e (/usr/sbin/netdata+0x549d8e) rrdpush_receiver_thread (streaming/receiver.c:482).
    #6 0x623e01 (/usr/sbin/netdata+0x623e01) thread_start (libnetdata/threads/threads.c:184).
    #7 0x7ffff4e64867 (/usr/lib64/libasan.so.0.0.0+0x19867)
```
This is a combined view of `gdb` and `asan` but I couldn't get memory contents because `asan` aborted the `gdb` run.

**Comment by mfundul** [comment]
Apparently it runs with 1000 child hosts, whereas the master branch crashes.

**Comment by amoss** [comment]
I can't do any useful testing on this because the only relevant issue is whether the increased contention on the global lock impacts stability when there is a large number of child nodes with short duration connections. The code is correct, but document the testing that you did in the test-plan of the PR before I approve it so that I can see if there are any gaps in coverage.

**Review by amoss — APPROVED** [review]
I see no adverse effect on system stability.

**Review by stelfrag — APPROVED** [review]
