### PR TITLE
Correct go.d.plugin sha256sum check

### LINKED ISSUE #5538: sha256sum: go.d.plugin-v0.1.0.linux-arm64: No such file or directory
Possibly related to https://github.com/netdata/netdata/issues/5459 ?

I did a reinstall of netdata today to make use of the newly introduced stable channel and I got the following error

`~/netdata$ git pull`
`~/netdata$ sudo ./netdata-installer.sh --auto-update --stable-channel`
> go.d.plugin-v0.1.0.linux-arm: OK
> sha256sum: go.d.plugin-v0.1.0.linux-arm64: No such file or directory
> go.d.plugin-v0.1.0.linux-arm64: FAILED open or read
> config.tar.gz: OK
> sha256sum: WARNING: 1 listed file could not be read
>  FAILED  go.d.plugin package files checksum validation failed.

But the file and checksum did actually exist:

`~/netdata$ cat packaging/go.d.checksums |grep go.d.plugin-v0.1.0.linux-arm64`
> 4b4d88b1b373ee5b8f544beb8827aa133a33cafd2340792607980b558e7552ba *go.d.plugin-v0.1.0.linux-arm64

and I could download the package manually via

`~/netdata$ curl -O https://github.com/netdata/go.d.plugin/releases/download/v0.1.0/go.d.plugin-v0.1.0.linux-amd64`

Other than that everything seems to have worked fine as far as I can tell.

I had previously installed netdata via

`~/netdata$ sudo ./netdata-installer.sh --auto-update`

netdata v1.12.2-4-geccf0b9
Raspbian GNU/Linux 9 (stretch)
Linux 4.14.79-v7+
Raspberry Pi 3 Model B Rev 1.2

### PR DESCRIPTION
**Pull request by cakrit**
Fixes #5538

### CODE REVIEW

File: netdata-installer.sh [hunk 1]
```diff
@@ -823,7 +823,7 @@ install_go() {
 		download "https://github.com/netdata/go.d.plugin/releases/download/$GO_PACKAGE_VERSION/$GO_PACKAGE_BASENAME" "${tmp}/$GO_PACKAGE_BASENAME"
 
 		download "https://github.com/netdata/go.d.plugin/releases/download/$GO_PACKAGE_VERSION/config.tar.gz" "${tmp}/config.tar.gz"
-		grep "${GO_PACKAGE_BASENAME}" "${installer_dir}/packaging/go.d.checksums" > "${tmp}/sha256sums.txt" 2>/dev/null
+		grep "${GO_PACKAGE_BASENAME}" "${installer_dir}/packaging/go.d.checksums\$" > "${tmp}/sha256sums.txt" 2>/dev/null
```
Comment (paulfantom) [inline netdata-installer.sh]: "${installer_dir}/packaging/go.d.checksums" is a path to a file on which grep is looking for line with "${GO_PACKAGE_BASENAME}". Why are you modifying a path to a file?

Comment (paulfantom) [reply netdata-installer.sh]: You probably wanted this:
```bash
grep "${GO_PACKAGE_BASENAME}\$" "${installer_dir}/packaging/go.d.checksums" > "${tmp}/sha256sums.txt" 2>/dev/null
```

Comment (cakrit) [reply netdata-installer.sh]: Yes, it was idiotic.
