### PR TITLE
Re-index when machine guid changes

### LINKED ISSUE #14293: [Bug]: child instance not accessible after changing guid but keeping same hostname
### Bug description

Netdata child instance is not accessible through either the parent instance or the Cloud after changing GUID but keeping the same hostname. But reachable according to `/api/v1/info`.

```json
{ "guid": "e619e970-974c-11ed-a669-4ea904ab059a", "hostname": "shared-centos9", "reachable": false, "hops": 1, "claim_id": null, "node_id": "2180fdc0-bc39-4987-bd0f-1c051f415bd8" },
{ "guid": "6446db30-9754-11ed-a051-4ea904ab059a", "hostname": "shared-centos9", "reachable": false, "hops": 1, "claim_id": null, "node_id": "b8dea3d1-bfab-47ab-9800-2888ab1164e6" },
{ "guid": "6047f4fa-9755-11ed-a9e2-4ea904ab059a", "hostname": "shared-centos9", "reachable": false, "hops": 1, "claim_id": null, "node_id": "062d3674-83d3-4bf5-bfd7-8c27d45828ee" },
{ "guid": "8890d5da-9755-11ed-801f-4ea904ab059a", "hostname": "shared-centos9", "reachable": true, "hops": 1, "claim_id": null, "node_id": "90c75b94-1e2f-4af7-8986-7f63641435c4" }
```

### Expected behavior

Child instance after changing GUID but keeping the same hostname:

 - available through the parent via `/host/HOSTNAME/`.
 - available on the Cloud.

### Steps to reproduce

1. set up child-parent.
2. stop child.
3. rm -rf child's cache and lib directories.
4. start child. 

### Installation method

kickstart.sh

### System info

```shell
Linux 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
Version: netdata v1.37.0-157-gb5b5df893
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O2 -g' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

Fixes #14293 

This PR tries to fix the above issue. 

We keep a dictionary of hosts, based on hostname, on `rrdhost_root_index_hostname`. This is populated on parent startup, from children info previously connected to the parent (even if not currently connected).

If a child was previously connected with guid X, then changed and connected with Y, the dictionary will only keep a link to the host with guid X, and will not store the one with Y. As such, when requesting /host/child which streams with guid Y there will be nothing there.

This PR just overwrites the dictionary. Assuming X is added to the dictionary during startup, then Y is streaming, the dictionary will delete X and keep Y.

The PR also sorts the list of `mirrored_hosts_status` according to their reachability. This is to make dashboard display the Live badge on children that have guid changed.

##### Test Plan

Setup a parent/child.
Stop the child and change it's guid.
Start the child again.
The dashboard on the parent should show metrics from the child.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  

This can help in cases where an child agent on a node is wiped and re-installed. The parent should now display the child's metrics.

</details>

### CODE REVIEW

**Comment by stelfrag** [comment]
Needs a rebase to resolve conflicts

File: database/rrdhost.c [hunk 1]
```diff
@@ -104,31 +104,33 @@ inline RRDHOST *rrdhost_find_by_hostname(const char *hostname) {
...
 
     RRDHOST *ret_hostname = dictionary_set(rrdhost_root_index_hostname, rrdhost_hostname(host), host, sizeof(RRDHOST));
     if(ret_hostname == host)
         rrdhost_option_set(host, RRDHOST_OPTION_INDEXED_HOSTNAME);
     else {
-        rrdhost_option_clear(host, RRDHOST_OPTION_INDEXED_HOSTNAME);
-        error("RRDHOST: %s() host with hostname '%s' is already indexed", __FUNCTION__, rrdhost_hostname(host));
+        //have the same hostname but it's not the same host
+        //keep the new one
+        rrdhost_index_del_hostname(ret_hostname);
```
Comment (stelfrag) [inline database/rrdhost.c:127]: Probably need to check that the host we are trying to remove is ORPHAN / ARCHIVED. This is probably needed to avoid having for example 3 children with the same hostname and two of them trying to connect

Comment (MrZammler) [reply database/rrdhost.c:127]: I will yes. I actually had a check that the new one wasn't archived, but didn't work (unseting that flag happens later during stream).

**Review by stelfrag — APPROVED** [review]

**Review by thiagoftsm — APPROVED** [review]
PR is working as expected, LGTM!
